import"server-only";import type{AuthorisedContext}from"@/lib/auth/dal";import{calendarStatus,itemTypeFromEvidence,type CalendarEvent}from"@/lib/calendar";import{createDb}from"@/lib/db";
export async function getCalendarEvents(context:AuthorisedContext,from:Date,to:Date):Promise<CalendarEvent[]>{const db=createDb(),locationIds=context.locations.map(({id})=>id),locationScope=context.allLocations?{}:{OR:[{locationId:null},{locationId:{in:locationIds}}]},strictLocation=context.allLocations?{}:{locationId:{in:locationIds}};try{const[policies,audits,meetings,risks,actions,evidence,manual]=await Promise.all([
db.policy.findMany({where:{organisationId:context.organisation.id,status:{not:"ARCHIVED"},nextReviewDate:{gte:from,lte:to}},select:{id:true,title:true,nextReviewDate:true,owner:{select:{id:true,name:true}},status:true}}),
db.audit.findMany({where:{organisationId:context.organisation.id,reviewDate:{gte:from,lte:to},...strictLocation},select:{id:true,title:true,reviewDate:true,status:true,auditor:{select:{id:true,name:true}},location:{select:{id:true,name:true}}}}),
db.governanceMeeting.findMany({where:{organisationId:context.organisation.id,meetingDate:{gte:from,lte:to},status:{not:"ARCHIVED"},...locationScope},select:{id:true,title:true,meetingDate:true,status:true,chair:{select:{id:true,name:true}},location:{select:{id:true,name:true}}}}),
db.risk.findMany({where:{organisationId:context.organisation.id,nextReviewDate:{gte:from,lte:to},status:{not:"ARCHIVED"},...locationScope},select:{id:true,reference:true,title:true,nextReviewDate:true,status:true,residualLevel:true,owner:{select:{id:true,name:true}},location:{select:{id:true,name:true}}}}),
db.action.findMany({where:{organisationId:context.organisation.id,dueDate:{gte:from,lte:to},status:{not:"ARCHIVED"},...locationScope},select:{id:true,reference:true,title:true,dueDate:true,status:true,priority:true,owner:{select:{id:true,name:true}},location:{select:{id:true,name:true}}}}),
db.evidence.findMany({where:{organisationId:context.organisation.id,reviewExpiryDate:{gte:from,lte:to},status:"ACTIVE",...locationScope},select:{id:true,title:true,category:true,evidenceType:true,reviewExpiryDate:true,owner:{select:{id:true,name:true}},location:{select:{id:true,name:true}}}}),
db.calendarItem.findMany({where:{organisationId:context.organisation.id,dueDate:{gte:from,lte:to},status:{not:"ARCHIVED"},...locationScope},select:{id:true,title:true,description:true,itemType:true,dueDate:true,status:true,riskLevel:true,owner:{select:{id:true,name:true}},location:{select:{id:true,name:true}}}})
]);const event=(input:Omit<CalendarEvent,"status"> &{sourceStatus:string}):CalendarEvent=>({...input,status:calendarStatus(input.sourceStatus,input.date)});return[
...policies.map((item)=>event({key:`POLICY_REVIEW:${item.id}`,title:item.title,description:"Policy review due",date:item.nextReviewDate!,type:"POLICY_REVIEW",sourceStatus:item.status==="APPROVED"?"PENDING":item.status,href:`/policies/${item.id}`,locationId:null,locationName:"Organisation-wide",ownerId:item.owner.id,ownerName:item.owner.name,riskLevel:null})),
...audits.map((item)=>event({key:`AUDIT_DUE:${item.id}`,title:item.title,description:"Audit review due",date:item.reviewDate!,type:"AUDIT_DUE",sourceStatus:["COMPLETED","CLOSED"].includes(item.status)?"COMPLETED":"PENDING",href:`/audits/${item.id}`,locationId:item.location.id,locationName:item.location.name,ownerId:item.auditor.id,ownerName:item.auditor.name,riskLevel:null})),
...meetings.map((item)=>event({key:`GOVERNANCE_MEETING:${item.id}`,title:item.title,description:"Governance meeting",date:item.meetingDate,type:"GOVERNANCE_MEETING",sourceStatus:["APPROVED","CANCELLED"].includes(item.status)?item.status==="APPROVED"?"COMPLETED":"CANCELLED":"PENDING",href:`/meetings/${item.id}`,locationId:item.location?.id??null,locationName:item.location?.name??"Organisation-wide",ownerId:item.chair.id,ownerName:item.chair.name,riskLevel:null})),
...risks.map((item)=>event({key:`RISK_REVIEW:${item.id}`,title:`${item.reference} · ${item.title}`,description:"Risk review due",date:item.nextReviewDate,type:"RISK_REVIEW",sourceStatus:item.status==="CLOSED"?"COMPLETED":"PENDING",href:`/risks/${item.id}`,locationId:item.location?.id??null,locationName:item.location?.name??"Organisation-wide",ownerId:item.owner?.id??null,ownerName:item.owner?.name??"Unassigned",riskLevel:item.residualLevel})),
...actions.map((item)=>event({key:`ACTION_DEADLINE:${item.id}`,title:`${item.reference} · ${item.title}`,description:"Action deadline",date:item.dueDate,type:"ACTION_DEADLINE",sourceStatus:item.status,href:`/actions/${item.id}`,locationId:item.location?.id??null,locationName:item.location?.name??"Organisation-wide",ownerId:item.owner.id,ownerName:item.owner.name,riskLevel:item.priority})),
...evidence.map((item)=>event({key:`EVIDENCE_EXPIRY:${item.id}`,title:item.title,description:`${item.category} · ${item.evidenceType}`,date:item.reviewExpiryDate!,type:itemTypeFromEvidence(item.category,item.evidenceType),sourceStatus:"PENDING",href:`/evidence/${item.id}`,locationId:item.location?.id??null,locationName:item.location?.name??"Organisation-wide",ownerId:item.owner.id,ownerName:item.owner.name,riskLevel:null})),
...manual.map((item)=>event({key:`MANUAL:${item.id}`,title:item.title,description:item.description??calendarStatus(item.status,item.dueDate),date:item.dueDate,type:item.itemType,sourceStatus:item.status,href:null,locationId:item.location?.id??null,locationName:item.location?.name??"Organisation-wide",ownerId:item.owner?.id??null,ownerName:item.owner?.name??"Unassigned",riskLevel:item.riskLevel}))
].sort((a,b)=>a.date.getTime()-b.date.getTime())}finally{await db.$disconnect()}}
