import { describe, expect, it } from "vitest";
import { lifecycleForAction, medicationResolutionBlocksRepeat, monitoringOutcome, refusalRequiresNewAction, suggestActionMatches, validateVerifiedClosure, type FindingInput, type MatchInput } from "@/lib/closure-loop";

const finding: FindingInput = { locationId: "branch-1", clientId: "client-1", staffMemberId: null, category: "Medicines", issueKey: "atorvastatin-stock", medicationIssueType: "OUT_OF_STOCK", sourceType: "REGISTER", sourceRecordId: "source-2", title: "Atorvastatin out of stock", description: "Medicine unavailable during call", occurredAt: new Date("2026-08-13T10:00:00Z") };
const existing: MatchInput = { id: "action-1", locationId: finding.locationId, clientId: finding.clientId, staffMemberId: finding.staffMemberId, category: finding.category, issueKey: finding.issueKey, medicationIssueType: finding.medicationIssueType, sourceType: finding.sourceType, sourceRecordId: "source-1", title: finding.title, description: finding.description, status: "IN_PROGRESS", lifecycleStatus: "ACTION_IN_PROGRESS", lastSeenAt: new Date("2026-08-13T08:00:00Z") };

describe("continuous assurance and closure loop", () => {
  it("A links repeated same-day medication shortages to one action", () => expect(suggestActionMatches(finding, [existing])[0]).toMatchObject({ actionId: "action-1", kind: "LIKELY_DUPLICATE" }));
  it("B prevents a new stock action after verified discontinuation", () => expect(medicationResolutionBlocksRepeat("OUT_OF_STOCK", "DISCONTINUED_BY_PRESCRIBER", "CLOSED_VERIFIED")).toBe(true));
  it("C keeps a GP request awaiting evidence", () => expect(lifecycleForAction({ actionStatus: "AWAITING_EVIDENCE", managementResponse: "Request emailed", evidenceCount: 0, verified: false })).toBe("MANAGEMENT_RESPONSE_RECORDED"));
  it("D avoids duplicate refusal actions when capacity and the care plan controls are satisfied", () => expect(refusalRequiresNewAction({ capacityConfirmed: true, carePlanFollowed: true, offered: true, escalationCompleted: true, thresholdMet: false })).toBe(false));
  it("E identifies a later issue against a closed record as recurrence", () => expect(suggestActionMatches({ ...finding, occurredAt: new Date("2026-09-13") }, [{ ...existing, status: "COMPLETED", lifecycleStatus: "CLOSED_VERIFIED" }])[0].kind).toBe("RECURRENCE"));
  it("F never matches similar wording across different service users", () => expect(suggestActionMatches(finding, [{ ...existing, clientId: "client-2" }])).toEqual([]));
  it("G rejects closure supported only by a management response", () => expect(() => validateVerifiedClosure({ status: "COMPLETED", evidenceCount: 0, managementResponse: "Done", ownerId: "owner", priority: "MEDIUM" })).toThrow(/management response alone/i));
  it("H keeps match rejection as an explicit human decision type", () => expect(["LINK_CONFIRMED", "MATCH_REJECTED"]).toContain("MATCH_REJECTED"));
  it("I records sustained improvement after a recurrence-free monitoring period", () => expect(monitoringOutcome({ monitoringUntil: new Date("2026-08-01"), lastSeenAt: new Date("2026-07-01"), recurrenceCount: 0 }, new Date("2026-08-13"))).toBe("SUSTAINED_IMPROVEMENT"));
  it("J treats missing verification data as missing, not success", () => expect(() => validateVerifiedClosure({ status: "COMPLETED", evidenceCount: 1, completedActionSummary: "Done", evidenceReviewedSummary: "Record", verificationRationale: "Checked", closureNote: "Closed", ownerId: "owner", priority: "MEDIUM" })).toThrow(/named verifier/i));
  it("requires independent verification for high-risk closure", () => expect(() => validateVerifiedClosure({ status: "COMPLETED", evidenceCount: 1, completedActionSummary: "Done", evidenceReviewedSummary: "Record", immediateRiskControlled: true, underlyingRecordCorrected: true, staffSupportCompleted: false, widerRecordsChecked: true, recurrenceChecked: true, verificationRationale: "Checked", closureNote: "Closed", verifiedById: "owner", ownerId: "owner", priority: "HIGH", verificationDate: new Date() })).toThrow(/independent/i));
});
