export type EvidenceRequirement = {
  key: string;
  title: string;
  keyQuestion: "SAFE" | "EFFECTIVE" | "CARING" | "RESPONSIVE" | "WELL_LED";
  qualityStatement: string;
  category: string;
  description: string;
  examples: string[];
  frequency: string;
  regulations: string[];
  sourceUrl: string;
  serviceSpecific?: boolean;
};

const CQC_ASSESSMENT = "https://www.cqc.org.uk/guidance-regulation/providers/assessment/assessment-framework";
const CQC_REGULATIONS = "https://www.cqc.org.uk/guidance-regulation/providers/regulations-service-providers-and-managers";
const REG_12 = "https://www.cqc.org.uk/guidance-regulation/providers/regulations-service-providers-and-managers/health-social-care-act/regulation-12";
const REG_17 = "https://www.cqc.org.uk/guidance-providers/regulations/regulation-17-good-governance";
const REG_18 = "https://www.cqc.org.uk/guidance-regulation/providers/regulations-service-providers-and-managers/health-social-care-act/regulation-18";
const PIR = "https://www.cqc.org.uk/pir-asc-community";
const NOTIFICATIONS = "https://www.cqc.org.uk/guidance-regulation/providers/registration/guidance";
const MEDICINES = "https://www.cqc.org.uk/guidance-providers/adult-social-care/medicines-administration-records-adult-social-care";
const DIGITAL_RECORDS = "https://www.cqc.org.uk/guidance-providers/adult-social-care/digital-record-systems-adult-social-care-services/what-good-records-look-like";

function req(key: string, title: string, keyQuestion: EvidenceRequirement["keyQuestion"], qualityStatement: string, category: string, description: string, examples: string[], frequency: string, regulations: string[], sourceUrl = CQC_ASSESSMENT, serviceSpecific = false): EvidenceRequirement {
  return { key, title, keyQuestion, qualityStatement, category, description, examples, frequency, regulations, sourceUrl, serviceSpecific };
}

export const EVIDENCE_REQUIREMENTS: EvidenceRequirement[] = [
  req("safe-safeguarding-policy", "Safeguarding policy and escalation procedure", "SAFE", "Safeguarding", "Safeguarding", "Shows how concerns are recognised, reported, referred and followed through.", ["Current policy", "Local authority referral route", "Out-of-hours escalation"], "Annual and after guidance changes", ["Regulation 13", "Regulation 17"], CQC_REGULATIONS),
  req("safe-safeguarding-log", "Safeguarding concerns, referrals and outcomes log", "SAFE", "Safeguarding", "Safeguarding", "Demonstrates prompt protection, referral decisions, outcomes and learning.", ["Anonymised safeguarding log", "Section 42 correspondence", "Outcome and lessons learned"], "Live; monthly management review", ["Regulation 13", "Regulation 17"], CQC_REGULATIONS),
  req("safe-incidents", "Incident, accident and near-miss records", "SAFE", "Learning culture", "Incidents", "Provides a complete record of safety events, immediate action and harm.", ["Incident register", "Accident forms", "Near-miss log"], "Live; monthly trend review", ["Regulation 12", "Regulation 17"], REG_12),
  req("safe-investigations", "Incident investigations and lessons learned", "SAFE", "Learning culture", "Quality improvement", "Shows proportionate investigation, root causes, actions and shared learning.", ["Investigation reports", "Lessons-learned briefing", "Completed improvement actions"], "After each significant event; monthly review", ["Regulation 12", "Regulation 17"], REG_17),
  req("safe-duty-candour", "Duty of candour records", "SAFE", "Learning culture", "Incidents", "Evidences openness, apology, written follow-up and communication after notifiable safety incidents.", ["Decision record", "Written notification and apology", "Communication log"], "For every applicable incident", ["Regulation 20"], "https://www.cqc.org.uk/guidance-regulation/providers/regulations-service-providers-and-managers/health-social-care-act/regulation-20/what-you-must-do"),
  req("safe-cqc-notifications", "CQC statutory notifications and acknowledgements", "SAFE", "Learning culture", "CQC notifications", "Shows that notifiable events and changes were submitted within the required timescale.", ["Submitted forms", "Portal or email acknowledgement", "Notification decision log"], "Live; monthly check", ["CQC Registration Regulations 14–18"], NOTIFICATIONS),
  req("safe-risk-assessments", "Person-level risk assessments and reviews", "SAFE", "Safe systems, pathways and transitions", "Audits", "Shows risks are person-centred, current and supported by practical controls.", ["Falls, skin, nutrition and environment assessments", "Review records", "Risk-management plans"], "At start, after change and scheduled review", ["Regulation 12", "Regulation 17"], REG_12),
  req("safe-medicines-policy", "Medicines policy and procedures", "SAFE", "Safe and effective staffing", "Medicines", "Defines safe ordering, storage, administration, recording, errors and escalation.", ["Current medicines policy", "PRN protocol", "Controlled-drug arrangements where applicable"], "Annual and after guidance changes", ["Regulation 12", "Regulation 17"], MEDICINES),
  req("safe-mar", "Medication administration records and audits", "SAFE", "Safe systems, pathways and transitions", "Medicines", "Shows each medicine support episode was recorded and checked.", ["MAR samples", "MAR audit reports", "Omission follow-up"], "Every administration; monthly audit", ["Regulation 12", "Regulation 17"], MEDICINES),
  req("safe-medication-errors", "Medication errors, near misses and learning", "SAFE", "Learning culture", "Medicines", "Tracks errors, clinical advice, harm, notifications and preventive action.", ["Error log", "Investigation", "Competency reassessment"], "Live; monthly trend review", ["Regulation 12", "Regulation 13", "Regulation 17"], MEDICINES),
  req("safe-medicines-competency", "Medicines competency assessments", "SAFE", "Safe and effective staffing", "Competencies", "Confirms staff are observed and authorised before supporting medicines.", ["Observed competency form", "Assessor decision", "Reassessment after error"], "Before practice and at least annually", ["Regulation 12", "Regulation 18"], REG_18),
  req("safe-infection-control", "Infection prevention and control assurance", "SAFE", "Infection prevention and control", "Infection control", "Shows infection risks, PPE practice, training, audits and outbreak response are controlled.", ["IPC policy", "Audit", "Training compliance", "Outbreak record"], "Monthly/quarterly and after an outbreak", ["Regulation 12"], REG_12),
  req("safe-moving-handling", "Moving and handling plans and competencies", "SAFE", "Safe and effective staffing", "Competencies", "Demonstrates assessed techniques, equipment and competent staff.", ["Individual handling plans", "Equipment instructions", "Observed competency"], "At start, after change and annually", ["Regulation 12", "Regulation 18"], REG_12),
  req("safe-equipment", "Equipment safety checks and maintenance", "SAFE", "Safe environments", "Health and safety", "Shows care equipment is suitable, maintained and defects are acted upon.", ["Equipment register", "LOLER/service certificates where applicable", "Defect log"], "According to manufacturer and risk", ["Regulation 12", "Regulation 15"], REG_12, true),
  req("safe-missed-late-visits", "Missed and late visit monitoring", "SAFE", "Safe systems, pathways and transitions", "Audits", "Shows exceptions are identified, people are protected and repeated causes are addressed.", ["ECM exception report", "Missed/late visit register", "Corrective actions"], "Daily monitoring; monthly trend review", ["Regulation 12", "Regulation 17"], REG_17),
  req("safe-staffing-rota", "Staffing rotas, capacity and contingency cover", "SAFE", "Safe and effective staffing", "Recruitment", "Shows sufficient skilled staff were planned and deployed to meet assessed needs.", ["Rotas", "Capacity assessment", "On-call and emergency cover"], "Live; weekly and monthly review", ["Regulation 18"], REG_18),
  req("safe-recruitment-files", "Safer recruitment files and checks", "SAFE", "Safe and effective staffing", "Recruitment", "Demonstrates identity, employment history, references, suitability and risk decisions.", ["Application and interview", "Two verified references", "Employment-gap risk assessment"], "Before employment; audit quarterly", ["Regulation 19", "Schedule 3"], CQC_REGULATIONS),
  req("safe-dbs", "DBS and barred-list assurance", "SAFE", "Safe and effective staffing", "Recruitment", "Shows appropriate checks, certificate decisions and update-service reviews.", ["DBS status record", "Risk assessment", "Renewal or update-service check"], "Before work and provider-defined review", ["Regulation 19"], "https://www.gov.uk/guidance/dbs-check-requests-guidance-for-employers"),
  req("safe-right-work", "Right-to-work and visa monitoring", "SAFE", "Safe and effective staffing", "Recruitment", "Shows lawful employment and timely follow-up of time-limited permissions.", ["Check record", "Share-code result", "Visa expiry tracker"], "Before employment and before expiry", ["Regulation 19"], "https://www.gov.uk/check-job-applicant-right-to-work"),
  req("safe-whistleblowing", "Whistleblowing arrangements and concern log", "SAFE", "Freedom to speak up", "Staff feedback", "Shows staff can raise concerns safely and leaders respond without detriment.", ["Policy", "Confidential concern log", "Investigation and feedback"], "Annual policy review; live log", ["Regulation 17"], REG_17),
  req("effective-assessments", "Initial needs assessments", "EFFECTIVE", "Assessing needs", "Audits", "Shows physical, mental, social, communication and equality needs were assessed before care began.", ["Pre-service assessment", "Clinical and social needs", "Commissioner information"], "Before service and after material change", ["Regulation 9", "Regulation 12"], CQC_REGULATIONS),
  req("effective-care-plans", "Person-centred care plans and reviews", "EFFECTIVE", "Assessing needs", "Audits", "Shows agreed outcomes, preferences, routines and support instructions remain current.", ["Care-plan sample", "Review schedule", "Change records"], "At start, scheduled review and after change", ["Regulation 9", "Regulation 17"], DIGITAL_RECORDS),
  req("effective-consent", "Consent, capacity and best-interest records", "EFFECTIVE", "Consent to care and treatment", "Audits", "Shows valid consent and lawful decisions where capacity is in question.", ["Consent record", "Capacity assessment", "Best-interest decision", "LPA evidence"], "Decision-specific and after change", ["Regulation 11", "Mental Capacity Act 2005"], CQC_REGULATIONS),
  req("effective-training-matrix", "Mandatory and role-specific training matrix", "EFFECTIVE", "Safe and effective staffing", "Training", "Shows required learning, completion, expiry and recovery action for every role.", ["Training matrix", "Certificates", "Overdue recovery plan"], "Live; monthly review", ["Regulation 18"], REG_18),
  req("effective-induction", "Induction and Care Certificate records", "EFFECTIVE", "Safe and effective staffing", "Training", "Shows new workers were prepared, supervised and assessed for their role.", ["Induction checklist", "Care Certificate", "Shadowing and sign-off"], "For every starter", ["Regulation 18"], REG_18),
  req("effective-competency-matrix", "Staff competency matrix and observed assessments", "EFFECTIVE", "Safe and effective staffing", "Competencies", "Shows role competencies are assessed, current and linked to duties.", ["Competency matrix", "Observed practice", "Development plans"], "Before unsupervised work and scheduled review", ["Regulation 12", "Regulation 18"], REG_18),
  req("effective-supervision", "Staff supervision records", "EFFECTIVE", "Safe and effective staffing", "Supervision", "Demonstrates regular support, performance discussion and risk escalation.", ["Supervision schedule", "Signed records", "Follow-up actions"], "Provider-defined schedule; monthly compliance review", ["Regulation 18"], REG_18),
  req("effective-appraisals", "Annual appraisals and development plans", "EFFECTIVE", "Safe and effective staffing", "Supervision", "Shows performance, values, objectives and development needs are reviewed.", ["Appraisal record", "Objectives", "Development plan"], "At least annually", ["Regulation 18"], REG_18),
  req("effective-spot-checks", "Care-worker spot checks", "EFFECTIVE", "Safe and effective staffing", "Competencies", "Provides direct assurance of care practice, dignity, recording and PPE.", ["Observed-practice form", "Feedback", "Corrective action"], "Risk-based and provider-defined", ["Regulation 12", "Regulation 18"], REG_18),
  req("effective-professional-registration", "Professional registration and revalidation", "EFFECTIVE", "Safe and effective staffing", "Certificates", "Confirms regulated professionals remain registered and supported to meet standards.", ["Registration check", "Revalidation record", "Expiry alert"], "On appointment and before renewal", ["Regulation 18", "Regulation 19"], REG_18, true),
  req("effective-delegated-healthcare", "Delegated healthcare task authorisation", "EFFECTIVE", "How staff, teams and services work together", "Competencies", "Shows a named clinician delegated the task with instructions, competency and review.", ["Delegation record", "Clinical protocol", "Staff competency", "Review"], "Before task and at each review", ["Regulation 12", "Regulation 18"], REG_12, true),
  req("effective-nutrition", "Nutrition and hydration assessments and monitoring", "EFFECTIVE", "Supporting people to live healthier lives", "Audits", "Shows risks, preferences, intake concerns and referrals are monitored.", ["Assessment", "Care plan", "Food/fluid chart where required", "Referral"], "At start and risk-based review", ["Regulation 14"], CQC_REGULATIONS, true),
  req("effective-transitions", "Hospital admission, discharge and handover records", "EFFECTIVE", "Safe systems, pathways and transitions", "Audits", "Shows timely information sharing and follow-up when care transfers.", ["Handover", "Discharge information", "Post-discharge review"], "For every transition", ["Regulation 12"], REG_12),
  req("effective-outcomes", "Individual outcomes and progress reviews", "EFFECTIVE", "Monitoring and improving outcomes", "Quality improvement", "Shows whether support is achieving outcomes that matter to each person.", ["Outcome plan", "Progress review", "Person’s view"], "At care-plan review and after change", ["Regulation 9", "Regulation 17"], CQC_ASSESSMENT),
  req("caring-feedback", "People’s feedback and satisfaction evidence", "CARING", "Kindness, compassion and dignity", "Service-user feedback", "Captures lived experience, including people who face communication barriers.", ["Survey results", "Interviews", "Feedback cards", "You said, we did"], "Continuous; formal review at least annually", ["Regulation 9", "Regulation 17"], "https://www.cqc.org.uk/guidance-regulation/providers/assessment/evidence-categories/peoples-experience"),
  req("caring-compliments", "Compliments and positive-practice log", "CARING", "Kindness, compassion and dignity", "Service-user feedback", "Shows what people value and how good practice is recognised and repeated.", ["Compliments log", "Thank-you messages", "Shared learning"], "Live; quarterly themes", ["Regulation 17"], CQC_ASSESSMENT),
  req("caring-dignity", "Dignity, privacy and respectful-care assurance", "CARING", "Kindness, compassion and dignity", "Audits", "Demonstrates respectful practice through observations, feedback and action.", ["Spot checks", "Care observations", "Feedback", "Dignity audit"], "Quarterly and risk-based", ["Regulation 10"], CQC_REGULATIONS),
  req("caring-involvement", "People’s involvement in care planning", "CARING", "Treating people as individuals", "Service-user feedback", "Shows people and representatives shape goals, routines and reviews.", ["Signed care plans", "Review notes", "Accessible choices"], "At start and every review", ["Regulation 9", "Regulation 11"], CQC_ASSESSMENT),
  req("caring-equality", "Equality, diversity and reasonable-adjustment evidence", "CARING", "Treating people as individuals", "Quality improvement", "Shows protected characteristics, cultural needs and inequalities are understood and acted upon.", ["Equality assessment", "Reasonable-adjustment plan", "Accessible information"], "At assessment; annual organisational review", ["Regulation 9", "Regulation 10", "Equality Act 2010"], CQC_REGULATIONS),
  req("caring-communication", "Communication and accessible-information plans", "CARING", "Independence, choice and control", "Audits", "Shows information and communication are adapted to individual needs.", ["Communication passport", "Preferred format", "Interpreter or advocacy arrangements"], "At start and after change", ["Regulation 9", "Accessible Information Standard"], CQC_ASSESSMENT),
  req("caring-advocacy", "Advocacy and representation records", "CARING", "Independence, choice and control", "Other", "Shows access to independent support where people need help expressing decisions or rights.", ["Advocacy referral", "Representative involvement", "Decision record"], "When required", ["Regulation 9", "Regulation 11"], CQC_ASSESSMENT, true),
  req("responsive-complaints", "Complaints register, responses and outcomes", "RESPONSIVE", "Listening to and involving people", "Complaints", "Shows acknowledgement, investigation, response, remedy and learning within timescales.", ["Complaint log", "Acknowledgement", "Final response", "Learning action"], "Live; monthly review", ["Regulation 16", "Regulation 17"], CQC_REGULATIONS),
  req("responsive-call-log", "Call log for telephone and other communications", "RESPONSIVE", "Person-centred care", "Other", "Provides a traceable record of important inbound and outbound calls, decisions and follow-up.", ["Call Log export", "Follow-up actions", "Linked correspondence"], "Live; daily follow-up review", ["Regulation 9", "Regulation 17"], DIGITAL_RECORDS),
  req("responsive-preferences", "Visit schedules, preferences and continuity monitoring", "RESPONSIVE", "Person-centred care", "Audits", "Shows visits reflect assessed timing, worker preferences and continuity wherever practicable.", ["Planned rota", "Continuity report", "Preference exceptions"], "Weekly; monthly trend review", ["Regulation 9", "Regulation 17"], CQC_ASSESSMENT),
  req("responsive-referrals", "Referral, start, handback and discharge records", "RESPONSIVE", "Care provision, integration and continuity", "Other", "Shows referral decisions, capacity, safe starts and responsible service endings.", ["Referral log", "Assessment decision", "Start/handback record", "Handover"], "For every referral or service change", ["Regulation 9", "Regulation 12", "Regulation 17"], PIR),
  req("responsive-end-life", "End-of-life wishes and coordination records", "RESPONSIVE", "Care provision, integration and continuity", "Audits", "Shows preferences, anticipatory plans and multi-agency coordination where applicable.", ["Advance care plan", "DNACPR location record", "Family/professional communication"], "When applicable and after change", ["Regulation 9", "Regulation 12"], CQC_ASSESSMENT, true),
  req("responsive-service-information", "Service-user guide and complaints information", "RESPONSIVE", "Equity in access", "Other", "Shows people receive accessible information about the service, charges, rights and concerns.", ["Service-user guide", "Terms and conditions", "Complaints leaflet"], "Annual and after change", ["Regulation 9", "Regulation 16"], CQC_REGULATIONS),
  req("well-registration", "CQC registration, conditions and statement of purpose", "WELL_LED", "Governance, management and sustainability", "Registration", "Shows the service operates within its registered activities, locations and conditions.", ["Certificate", "Statement of purpose", "Registered manager details"], "Annual and after change", ["Registration Regulation 12"], CQC_REGULATIONS),
  req("well-insurance", "Current insurance certificates", "WELL_LED", "Governance, management and sustainability", "Insurance", "Demonstrates required employer, public and professional cover.", ["Employer’s liability", "Public liability", "Professional indemnity where applicable"], "Before expiry", ["Employer’s Liability legislation", "Contract requirements"], CQC_REGULATIONS),
  req("well-org-chart", "Governance structure, roles and accountability", "WELL_LED", "Shared direction and culture", "Governance meetings", "Makes leadership, escalation, delegated authority and oversight clear.", ["Organisation chart", "Role descriptions", "Delegation matrix", "On-call structure"], "Annual and after change", ["Regulation 5", "Regulation 7", "Regulation 17"], REG_17),
  req("well-policy-control", "Policy register, approvals and version control", "WELL_LED", "Governance, management and sustainability", "Policies", "Shows policies are owned, approved, current, communicated and archived safely.", ["Policy index", "Approval record", "Review schedule", "Version history"], "Monthly oversight; each policy by review date", ["Regulation 17"], REG_17),
  req("well-audit-programme", "Quality audit programme and completed audits", "WELL_LED", "Governance, management and sustainability", "Audits", "Shows systematic monitoring across care, records, medicines, staff and service delivery.", ["Annual audit schedule", "Completed audits", "Trend report"], "Monthly/quarterly according to risk", ["Regulation 17"], REG_17),
  req("well-actions", "Quality improvement and corrective-action tracker", "WELL_LED", "Learning, improvement and innovation", "Quality improvement", "Shows findings have owners, deadlines, evidence of completion and verification.", ["Action plan", "Completion evidence", "Effectiveness check"], "Live; reviewed at least monthly", ["Regulation 17"], REG_17),
  req("well-risk-register", "Organisational risk register and reviews", "WELL_LED", "Governance, management and sustainability", "Health and safety", "Shows strategic and operational risks, controls, ownership and review.", ["Risk register", "Risk reviews", "Escalations to governance"], "Monthly/quarterly and after change", ["Regulation 17"], REG_17),
  req("well-governance-minutes", "Governance meeting minutes and decisions", "WELL_LED", "Governance, management and sustainability", "Governance meetings", "Records oversight of quality, risk, workforce, complaints, incidents and improvement.", ["Agenda", "Minutes", "Attendance", "Decision and action log"], "Monthly or provider-defined", ["Regulation 17"], REG_17),
  req("well-kpis", "Quality, workforce and commissioner KPI reports", "WELL_LED", "Governance, management and sustainability", "Quality improvement", "Shows leaders use reliable performance information to identify risk and improvement.", ["Monthly dashboard", "Commissioner return", "Trend analysis", "Management commentary"], "Monthly", ["Regulation 17"], PIR),
  req("well-pir", "Provider Information Return and supporting evidence", "WELL_LED", "Governance, management and sustainability", "CQC notifications", "Keeps the annual PIR response and the evidence used to support it inspection-ready.", ["Submitted PIR", "Submission summary", "Supporting data pack"], "Annually when requested", ["Regulation 17(3)"], PIR),
  req("well-business-continuity", "Business continuity plan, tests and lessons", "WELL_LED", "Planning for the future", "Business continuity", "Shows critical care can continue through technology, staffing, utilities or premises disruption.", ["Plan", "Contact tree", "Exercise report", "Lessons and retest"], "Annual exercise and after activation", ["Regulation 12", "Regulation 17"], REG_17),
  req("well-data-protection", "Data protection accountability pack", "WELL_LED", "Governance, management and sustainability", "Certificates", "Shows lawful, secure and proportionate handling of care, staff and governance information.", ["ROPA", "Privacy notices", "DPIAs", "Retention schedule", "Data-sharing agreements"], "Annual and after processing change", ["UK GDPR", "Data Protection Act 2018"], DIGITAL_RECORDS),
  req("well-data-breaches", "Data breach and information-risk records", "WELL_LED", "Learning culture", "Incidents", "Shows containment, risk assessment, notification decisions and prevention.", ["Breach log", "ICO decision record", "Investigation", "Improvement action"], "Live; monthly review", ["UK GDPR Articles 33–34", "Regulation 17"], DIGITAL_RECORDS),
  req("well-access-security", "Access reviews, backups and cyber assurance", "WELL_LED", "Governance, management and sustainability", "Certificates", "Shows access is role-based, reviewed, backed up and protected from common threats.", ["User access review", "Backup/restore test", "Cyber Essentials or DSPT evidence", "Incident response test"], "Quarterly access review; annual assurance", ["UK GDPR Article 32", "Regulation 17"], DIGITAL_RECORDS),
  req("well-record-retention", "Records retention and secure disposal schedule", "WELL_LED", "Governance, management and sustainability", "Policies", "Defines how long care, workforce and governance records are kept and how disposal is authorised.", ["Retention schedule", "Disposal log", "Legal-hold process"], "Annual and after guidance changes", ["UK GDPR storage limitation", "Regulation 17"], "https://transform.england.nhs.uk/information-governance/guidance/records-management-code/"),
  req("well-staff-feedback", "Staff survey, engagement and speaking-up evidence", "WELL_LED", "Workforce equality, diversity and inclusion", "Staff feedback", "Shows leaders listen to staff, analyse themes and report action taken.", ["Survey", "Team forum notes", "You said, we did", "Whistleblowing themes"], "At least annually; continuous routes", ["Regulation 17", "Regulation 18"], "https://www.cqc.org.uk/guidance-regulation/providers/assessment/evidence-categories/feedback-staff-and-leaders"),
  req("well-partner-feedback", "Commissioner and partner feedback", "WELL_LED", "Partnerships and communities", "Quality improvement", "Shows constructive working with commissioners, health professionals and safeguarding partners.", ["Contract reviews", "Professional feedback", "Partnership meeting records"], "Quarterly and after significant feedback", ["Regulation 12", "Regulation 17"], CQC_ASSESSMENT),
  req("well-financial", "Financial sustainability and resource assurance", "WELL_LED", "Governance, management and sustainability", "Other", "Shows the provider can sustain safe staffing, systems and service commitments.", ["Management accounts", "Budget oversight", "Going-concern or continuity assurance"], "Monthly/quarterly", ["Regulation 17", "Registration Regulation 13"], CQC_REGULATIONS),
  req("well-rating-display", "CQC rating display evidence", "WELL_LED", "Governance, management and sustainability", "Registration", "Shows the current rating is displayed correctly at locations and online where required.", ["Website screenshot", "Location photograph", "Display review"], "After rating change and quarterly check", ["Regulation 20A"], CQC_REGULATIONS, true),
];

export function evidenceRequirementByKey(key: string | null | undefined) {
  return EVIDENCE_REQUIREMENTS.find((item) => item.key === key);
}

export function evidenceRequirementStatus(items: { reviewExpiryDate: Date | null }[], now = new Date()) {
  if (!items.length) return "NEEDS_EVIDENCE" as const;
  if (items.every((item) => item.reviewExpiryDate && item.reviewExpiryDate < now)) return "EXPIRED" as const;
  const soon = new Date(now); soon.setDate(soon.getDate() + 30);
  if (items.some((item) => item.reviewExpiryDate && item.reviewExpiryDate <= soon)) return "REVIEW_SOON" as const;
  return "CURRENT" as const;
}
