import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const interfaceFiles = [
  "src/app/(app)/policies/page.tsx",
  "src/components/policy-studio.tsx",
  "src/components/module-placeholder.tsx",
  "src/app/(app)/evidence/page.tsx",
  "src/app/(app)/evidence/[id]/page.tsx",
  "src/app/(app)/audits/page.tsx",
  "src/app/(app)/registers/page.tsx",
  "src/app/(app)/risks/page.tsx",
  "src/app/(app)/meetings/page.tsx",
  "src/app/(app)/kpis/page.tsx",
  "src/app/(app)/activity/page.tsx",
  "src/app/(app)/calendar/page.tsx",
];

const banned = [
  "new premium product",
  "premium policy product",
  "source-grounded",
  "scalable assurance catalogue",
  "comprehensive registers",
  "ready for its build milestone",
  "module foundation",
  "deliberately not implemented",
  "generated by qcgms",
  "live system record",
  "one-copy live evidence link",
];

describe("interface wording", () => {
  it("does not show promotional or development-language phrases", () => {
    const copy = interfaceFiles.map((file) => readFileSync(resolve(file), "utf8").toLowerCase()).join("\n");
    for (const phrase of banned) expect(copy, phrase).not.toContain(phrase);
  });
});
