export type PolicySource = { key: string; title: string; publisher: string; url: string; relevance: string; checkedAt: string };
export type PolicyTemplate = { key: string; title: string; category: string; cqcKey: "Safe" | "Effective" | "Caring" | "Responsive" | "Well-led"; complianceAreas: string[]; sourceKeys: string[]; purpose: string; practice: string[]; evidence: string };
export type PolicyBrand = { name: string; registrationNumber?: string | null; address?: string | null; email?: string | null; phone?: string | null; website?: string | null; primaryColour?: string | null; footerText?: string | null };
export type GeneratedPolicySection = { heading: string; paragraphs: string[] };

const CHECKED = "2026-08-01";
export const POLICY_TEMPLATE_VERSION = "2026.08";

export const POLICY_SOURCES: Record<string, PolicySource> = Object.fromEntries([
  source("cqc-framework", "CQC assessment framework", "Care Quality Commission", "https://www.cqc.org.uk/guidance-regulation/providers/assessment/assessment-framework", "The five key questions, quality statements and provider expectations."),
  source("cqc-homecare", "Homecare and shared lives evidence categories", "Care Quality Commission", "https://www.cqc.org.uk/guidance-regulation/providers/assessment/homecare-and-shared-lives-services-evidence-categories/well-led", "Examples of evidence CQC may consider for homecare and shared lives services."),
  source("regulated-activities", "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014", "UK Legislation", "https://www.legislation.gov.uk/uksi/2014/2936/contents", "The fundamental standards applying to regulated activities in England."),
  source("registration-regs", "Care Quality Commission (Registration) Regulations 2009", "UK Legislation", "https://www.legislation.gov.uk/uksi/2009/3112/contents", "Registration, statement of purpose, notifications and provider information requirements."),
  source("care-act", "Care and support statutory guidance", "Department of Health and Social Care", "https://www.gov.uk/government/publications/care-act-statutory-guidance/care-and-support-statutory-guidance", "Care Act duties, wellbeing, safeguarding, cooperation and person-led practice."),
  source("mca-code", "Mental Capacity Act Code of Practice", "Office of the Public Guardian", "https://www.gov.uk/government/publications/mental-capacity-act-code-of-practice", "Decision-specific capacity, best interests and least restrictive practice."),
  source("dols-code", "Deprivation of Liberty Code of Practice", "Office of the Public Guardian", "https://www.gov.uk/government/publications/deprivation-of-liberty-code-of-practice", "Current safeguards and authorisation framework for deprivation of liberty."),
  source("nice-community-medicines", "Managing medicines for adults receiving social care in the community (NG67)", "NICE", "https://www.nice.org.uk/guidance/ng67", "Assessment, medicines support, records, errors, review and safeguarding in community care."),
  source("nice-medicines-standard", "Medicines management for people receiving social care in the community (QS171)", "NICE", "https://www.nice.org.uk/guidance/qs171", "Priority quality statements for safe, person-centred medicines support."),
  source("ipc-code", "Code of practice on prevention and control of infections", "Department of Health and Social Care", "https://www.gov.uk/government/publications/the-health-and-social-care-act-2008-code-of-practice-on-the-prevention-and-control-of-infections-and-related-guidance/health-and-social-care-act-2008-code-of-practice-on-the-prevention-and-control-of-infections-and-related-guidance", "The infection prevention criteria considered in regulated health and adult social care."),
  source("ipc-social-care", "Infection prevention and control in adult social care settings", "Department of Health and Social Care", "https://www.gov.uk/government/publications/infection-prevention-and-control-in-adult-social-care-settings", "Current operational infection prevention principles for adult social care."),
  source("ico-data", "Data protection guidance for organisations", "Information Commissioner's Office", "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/", "UK GDPR accountability, lawful processing, security, rights and breach management."),
  source("ico-health", "Transparency in health and social care", "Information Commissioner's Office", "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/transparency-in-health-and-social-care/", "Clear and lawful use of health and social care information."),
  source("hse-care", "Health and social care services", "Health and Safety Executive", "https://www.hse.gov.uk/healthservices/", "Employer duties and sector-specific health and safety risk controls."),
  source("hse-moving", "Moving and handling in health and social care", "Health and Safety Executive", "https://www.hse.gov.uk/healthservices/moving-handling/manage-the-risk.htm", "Policy, assessment, equipment, training and monitoring expectations."),
  source("hse-riddor", "RIDDOR guidance", "Health and Safety Executive", "https://www.hse.gov.uk/riddor/", "Statutory reporting of specified work-related incidents and diseases."),
  source("acas-whistleblowing", "Whistleblowing at work", "Acas", "https://www.acas.org.uk/whistleblowing-at-work/having-a-whistleblowing-policy", "Good practice for raising, investigating and protecting disclosures."),
  source("acas-discipline", "Discipline and grievances at work", "Acas", "https://www.acas.org.uk/acas-code-of-practice-on-disciplinary-and-grievance-procedures", "Fair workplace disciplinary and grievance procedures."),
  source("employment-rights", "Employment Rights Act 1996", "UK Legislation", "https://www.legislation.gov.uk/ukpga/1996/18/contents", "Core statutory employment rights, written particulars, protected disclosures, dismissal and worker protections."),
  source("equality-act", "Equality Act 2010", "UK Legislation", "https://www.legislation.gov.uk/ukpga/2010/15/contents", "Employment and service protections from discrimination, harassment and victimisation, including reasonable adjustments."),
  source("working-time", "Working Time Regulations 1998", "UK Legislation", "https://www.legislation.gov.uk/uksi/1998/1833/contents", "Working time, rest and paid annual-leave requirements relevant to safe workforce planning."),
  source("gov-employing", "Get ready to employ someone", "GOV.UK", "https://www.gov.uk/get-ready-to-employ-someone", "Official employer responsibilities covering status, pay, written terms, safety, equality and statutory employment arrangements."),
  source("right-to-work", "Right to work checks: an employer's guide", "Home Office", "https://www.gov.uk/government/publications/right-to-work-checks-employers-guide", "Current prescribed right-to-work checking, evidence and follow-up requirements."),
  source("dbs-employers", "DBS checks guidance for employers", "Disclosure and Barring Service", "https://www.gov.uk/guidance/dbs-check-requests-guidance-for-employers", "Eligibility, lawful requests, applicant rights, storage and the DBS Code of Practice."),
  source("acas-leave", "Holiday and leave", "Acas", "https://www.acas.org.uk/holiday-and-leave", "Employment-law good practice for annual leave, sickness, family leave, absence and return to work."),
  source("acas-adjustments", "Reasonable adjustments at work", "Acas", "https://www.acas.org.uk/reasonable-adjustments", "Individual reasonable-adjustment duties and fair workplace implementation under the Equality Act 2010."),
  source("skills-conduct", "Code of Conduct for adult social care workers", "Skills for Care", "https://www.skillsforcare.org.uk/Support-for-leaders-and-managers/Managing-people/Code-of-conduct/Code-of-conduct.aspx", "Expected conduct and employer support for adult social care workers."),
  source("skills-supervision", "Effective supervision guide", "Skills for Care", "https://www.skillsforcare.org.uk/Support-for-leaders-and-managers/Managing-people/Supervision/Supervision.aspx", "Good practice for reflective, accountable supervision."),
].map((item) => [item.key, item]));

function source(key: string, title: string, publisher: string, url: string, relevance: string): PolicySource { return { key, title, publisher, url, relevance, checkedAt: CHECKED }; }
function policy(key: string, title: string, category: string, cqcKey: PolicyTemplate["cqcKey"], complianceAreas: string[], sourceKeys: string[], purpose: string, practice: string[], evidence: string): PolicyTemplate { return { key, title, category, cqcKey, complianceAreas, sourceKeys, purpose, practice, evidence }; }

export const POLICY_CATALOGUE: PolicyTemplate[] = [
  policy("adult-safeguarding", "Adult safeguarding policy and procedure", "Safeguarding", "Safe", ["Regulation 13", "Care Act 2014"], ["regulated-activities", "care-act", "cqc-framework"], "to prevent abuse and neglect and ensure concerns are recognised, reported and managed without delay", ["Any immediate danger must be addressed first by contacting emergency services where necessary, arranging urgent medical help and taking proportionate steps to protect the adult and others.", "The worker must listen without leading questions, preserve available evidence, record facts and the adult's words, notify the manager immediately and follow the local authority safeguarding pathway.", "The manager must consider consent, capacity, advocacy, police involvement, CQC notifications, duty of candour, staff suspension or risk controls and must cooperate with any section 42 enquiry."], "safeguarding referrals, decision logs, body maps where appropriate, chronology, notifications, outcomes, learning and completed actions"),
  policy("safeguarding-children", "Safeguarding children and young people policy", "Safeguarding", "Safe", ["Regulation 13", "Children Act duties"], ["regulated-activities", "care-act", "cqc-framework"], "to protect children encountered through the service and ensure concerns reach the correct statutory agency", ["Workers must never assume that another professional has reported a concern and must act promptly where a child may be at risk.", "The designated safeguarding lead must follow local multi-agency procedures, consider emergency police or children's social care referral and record the rationale for every decision.", "Information must be shared lawfully, proportionately and in the child's best interests, with parental involvement unless this would increase risk or prejudice an investigation."], "referral records, safeguarding advice, chronologies, information-sharing decisions, outcomes and learning"),
  policy("whistleblowing", "Freedom to speak up and whistleblowing policy", "Whistleblowing", "Well-led", ["Regulation 17", "Public Interest Disclosure Act 1998"], ["acas-whistleblowing", "cqc-homecare", "regulated-activities"], "to give workers safe routes to raise public-interest concerns without retaliation", ["A worker may raise a concern with their line manager, a senior leader or the named whistleblowing contact and may bypass normal reporting lines where those lines are implicated.", "The receiving manager must acknowledge the disclosure, assess immediate safety, protect confidentiality as far as possible, arrange an impartial review and keep the worker informed within lawful limits.", "Victimisation, threats, loss of opportunity or other detriment because of a protected disclosure will be treated as a serious matter and external prescribed-person routes will remain available."], "disclosure register, acknowledgements, risk actions, investigation records, outcomes, support and monitoring for detriment"),
  policy("duty-candour", "Duty of candour and openness policy", "Duty of Candour", "Safe", ["Regulation 20"], ["regulated-activities", "cqc-framework"], "to ensure the organisation is open, honest and supportive when care goes wrong", ["The organisation will be open in all interactions and will separately identify whether an event meets the statutory threshold for a notifiable safety incident.", "Where the statutory duty applies, an appropriate representative will provide a truthful account, explain known facts and enquiries, offer a sincere apology, give reasonable support and confirm the notification in writing.", "The process must not delay safeguarding, emergency treatment, notification, investigation or action to reduce continuing risk."], "candour assessment, verbal and written notifications, apology, support offered, investigation, family communication and learning"),
  policy("complaints", "Complaints, concerns and compliments policy", "Complaints", "Responsive", ["Regulation 16"], ["regulated-activities", "cqc-framework"], "to make feedback easy, accessible, fair and useful for improvement", ["People may complain verbally, in writing, through a representative or in an accessible format and will not receive poorer care because they raised a concern.", "The manager will acknowledge the complaint, agree the issues and desired outcome, investigate impartially, maintain confidentiality and provide a reasoned response within the organisation's published timescale.", "Responses will explain findings, apologies or remedies, improvement action and escalation routes, while themes and response times will be reviewed through governance."], "complaint record, consent, acknowledgement, investigation material, response, remedy, satisfaction and improvement action"),
  policy("medicines", "Medicines management policy and procedure", "Medicines", "Safe", ["Regulation 12", "Regulation 13"], ["nice-community-medicines", "nice-medicines-standard", "regulated-activities"], "to ensure medicines support is person-centred, authorised, accurately recorded and delivered by competent workers", ["Medicines support must begin with an assessment of the person's abilities, preferences, consent, risks, prescribed directions and agreed responsibilities, which must be reflected in the care plan.", "Only trained and assessed workers may provide the level of support authorised for them, and every administration, prompt, refusal, omission, error and disposal must be recorded at the time.", "Errors or adverse effects require immediate clinical advice where indicated, protection from harm, transparent reporting, safeguarding consideration, investigation and learning without unsafe concealment."], "medicines assessment, care plan, MAR, competency, reconciliation, reviews, errors, clinical advice and pharmacy communication"),
  policy("prn-covert", "PRN, covert medicines and self-administration procedure", "Medicines", "Safe", ["Regulation 11", "Regulation 12", "Mental Capacity Act 2005"], ["nice-community-medicines", "nice-medicines-standard", "mca-code"], "to protect autonomy and ensure higher-risk medicines arrangements are individually authorised and reviewed", ["A person will be supported to self-administer whenever this is their informed choice and risks can be managed through an agreed plan.", "Each PRN medicine requires an individual protocol describing indication, non-drug approaches, dose, interval, maximum dose, monitoring, escalation and how effectiveness is recorded.", "Covert administration may occur only after decision-specific capacity assessment and a documented best-interests process involving the prescriber and pharmacist, with the least restrictive method and regular review."], "capacity and best-interests records, PRN protocols, risk assessments, administration records, monitoring and multidisciplinary reviews"),
  policy("infection-control", "Infection prevention and control policy", "Infection prevention and control", "Safe", ["Regulation 12", "IPC Code of Practice"], ["ipc-code", "ipc-social-care", "regulated-activities"], "to embed proportionate infection prevention in daily care and protect people, workers and visitors", ["Standard infection control precautions apply according to the task and assessed risk, including hand hygiene, respiratory hygiene, appropriate PPE, safe waste and linen handling and environmental cleanliness.", "Workers must report symptoms, exposures, outbreaks, sharps injuries or failures in controls promptly so that clinical and public health advice can be obtained and staffing or visiting risks managed.", "The IPC lead will maintain risk assessments, supplies, training, competency checks, audits, outbreak records and an annual review of infection prevention performance."], "IPC risk assessments, audits, training, competency, outbreak logs, cleaning records, exposure management and annual statement"),
  policy("health-safety", "Health and safety policy", "Health and safety", "Safe", ["Regulation 12", "Health and Safety at Work etc. Act 1974"], ["hse-care", "regulated-activities", "cqc-framework"], "to manage risks to people, workers and others through clear responsibilities and proportionate controls", ["Senior leadership will provide suitable resources, competent advice and oversight, while managers will assess risks, implement controls and consult workers.", "Workers must follow safe systems, use equipment correctly, report hazards and incidents and stop work where there is a serious and immediate danger.", "Risk controls will be reviewed after incidents, changes in work, new equipment or guidance and through a planned audit programme."], "risk assessments, maintenance, training, consultation, inspections, incidents, statutory reports and corrective actions"),
  policy("moving-handling", "Moving and handling policy and procedure", "Health and safety", "Safe", ["Regulation 12", "Manual Handling Operations Regulations 1992"], ["hse-moving", "hse-care", "regulated-activities"], "to prevent avoidable injury while supporting each person's dignity, mobility and independence", ["Hazardous manual handling will be avoided where reasonably practicable and unavoidable tasks will be assessed for the person, worker, task, environment and equipment.", "The individual handling plan must specify techniques, number of workers, equipment, sling details, communication, consent and contingency arrangements and must be available where care is delivered.", "Only workers trained and assessed as competent may undertake the task, and damaged equipment, changed mobility or unsafe conditions require work to stop and the plan to be reviewed."], "individual assessments, handling plans, competency, equipment checks, maintenance, incidents and post-incident review"),
  policy("lone-working", "Lone working and personal safety policy", "Health and safety", "Safe", ["Regulation 12", "Health and Safety at Work etc. Act 1974"], ["hse-care", "regulated-activities"], "to protect workers delivering care alone without withdrawing person-centred support unnecessarily", ["Managers will assess travel, environment, known behaviour, communication, medication, animals, access and emergency risks before lone work is allocated.", "Workers will follow check-in arrangements, carry agreed communication and identification, maintain professional boundaries and leave or summon help where risk becomes unacceptable.", "Missed check-ins, threats, violence or welfare concerns will activate a defined escalation response and the assessment will be reviewed before further visits."], "lone-working assessments, alerts, check-in records, incidents, staff support and control reviews"),
  policy("fire-safety", "Fire safety and evacuation policy", "Health and safety", "Safe", ["Regulation 12", "Regulatory Reform (Fire Safety) Order 2005"], ["hse-care", "regulated-activities"], "to prevent fire and ensure safe, person-specific action during an emergency", ["The organisation will maintain proportionate fire risk assessments for premises and consider fire risks encountered in people's homes during service assessment and review.", "Workers must know how to raise the alarm, contact emergency services, support people according to their plan and avoid placing themselves or others in unreasonable danger.", "Equipment, escape routes, drills, training and personal emergency arrangements will be checked and shortcomings acted on promptly."], "fire risk assessments, PEEPs where applicable, drills, equipment checks, training and remedial actions"),
  policy("coshh", "Control of substances hazardous to health policy", "Health and safety", "Safe", ["COSHH Regulations 2002", "Regulation 12"], ["hse-care", "regulated-activities"], "to control exposure to cleaning chemicals, infectious agents and other hazardous substances", ["Hazardous substances will be identified and assessed before use, with safer alternatives selected where reasonably practicable.", "Controls will address storage, labelling, dilution, ventilation, PPE, spill response, disposal, exposure and access to safety information.", "Workers must not mix chemicals or use unlabelled products and must report exposure, damaged packaging or ineffective controls immediately."], "COSHH assessments, safety data, inventories, training, exposure records and control reviews"),
  policy("incident-riddor", "Incident, accident, near miss and RIDDOR policy", "Health and safety", "Safe", ["Regulation 12", "Regulation 17", "RIDDOR 2013"], ["hse-riddor", "regulated-activities", "cqc-framework"], "to ensure events are treated, reported, investigated and used to reduce recurrence", ["Immediate priorities are emergency care, scene safety, preservation of evidence and protection of people from continuing harm.", "All incidents and near misses must be recorded promptly and escalated according to severity, including safeguarding, police, commissioner, CQC, HSE and duty of candour consideration.", "Investigation must be proportionate, identify system and human factors, involve affected people where appropriate and lead to owned, timed and verified improvement actions."], "incident form, chronology, injury record, notifications, investigation, candour, learning review and action closure"),
  policy("business-continuity", "Business continuity and emergency preparedness policy", "Business continuity", "Well-led", ["Regulation 17", "Regulation 18"], ["cqc-homecare", "regulated-activities", "cqc-framework"], "to maintain safe priority care through disruption and recover services in a controlled way", ["Plans will identify critical activities, people at greatest risk, minimum staffing, dependencies, communication routes and recovery priorities for credible disruption scenarios.", "The incident lead will assess impact, activate the proportionate response, maintain a decision log and communicate with people, workers, commissioners and emergency partners.", "Exercises and real activations will be reviewed to update contacts, assumptions, mutual aid, technology, supplies and recovery arrangements."], "business impact assessment, plans, contact trees, exercises, activation logs, communications and lessons learned"),
  policy("safer-recruitment", "Safer recruitment and selection policy", "Recruitment", "Safe", ["Regulation 19", "Schedule 3"], ["regulated-activities", "cqc-homecare", "skills-conduct"], "to appoint fit, suitable and values-aligned workers through fair and evidenced checks", ["Selection will use a defined role profile, fair shortlisting, structured interview and exploration of values, competence and gaps in employment.", "Required identity, right-to-work, employment history, references, relevant qualifications, health capability and criminal record checks must be satisfactorily resolved before unsupervised work.", "Risk assessments and documented senior authorisation are required where information is incomplete or raises concern, and no risk decision may override a legal restriction."], "application, interview scoring, identity, references, DBS, right-to-work, qualifications, risk decisions and approval"),
  policy("dbs-right-work", "DBS, barred list and right-to-work checking procedure", "Recruitment", "Safe", ["Regulation 19", "Schedule 3"], ["regulated-activities", "cqc-homecare"], "to complete lawful pre-employment and renewal checks and respond to changes", ["The appropriate level of DBS and barred-list check will be determined from the regulated activity and role rather than applied without analysis.", "Original or approved digital evidence of identity and right to work must be checked, copied and dated in accordance with current Home Office requirements, with time-limited status monitored.", "New convictions, cautions, restrictions or immigration changes must be reported and considered through a fair, documented risk and employment process."], "check type and date, certificate decision, identity evidence, right-to-work evidence, expiry alerts and risk assessment"),
  policy("induction-training", "Induction, training and competency policy", "Workforce", "Effective", ["Regulation 18"], ["regulated-activities", "skills-conduct", "cqc-framework"], "to ensure every worker has the knowledge, skills, values and assessed competence required for their role", ["Induction will be role-specific and include organisational values, rights, safeguarding, emergency arrangements, information governance and supervised practice before unsupervised duties.", "Training requirements will be set from law, role, service risks and individual need, with expiry monitoring and protected time to complete learning.", "Competence will be assessed through observation, questioning, records or simulation as appropriate and retraining or restricted duties will follow where safe practice is not demonstrated."], "induction checklist, training matrix, certificates, competency assessments, supervision and development plans"),
  policy("supervision-appraisal", "Supervision, appraisal and performance development policy", "Workforce", "Well-led", ["Regulation 18"], ["skills-supervision", "regulated-activities", "cqc-homecare"], "to provide regular reflective oversight, wellbeing support and accountable development", ["Supervision will be planned at a frequency proportionate to role, experience and risk and will provide protected space for reflection and challenge.", "Discussion will cover people supported, safeguarding, incidents, medicines, competence, workload, wellbeing, conduct, equality, learning and agreed actions.", "Annual appraisal will evaluate performance and values over the whole period, recognise contribution and agree measurable development objectives without replacing routine supervision."], "supervision schedule, confidential record, actions, appraisal, objectives and follow-up"),
  policy("code-conduct", "Professional conduct and boundaries policy", "Workforce", "Caring", ["Regulation 19"], ["skills-conduct", "regulated-activities", "cqc-framework"], "to define respectful conduct, professional boundaries and accountability in care relationships", ["Workers must act honestly, preserve dignity, respect choice, avoid discrimination and place the safety and wellbeing of people above personal interests.", "Personal, financial, sexual or social relationships that exploit trust are prohibited, and gifts, social media contact and conflicts must be declared and managed.", "Concerns about conduct will be assessed fairly alongside immediate protection, safeguarding, referral and employment duties."], "signed code, declarations, boundary advice, conduct concerns, referrals and outcomes"),
  policy("equality-human-rights", "Equality, diversity, inclusion and human rights policy", "Equality and diversity", "Caring", ["Regulation 9", "Regulation 10", "Equality Act 2010"], ["regulated-activities", "cqc-framework", "cqc-homecare"], "to deliver equitable care and employment that respects identity, culture, rights and individual experience", ["Assessments and service design will explore communication, culture, faith, sexuality, gender identity, disability and other needs without stereotypes or assumptions.", "Reasonable adjustments and accessible information will be agreed, recorded and reviewed so that people can participate and achieve equitable outcomes.", "Discrimination, harassment and victimisation will be challenged, investigated and used to improve practice and organisational culture."], "equality assessment, reasonable adjustments, accessible formats, feedback, incidents, training and equality actions"),
  policy("disciplinary", "Disciplinary policy and procedure", "Workforce", "Well-led", ["Employment Rights Act 1996", "ACAS Code"], ["acas-discipline", "skills-conduct"], "to address conduct fairly, consistently and without delaying protection from harm", ["Informal improvement will be considered where appropriate, but serious allegations may require precautionary measures that are neutral and reviewed regularly.", "Formal cases will involve a reasonable investigation, written allegations, access to evidence, a hearing, the right to be accompanied, a reasoned outcome and appeal.", "Safeguarding, professional referral, police or regulatory duties will be considered separately from the employment decision and coordinated lawfully."], "allegation, risk decision, investigation, invitations, hearing, outcome, appeal and referrals"),
  policy("grievance", "Grievance policy and procedure", "Workforce", "Well-led", ["Employment Rights Act 1996", "ACAS Code"], ["acas-discipline", "cqc-homecare"], "to resolve workplace concerns fairly and protect open, inclusive working relationships", ["Workers are encouraged to raise concerns early and may use the formal route where informal resolution is unsuitable or unsuccessful.", "The manager will clarify the grievance, investigate proportionately, hold a meeting, consider requested adjustments and provide a written, reasoned decision with appeal rights.", "Where the concern is a protected disclosure, safeguarding matter or allegation of abuse, the corresponding procedure will be activated rather than treating it only as a grievance."], "grievance, adjustments, investigation, meeting, outcome, appeal and improvement action"),
  policy("absence-wellbeing", "Sickness absence, wellbeing and return-to-work policy", "Workforce", "Well-led", ["Equality Act 2010", "Health and Safety duties"], ["hse-care", "cqc-homecare", "ico-data"], "to support health, maintain safe staffing and manage attendance fairly", ["Workers must report absence through the agreed route and provide information necessary for safe staffing without being required to disclose irrelevant medical detail.", "Managers will maintain appropriate contact, consider occupational health advice, disability-related adjustments, infection risks and a supported return to work.", "Attendance review will be fair, evidence-based and sensitive to disability, pregnancy, work-related harm and the confidentiality of health information."], "absence notification, certification, contact, occupational advice, adjustments, return-to-work discussion and review decisions"),
  policy("data-protection", "Data protection, confidentiality and privacy policy", "Information governance", "Well-led", ["UK GDPR", "Data Protection Act 2018", "Regulation 17"], ["ico-data", "ico-health", "cqc-homecare"], "to process personal and special-category information lawfully, fairly, transparently and securely", ["Each processing activity must have a documented purpose, lawful basis and, where needed, Article 9 condition, with data minimised to what is necessary.", "Access is role-based and information may be shared only with authority, for a legitimate purpose and through an appropriately secure method, while recognising lawful safeguarding and care-sharing duties.", "People will receive clear privacy information and requests for access, correction, restriction or other rights will be identified and escalated without delay."], "record of processing, privacy notices, sharing decisions, access reviews, rights requests, retention and training"),
  policy("records-management", "Records management and retention policy", "Information governance", "Well-led", ["Regulation 17", "UK GDPR"], ["ico-data", "regulated-activities", "cqc-homecare"], "to create accurate, contemporaneous, accessible and appropriately retained records", ["Records must be factual, dated, attributable, legible and sufficient to explain assessment, consent, care delivered, decisions, incidents and follow-up.", "Corrections must preserve the original entry and show who made the change, when and why; records must never be falsified, backdated or destroyed to conceal events.", "Retention and secure disposal will follow an approved schedule that accounts for legal, contractual, safeguarding and limitation requirements."], "care and governance records, amendments, access logs, retention schedule, legal holds and destruction certificates"),
  policy("cyber-breach", "Cyber security and personal data breach policy", "Information governance", "Well-led", ["UK GDPR Articles 32 and 33", "Regulation 17"], ["ico-data", "cqc-homecare"], "to prevent, contain, assess and report security incidents affecting care or personal information", ["Devices, accounts and systems will use proportionate access control, supported software, secure configuration, backups and monitoring, with multi-factor authentication where available.", "Suspected loss, disclosure, malware, phishing or unauthorised access must be reported immediately and preserved for assessment rather than hidden or informally deleted.", "The response lead will contain the incident, assess harm, restore safe service, determine ICO and individual notification duties, record the decision and verify improvement actions."], "asset and access records, incident chronology, risk assessment, notifications, recovery, lessons and control testing"),
  policy("consent", "Consent to care, treatment and information sharing policy", "Consent", "Effective", ["Regulation 11", "Mental Capacity Act 2005"], ["regulated-activities", "mca-code", "cqc-framework"], "to ensure consent is informed, voluntary, decision-specific and reviewed", ["People will receive information they can understand about proposed care, choices, benefits, material risks and alternatives and will have opportunity to ask questions.", "Consent must be sought before care and may be expressed verbally, in writing or through clear conduct; refusal or withdrawal must be respected unless a lawful basis permits otherwise.", "Where there is reason to doubt capacity, the worker must pause non-urgent action and obtain decision-specific assessment and best-interests authority rather than relying on diagnosis or family preference alone."], "information provided, consent, refusals, capacity assessment, best-interests decision, representatives and review"),
  policy("mental-capacity", "Mental capacity, best interests and least restrictive practice policy", "Mental Capacity Act", "Effective", ["Regulation 11", "Mental Capacity Act 2005"], ["mca-code", "dols-code", "regulated-activities"], "to apply the Mental Capacity Act principles consistently and protect autonomy", ["Capacity is presumed and assessed only for the specific decision at the time, after practicable support has been offered to help the person decide.", "Where capacity is lacking, the decision maker will identify authority, consult relevant people, consider wishes, beliefs and alternatives and record why the decision is in the person's best interests.", "Any restriction must be necessary, proportionate and the least restrictive available, with possible deprivation of liberty escalated for lawful authorisation in the relevant setting."], "support to decide, capacity assessment, best-interests record, consultation, restrictions, authorisation and review"),
  policy("restrictive-practice", "Restrictive practice, restraint and deprivation of liberty policy", "Mental Capacity Act", "Safe", ["Regulation 13", "Mental Capacity Act 2005"], ["mca-code", "dols-code", "regulated-activities"], "to prevent unlawful restriction and reduce restrictive practices through person-centred alternatives", ["Restriction must never be used for punishment, convenience, coercion or as a substitute for staffing, skill or appropriate care planning.", "Where an immediate intervention is necessary to prevent harm, it must be proportionate, used for the shortest time and followed by welfare checks, reporting and review.", "Planned restrictions require lawful authority, assessment, person involvement, alternatives, monitoring and reduction goals, and potential deprivation of liberty requires specialist legal escalation."], "restriction assessment, consent or authority, care plan, incident record, monitoring, review and reduction action"),
  policy("person-centred-care", "Person-centred care planning and review policy", "Care delivery", "Responsive", ["Regulation 9"], ["regulated-activities", "cqc-framework", "care-act"], "to co-produce care that reflects the person's strengths, goals, identity, preferences and changing needs", ["Assessment will begin with what matters to the person and will cover outcomes, strengths, communication, culture, relationships, health, medicines, risks and desired involvement of others.", "The plan will describe agreed support in clear practical language, balance safety with positive risk taking and be available to workers at the point of care.", "Review will occur at the agreed interval and promptly after significant change, incident, hospital transition, concern or request, with the person and authorised others involved."], "assessment, outcome-focused plan, consent, risks, daily records, reviews, changes and person feedback"),
  policy("risk-management", "Care risk assessment and positive risk-taking policy", "Care delivery", "Safe", ["Regulation 12"], ["regulated-activities", "cqc-framework", "care-act"], "to identify and control avoidable harm while respecting choice, independence and ordinary life", ["Risk assessment will be collaborative, specific to the person and activity and will consider likelihood, impact, existing controls, strengths and the person's own view.", "Controls must be proportionate, practical and recorded in the care plan, with clear contingency and escalation arrangements rather than blanket restrictions.", "Assessments will be reviewed after change, incident or concern and at the planned interval, and unresolved high risk will be escalated to an accountable manager."], "risk assessment, person involvement, controls, contingency, review, incidents and escalations"),
  policy("nutrition-hydration", "Nutrition, hydration and food safety policy", "Care delivery", "Effective", ["Regulation 14", "Regulation 12"], ["regulated-activities", "cqc-framework", "care-act"], "to support safe nutrition and hydration that respects preferences, culture and clinical need", ["Assessment will identify preferences, allergies, swallowing, equipment, assistance, fortified diets, fluid needs and professional instructions and will be reflected in the care plan.", "Workers will provide dignified support, prepare food safely, record intake where required and escalate refusal, weight loss, dehydration, choking or swallowing concerns promptly.", "Clinical advice and emergency action will be sought according to risk, and modified diets or thickened fluids will follow current authorised recommendations."], "assessment, care plan, intake and weight records, allergies, professional guidance, competency and escalation"),
  policy("end-life", "End of life, advance care planning and bereavement policy", "Care delivery", "Caring", ["Regulation 9", "Regulation 10"], ["regulated-activities", "cqc-framework", "care-act"], "to provide compassionate, coordinated and culturally sensitive support at the end of life", ["Conversations will be led by the person's readiness and will explore wishes, relationships, faith, comfort, preferred place of care and involvement of authorised representatives.", "Workers will follow current care plans and clinical directions, recognise deterioration, escalate symptoms and maintain dignity, privacy and communication with the multidisciplinary team.", "After death, staff will follow verification, notification, property, infection control and family support arrangements and will be offered reflection and support."], "advance plans, capacity and consent, clinical instructions, communication, care records, after-death checks and bereavement support"),
  policy("dignity-respect", "Dignity, privacy and respectful care policy", "Care delivery", "Caring", ["Regulation 10"], ["regulated-activities", "cqc-framework"], "to make dignity, privacy, compassion and respect visible in every interaction", ["Workers will introduce themselves, seek permission, protect privacy, explain care, use the person's preferred name and respect personal routines, possessions and relationships.", "Intimate care will use appropriate covering, privacy and choice of worker where reasonably possible, with no unnecessary exposure or discussion in public areas.", "Demeaning language, ridicule, infantilisation, discrimination or avoidable intrusion will be challenged and reported."], "preferences, consent, observations, feedback, concerns, training and improvement actions"),
  policy("accessible-information", "Communication and accessible information policy", "Care delivery", "Responsive", ["Regulation 9", "Accessible Information Standard"], ["regulated-activities", "cqc-framework", "care-act"], "to identify, record, flag, share and meet each person's communication needs", ["Assessment will establish language, sensory, cognitive, literacy, cultural and technological needs and the person's preferred communication methods.", "Information will be offered in an accessible format and communication support, interpreter or advocate arranged where needed for meaningful participation.", "Needs and adjustments will be visible to authorised workers, reviewed after change and transferred safely when the person moves between services."], "communication assessment, flags, formats provided, interpreter or advocacy, review and person feedback"),
  policy("missed-visits", "Care visits, lateness and missed-call procedure", "Care delivery", "Responsive", ["Regulation 9", "Regulation 12", "Regulation 17"], ["regulated-activities", "cqc-framework"], "to deliver agreed visits reliably and respond safely when a visit is late, missed or cannot be completed", ["The service will plan sufficient travel and staffing and will monitor exceptions rather than treating lateness as inevitable.", "A late or potentially missed visit requires prompt contact, risk assessment, prioritisation of time-critical care, alternative cover and communication with the person or representative.", "No-access situations require the person's agreed contingency plan, welfare escalation and accurate recording, while repeated exceptions require root-cause review and commissioner communication where applicable."], "planned and actual visit times, contact attempts, risk decisions, replacement cover, welfare checks, notifications and trend actions"),
  policy("delegated-healthcare", "Delegated healthcare tasks and clinical governance policy", "Care delivery", "Effective", ["Regulation 12", "Regulation 18"], ["regulated-activities", "cqc-framework", "nice-community-medicines"], "to accept and deliver delegated tasks only where accountability, instruction and competence are clear", ["Before accepting a task, the manager will confirm the delegating professional, individual plan, legal and contractual scope, equipment, supplies, monitoring and emergency arrangements.", "Each worker must receive person-specific training and competence assessment by an appropriate professional and may decline or stop if instructions, competence or conditions are unsafe.", "Changes, errors, deterioration and unavailable support will be escalated immediately, with competence reviewed at the agreed interval and after incidents."], "delegation agreement, clinical instructions, consent, worker competency, monitoring, escalation and review"),
  policy("falls-pressure", "Falls, skin integrity and pressure damage prevention policy", "Care delivery", "Safe", ["Regulation 12"], ["regulated-activities", "cqc-framework", "care-act"], "to identify changing risk and coordinate timely prevention and clinical escalation", ["Assessment will consider previous falls, mobility, medicines, cognition, environment, footwear, nutrition, skin condition, equipment and professional advice.", "Care plans will specify person-centred prevention, observation, repositioning or equipment where authorised and the action required after a fall or skin change.", "Workers must not move a person after a fall without assessment where injury is possible and must obtain urgent clinical support for red flags, record findings and trigger review."], "falls and skin assessments, care plans, body maps, equipment, observations, clinical referrals, incidents and review"),
  policy("quality-governance", "Quality assurance and governance policy", "Governance", "Well-led", ["Regulation 17"], ["regulated-activities", "cqc-homecare", "cqc-framework"], "to provide reliable oversight of quality, safety, outcomes, risk and improvement", ["Named leaders will review evidence from audits, incidents, complaints, safeguarding, medicines, workforce, feedback, outcomes, risks and contractual performance at a defined cadence.", "Information will be validated, analysed for inequity and trends and challenged in governance meetings, with decisions and accountable actions recorded.", "Improvement will be verified for impact rather than closed on activity alone, and significant gaps will be escalated to the provider, commissioners or regulator as required."], "governance calendar, dashboards, audits, minutes, risk register, action tracker, feedback and effectiveness review"),
  policy("audit-improvement", "Audit, learning and continuous improvement policy", "Governance", "Well-led", ["Regulation 17"], ["regulated-activities", "cqc-homecare", "cqc-framework"], "to use proportionate audit and learning to improve outcomes rather than merely demonstrate activity", ["The annual audit programme will be based on risk, regulation, service data, previous findings and the experience of people and workers.", "Audits will use defined criteria, representative evidence and transparent scoring, with findings distinguishing isolated error from systemic weakness.", "Actions will have owners, deadlines, evidence and success measures, and follow-up will test whether change is embedded and beneficial."], "audit programme, tools, samples, findings, actions, re-audit, outcome measures and shared learning"),
  policy("notifications", "CQC and statutory notifications policy", "Governance", "Well-led", ["CQC Registration Regulations 2009"], ["registration-regs", "regulated-activities", "cqc-framework"], "to identify and submit required notifications accurately and without avoidable delay", ["Managers will maintain a current notification decision guide and will escalate potentially notifiable events to the registered person promptly.", "The decision will consider the event, regulated activity, harm, police or safeguarding involvement and relevant statutory category, with specialist advice sought where uncertain.", "Submission, supporting facts, reference, corrections and follow-up communication will be recorded and reviewed alongside incident, candour and improvement processes."], "decision record, notification form, submission reference, correspondence, linked incident and follow-up"),
  policy("visiting-community", "Visitors, contractors and working in people's homes policy", "Care delivery", "Caring", ["Regulation 10", "Regulation 12"], ["regulated-activities", "cqc-framework", "hse-care"], "to respect the person's home while managing identity, safety, confidentiality and third-party risks", ["Workers will remember that they are guests in the person's home, will show identification, follow agreed access arrangements and respect property, privacy and household preferences.", "Contractors or observers require authorisation, identity checks, confidentiality expectations and the person's consent unless a lawful emergency or statutory power applies.", "Unsafe premises, abuse, environmental hazards, animals, smoking or third-party conduct will be managed through proportionate assessment and escalation rather than judgment or discrimination."], "consent, access plan, visitor or contractor checks, environmental risks, concerns and agreed controls"),
  policy("financial-property", "People's money, property, gifts and financial safeguarding policy", "Safeguarding", "Safe", ["Regulation 13", "Care Act 2014"], ["care-act", "regulated-activities", "skills-conduct"], "to prevent financial abuse and ensure any authorised support is transparent and accountable", ["Workers must not borrow from, lend to, trade with or seek gifts, bequests, passwords or personal benefit from people using the service.", "Where financial support is commissioned and consented, the care plan will define the task, limits, receipts, reconciliation and oversight and will keep the person's money separate from organisational or worker funds.", "Missing money, unusual transactions, coercion, gifts or concerns about capacity require immediate reporting, preservation of records and safeguarding consideration."], "authorisation, transaction and receipt records, reconciliations, gift declarations, concerns and safeguarding outcomes"),
  policy("service-continuity", "Admission, commencement, transfer and discharge policy", "Care delivery", "Responsive", ["Regulation 9", "Regulation 12"], ["regulated-activities", "cqc-framework", "care-act"], "to ensure safe, planned and person-centred transitions into, between and out of services", ["Service commencement requires sufficient assessment, consent, staffing, information, equipment, medicines arrangements and contingency planning before support begins.", "Transfers will use current, necessary information shared securely with the receiving service and will include risks, medicines, communication needs and unresolved actions.", "Discharge or service termination will be planned, explained and coordinated without unsafe abandonment, with urgent commissioner escalation where needs can no longer be met safely."], "referral, assessment, acceptance decision, transition plan, information transfer, discharge rationale and handover confirmation"),
  policy("working-partnership", "Partnership working and information sharing policy", "Governance", "Well-led", ["Regulation 17", "Care Act cooperation duties"], ["care-act", "ico-health", "cqc-homecare"], "to coordinate care with partners while sharing information lawfully and proportionately", ["The service will clarify roles, accountability and communication with commissioners, clinicians, pharmacies, emergency services, advocates and other providers.", "Information will be shared on a need-to-know basis using the appropriate lawful basis, with the person's expectations and confidentiality considered and safeguarding overrides documented.", "Disagreement or delay that threatens care will be escalated through professional and contractual routes and recorded until resolved."], "agreements, referrals, multidisciplinary communication, sharing decisions, escalation and partner feedback"),
];

export function sourceAnnex(template: PolicyTemplate): PolicySource[] {
  const keys = [...template.sourceKeys];
  if (["Workforce", "Recruitment", "Whistleblowing", "Equality and diversity"].includes(template.category)) keys.push("employment-rights", "equality-act", "gov-employing");
  if (template.key === "dbs-right-work" || template.key === "safer-recruitment") keys.push("right-to-work", "dbs-employers");
  if (template.key === "absence-wellbeing") keys.push("working-time", "acas-leave", "acas-adjustments");
  return [...new Set(keys)].map((key) => POLICY_SOURCES[key]).filter(Boolean);
}
export function policyTemplate(key: string) { return POLICY_CATALOGUE.find((item) => item.key === key); }

export function generatePolicySections(template: PolicyTemplate, brand: PolicyBrand): GeneratedPolicySection[] {
  const name = brand.name.trim() || "the provider";
  const sources = sourceAnnex(template).map((item) => `${item.publisher}: ${item.title}`).join("; ");
  const employmentRelated = ["Workforce", "Recruitment", "Whistleblowing", "Equality and diversity"].includes(template.category);
  return [
    { heading: "Policy statement", paragraphs: [`${name} is committed ${template.purpose}. This controlled policy sets the minimum organisational standard. It must be read with the person's care plan, local safeguarding and emergency arrangements, employment obligations and any current professional instruction that applies to the situation.`, `This template is CQC-aligned and source-grounded, but adoption does not by itself demonstrate compliance. ${name} must confirm that the document reflects its regulated activities, service model, contracts, local authority pathways, staffing and actual practice before approval.`] },
    { heading: "Purpose and intended outcomes", paragraphs: [`The purpose of this policy is ${template.purpose}. The intended outcome is safe, lawful, person-centred practice that can be evidenced through consistent records, competent decisions and timely improvement.`, `The policy supports the CQC ${template.cqcKey} key question and the following compliance areas: ${template.complianceAreas.join(", ")}. Regulatory references are described in the source annex and must be checked again whenever this policy is reviewed.`] },
    { heading: "Scope", paragraphs: [`This policy applies to directors, registered persons, managers, employees, agency workers, contractors, volunteers and any other person acting on behalf of ${name}. It applies across every location and to remote or community work where the organisation controls or influences the activity.`, `Nothing in this policy authorises a worker to act outside their competence, professional scope, delegated authority or the person's consent. Where law, current clinical instruction or local multi-agency procedure sets a higher or more specific standard, that standard must be followed and the manager informed.`] },
    { heading: "Rights and decision-making", paragraphs: [`Practice must preserve dignity, privacy, equality, autonomy and the person's right to be involved. Information must be communicated in an accessible way, consent must be sought where required, and decision-specific mental capacity principles must be applied whenever there is reason to doubt capacity.`, `Safety measures must be proportionate and must not become blanket restrictions. The person's wishes, strengths, culture, relationships and desired outcomes must be considered alongside foreseeable risk, with advocacy or authorised representatives involved where appropriate.`] },
    { heading: "Regulatory and legal basis", paragraphs: [`This policy is grounded in ${template.complianceAreas.join(", ")}. Its controlled source annex identifies the legislation, CQC requirements and official sector guidance used when the template was prepared. The policy owner must resolve any conflict in favour of current law and must obtain competent advice where interpretation affects a person's rights, safety or employment.`, employmentRelated ? `Because this policy affects workers, ${name} must also apply current employment contracts, collective or recognition arrangements, statutory employment rights, equality duties, data protection, working-time and health-and-safety obligations. A fair procedure in this document must not be treated as legal advice for an individual employment case; material dismissal, immigration, discrimination, transfer or contractual-change decisions require suitably qualified HR or legal review.` : `CQC alignment describes how this document supports regulated care governance; it does not predict or guarantee an inspection judgement. Compliance depends on implementation, competent practice, accurate records, oversight and evidence that learning improves outcomes.`] },
    { heading: "Responsibilities", paragraphs: [`The registered provider remains accountable for adequate resources, oversight and a culture in which concerns are acted on. The Registered Manager is responsible for implementing this policy, confirming local procedures, assigning competent leads and reporting material gaps through governance.`, `Line managers are responsible for briefing workers, checking competence, supervising practice, reviewing records and escalating concerns. Every worker is responsible for following the current approved version, recording contemporaneously, reporting changes and stopping or seeking advice when safe practice cannot be assured.`] },
    { heading: "Procedure", paragraphs: template.practice },
    { heading: "Records and evidence", paragraphs: [`The organisation will maintain ${template.evidence}. Records must be factual, attributable, dated, secure, proportionate and available to authorised reviewers. Corrections must preserve the original entry and explain who changed it, when and why.`, `Records will be retained and disposed of under the approved retention schedule. Access, sharing and confidentiality will follow the organisation's information governance controls, while safeguarding, statutory reporting and legal-preservation duties will take precedence where applicable.`] },
    { heading: "Training, competence and supervision", paragraphs: [`Workers will receive role-appropriate induction, training, supervised practice and competence assessment before undertaking duties covered by this policy without support. Managers will determine refresher frequency from law, guidance, role, incidents, audit and individual need rather than relying only on certificate expiry.`, `Supervision will create space to examine judgement, values, workload, concerns and learning. A worker who is not competent or whose practice creates risk will receive immediate protection measures, support and reassessment, with duties restricted where necessary.`] },
    { heading: "Monitoring and improvement", paragraphs: [`${name} will monitor this policy through audits, record sampling, incident and complaint themes, feedback from people and workers, supervision, outcome measures and governance review. Findings will lead to named actions with deadlines, evidence and measures of success.`, `Leaders will test whether improvement is embedded and beneficial. Serious, repeated or systemic gaps will be placed on the risk register and escalated to the registered provider, commissioners, safeguarding partners, CQC or another authority where required.`] },
    { heading: "Review and approval", paragraphs: [`This policy is a draft until approved through ${name}'s governance process. It must be reviewed at least annually and sooner after relevant legal or guidance change, a serious incident, service-model change, audit finding or evidence that the procedure is not achieving its intended outcome.`, `The source annex was last checked on ${CHECKED} and currently includes ${sources}. The policy owner must verify that every link and requirement remains current before approval and must record local customisations, consultation, implementation arrangements and the next review date.`] },
  ];
}

export function policyBrandFromOrganisation(organisation: { name: string; policyBrandName: string | null; policyRegistrationNumber: string | null; policyAddress: string | null; policyEmail: string | null; policyPhone: string | null; policyWebsite: string | null; policyPrimaryColour: string; policyFooterText: string | null }): PolicyBrand {
  return { name: organisation.policyBrandName || organisation.name, registrationNumber: organisation.policyRegistrationNumber, address: organisation.policyAddress, email: organisation.policyEmail, phone: organisation.policyPhone, website: organisation.policyWebsite, primaryColour: organisation.policyPrimaryColour, footerText: organisation.policyFooterText };
}
