import { describe, expect, it } from "vitest";
import { generatePolicySections, POLICY_CATALOGUE, policyBrandFromOrganisation, policyTemplate, sourceAnnex } from "@/lib/policy-catalogue";

describe("premium policy catalogue", () => {
  it("contains a comprehensive catalogue with unique keys", () => { expect(POLICY_CATALOGUE.length).toBeGreaterThanOrEqual(35); expect(new Set(POLICY_CATALOGUE.map(({ key }) => key)).size).toBe(POLICY_CATALOGUE.length); });
  it("grounds every policy in authoritative sources", () => { for (const template of POLICY_CATALOGUE) { expect(sourceAnnex(template).length).toBeGreaterThanOrEqual(2); expect(sourceAnnex(template).every(({ url }) => url.startsWith("https://"))).toBe(true); } });
  it("generates branded paragraph-led content without bullet markers", () => { const template = policyTemplate("adult-safeguarding")!; const sections = generatePolicySections(template, { name: "Example Care Ltd" }); expect(sections[0].paragraphs.join(" ")).toContain("Example Care Ltd"); expect(sections.length).toBeGreaterThanOrEqual(10); expect(sections.flatMap(({ paragraphs }) => paragraphs).every((paragraph) => !/^\s*[-*•]/.test(paragraph))).toBe(true); });
  it("adds employment-law grounding to workforce policies", () => { const template = policyTemplate("disciplinary")!; const annex = sourceAnnex(template); expect(annex.some(({ key }) => key === "employment-rights")).toBe(true); expect(annex.some(({ key }) => key === "equality-act")).toBe(true); const legalSection = generatePolicySections(template, { name: "Example Care Ltd" }).find(({ heading }) => heading === "Regulatory and legal basis"); expect(legalSection?.paragraphs.join(" ")).toContain("employment contracts"); });
  it("uses professional policy language without template disclaimers", () => { const content = generatePolicySections(policyTemplate("adult-safeguarding")!, { name: "Example Care Ltd" }).flatMap(({ paragraphs }) => paragraphs).join(" "); expect(content).not.toContain("This template"); expect(content).not.toContain("does not predict or guarantee"); expect(content).not.toContain("must not be treated as legal advice"); expect(content).toContain("Example Care Ltd is committed"); });
  it("binds policy branding to the registered organisation name", () => { expect(policyBrandFromOrganisation({ name: "Registered Care Ltd", policyBrandName: "Different Brand", policyRegistrationNumber: null, policyAddress: null, policyEmail: null, policyPhone: null, policyWebsite: null, policyPrimaryColour: "#0f766e", policyFooterText: null }).name).toBe("Registered Care Ltd"); });
});
