import { createHash } from "node:crypto";
import type { PrismaClient } from "@/generated/prisma/client";

type Definition = {
  title: string;
  category: string;
  description: string;
  tags: string[];
  body: string;
};

type Section = [heading: string, prompts: string[]];

function document(title: string, purpose: string, sections: Section[]): string {
  return [
    title.toUpperCase(),
    "Controlled registered-manager working document",
    "",
    "DOCUMENT CONTROL",
    "Organisation:",
    "Service / location:",
    "Document owner:",
    "Reference and version:",
    "Effective date:",
    "Next review date:",
    "Approved by / date:",
    "",
    "PURPOSE AND EXPECTED OUTCOME",
    purpose,
    "Record objective evidence, name accountable owners and verify that actions improve outcomes for people. Do not include unnecessary personal or special-category information.",
    ...sections.flatMap(([heading, prompts]) => ["", heading.toUpperCase(), ...prompts]),
    "",
    "MANAGEMENT ASSURANCE AND SIGN-OFF",
    "Overall assurance: Assured / Partially assured / Not assured",
    "Key strengths:",
    "Material risks or gaps:",
    "Actions, owners and deadlines:",
    "How effectiveness will be checked:",
    "Registered Manager decision:",
    "Registered Manager name / signature / date:",
    "Next review or re-audit date:",
  ].join("\n");
}

const control: Section = ["Evidence and control test", ["Requirement or control being tested:", "Sample selected and rationale:", "Evidence examined:", "Finding and impact on people:", "Assurance judgement and reason:"]];
const action: Section = ["Action and verification", ["Required improvement:", "Accountable owner:", "Priority and due date:", "Evidence required for closure:", "Effectiveness review date and outcome:"]];

function template(title: string, category: string, description: string, purpose: string, sections: Section[], tags: string[] = []): Definition {
  return { title, category, description, tags: ["premium", "rm-grade", "controlled-document", ...tags], body: document(title, purpose, sections) };
}

const NEW_PREMIUM_TEMPLATES: Definition[] = [
  template("Registered Manager annual audit programme", "Audit forms", "Risk-based annual audit schedule with ownership, frequency, standards and governance oversight.", "Plan a proportionate audit programme covering regulatory, clinical, operational and workforce assurance.", [["Programme scope", ["Year:", "Regulated activities and locations in scope:", "Regulatory and contractual priorities:", "Known risks, incidents and previous weak assurance:"]], ["Audit schedule", ["Audit area / standard:", "Frequency and rationale:", "Lead auditor and reviewer:", "Planned sample and evidence sources:", "Reporting forum and due date:"]], ["Programme review", ["Audits completed / overdue:", "Themes and repeat findings:", "Changes required to the programme:"]], action], ["audit", "programme"]),
  template("Audit evidence and sampling record", "Audit forms", "Defensible sampling and evidence trail for any internal audit.", "Show how the audit sample was chosen, what was tested and the limitations of the assurance conclusion.", [["Audit definition", ["Audit title and objective:", "Standard, policy or regulation tested:", "Population and reporting period:", "Sampling method: random / targeted / stratified / full population:", "Sample size and reason:"]], ["Evidence schedule", ["Evidence reference:", "Record date and owner:", "Test performed:", "Result: compliant / partial / non-compliant / not applicable:", "Auditor note:"]], ["Limitations", ["Unavailable records or exclusions:", "Potential bias or uncertainty:", "Effect on assurance conclusion:"]], control, action], ["audit", "sampling", "evidence"]),
  template("Audit finding, action and effectiveness review", "Audit forms", "End-to-end record from finding through verified sustainable closure.", "Ensure audit findings are risk-rated, corrected, independently verified and closed only when impact is demonstrated.", [["Finding", ["Audit and finding reference:", "Requirement not met:", "Objective evidence:", "Actual or potential impact on people:", "Severity and immediate containment:"]], ["Cause and improvement", ["Root and contributory causes:", "Corrective action:", "Preventive or system action:", "Owner and deadline:"]], ["Verification", ["Evidence submitted:", "Verifier and date:", "Repeat sample or measure:", "Effectiveness result:", "Closure / reopen decision:"]], action], ["audit", "finding", "effectiveness"]),
  template("CQC evidence quality review", "Audit forms", "RM review of evidence strength across people’s experience, observation, outcomes and processes.", "Test whether inspection evidence is current, triangulated, traceable and demonstrates impact rather than activity alone.", [["Quality statement", ["Key question and quality statement:", "Regulations and guidance:", "Intended outcome for people:"]], ["Evidence triangulation", ["People’s experience evidence:", "Staff and leader feedback:", "Observation evidence:", "Outcome evidence:", "Process evidence:"]], ["RM challenge", ["What does the evidence prove?:", "Contradictions or gaps:", "Confidence level and rationale:", "Further evidence or action required:"]], control, action], ["cqc", "inspection", "evidence"]),
  template("Operational risk assessment", "Risk assessments", "Premium five-by-five risk assessment with controls, tolerance and treatment verification.", "Assess inherent and residual risk consistently and ensure controls are effective, owned and reviewed.", [["Risk definition", ["Risk event, cause and consequence:", "People or services affected:", "Risk source and category:", "Inherent likelihood / impact / score:"]], ["Controls and residual risk", ["Existing preventive controls:", "Existing detective or recovery controls:", "Evidence that controls operate:", "Residual likelihood / impact / score:", "Risk tolerance and escalation threshold:"]], ["Treatment plan", ["Avoid / reduce / transfer / accept:", "Further controls, owner and date:", "Target score:", "Monitoring indicator and review trigger:"]], action], ["risk", "assessment"]),
  template("Care plan and individual risk review", "Risk assessments", "Person-centred care-plan and risk review record with consent, outcomes and least-restrictive controls.", "Confirm that assessed needs, choices, risks and daily care remain consistent and current.", [["Person-centred review", ["What matters to the person:", "Communication and involvement:", "Consent, capacity or representative authority:", "Desired outcomes and progress:"]], ["Risk review", ["Current risks and early warning signs:", "Proportionate, least-restrictive controls:", "Changes, incidents or professional advice:", "Consistency with medicines and daily records:"]], ["Decision", ["Changes agreed:", "Who must be informed:", "Urgent escalation required:", "Next planned and trigger review:"]], action], ["care-plan", "risk", "person-centred"]),
  template("Positive risk-taking decision record", "Risk assessments", "Balanced decision record protecting autonomy while managing foreseeable harm.", "Evidence a lawful, proportionate and person-centred decision where choice involves risk.", [["Decision context", ["Choice or activity:", "Benefits important to the person:", "Foreseeable harms:", "Information provided in accessible form:"]], ["Decision making", ["Consent and decision-specific capacity:", "People consulted and authority:", "Options considered:", "Least-restrictive safeguards:"]], ["Agreed plan", ["Controls and contingency:", "Indicators for escalation:", "Responsible staff:", "Review triggers and date:"]], action], ["choice", "capacity", "least-restrictive"]),
  template("Monthly governance meeting agenda and minutes", "Governance meetings", "Board-ready agenda, challenge record, decisions and accountable actions.", "Create a complete governance record showing oversight, challenge, decisions and follow-through.", [["Meeting control", ["Meeting date, time and location:", "Chair and minute taker:", "Attendees and apologies:", "Conflicts of interest:", "Previous minutes approved:"]], ["Standing assurance agenda", ["People’s experience, complaints and compliments:", "Safeguarding, incidents, duty of candour and medicines:", "Care quality, outcomes and inequalities:", "Workforce, training, supervision and competency:", "Audits, risks, actions, policies and evidence:", "KPIs, contracts, notifications and business continuity:"]], ["Challenge and decisions", ["Evidence considered:", "Questions and constructive challenge:", "Decisions and rationale:", "Escalations:"]], action], ["governance", "minutes", "agenda"]),
  template("Registered Manager monthly assurance report", "Reports", "Premium monthly RM report spanning safety, quality, workforce and regulatory assurance.", "Give the provider a concise, evidence-led account of performance, risk, improvement and decisions required.", [["Executive assurance", ["Reporting period and locations:", "Overall assurance and material change:", "Immediate safety or compliance issues:", "Decisions or support required from the provider:"]], ["Performance and experience", ["People’s outcomes and feedback:", "Complaints, incidents, safeguarding and duty of candour:", "Medicines, care delivery and clinical risks:", "Workforce capacity, competence and wellbeing:"]], ["Governance", ["KPI exceptions and trends:", "Audit assurance and repeat findings:", "High risks and overdue actions:", "Notifications, contracts and external scrutiny:", "Improvement impact demonstrated:"]], action], ["registered-manager", "monthly-report"]),
  template("Quality improvement action plan", "Action plans", "Outcome-focused improvement plan with milestones, evidence and effectiveness review.", "Translate a concern, audit finding or ambition into measurable and sustained improvement.", [["Problem and aim", ["Source and reference:", "Problem statement and impact on people:", "Baseline measure:", "SMART improvement aim:"]], ["Delivery plan", ["Action and milestone:", "Owner and support:", "Due date and priority:", "Resource or dependency:", "Evidence of completion:"]], ["Measurement", ["Process measure:", "Outcome measure:", "Balancing measure:", "Review frequency and forum:"]], action], ["quality-improvement", "action-plan"]),
  template("Incident investigation and learning review", "Investigation forms", "Proportionate investigation with chronology, causation, duty of candour and learning.", "Establish facts fairly, identify system causes and reduce the risk of recurrence.", [["Incident and response", ["Reference, date, time and location:", "Factual description and harm:", "Immediate care and containment:", "Notifications, safeguarding and duty of candour decisions:"]], ["Investigation", ["Investigator and terms of reference:", "Chronology:", "People interviewed and records reviewed:", "Root and contributory causes:", "Human, task, environment, equipment and organisational factors:"]], ["Learning", ["What worked well:", "What must change:", "Learning shared with whom and when:", "Person or family feedback:"]], action], ["incident", "investigation", "learning"]),
  template("Complaint investigation and final response record", "Complaints", "Complete complaint file from acknowledgement to remedy, learning and final response.", "Resolve complaints fairly, promptly and transparently while demonstrating learning and improvement.", [["Complaint control", ["Reference and date received:", "Complainant and authority / consent:", "Issues raised and desired outcome:", "Acknowledgement and response deadline:", "Accessibility or advocacy needs:"]], ["Investigation", ["Investigator and independence:", "Evidence and people consulted:", "Finding for each issue: upheld / partly / not upheld:", "Reasons and evidence:", "Duty of candour or safeguarding consideration:"]], ["Outcome", ["Remedy and apology:", "Final response approval and date:", "Escalation rights explained:", "Themes and learning:"]], action], ["complaint", "investigation", "response"]),
  template("Safeguarding concern and referral record", "Safeguarding", "Decision-quality safeguarding record covering immediate safety, consent, referral and outcome.", "Ensure concerns are recognised, protected, referred and tracked without avoidable delay.", [["Concern", ["Date, source and factual account:", "Adult at risk and immediate safety:", "Alleged harm and person alleged responsible:", "Views, wishes, consent and capacity:"]], ["Decision and referral", ["Safeguarding lead informed:", "Local authority / police / emergency referral and time:", "Information-sharing basis:", "CQC, commissioner or other notification:", "Protection plan:"]], ["Follow-up", ["Section 42 or partner outcome:", "Support for the person and staff:", "Learning and preventive action:", "Closure rationale and approval:"]], action], ["safeguarding", "referral"]),
  template("Duty of candour decision and communication record", "Incident management", "Regulation 20 assessment and complete communication trail.", "Evidence prompt recognition, truthful communication, apology, investigation updates and written follow-up.", [["Trigger assessment", ["Incident reference and harm:", "Notifiable safety incident decision:", "Threshold evidence and reviewer:", "Decision date and rationale:"]], ["Communication", ["Relevant person and accessibility needs:", "Initial notification date, method and attendees:", "Factual explanation and sincere apology:", "Support offered and questions raised:", "Written follow-up date:"]], ["Ongoing candour", ["Investigation updates:", "Final findings shared:", "Actions and learning shared:", "Communication preferences and closure:"]], action], ["duty-of-candour", "regulation-20"]),
  template("Safer recruitment compliance checklist", "Recruitment", "Schedule 3 and Regulation 19 recruitment assurance checklist.", "Prevent deployment until identity, suitability, competence and lawful employment checks are complete or safely controlled.", [["Pre-employment checks", ["Application and complete employment history:", "Interview and values assessment:", "Identity and right to work:", "DBS level, date and update status:", "Two verified references including most recent employer:", "Qualifications and professional registration:", "Health, conduct and role suitability:"]], ["Exceptions", ["Gaps, discrepancies or disclosures:", "Risk assessment and authorised controls:", "Conditional start restrictions:", "Outstanding check owner and deadline:"]], ["Authorisation", ["File audit completed by:", "Approved to start by / date:", "Induction and probation plan:"]], action], ["recruitment", "schedule-3"]),
  template("Staff supervision and wellbeing record", "Supervision", "Reflective, accountable supervision covering wellbeing, practice, competence and actions.", "Support staff performance and wellbeing while identifying risks, learning and development needs.", [["Review", ["Employee, supervisor and date:", "Wellbeing, workload and support:", "Performance, conduct and attendance:", "People supported, outcomes and feedback:", "Safeguarding, incidents and professional boundaries:", "Training, competency and policy understanding:"]], ["Reflection and challenge", ["What is working well:", "Difficult situations and reflection:", "Manager feedback and challenge:", "Ideas or concerns raised:"]], ["Agreement", ["Actions, owners and dates:", "Support or development agreed:", "Escalations:", "Next supervision date:"]], action], ["supervision", "wellbeing"]),
  template("Observed practice competency assessment", "Competency assessments", "Knowledge, direct observation and authorisation record for role-specific practice.", "Confirm competence before unsupervised practice and define restrictions, development and reassessment.", [["Assessment control", ["Worker, role and competency:", "Assessor, qualification and authority:", "Person-specific considerations:", "Procedure, standard and assessment criteria:"]], ["Evidence", ["Knowledge questions and outcome:", "Simulation or record review:", "Direct practice observed:", "Safety, dignity, infection control and communication:", "Escalation and documentation demonstrated:"]], ["Decision", ["Competent / competent with conditions / not competent:", "Restrictions and communication to scheduling:", "Development and supervised practice:", "Reassessment / expiry date:"]], action], ["competency", "observed-practice"]),
  template("Medication competency assessment", "Competency assessments", "Premium medicines knowledge and observed-practice assessment.", "Authorise medicines support only where the worker demonstrates safe person-specific practice.", [["Knowledge", ["Rights of administration and consent:", "Allergies, interactions and changes:", "MAR codes, omissions, refusals and errors:", "PRN, covert medicines and controlled drugs:", "Storage, disposal and escalation:"]], ["Observed practice", ["Identity and current authorisation checked:", "Medicine, dose, route and time checked:", "Person supported safely and respectfully:", "MAR completed contemporaneously:", "Outcome, refusal or concern escalated:"]], ["Authorisation", ["Scope of authorised tasks:", "Restrictions:", "Outcome and assessor rationale:", "Reassessment date:"]], action], ["medicines", "competency"]),
  template("Home-care spot check record", "Checklists", "Direct observation of punctual, safe, dignified and person-centred home-care practice.", "Triangulate call data, care records, observation and the person’s experience.", [["Visit control", ["Person reference and worker:", "Date, planned and actual arrival / duration:", "Observer and consent:"]], ["Observation", ["Identity, entry and lone-working controls:", "Dignity, choice, communication and independence:", "Care-plan knowledge and risk controls:", "Infection prevention and equipment:", "Medicines or delegated tasks:", "Recording and escalation:"]], ["Experience", ["Person’s feedback:", "Worker feedback:", "Immediate coaching or safety action:"]], control, action], ["spot-check", "home-care"]),
  template("Business continuity exercise and debrief", "Business continuity", "Scenario-based resilience exercise with decisions, communications and tracked learning.", "Test whether critical care can continue safely during realistic disruption.", [["Exercise design", ["Scenario and objectives:", "Critical services and maximum tolerable disruption:", "Participants, observers and assumptions:", "Systems, suppliers and communications tested:"]], ["Exercise record", ["Timeline and injects:", "Decisions and escalation:", "People prioritisation and welfare:", "Communication with staff, people, families and commissioners:", "Data access and recovery:"]], ["Debrief", ["What worked:", "Gaps and consequences:", "Plan or contact updates:", "Retest scope and date:"]], action], ["business-continuity", "exercise"]),
  template("CQC statutory notification decision log", "Checklists", "Traceable decision record for events that may require regulatory notification.", "Ensure notifiable events are identified, reviewed, submitted and reconciled without delay.", [["Event", ["Event reference and date:", "Notification category considered:", "Relevant facts and source records:", "Safeguarding, police, commissioner or coroner involvement:"]], ["Decision", ["Notify / do not notify:", "Legal or guidance basis:", "Decision maker and review:", "Submission deadline and actual submission:", "CQC reference or evidence retained:"]], ["Reconciliation", ["Linked incident or safeguarding record:", "Information updated after submission:", "Monthly reconciliation outcome:"]], action], ["cqc", "notification"]),
  template("Data protection impact assessment", "Risk assessments", "UK GDPR privacy-risk assessment for new or changed processing.", "Identify and reduce privacy risks before high-risk processing begins.", [["Processing", ["Project, system or change:", "Purpose and lawful basis:", "Data subjects and data categories:", "Sources, recipients, transfers and retention:", "Necessity and proportionality:"]], ["Consultation", ["Data protection lead:", "People or representatives consulted:", "Supplier and processor assurance:", "Information security review:"]], ["Privacy risk", ["Threat or harm:", "Likelihood and severity:", "Existing and further controls:", "Residual risk and approval / ICO consultation:"]], action], ["uk-gdpr", "dpia"]),
  template("Information breach assessment and response", "Incident management", "Personal-data breach triage, containment, notification and learning record.", "Control a suspected breach and make timely, evidence-based ICO and individual notification decisions.", [["Breach", ["Discovery date and reporter:", "What happened and containment:", "Data, people and systems affected:", "Confidentiality, integrity or availability impact:"]], ["Risk decision", ["Likelihood and severity of harm:", "Risk to rights and freedoms:", "ICO notification required and 72-hour deadline:", "Individual notification required:", "Decision maker and rationale:"]], ["Recovery", ["Technical and organisational remediation:", "Communication and support:", "Evidence preservation:", "Lessons and control improvement:"]], action], ["data-protection", "breach"]),
  template("Whistleblowing concern management record", "Investigation forms", "Confidential concern, protection, investigation and outcome record.", "Respond to protected disclosures fairly, independently and without retaliation.", [["Concern", ["Date, route and confidential reference:", "Concern summary and public-interest issue:", "Immediate safety or evidence-preservation action:", "Confidentiality and contact preference:"]], ["Assessment", ["Protected disclosure consideration:", "Conflict and independent investigator:", "Terms of reference:", "External referral or specialist advice:", "Anti-retaliation controls:"]], ["Outcome", ["Findings and evidence:", "Feedback provided:", "Actions and systemic learning:", "Welfare and detriment follow-up:"]], action], ["whistleblowing", "speaking-up"]),
  template("Equality impact assessment", "Quality improvement", "Structured review of accessibility, protected characteristics and unequal effects.", "Prevent avoidable disadvantage and design proportionate reasonable adjustments.", [["Proposal", ["Policy, service or change:", "Purpose and intended outcomes:", "People and groups affected:", "Evidence and consultation used:"]], ["Impact", ["Potential positive impact:", "Potential adverse or unequal impact:", "Communication and accessibility needs:", "Reasonable adjustments:", "Alternative approaches considered:"]], ["Decision and monitoring", ["Proceed / modify / stop:", "Mitigations and owners:", "Measures by relevant group:", "Review date and escalation:"]], action], ["equality", "accessible-information"]),
  template("Provider visit quality assurance record", "Checklists", "Provider or nominated-individual visit with evidence, challenge and RM follow-up.", "Provide independent leadership oversight of culture, care quality, risk and improvement.", [["Visit", ["Date, location and reviewer:", "People, relatives and staff spoken with:", "Care observed:", "Records and environment sampled:"]], ["Leadership assurance", ["Safety and quality strengths:", "People’s experience and outcomes:", "Staff culture and speaking up:", "RM oversight and data understanding:", "Risks, incidents, complaints and safeguarding:", "Previous actions and sustained improvement:"]], ["Challenge", ["Questions asked and evidence received:", "Immediate escalation:", "Provider judgement:"]], action], ["provider", "nominated-individual", "visit"]),
  template("Service-user and representative review", "Quality improvement", "Accessible review of experience, outcomes, choice and improvement priorities.", "Put people’s direct experience and desired outcomes at the centre of quality assurance.", [["Participation", ["Person reference and preferred communication:", "Representative or advocate and authority:", "Consent and accessibility adjustments:"]], ["Experience and outcomes", ["What is working well:", "Choice, dignity and independence:", "Reliability and continuity:", "Health, wellbeing and goals:", "Concerns, complaints or unmet needs:"]], ["Agreed changes", ["Care-plan or risk changes:", "Actions and owners:", "Information shared:", "How the person will know improvement occurred:"]], action], ["people-experience", "outcomes"]),
  template("Commissioner KPI validation and submission", "Reports", "Source-to-return validation, variance commentary and approval record.", "Ensure contractual performance information is complete, reproducible, approved and submitted on time.", [["Return control", ["Commissioner, contract and period:", "Submission deadline and owner:", "KPI definitions and source systems:", "Exclusions, denominators and calculation rules:"]], ["Validation", ["Source totals reconciled:", "Completeness and duplicate checks:", "Prior-period and target variance:", "Adverse results linked to risks and actions:", "Corrections and reviewer challenge:"]], ["Approval and submission", ["Approved by and date:", "Submitted by / date / method:", "Receipt or reference:", "Queries and corrections:"]], action], ["commissioner", "kpi", "validation"]),
  template("Emergency staffing and capacity escalation plan", "Business continuity", "Risk-based response to staffing shortages and unsafe capacity.", "Maintain safe, prioritised care and transparent escalation during workforce disruption.", [["Trigger", ["Date, shift / period and affected service:", "Planned versus available staffing and competencies:", "Cause and expected duration:", "People at highest risk:"]], ["Response", ["Internal cover and on-call action:", "Agency or contingency staff checks:", "Prioritisation and delayed / changed care decisions:", "Communication with people and representatives:", "Commissioner, safeguarding or CQC escalation:"]], ["Recovery", ["Ongoing monitoring:", "Restoration criteria:", "Incidents, missed care or harm review:", "Learning and preventive action:"]], action], ["staffing", "capacity", "contingency"]),
  template("Policy implementation and staff assurance record", "Policies", "Evidence that an approved policy is communicated, understood and operating in practice.", "Move beyond policy publication to tested implementation and sustained compliance.", [["Policy control", ["Policy title, reference and version:", "Owner and approval date:", "Affected roles and locations:", "Material change from previous version:"]], ["Implementation", ["Communication method and date:", "Training or briefing required:", "Acknowledgement completion:", "Systems, forms or workflows changed:", "Accessible versions or adjustments:"]], ["Assurance", ["Practice sample or observation:", "Staff knowledge check:", "Exceptions and incidents:", "Implementation judgement:"]], action], ["policy", "implementation"]),
  template("Document control and approval record", "Checklists", "Version, approval, distribution, review and withdrawal control for governance documents.", "Keep only current, authorised documents in use and retain a traceable history.", [["Document", ["Title, owner and category:", "Reference and version:", "Author and reviewers:", "Changes and reason:", "Legal, regulatory or evidence sources checked:"]], ["Approval and issue", ["Approver and approval date:", "Effective and review dates:", "Locations and roles affected:", "Communication and training:", "Published locations:"]], ["Withdrawal", ["Superseded version removed:", "Archived copy retained:", "Printed or local copies controlled:", "Early-review triggers:"]], action], ["document-control", "approval"]),
];

function legacy(title: string, category: string, description: string): Definition {
  return template(title, category, description, `Provide a complete, controlled and evidence-led ${title.toLowerCase()} suitable for registered-manager review.`, [
    ["Scope and accountability", ["Purpose and scope:", "Service, location or people covered:", "Responsible owner:", "Relevant regulation, policy or standard:", "Review period and completion deadline:"]],
    ["Assessment and evidence", ["Current position:", "Evidence reviewed:", "People's experience or outcome evidence:", "Strengths and good practice:", "Gaps, risks or required escalation:"]],
    action,
  ], ["legacy-upgraded"]);
}

const LEGACY_PREMIUM_TEMPLATES: Definition[] = [
  legacy("Safeguarding Policy Template", "Policies", "Controlled safeguarding policy implementation and assurance record."),
  legacy("Quality Audit Form", "Audit forms", "Comprehensive quality audit with sample, evidence, findings and RM sign-off."),
  legacy("Operational Risk Assessment", "Risk assessments", "Five-by-five operational risk assessment with control effectiveness review."),
  legacy("Governance Meeting Agenda", "Governance meetings", "Structured governance agenda with challenge, decisions and accountable actions."),
  legacy("Quality Improvement Action Plan", "Action plans", "Outcome-led improvement plan with ownership and effectiveness verification."),
  legacy("Incident Investigation Form", "Investigation forms", "Proportionate incident investigation, causation, learning and follow-up."),
  legacy("Complaint Acknowledgement and Investigation", "Complaints", "Complete complaint acknowledgement, investigation, remedy and learning record."),
  legacy("Incident Management Checklist", "Incident management", "Immediate safety, escalation, notification and learning checklist."),
  legacy("Safeguarding Referral Checklist", "Safeguarding", "Immediate protection, referral, notification and outcome checklist."),
  legacy("Safer Recruitment Checklist", "Recruitment", "Schedule 3 safer-recruitment control and deployment authorisation checklist."),
  legacy("Supervision Record", "Supervision", "Reflective supervision, wellbeing, performance and development record."),
  legacy("Competency Assessment", "Competency assessments", "Knowledge, direct observation, authorisation and reassessment record."),
  legacy("Quality Improvement Plan", "Quality improvement", "Plan-do-study-act improvement record with measurable outcomes."),
  legacy("Business Continuity Test Record", "Business continuity", "Scenario exercise, critical-service assurance and learning record."),
  legacy("Monthly Governance Report", "Reports", "Registered-manager monthly assurance, performance and improvement report."),
  legacy("Duty of Candour Letter", "Letters", "Controlled duty-of-candour communication with factual explanation, apology and follow-up."),
  legacy("Inspection Readiness Checklist", "Checklists", "Evidence-led registered-manager inspection readiness and gap review."),
];

export const PREMIUM_TEMPLATES: Definition[] = [...NEW_PREMIUM_TEMPLATES, ...LEGACY_PREMIUM_TEMPLATES];

function uuidFor(title: string): string {
  const hex = createHash("md5").update(`qcgms-premium-template-v2:${title}`).digest("hex");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-a${hex.slice(17, 20)}-${hex.slice(20, 32)}`;
}

export async function ensurePremiumTemplates(db: PrismaClient): Promise<void> {
  const installed = await db.template.count({ where: { organisationId: null, tags: { has: "rm-grade-v3" } } });
  if (installed >= PREMIUM_TEMPLATES.length) return;
  for (const item of PREMIUM_TEMPLATES) {
    const data = {
      title: item.title,
      category: item.category,
      description: item.description,
      version: "3.0",
      tags: [...item.tags, "rm-grade-v3", "structured-tables", "print-ready"],
      status: "PUBLISHED" as const,
      fileName: `${item.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}.html`,
      contentType: "text/html",
      sizeBytes: Buffer.byteLength(item.body),
      checksum: createHash("sha256").update(item.body).digest("hex"),
      bodyText: item.body,
      updatedAt: new Date(),
    };
    const existing = await db.template.findFirst({ where: { organisationId: null, title: item.title }, select: { id: true } });
    if (existing) await db.template.update({ where: { id: existing.id }, data });
    else await db.template.upsert({ where: { id: uuidFor(item.title) }, update: data, create: { id: uuidFor(item.title), ...data } });
  }
}
