export type RegisterField={key:string;label:string;type:"text"|"date"|"textarea"|"boolean"|"number"|"select";required?:boolean;options?:string[]};
export type RegisterFormExperience={dateLabel:string;titleLabel:string;titlePlaceholder:string;summaryLabel:string;summaryPlaceholder:string;detailsIntro:string;saveLabel:string};
export const REGISTER_STATUSES=["OPEN","IN_REVIEW","AWAITING_ACTION","CLOSED","ARCHIVED"] as const;
export const REGISTER_RISK_LEVELS=["LOW","MEDIUM","HIGH","CRITICAL"] as const;
export function parseRegisterFields(value:unknown):RegisterField[]{if(!Array.isArray(value))return[];return value.filter((item):item is RegisterField=>Boolean(item&&typeof item==="object"&&"key" in item&&"label" in item&&"type" in item));}
export function registerStatusLabel(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/^\w/,(letter)=>letter.toUpperCase());}
export function makeRegisterReference(key:string,now=new Date(),random=Math.floor(Math.random()*1000)){const prefix=key.split("-").map((part)=>part[0]).join("").toUpperCase().slice(0,4);const date=`${now.getUTCFullYear()}${String(now.getUTCMonth()+1).padStart(2,"0")}${String(now.getUTCDate()).padStart(2,"0")}`;return `${prefix}-${date}-${String(random).padStart(3,"0")}`;}
export function registerScopeWhere(context:{organisation:{id:string};allLocations:boolean;locations:{id:string}[]}){return{organisationId:context.organisation.id,...(context.allLocations?{}:{OR:[{locationId:null},{locationId:{in:context.locations.map((item)=>item.id)}}]})};}
export function collectRegisterData(form:FormData,fields:RegisterField[]):Record<string,string|boolean>{return Object.fromEntries(fields.map((field)=>{const value=form.get(`field_${field.key}`);return[field.key,field.type==="boolean"?value==="true":String(value??"").trim()];}));}

const EXPERIENCES:Record<string,Partial<RegisterFormExperience>>={
  complaints:{dateLabel:"Date complaint received",titleLabel:"What is the complaint about?",titlePlaceholder:"For example, missed evening call and poor communication",summaryLabel:"What did the person say happened?",summaryPlaceholder:"Record the concern in the person’s own words, the impact and the outcome they are seeking.",detailsIntro:"Record acknowledgement, investigation, response, outcome and learning.",saveLabel:"Save complaint"},
  compliments:{dateLabel:"Date compliment received",titleLabel:"What was praised?",titlePlaceholder:"For example, compassionate support during a hospital discharge",summaryLabel:"What did the person say?",summaryPlaceholder:"Record the feedback, who or what it relates to and why it mattered.",detailsIntro:"Capture the source of the compliment, recognition shared and learning to retain.",saveLabel:"Save compliment"},
  incidents:{dateLabel:"Date and time of incident",titleLabel:"What happened?",titlePlaceholder:"For example, medicine omitted during the morning call",summaryLabel:"Incident account",summaryPlaceholder:"Record the facts, people affected, immediate response and known harm. Do not speculate.",detailsIntro:"Record harm, escalation, notifications, investigation and learning.",saveLabel:"Save incident"},
  accidents:{dateLabel:"Date and time of accident",titleLabel:"What accident occurred?",titlePlaceholder:"For example, staff member slipped at the service location",summaryLabel:"Accident account",summaryPlaceholder:"Record where and how it happened, injury or harm and the immediate response.",detailsIntro:"Capture injury, treatment, reporting, investigation and prevention.",saveLabel:"Save accident"},
  "near-misses":{dateLabel:"Date and time of near miss",titleLabel:"What nearly happened?",titlePlaceholder:"For example, incorrect medicine detected before administration",summaryLabel:"Near-miss account",summaryPlaceholder:"Explain the hazard, how harm was avoided and the immediate safeguard.",detailsIntro:"Record contributory factors, preventive action and learning.",saveLabel:"Save near miss"},
  safeguarding:{dateLabel:"Date concern identified",titleLabel:"What is the safeguarding concern?",titlePlaceholder:"For example, unexplained bruising reported during a care visit",summaryLabel:"Concern and immediate protection",summaryPlaceholder:"Record factual information, the person’s account, immediate risk and protective action.",detailsIntro:"Capture referral, consent, Section 42 activity, outcome and learning.",saveLabel:"Save safeguarding concern"},
  whistleblowing:{dateLabel:"Date concern raised",titleLabel:"What concern was raised?",titlePlaceholder:"For example, unsafe staffing practice raised confidentially",summaryLabel:"Concern as reported",summaryPlaceholder:"Record the concern without exposing the reporter more than necessary.",detailsIntro:"Record protection, investigation, outcome and feedback to the reporter.",saveLabel:"Save whistleblowing concern"},
  "cqc-notifications":{dateLabel:"Date event occurred or was identified",titleLabel:"What notifiable event occurred?",titlePlaceholder:"For example, serious injury requiring hospital treatment",summaryLabel:"Event and notification decision",summaryPlaceholder:"Explain the event, why it is or is not notifiable and who made the decision.",detailsIntro:"Capture submission date, notification reference, timeliness and follow-up.",saveLabel:"Save CQC notification record"},
  "medicines-errors":{dateLabel:"Date and time of medicines error",titleLabel:"What medicines error occurred?",titlePlaceholder:"For example, evening dose administered late",summaryLabel:"Error, impact and immediate response",summaryPlaceholder:"Record the medicine, dose, person affected, known harm, advice and immediate safeguards.",detailsIntro:"Capture clinical advice, notifications, investigation, competency and learning.",saveLabel:"Save medicines error"},
  falls:{dateLabel:"Date and time of fall",titleLabel:"Where and how did the fall occur?",titlePlaceholder:"For example, unwitnessed fall beside the bed",summaryLabel:"Fall account and immediate response",summaryPlaceholder:"Record circumstances, injury, observations, assistance and medical advice.",detailsIntro:"Capture injury, post-fall checks, referrals, risk review and prevention.",saveLabel:"Save fall record"},
  "pressure-damage":{dateLabel:"Date pressure damage identified",titleLabel:"What pressure damage was identified?",titlePlaceholder:"For example, new category 2 damage to left heel",summaryLabel:"Skin condition and immediate action",summaryPlaceholder:"Record site, category, condition, pain, immediate care and escalation.",detailsIntro:"Capture clinical review, equipment, repositioning, safeguarding consideration and healing.",saveLabel:"Save pressure-damage record"},
  "hospital-admissions":{dateLabel:"Date of hospital admission",titleLabel:"Why was the person admitted?",titlePlaceholder:"For example, suspected chest infection and reduced oxygen saturation",summaryLabel:"Admission circumstances",summaryPlaceholder:"Record symptoms, advice, transport, information shared and contacts notified.",detailsIntro:"Capture admission route, handover, discharge planning and follow-up.",saveLabel:"Save hospital admission"},
  "missed-visits":{dateLabel:"Date and time of missed visit",titleLabel:"Which visit was missed?",titlePlaceholder:"For example, scheduled 18:00 medicines and meal call",summaryLabel:"What happened and what was the impact?",summaryPlaceholder:"Record why the call was missed, how it was discovered, the person’s safety and immediate response.",detailsIntro:"Capture contact attempts, replacement care, notifications, investigation and prevention.",saveLabel:"Save missed visit"},
  "late-visits":{dateLabel:"Date of late visit",titleLabel:"Which visit was late?",titlePlaceholder:"For example, morning call arrived 55 minutes late",summaryLabel:"Delay, cause and impact",summaryPlaceholder:"Record scheduled and actual times, reason, impact on the person and communication.",detailsIntro:"Capture duration, repeated pattern, action and prevention.",saveLabel:"Save late visit"},
  "staff-concerns":{dateLabel:"Date concern identified",titleLabel:"What staff concern requires review?",titlePlaceholder:"For example, repeated failure to follow moving-and-handling plan",summaryLabel:"Factual concern and immediate management response",summaryPlaceholder:"Record observed facts, risk, conversation and interim safeguards.",detailsIntro:"Capture investigation, support, HR process, outcome and learning.",saveLabel:"Save staff concern"},
  "service-user-feedback":{dateLabel:"Date feedback received",titleLabel:"What did the person want us to know?",titlePlaceholder:"For example, request for more consistent call times",summaryLabel:"Feedback in the person’s own words",summaryPlaceholder:"Record what matters to the person, the impact and any response already given.",detailsIntro:"Capture theme, response, improvement and feedback to the person.",saveLabel:"Save service-user feedback"},
  "staff-feedback":{dateLabel:"Date feedback received",titleLabel:"What did staff want leaders to know?",titlePlaceholder:"For example, handover information is difficult to find",summaryLabel:"Feedback and context",summaryPlaceholder:"Record the point raised, affected teams or services and suggested improvement.",detailsIntro:"Capture theme, management response, action and communication back to staff.",saveLabel:"Save staff feedback"},
  "training-exceptions":{dateLabel:"Date exception identified",titleLabel:"Which training requirement is overdue or exceptional?",titlePlaceholder:"For example, moving-and-handling refresher overdue",summaryLabel:"Reason and current risk",summaryPlaceholder:"Record the worker reference, requirement, reason, duties affected and interim control.",detailsIntro:"Capture due date, recovery plan, authorisation and escalation.",saveLabel:"Save training exception"},
  "supervision-exceptions":{dateLabel:"Date exception identified",titleLabel:"Which supervision is overdue or exceptional?",titlePlaceholder:"For example, quarterly supervision delayed due to long-term absence",summaryLabel:"Reason and staff-support impact",summaryPlaceholder:"Record the worker reference, due date, reason, current support and risk.",detailsIntro:"Capture rescheduled date, interim contact, escalation and completion.",saveLabel:"Save supervision exception"},
  "data-breaches":{dateLabel:"Date and time breach identified",titleLabel:"What personal-data breach occurred?",titlePlaceholder:"For example, care rota emailed to the wrong recipient",summaryLabel:"Data involved, people affected and containment",summaryPlaceholder:"Record what happened, data categories, recipients, immediate containment and known impact.",detailsIntro:"Capture risk assessment, ICO decision, notifications, investigation and prevention.",saveLabel:"Save data-breach record"},
  "care-plan-reviews":{dateLabel:"Date review was due or completed",titleLabel:"Which care plan was reviewed?",titlePlaceholder:"For example, mobility and personal-care plan review",summaryLabel:"Reason for review and main outcome",summaryPlaceholder:"Record what prompted the review, who was involved and the main agreed changes.",detailsIntro:"Capture due and completion dates, involvement, changes and outcomes.",saveLabel:"Save care-plan review"},
  "risk-assessment-reviews":{dateLabel:"Date review was due or completed",titleLabel:"Which person-level risk was reviewed?",titlePlaceholder:"For example, falls risk assessment following a change in mobility",summaryLabel:"Change in risk and review outcome",summaryPlaceholder:"Explain what changed, evidence considered and whether controls remain suitable.",detailsIntro:"Capture assessment type, due date, changed risks, controls and outcome.",saveLabel:"Save risk-assessment review"},
  "mar-audits":{dateLabel:"Date audit completed",titleLabel:"Which MAR sample was audited?",titlePlaceholder:"For example, July MAR sample for Basingstoke branch",summaryLabel:"Scope and headline result",summaryPlaceholder:"Record the period, sample, main strengths, omissions and immediate action.",detailsIntro:"Capture sample size, omissions, stock issues, score and corrective action.",saveLabel:"Save medication and MAR audit"},
  "delegated-healthcare":{dateLabel:"Date delegation or review occurred",titleLabel:"Which healthcare task is being recorded?",titlePlaceholder:"For example, insulin administration delegated by community nurse",summaryLabel:"Delegation arrangement",summaryPlaceholder:"Record the person, task, clinical professional, authorised staff and current instructions.",detailsIntro:"Capture authorisation, competency, review and escalation instructions.",saveLabel:"Save delegated healthcare task"},
  "service-user-outcomes":{dateLabel:"Date outcome reviewed",titleLabel:"Which personal outcome is being tracked?",titlePlaceholder:"For example, regain confidence preparing a light meal",summaryLabel:"Goal and current progress",summaryPlaceholder:"Record the person’s goal, what has changed and what they say about progress.",detailsIntro:"Capture the agreed goal, evidence of progress, the person’s view and next review.",saveLabel:"Save outcome review"},
  "satisfaction-surveys":{dateLabel:"Date survey period closed",titleLabel:"Which survey results are being recorded?",titlePlaceholder:"For example, quarter 2 service-user satisfaction survey",summaryLabel:"Response and headline findings",summaryPlaceholder:"Record audience, response level, overall result and the most important themes.",detailsIntro:"Capture response numbers, scores, positive themes and ‘you said, we did’ action.",saveLabel:"Save survey results"},
  "business-continuity":{dateLabel:"Date of exercise or disruption",titleLabel:"Which scenario or disruption was reviewed?",titlePlaceholder:"For example, 4-hour care-planning system outage exercise",summaryLabel:"What happened and was care maintained?",summaryPlaceholder:"Record the scenario, services affected, decisions, recovery and outcome.",detailsIntro:"Capture activation, critical services, recovery time, lessons and retest date.",saveLabel:"Save continuity record"},
  "commissioner-contracts":{dateLabel:"Reporting or correspondence date",titleLabel:"Which contract obligation is being tracked?",titlePlaceholder:"For example, monthly home-care KPI return",summaryLabel:"Requirement and current position",summaryPlaceholder:"Record what is due, reporting period, performance position, feedback and risk.",detailsIntro:"Capture commissioner, contract, submission dates, performance issues and required action.",saveLabel:"Save contract record"},
  "call-log":{dateLabel:"Date of call",titleLabel:"What was the call about?",titlePlaceholder:"For example, family update about a delayed morning visit",summaryLabel:"Call summary and outcome",summaryPlaceholder:"Record the important facts, decision, advice given and agreed next step. Use internal references instead of unnecessary personal details.",detailsIntro:"Capture who the call involved, direction, time, subject, outcome, follow-up and escalation.",saveLabel:"Save call log entry"},
};

export function registerFormExperience(key:string,name:string):RegisterFormExperience{
  const specific=EXPERIENCES[key]??{};
  return{dateLabel:specific.dateLabel??"Date recorded",titleLabel:specific.titleLabel??`What ${name.toLowerCase()} record are you adding?`,titlePlaceholder:specific.titlePlaceholder??`Enter a clear, specific ${name.toLowerCase()} title`,summaryLabel:specific.summaryLabel??"What happened and what needs attention?",summaryPlaceholder:specific.summaryPlaceholder??"Record the facts, impact, response and next step.",detailsIntro:specific.detailsIntro??`Complete the information needed for this ${name.toLowerCase()} record.`,saveLabel:specific.saveLabel??`Save ${name.toLowerCase()} record`};
}
