export type RegisterField={key:string;label:string;type:"text"|"date"|"textarea"|"boolean"|"number"|"select";required?:boolean;options?:string[]};
export type RegisterFormExperience={dateLabel:string;titleLabel:string;titlePlaceholder:string;summaryLabel:string;summaryPlaceholder:string;detailsIntro:string;saveLabel:string};
export const REGISTER_STATUSES=["OPEN","IN_REVIEW","AWAITING_ACTION","CLOSED","ARCHIVED"] as const;
export const REGISTER_RISK_LEVELS=["LOW","MEDIUM","HIGH","CRITICAL"] as const;
export function parseRegisterFields(value:unknown):RegisterField[]{if(!Array.isArray(value))return[];return value.filter((item):item is RegisterField=>Boolean(item&&typeof item==="object"&&"key" in item&&"label" in item&&"type" in item));}
export function registerStatusLabel(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/^\w/,(letter)=>letter.toUpperCase());}
export function makeRegisterReference(key:string,now=new Date(),random=Math.floor(Math.random()*1000)){const prefix=key.split("-").map((part)=>part[0]).join("").toUpperCase().slice(0,4);const date=`${now.getUTCFullYear()}${String(now.getUTCMonth()+1).padStart(2,"0")}${String(now.getUTCDate()).padStart(2,"0")}`;return `${prefix}-${date}-${String(random).padStart(3,"0")}`;}
export function registerScopeWhere(context:{organisation:{id:string};allLocations:boolean;locations:{id:string}[]}){return{organisationId:context.organisation.id,...(context.allLocations?{}:{OR:[{locationId:null},{locationId:{in:context.locations.map((item)=>item.id)}}]})};}
export function collectRegisterData(form:FormData,fields:RegisterField[]):Record<string,string|boolean>{return Object.fromEntries(fields.map((field)=>{const value=form.get(`field_${field.key}`);const parsed=field.type==="boolean"?value==="true":String(value??"").trim();if(field.required&&field.type!=="boolean"&&!parsed)throw new Error(`Complete ${field.label.toLowerCase()}.`);return[field.key,parsed];}));}

const EXPERIENCES:Record<string,Partial<RegisterFormExperience>>={
  complaints:{dateLabel:"Date complaint received",titleLabel:"What is the complaint about?",titlePlaceholder:"For example, missed evening call and poor communication",summaryLabel:"What did the person say happened?",summaryPlaceholder:"Record the concern in the person’s own words, the impact and the outcome they are seeking.",detailsIntro:"Record acknowledgement, investigation, response, outcome and learning.",saveLabel:"Save complaint"},
  compliments:{dateLabel:"Date compliment received",titleLabel:"What was praised?",titlePlaceholder:"For example, compassionate support during a hospital discharge",summaryLabel:"What did the person say?",summaryPlaceholder:"Record the feedback, who or what it relates to and why it mattered.",detailsIntro:"Capture the source of the compliment, recognition shared and learning to retain.",saveLabel:"Save compliment"},
  incidents:{dateLabel:"Date and time of incident",titleLabel:"What happened?",titlePlaceholder:"For example, medicine omitted during the morning call",summaryLabel:"Incident account",summaryPlaceholder:"Record the facts, people affected, immediate response and known harm. Do not speculate.",detailsIntro:"Record harm, escalation, notifications, investigation and learning.",saveLabel:"Save incident"},
  accidents:{dateLabel:"Date and time of accident",titleLabel:"What accident occurred?",titlePlaceholder:"For example, staff member slipped at the service location",summaryLabel:"Accident account",summaryPlaceholder:"Record where and how it happened, injury or harm and the immediate response.",detailsIntro:"Capture injury, treatment, reporting, investigation and prevention.",saveLabel:"Save accident"},
  "near-misses":{dateLabel:"Date and time of near miss",titleLabel:"What nearly happened?",titlePlaceholder:"For example, incorrect medicine detected before administration",summaryLabel:"Near-miss account",summaryPlaceholder:"Explain the hazard, how harm was avoided and the immediate safeguard.",detailsIntro:"Record contributory factors, preventive action and learning.",saveLabel:"Save near miss"},
  safeguarding:{dateLabel:"Date concern identified",titleLabel:"What is the safeguarding concern?",titlePlaceholder:"For example, unexplained bruising reported during a care visit",summaryLabel:"Concern and immediate protection",summaryPlaceholder:"Record factual information, the person’s account, immediate risk and protective action.",detailsIntro:"Capture referral, consent, Section 42 activity, outcome and learning.",saveLabel:"Save safeguarding concern"},
  whistleblowing:{dateLabel:"Date concern raised",titleLabel:"What concern was raised?",titlePlaceholder:"For example, unsafe staffing practice raised confidentially",summaryLabel:"Concern as reported",summaryPlaceholder:"Record the concern without exposing the reporter more than necessary.",detailsIntro:"Record protection, investigation, outcome and feedback to the reporter.",saveLabel:"Save whistleblowing concern"},
  "cqc-notifications":{dateLabel:"Date event occurred or was identified",titleLabel:"What notifiable event occurred?",titlePlaceholder:"For example, serious injury requiring hospital treatment",summaryLabel:"Event and notification decision",summaryPlaceholder:"Explain the event, why it is or is not notifiable and who made the decision.",detailsIntro:"Capture submission date, notification reference, timeliness and follow-up.",saveLabel:"Save CQC notification record"},
  "medicines-errors":{dateLabel:"Date and time of medicines error",titleLabel:"What medicines error occurred?",titlePlaceholder:"For example, evening dose administered late",summaryLabel:"Error, impact and immediate response",summaryPlaceholder:"Record the medicine, dose, person affected, known harm, advice and immediate safeguards.",detailsIntro:"Capture clinical advice, notifications, investigation, competency and learning.",saveLabel:"Save medicines error"},
  falls:{dateLabel:"Date and time of fall",titleLabel:"Where and how did the fall occur?",titlePlaceholder:"For example, unwitnessed fall beside the bed",summaryLabel:"Fall account and immediate response",summaryPlaceholder:"Record circumstances, injury, observations, assistance and medical advice.",detailsIntro:"Capture injury, post-fall checks, referrals, risk review and prevention.",saveLabel:"Save fall record"},
  "pressure-damage":{dateLabel:"Date pressure damage identified",titleLabel:"What pressure damage was identified?",titlePlaceholder:"For example, new category 2 damage to left heel",summaryLabel:"Skin condition and immediate action",summaryPlaceholder:"Record site, category, condition, pain, immediate care and escalation.",detailsIntro:"Capture clinical review, equipment, repositioning, safeguarding consideration and healing.",saveLabel:"Save pressure-damage record"},
  "hospital-admissions":{dateLabel:"Date of hospital admission",titleLabel:"Why was the person admitted?",titlePlaceholder:"For example, suspected chest infection and reduced oxygen saturation",summaryLabel:"Admission circumstances",summaryPlaceholder:"Record symptoms, advice, transport, information shared and contacts notified.",detailsIntro:"Capture admission route, handover, discharge planning and follow-up.",saveLabel:"Save hospital admission"},
  "missed-visits":{dateLabel:"Date and time of missed visit",titleLabel:"Which visit was missed?",titlePlaceholder:"For example, scheduled 18:00 medicines and meal call",summaryLabel:"What happened and what was the impact?",summaryPlaceholder:"Record why the call was missed, how it was discovered, the person’s safety and immediate response.",detailsIntro:"Capture contact attempts, replacement care, notifications, investigation and prevention.",saveLabel:"Save missed visit"},
  "late-visits":{dateLabel:"Date of late visit",titleLabel:"Which visit was late?",titlePlaceholder:"For example, morning call arrived 55 minutes late",summaryLabel:"Delay, cause and impact",summaryPlaceholder:"Record scheduled and actual times, reason, impact on the person and communication.",detailsIntro:"Capture duration, repeated pattern, action and prevention.",saveLabel:"Save late visit"},
  "staff-concerns":{dateLabel:"Date concern identified",titleLabel:"What staff concern requires review?",titlePlaceholder:"For example, repeated failure to follow moving-and-handling plan",summaryLabel:"Factual concern and immediate management response",summaryPlaceholder:"Record observed facts, risk, conversation and interim safeguards.",detailsIntro:"Capture investigation, support, HR process, outcome and learning.",saveLabel:"Save staff concern"},
  "service-user-feedback":{dateLabel:"Date feedback received",titleLabel:"What did the person want us to know?",titlePlaceholder:"For example, request for more consistent call times",summaryLabel:"Feedback in the person’s own words",summaryPlaceholder:"Record what matters to the person, the impact and any response already given.",detailsIntro:"Capture theme, response, improvement and feedback to the person.",saveLabel:"Save service-user feedback"},
  "staff-feedback":{dateLabel:"Date feedback received",titleLabel:"What did staff want leaders to know?",titlePlaceholder:"For example, handover information is difficult to find",summaryLabel:"Feedback and context",summaryPlaceholder:"Record the point raised, affected teams or services and suggested improvement.",detailsIntro:"Capture theme, management response, action and communication back to staff.",saveLabel:"Save staff feedback"},
  "training-exceptions":{dateLabel:"Date exception identified",titleLabel:"Which training requirement is overdue or exceptional?",titlePlaceholder:"For example, moving-and-handling refresher overdue",summaryLabel:"Reason and current risk",summaryPlaceholder:"Record the worker reference, requirement, reason, duties affected and interim control.",detailsIntro:"Capture due date, recovery plan, authorisation and escalation.",saveLabel:"Save training exception"},
  "supervision-exceptions":{dateLabel:"Date exception identified",titleLabel:"Which supervision is overdue or exceptional?",titlePlaceholder:"For example, quarterly supervision delayed due to long-term absence",summaryLabel:"Reason and staff-support impact",summaryPlaceholder:"Record the worker reference, due date, reason, current support and risk.",detailsIntro:"Capture rescheduled date, interim contact, escalation and completion.",saveLabel:"Save supervision exception"},
  "data-breaches":{dateLabel:"Date and time breach identified",titleLabel:"What personal-data breach occurred?",titlePlaceholder:"For example, care rota emailed to the wrong recipient",summaryLabel:"Data involved, people affected and containment",summaryPlaceholder:"Record what happened, data categories, recipients, immediate containment and known impact.",detailsIntro:"Capture risk assessment, ICO decision, notifications, investigation and prevention.",saveLabel:"Save data-breach record"},
  "care-plan-reviews":{dateLabel:"Date review was due or completed",titleLabel:"Which care plan was reviewed?",titlePlaceholder:"For example, mobility and personal-care plan review",summaryLabel:"Reason for review and main outcome",summaryPlaceholder:"Record what prompted the review, who was involved and the main agreed changes.",detailsIntro:"Capture due and completion dates, involvement, changes and outcomes.",saveLabel:"Save care-plan review"},
  "risk-assessment-reviews":{dateLabel:"Date review was due or completed",titleLabel:"Which person-level risk was reviewed?",titlePlaceholder:"For example, falls risk assessment following a change in mobility",summaryLabel:"Change in risk and review outcome",summaryPlaceholder:"Explain what changed, evidence considered and whether controls remain suitable.",detailsIntro:"Capture assessment type, due date, changed risks, controls and outcome.",saveLabel:"Save risk-assessment review"},
  "mar-audits":{dateLabel:"Date audit completed",titleLabel:"Which MAR sample was audited?",titlePlaceholder:"For example, July MAR sample for Basingstoke branch",summaryLabel:"Scope and headline result",summaryPlaceholder:"Record the period, sample, main strengths, omissions and immediate action.",detailsIntro:"Capture sample size, omissions, stock issues, score and corrective action.",saveLabel:"Save medication and MAR audit"},
  "delegated-healthcare":{dateLabel:"Date delegation or review occurred",titleLabel:"Which healthcare task is being recorded?",titlePlaceholder:"For example, insulin administration delegated by community nurse",summaryLabel:"Delegation arrangement",summaryPlaceholder:"Record the person, task, clinical professional, authorised staff and current instructions.",detailsIntro:"Capture authorisation, competency, review and escalation instructions.",saveLabel:"Save delegated healthcare task"},
  "service-user-outcomes":{dateLabel:"Date outcome reviewed",titleLabel:"Which personal outcome is being tracked?",titlePlaceholder:"For example, regain confidence preparing a light meal",summaryLabel:"Goal and current progress",summaryPlaceholder:"Record the person’s goal, what has changed and what they say about progress.",detailsIntro:"Capture the agreed goal, evidence of progress, the person’s view and next review.",saveLabel:"Save outcome review"},
  "satisfaction-surveys":{dateLabel:"Date survey period closed",titleLabel:"Which survey results are being recorded?",titlePlaceholder:"For example, quarter 2 service-user satisfaction survey",summaryLabel:"Response and headline findings",summaryPlaceholder:"Record audience, response level, overall result and the most important themes.",detailsIntro:"Capture response numbers, scores, positive themes and ‘you said, we did’ action.",saveLabel:"Save survey results"},
  "business-continuity":{dateLabel:"Date of exercise or disruption",titleLabel:"Which scenario or disruption was reviewed?",titlePlaceholder:"For example, 4-hour care-planning system outage exercise",summaryLabel:"What happened and was care maintained?",summaryPlaceholder:"Record the scenario, services affected, decisions, recovery and outcome.",detailsIntro:"Capture activation, critical services, recovery time, lessons and retest date.",saveLabel:"Save continuity record"},
  "commissioner-contracts":{dateLabel:"Reporting or correspondence date",titleLabel:"Which contract obligation is being tracked?",titlePlaceholder:"For example, monthly home-care KPI return",summaryLabel:"Requirement and current position",summaryPlaceholder:"Record what is due, reporting period, performance position, feedback and risk.",detailsIntro:"Capture commissioner, contract, submission dates, performance issues and required action.",saveLabel:"Save contract record"},
  "call-log":{dateLabel:"Date of call",titleLabel:"What was the call about?",titlePlaceholder:"For example, family update about a delayed morning visit",summaryLabel:"Call summary and outcome",summaryPlaceholder:"Record the important facts, decision, advice given and agreed next step. Use internal references instead of unnecessary personal details.",detailsIntro:"Capture who the call involved, direction, time, subject, outcome, follow-up and escalation.",saveLabel:"Save call log entry"},
  deaths:{dateLabel:"Date and time of death",titleLabel:"What death is being recorded?",titlePlaceholder:"For example, expected death at home following end-of-life care",summaryLabel:"Circumstances and immediate response",summaryPlaceholder:"Record factual circumstances, who attended, who was informed and immediate actions.",detailsIntro:"Capture expected status, professional contacts, statutory notification decisions and management review.",saveLabel:"Save death record"},
  "serious-injuries":{dateLabel:"Date and time of injury",titleLabel:"What serious injury occurred?",titlePlaceholder:"For example, fracture confirmed after an unwitnessed fall",summaryLabel:"Injury and immediate response",summaryPlaceholder:"Record what happened, known harm, treatment, escalation and current safety.",detailsIntro:"Capture treatment, hospital attendance, safeguarding, police and CQC notification decisions.",saveLabel:"Save serious-injury record"},
  "duty-of-candour":{dateLabel:"Date incident was identified",titleLabel:"Which candour case is being reviewed?",titlePlaceholder:"For example, medication incident causing prolonged pain",summaryLabel:"Candour decision and communication",summaryPlaceholder:"Explain the threshold decision, what the person was told, support and next steps.",detailsIntro:"Keep the verbal notification, apology, written follow-up and contact attempts together.",saveLabel:"Save duty-of-candour record"},
  "infection-events":{dateLabel:"Date symptoms or concern began",titleLabel:"What infection event occurred?",titlePlaceholder:"For example, two linked respiratory infections affecting care visits",summaryLabel:"Cases, risks and initial controls",summaryPlaceholder:"Record symptoms or diagnosis, linked cases, advice and immediate infection controls.",detailsIntro:"Capture professional advice, notifications, service impact, closure and learning.",saveLabel:"Save infection event"},
  "capacity-consent":{dateLabel:"Date of assessment or decision",titleLabel:"What decision required consent or capacity assessment?",titlePlaceholder:"For example, consent to staff administering prescribed medicines",summaryLabel:"Decision-specific circumstances",summaryPlaceholder:"Record the decision, the person’s wishes, support provided and why assessment was needed.",detailsIntro:"Capture consent, capacity, best-interest reasoning, legal authority, consultation and review.",saveLabel:"Save capacity and consent decision"},
  "restrictive-practice":{dateLabel:"Date restriction was used or proposed",titleLabel:"What restrictive practice is being reviewed?",titlePlaceholder:"For example, limiting access to unsafe equipment during acute confusion",summaryLabel:"Risk, restriction and immediate outcome",summaryPlaceholder:"Record the risk, action taken, duration, person’s response and any harm or distress.",detailsIntro:"Document legal basis, proportionality, alternatives, authorisation, safeguarding and reduction planning.",saveLabel:"Save restrictive-practice record"},
  "nutrition-hydration":{dateLabel:"Date concern identified",titleLabel:"What nutrition or hydration concern was identified?",titlePlaceholder:"For example, reduced fluid intake over three consecutive visits",summaryLabel:"Observed concern and impact",summaryPlaceholder:"Record observations, measurements, the person’s view and immediate support.",detailsIntro:"Capture clinical referral, care-plan changes, monitoring and outcome.",saveLabel:"Save nutrition or hydration concern"},
  "clinical-escalations":{dateLabel:"Date and time deterioration was observed",titleLabel:"What change in health was escalated?",titlePlaceholder:"For example, new breathlessness and confusion during morning care",summaryLabel:"Signs, advice and response",summaryPlaceholder:"Record the change, observations, who was contacted, advice and actions taken.",detailsIntro:"Capture professional escalation, handover, family communication and outcome.",saveLabel:"Save clinical escalation"},
  "medicines-support":{dateLabel:"Assessment or review date",titleLabel:"Whose medicines support was assessed?",titlePlaceholder:"For example, medicines support review after hospital discharge",summaryLabel:"Assessed need and agreed support",summaryPlaceholder:"Explain what the person can do, support required, consent and responsibilities.",detailsIntro:"Capture support level, risks, care-plan and recording requirements and review date.",saveLabel:"Save medicines support assessment"},
  "prn-protocols":{dateLabel:"Protocol approval or review date",titleLabel:"Which when-required medicine protocol is this?",titlePlaceholder:"For example, paracetamol PRN protocol for pain",summaryLabel:"Purpose and safe-use instructions",summaryPlaceholder:"Record indication, dose limits, alternatives, monitoring and escalation.",detailsIntro:"Keep person-specific PRN instructions, source authorisation and review together.",saveLabel:"Save PRN protocol"},
  "covert-medicines":{dateLabel:"Decision date",titleLabel:"Which covert-medicines decision is being recorded?",titlePlaceholder:"For example, time-limited covert administration following capacity assessment",summaryLabel:"Exceptional decision and reasons",summaryPlaceholder:"Record capacity findings, best-interest reasoning, consultation and alternatives considered.",detailsIntro:"Capture professional authorisation, administration instructions, records and review date.",saveLabel:"Save covert-medicines decision"},
  "medicines-reconciliation":{dateLabel:"Reconciliation date",titleLabel:"What medicines transition or change was checked?",titlePlaceholder:"For example, reconciliation following hospital discharge",summaryLabel:"Sources, differences and confirmation",summaryPlaceholder:"Record the lists checked, discrepancies found, clarification and confirmed changes.",detailsIntro:"Capture information sources, updates to MAR and care plans, staff communication and checker.",saveLabel:"Save medicines reconciliation"},
  "equipment-safety":{dateLabel:"Check, fault or service date",titleLabel:"Which item of equipment is being recorded?",titlePlaceholder:"For example, mobile hoist fault reported during a care visit",summaryLabel:"Condition, risk and immediate control",summaryPlaceholder:"Record the item, fault or check result, people at risk and action taken.",detailsIntro:"Capture removal from use, supplier contact, repair, servicing and verification.",saveLabel:"Save equipment-safety record"},
  "health-safety-hazards":{dateLabel:"Date hazard identified",titleLabel:"What health and safety hazard was found?",titlePlaceholder:"For example, damaged stair rail affecting safe access for staff",summaryLabel:"Hazard, people at risk and immediate action",summaryPlaceholder:"Record where it was found, potential harm and what was done immediately.",detailsIntro:"Capture controls, further action, reporting, RIDDOR consideration and closure.",saveLabel:"Save health and safety hazard"},
  "riddor-reports":{dateLabel:"Date reportability was considered",titleLabel:"Which event was assessed under RIDDOR?",titlePlaceholder:"For example, staff fracture following a work-related fall",summaryLabel:"Event and reporting decision",summaryPlaceholder:"Record the work activity, injury or event, category considered and decision basis.",detailsIntro:"Capture HSE submission, reference, investigation, action and closure.",saveLabel:"Save RIDDOR decision"},
  "lone-working":{dateLabel:"Date and time of lone-working event",titleLabel:"What lone-working concern occurred?",titlePlaceholder:"For example, worker failed to complete scheduled welfare check",summaryLabel:"Risk and response",summaryPlaceholder:"Record the last known contact, attempts made, risks and escalation.",detailsIntro:"Capture safety confirmation, emergency response, risk review and lessons.",saveLabel:"Save lone-working event"},
  "referrals-intake":{dateLabel:"Date referral received",titleLabel:"What service was requested?",titlePlaceholder:"For example, twice-daily personal care after hospital discharge",summaryLabel:"Needs, timescales and initial risks",summaryPlaceholder:"Record the requested support, start date, known risks and missing information.",detailsIntro:"Capture capacity assessment, acceptance decision, reasons, communication and next step.",saveLabel:"Save referral decision"},
  "service-starts":{dateLabel:"Planned start date",titleLabel:"Which new service start is being checked?",titlePlaceholder:"For example, commencement of four daily care visits",summaryLabel:"Readiness and outstanding matters",summaryPlaceholder:"Record the agreed service, assessment status, risks, staffing and information shared.",detailsIntro:"Confirm the essential checks for a safe, person-centred service start.",saveLabel:"Save service-start record"},
  "service-endings":{dateLabel:"Decision or final-service date",titleLabel:"Which service ending or handback is being recorded?",titlePlaceholder:"For example, commissioner handback after needs exceeded service capacity",summaryLabel:"Reason, communication and continuity",summaryPlaceholder:"Record the decision basis, notice, risks and safe transition arrangements.",detailsIntro:"Capture handover, final records, property reconciliation and outstanding matters.",saveLabel:"Save service-ending record"},
  "accessible-information":{dateLabel:"Date need identified or reviewed",titleLabel:"What communication need or adjustment is required?",titlePlaceholder:"For example, care information in large print with verbal explanation",summaryLabel:"Person’s need and preferred approach",summaryPlaceholder:"Record how the person communicates, barriers and what works for them.",detailsIntro:"Capture formats, support, adjustments, system flags, sharing and confirmation from the person.",saveLabel:"Save communication requirement"},
  "key-access":{dateLabel:"Issue, change or return date",titleLabel:"What key or access arrangement is being recorded?",titlePlaceholder:"For example, replacement key-safe code issued after compromise",summaryLabel:"Access item, holder and security position",summaryPlaceholder:"Record the item or code without exposing the actual secret, who holds it and what changed.",detailsIntro:"Capture authorisation, loss or compromise, immediate controls, return and verification.",saveLabel:"Save key and access record"},
  "money-property":{dateLabel:"Transaction or event date",titleLabel:"What money or property record is being added?",titlePlaceholder:"For example, shopping cash reconciled with receipt and change",summaryLabel:"Instruction, transaction and outcome",summaryPlaceholder:"Record the person’s instruction, amount or item, staff involved and supporting receipt.",detailsIntro:"Capture authorisation, discrepancies, safeguarding consideration and reconciliation.",saveLabel:"Save money or property record"},
  "data-subject-rights":{dateLabel:"Date request received",titleLabel:"What information-rights request was received?",titlePlaceholder:"For example, representative requesting a copy of care records",summaryLabel:"Requester, scope and identity position",summaryPlaceholder:"Record the request in clear terms, authority, identity checks and records involved.",detailsIntro:"Track deadline, searches, redactions or exemptions, response and outcome.",saveLabel:"Save information-rights request"},
  "data-sharing":{dateLabel:"Date information was shared or requested",titleLabel:"What information-sharing decision was made?",titlePlaceholder:"For example, safeguarding information shared with the local authority",summaryLabel:"Purpose, recipient and information",summaryPlaceholder:"Record why sharing was needed, with whom and the minimum information involved.",detailsIntro:"Capture lawful basis, necessity, security, agreements and outcome.",saveLabel:"Save information-sharing record"},
  "records-disposal":{dateLabel:"Decision or disposal date",titleLabel:"Which records are being reviewed for disposal?",titlePlaceholder:"For example, archived staff recruitment records reaching retention limit",summaryLabel:"Record series, date range and retention basis",summaryPlaceholder:"Describe the records, applicable retention rule and checks completed.",detailsIntro:"Capture legal holds, authorisation, disposal method, certificate and completion.",saveLabel:"Save records-disposal decision"},
  "conflicts-interests":{dateLabel:"Date interest declared",titleLabel:"What conflict of interest was declared?",titlePlaceholder:"For example, manager related to a potential supplier",summaryLabel:"Interest and affected decision",summaryPlaceholder:"Record the relationship or interest, activity affected and current risk.",detailsIntro:"Capture actual or potential status, management plan, exclusions, approval and review.",saveLabel:"Save conflict declaration"},
  "gifts-hospitality":{dateLabel:"Date offered or received",titleLabel:"What gift or hospitality was offered?",titlePlaceholder:"For example, £30 gift voucher offered by a family",summaryLabel:"Offer, value and decision",summaryPlaceholder:"Record what was offered, by whom, estimated value and whether it was accepted.",detailsIntro:"Capture policy decision, approval, conflicts and final action.",saveLabel:"Save gift or hospitality record"},
  "regulatory-actions":{dateLabel:"Date correspondence or notice received",titleLabel:"What regulatory action or request was received?",titlePlaceholder:"For example, CQC request for evidence following a concern",summaryLabel:"Requirement, deadline and current risk",summaryPlaceholder:"Record the regulator’s concern or requirement, response date and immediate governance action.",detailsIntro:"Track notices, leadership ownership, evidence submitted, outcome and appeal where relevant.",saveLabel:"Save regulatory action"},
  "professional-referrals":{dateLabel:"Date referral was considered",titleLabel:"Which professional or barring referral is being reviewed?",titlePlaceholder:"For example, DBS referral following dismissal for safeguarding conduct",summaryLabel:"Concern, employment action and risk",summaryPlaceholder:"Record the conduct or risk, employment decision and why referral thresholds were considered.",detailsIntro:"Capture advice, decision maker, submission, reference and restrictions.",saveLabel:"Save professional-referral decision"},
  "pir-submissions":{dateLabel:"Date PIR request received",titleLabel:"Which Provider Information Return is being prepared?",titlePlaceholder:"For example, 2026 annual domiciliary-care PIR",summaryLabel:"Period, deadline and preparation position",summaryPlaceholder:"Record the reporting period, key changes, responsible lead and outstanding evidence.",detailsIntro:"Track contributors, data validation, approval, submission and confirmation.",saveLabel:"Save PIR record"},
  "insurance-claims":{dateLabel:"Date claim or potential claim identified",titleLabel:"What insurance matter is being recorded?",titlePlaceholder:"For example, potential public-liability claim following property damage",summaryLabel:"Circumstances, alleged loss and immediate response",summaryPlaceholder:"Record the event, claimant reference, evidence preserved and notification position.",detailsIntro:"Capture insurer contact, claim reference, legal restrictions and outcome.",saveLabel:"Save insurance claim"},
  "agency-staff-assurance":{dateLabel:"Assignment or assurance-check date",titleLabel:"Which agency worker is being checked?",titlePlaceholder:"For example, agency care worker allocated to medication calls",summaryLabel:"Role, checks and deployment limits",summaryPlaceholder:"Record the worker reference, agency, duties and evidence received before deployment.",detailsIntro:"Confirm identity, recruitment, training, competency, induction and restrictions.",saveLabel:"Save agency-worker assurance"},
  "end-of-life-coordination":{dateLabel:"Planning or review date",titleLabel:"Whose end-of-life coordination is being reviewed?",titlePlaceholder:"For example, anticipatory care plan agreed with community nursing team",summaryLabel:"Person’s wishes and coordination position",summaryPlaceholder:"Record what matters to the person, professional involvement and current arrangements.",detailsIntro:"Capture capacity, representation, advance planning, clinical contacts, staff briefing and review.",saveLabel:"Save end-of-life coordination record"},
};

export function registerFormExperience(key:string,name:string):RegisterFormExperience{
  const specific=EXPERIENCES[key]??{};
  if(isAssessmentKey(key))return{dateLabel:"Assessment date",titleLabel:key==="assessment-initial-needs"?"Whose initial assessment is this?":"Which person, service or decision is being assessed?",titlePlaceholder:"Use a secure internal reference and a clear assessment subject",summaryLabel:"Assessment conclusion and immediate next step",summaryPlaceholder:"Summarise the main findings, decision, controls and any urgent escalation.",detailsIntro:key==="assessment-consent-authority"?"Record each consent decision separately. Consent must be informed, voluntary, current and capable of withdrawal; do not use a blanket decision.":"Complete the relevant findings, controls, involvement, evidence and review plan. Use recognised clinical tools where required and attach them as evidence.",saveLabel:`Save ${name.toLowerCase()}`};
  return{dateLabel:specific.dateLabel??"Date recorded",titleLabel:specific.titleLabel??`What ${name.toLowerCase()} record are you adding?`,titlePlaceholder:specific.titlePlaceholder??`Enter a clear, specific ${name.toLowerCase()} title`,summaryLabel:specific.summaryLabel??"What happened and what needs attention?",summaryPlaceholder:specific.summaryPlaceholder??"Record the facts, impact, response and next step.",detailsIntro:specific.detailsIntro??`Complete the information needed for this ${name.toLowerCase()} record.`,saveLabel:specific.saveLabel??`Save ${name.toLowerCase()} record`};
}

export const REGISTER_GROUPS = [
  { key:"safety", name:"Safety, incidents and safeguarding", description:"Events, immediate protection, statutory decisions, investigation and learning." },
  { key:"medicines", name:"Medicines and clinical assurance", description:"Medicines support, clinical escalation, health monitoring and delegated care." },
  { key:"people", name:"People’s rights, care and outcomes", description:"Consent, involvement, individual outcomes, communication and person-centred reviews." },
  { key:"delivery", name:"Service delivery and continuity", description:"Referrals, service starts and endings, visits, access and operational continuity." },
  { key:"workforce", name:"Workforce and workplace safety", description:"Staff assurance, speaking up, competence exceptions and worker safety." },
  { key:"feedback", name:"Feedback, complaints and improvement", description:"What people and staff say, formal complaints, recognition and survey learning." },
  { key:"governance", name:"Governance, information and external assurance", description:"Regulatory returns, information governance, declarations, claims and commissioner oversight." },
] as const;

const GROUP_KEYS:Record<string,string[]>={
  safety:["incidents","accidents","near-misses","safeguarding","falls","pressure-damage","deaths","serious-injuries","duty-of-candour","infection-events","restrictive-practice","health-safety-hazards","riddor-reports"],
  medicines:["medicines-errors","mar-audits","medicines-support","prn-protocols","covert-medicines","medicines-reconciliation","clinical-escalations","nutrition-hydration","delegated-healthcare","equipment-safety"],
  people:["care-plan-reviews","risk-assessment-reviews","capacity-consent","service-user-outcomes","accessible-information","end-of-life-coordination"],
  delivery:["missed-visits","late-visits","hospital-admissions","referrals-intake","service-starts","service-endings","call-log","key-access","money-property","business-continuity"],
  workforce:["staff-concerns","training-exceptions","supervision-exceptions","whistleblowing","agency-staff-assurance","lone-working","professional-referrals"],
  feedback:["complaints","compliments","service-user-feedback","staff-feedback","satisfaction-surveys"],
  governance:["cqc-notifications","data-breaches","data-subject-rights","data-sharing","records-disposal","conflicts-interests","gifts-hospitality","regulatory-actions","pir-submissions","insurance-claims","commissioner-contracts"],
};

const CQC_REGULATIONS="https://www.cqc.org.uk/guidance-regulation/providers/regulations-service-providers-and-managers";
const SOURCE_BY_KEY:Record<string,string>={
  deaths:"https://www.cqc.org.uk/guidance-regulation/providers/registration/guidance",
  "serious-injuries":"https://www.cqc.org.uk/guidance-regulation/providers/registration/guidance",
  "cqc-notifications":"https://www.cqc.org.uk/guidance-providers/notifications",
  "duty-of-candour":"https://www.cqc.org.uk/guidance-regulation/providers/regulations-service-providers-and-managers/health-social-care-act/regulation-20/what-you-must-do",
  "infection-events":"https://www.gov.uk/government/publications/infection-prevention-and-control-in-adult-social-care-settings/infection-prevention-and-control-resource-for-adult-social-care",
  "medicines-errors":"https://www.cqc.org.uk/guidance-providers/adult-social-care/reporting-medicine-related-incidents",
  "mar-audits":"https://www.cqc.org.uk/guidance-providers/adult-social-care/medicines-administration-records-adult-social-care",
  "medicines-support":"https://www.nice.org.uk/guidance/ng67/chapter/Recommendations",
  "prn-protocols":"https://www.nice.org.uk/guidance/ng67/chapter/Recommendations",
  "covert-medicines":"https://www.nice.org.uk/guidance/ng67/chapter/Recommendations",
  "medicines-reconciliation":"https://www.nice.org.uk/guidance/ng67/chapter/Recommendations",
  "capacity-consent":"https://www.gov.uk/government/publications/mental-capacity-act-code-of-practice",
  "restrictive-practice":"https://www.gov.uk/government/publications/mental-capacity-act-code-of-practice",
  "riddor-reports":"https://www.hse.gov.uk/riddor/",
  "lone-working":"https://www.hse.gov.uk/lone-working/",
  "accessible-information":"https://www.england.nhs.uk/long-read/accessible-information-standard-requirements-dapb1605/",
  "data-breaches":"https://ico.org.uk/for-organisations/advice-and-services/audits/data-protection-audit-framework/toolkits/personal-data-breach-management/breach-identification-assessment-and-logging/",
  "data-subject-rights":"https://ico.org.uk/for-the-public/your-right-to-get-copies-of-your-data/",
  "data-sharing":"https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-sharing/data-sharing-a-code-of-practice/",
  "records-disposal":"https://transform.england.nhs.uk/information-governance/guidance/records-management-code/",
  "pir-submissions":"https://www.cqc.org.uk/adult-social-care-provider-information-return",
  "regulatory-actions":"https://www.cqc.org.uk/guidance-regulation/providers/enforcement",
};

const WHEN_BY_KEY:Record<string,string>={
  deaths:"Use for every death of a person receiving the regulated service; separately assess CQC and other notification duties.",
  "serious-injuries":"Use when an injury may meet CQC serious-injury criteria or needs enhanced management oversight.",
  "duty-of-candour":"Use whenever the Regulation 20 threshold may apply, including a recorded decision when it does not.",
  "infection-events":"Use for significant infection concerns, linked cases, possible outbreaks or events needing professional advice.",
  "capacity-consent":"Use for a specific care or treatment decision where consent, capacity or lawful authority needs evidence.",
  "restrictive-practice":"Use whenever care restricts a person’s movement, access or choices, including emergency use and review.",
  "riddor-reports":"Use when a work-related accident, disease or dangerous occurrence needs a documented RIDDOR decision.",
  "data-subject-rights":"Use when a person exercises a UK GDPR information right; monitor the statutory response deadline.",
  "professional-referrals":"Use when conduct or risk may trigger DBS, professional-regulator or commissioner referral duties.",
  "regulatory-actions":"Use for formal regulator correspondence, notices, requirements, evidence requests or enforcement action.",
};

export function registerGroupKey(key:string):string{
  return Object.entries(GROUP_KEYS).find(([,keys])=>keys.includes(key))?.[0]??"governance";
}

export function registerGuidance(key:string){
  const assessment=assessmentType(key);if(assessment)return{group:{key:"people",name:"Assessment Centre",description:"Structured person-centred and service assessment records."},sourceUrl:assessment.sourceUrl,when:key==="assessment-initial-needs"?"Complete before accepting or starting a service, then review whenever needs or circumstances materially change.":key==="assessment-consent-authority"?"Complete after the initial assessment and before specialist assessment or planned support. Record each decision separately and reassess when the decision or capacity changes.":"Complete only where the initial assessment indicates this assessment is relevant. Link the initial assessment and consent record, involve the person, and review after change or at the planned date."};
  const group=REGISTER_GROUPS.find((item)=>item.key===registerGroupKey(key))??REGISTER_GROUPS[6];
  return{group,sourceUrl:SOURCE_BY_KEY[key]??CQC_REGULATIONS,when:WHEN_BY_KEY[key]??`Use this register whenever a ${key.replaceAll("-"," ")} event, decision or exception needs accountable oversight, evidence or follow-up.`};
}
import { assessmentType, isAssessmentKey } from "@/lib/assessments";
