export const TEMPLATE_CATEGORIES = ["Policies","Audit forms","Risk assessments","Governance meetings","Action plans","Investigation forms","Complaints","Incident management","Safeguarding","Recruitment","Supervision","Competency assessments","Quality improvement","Business continuity","Reports","Letters","Checklists"] as const;
export const TEMPLATE_STATUSES = ["DRAFT","PUBLISHED","ARCHIVED"] as const;
export const MAX_TEMPLATE_FILE_BYTES = 10 * 1024 * 1024;
export const ALLOWED_TEMPLATE_FILE_TYPES = new Set(["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/csv","text/plain","image/jpeg","image/png"]);
export function templateLabel(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/^\w/,(letter)=>letter.toUpperCase());}
export function validateTemplateFile(file:File){if(!file.size)throw new Error("Choose a template file.");if(file.size>MAX_TEMPLATE_FILE_BYTES)throw new Error("The template file must be 10 MB or smaller.");if(!ALLOWED_TEMPLATE_FILE_TYPES.has(file.type))throw new Error("Upload a PDF, Office, CSV, text, JPG or PNG file.");}
export function templateScopeWhere(organisationId:string){return{OR:[{organisationId:null},{organisationId}]};}
export function templateEvidenceCategory(category:string){if(category==="Policies")return"Policies";if(category==="Audit forms")return"Audits";if(category==="Complaints")return"Complaints";if(category==="Safeguarding")return"Safeguarding";if(category==="Incident management"||category==="Investigation forms")return"Incidents";if(category==="Business continuity")return"Business continuity";if(category==="Recruitment"||category==="Supervision"||category==="Competency assessments")return"Competencies";if(category==="Quality improvement"||category==="Action plans")return"Quality improvement";if(category==="Reports"||category==="Governance meetings")return"Governance meetings";return"Other";}
export function canPreviewTemplate(contentType:string){return contentType==="application/pdf"||contentType.startsWith("image/")||contentType.startsWith("text/");}
