import "server-only";

import { getPolicyFile } from "@/lib/policy-storage";

export type TemplateBrand = {
  name: string;
  policyBrandName: string | null;
  policyRegistrationNumber: string | null;
  policyAddress: string | null;
  policyEmail: string | null;
  policyPhone: string | null;
  policyWebsite: string | null;
  policyPrimaryColour: string;
  policyLogoStorageKey: string | null;
  policyLogoContentType: string | null;
};

function escape(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

function bodyMarkup(body: string): string {
  const normalised = body.replaceAll("\\r\\n", "\n").replaceAll("\\n", "\n");
  return normalised.split(/\r?\n/).map((raw) => {
    const line = raw.trim();
    if (!line) return '<div class="space"></div>';
    if (/^[A-Z0-9 /&(),'-]{4,}$/.test(line)) return `<h2>${escape(line)}</h2>`;
    if (/^\[[ xX]\]/.test(line)) return `<p class="check">☐ ${escape(line.replace(/^\[[ xX]\]\s*/, ""))}</p>`;
    if (/^[^:]{2,80}:$/.test(line)) return `<div class="field"><strong>${escape(line)}</strong><span></span></div>`;
    return `<p>${escape(line)}</p>`;
  }).join("");
}

export async function templateLogoDataUrl(brand: TemplateBrand): Promise<string | null> {
  if (!brand.policyLogoStorageKey || !brand.policyLogoContentType) return null;
  const file = await getPolicyFile(brand.policyLogoStorageKey);
  if (!file) return null;
  const bytes = new Uint8Array(await new Response(file).arrayBuffer());
  return `data:${brand.policyLogoContentType};base64,${Buffer.from(bytes).toString("base64")}`;
}

export function brandedTemplateHtml(input: { title: string; category: string; version: string; bodyText: string; brand: TemplateBrand; logoDataUrl: string | null }): string {
  const displayName = input.brand.policyBrandName?.trim() || input.brand.name;
  const colour = /^#[0-9a-f]{6}$/i.test(input.brand.policyPrimaryColour) ? input.brand.policyPrimaryColour : "#0f766e";
  const contact = [input.brand.policyRegistrationNumber, input.brand.policyEmail, input.brand.policyPhone, input.brand.policyWebsite].filter(Boolean).map(String).join(" · ");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(input.title)} | ${escape(displayName)}</title><style>
  @page{size:A4;margin:18mm}*{box-sizing:border-box}body{margin:0;background:#eef2f1;color:#17211f;font:14px/1.55 Arial,sans-serif}.page{width:min(210mm,100%);min-height:297mm;margin:24px auto;background:#fff;box-shadow:0 16px 45px #102a2430}.brand{display:grid;grid-template-columns:150px 1fr;gap:24px;align-items:center;padding:28px 34px;background:${colour};color:#fff}.brand img{width:138px;height:88px;object-fit:contain;background:#fff;border-radius:12px;padding:10px}.brand .name{font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.brand h1{margin:7px 0 0;font-size:28px;line-height:1.15}.meta{display:flex;flex-wrap:wrap;gap:8px 20px;padding:12px 34px;border-bottom:1px solid #dbe4e1;background:#f7faf9;color:#50605c;font-size:11px}.content{padding:22px 34px 42px}.content h2{margin:22px 0 10px;padding-bottom:7px;border-bottom:2px solid ${colour};color:${colour};font-size:16px;letter-spacing:.05em}.content p{margin:8px 0}.space{height:5px}.field{display:grid;grid-template-columns:minmax(175px,35%) 1fr;gap:12px;align-items:end;margin:8px 0}.field span{min-height:23px;border-bottom:1px solid #86938f}.check{padding:5px 8px;border:1px solid #dbe4e1;border-radius:6px}.footer{margin:0 34px;padding:14px 0 24px;border-top:1px solid #dbe4e1;color:#687772;font-size:10px}@media print{body{background:#fff}.page{width:auto;min-height:auto;margin:0;box-shadow:none}.brand{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
  </style></head><body><article class="page"><header class="brand">${input.logoDataUrl ? `<img src="${input.logoDataUrl}" alt="${escape(displayName)} logo">` : `<div class="name">${escape(displayName)}</div>`}<div><div class="name">${escape(input.category)} · Controlled template v${escape(input.version)}</div><h1>${escape(input.title)}</h1></div></header><div class="meta"><span>${escape(displayName)}</span>${contact ? `<span>${escape(contact)}</span>` : ""}<span>Generated ${new Intl.DateTimeFormat("en-GB", { dateStyle: "long", timeZone: "Europe/London" }).format(new Date())}</span></div><main class="content">${bodyMarkup(input.bodyText)}</main><footer class="footer">Controlled working document generated by QCGMS. Complete all relevant fields, protect personal information, obtain the required approval and retain the final record in the Evidence Library.</footer></article></body></html>`;
}
