INSERT INTO "KpiDefinition" ("organisationId","name","slug","description","unit","direction","targetValue","greenThreshold","amberThreshold","sortOrder","updatedAt")
SELECT o."id", v.name, v.slug, v.description, v.unit, v.direction::"KpiDirection", v.target, v.green_value, v.amber_value, v.sort_order, CURRENT_TIMESTAMP
FROM "Organisation" o
CROSS JOIN (VALUES
('2.1a — Packages of care ended','scc-pocs-ended','Surrey 2026 commissioner tracker field 2.1a. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,100),
('2.1b — Packages handed back by provider','scc-pocs-handed-back','Surrey 2026 commissioner tracker field 2.1b. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,101),
('2.2a — Total calls provided','scc-total-calls','Surrey 2026 commissioner tracker field 2.2a. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,102),
('2.3a — Late calls','scc-late-calls','Surrey 2026 commissioner tracker field 2.3a. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,103),
('3.3b — Missed calls','scc-missed-calls','Surrey 2026 commissioner tracker field 3.3b. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,104),
('2.3c — Rescheduled calls','scc-rescheduled-calls','Surrey 2026 commissioner tracker field 2.3c. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,105),
('2.3d — Calls cancelled by provider','scc-provider-cancelled-calls','Surrey 2026 commissioner tracker field 2.3d. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,106),
('2.3f — Calls cancelled by service user','scc-service-user-cancelled-calls','Surrey 2026 commissioner tracker field 2.3f. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,107),
('2.3g — Service-user cancellations within 24 hours','scc-service-user-cancelled-under24h','Surrey 2026 commissioner tracker field 2.3g. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,108),
('3.1a — Restarts offered','scc-restarts-offered','Surrey 2026 commissioner tracker field 3.1a. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,109),
('3.1b — Eligible restarts taken on','scc-eligible-restarts-taken','Surrey 2026 commissioner tracker field 3.1b. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,110),
('SCC — POCs accepted on eBrokerage','scc-referrals-accepted','Surrey commissioner data item recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,111),
('SCC — POCs rejected on eBrokerage','scc-referrals-rejected','Surrey commissioner data item recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,112),
('SCC — POC requests answered positively','scc-referrals-positive-response','Surrey commissioner data item recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,113),
('SCC — POC requests answered negatively','scc-referrals-negative-response','Surrey commissioner data item recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,114),
('SCC — POC requests with no response','scc-referrals-no-response','Surrey commissioner data item recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,115),
('SCC — POC requests started','scc-pocs-started','Surrey commissioner data item recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,116),
('SCC — POCs awarded','scc-pocs-awarded','Surrey commissioner data item recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,117),
('SCC — POCs active at month end','scc-active-pocs-month-end','Surrey commissioner data item recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,118),
('4.1a — Live-in packages ended','scc-live-in-pocs-ended','Surrey 2026 commissioner tracker field 4.1a. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,119),
('4.1b — Live-in packages handed back','scc-live-in-pocs-handed-back','Surrey 2026 commissioner tracker field 4.1b. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,120),
('4.2a — Live-in break periods delivered','scc-live-in-break-periods-delivered','Surrey 2026 commissioner tracker field 4.2a. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,121),
('4.2b — Live-in break periods not required','scc-live-in-break-periods-not-required','Surrey 2026 commissioner tracker field 4.2b. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,122),
('4.3a — Active live-in care staff','scc-active-live-in-staff','Surrey 2026 commissioner tracker field 4.3a. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,123),
('4.3b — Live-in staff supervised','scc-live-in-staff-supervised','Surrey 2026 commissioner tracker field 4.3b. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,124),
('5.1a — Total staff at month end','scc-staff-month-end','Surrey 2026 commissioner tracker field 5.1a. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,125),
('5.1b — New direct-care staff','scc-new-direct-care-staff','Surrey 2026 commissioner tracker field 5.1b. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,126),
('5.1c — New back-office staff','scc-new-back-office-staff','Surrey 2026 commissioner tracker field 5.1c. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,127),
('5.1d — Staff who left','scc-staff-left','Surrey 2026 commissioner tracker field 5.1d. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,128),
('5.2a — New staff eligible for orientation training','scc-orientation-eligible','Surrey 2026 commissioner tracker field 5.2a. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,129),
('5.2b — New staff due to complete orientation training','scc-orientation-completed','Surrey 2026 commissioner tracker field 5.2b. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,130),
('5.2c — Staff with valid Care Certificate','scc-care-certificate-valid','Surrey 2026 commissioner tracker field 5.2c. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,131),
('6.1a — Sponsored staff working in Surrey','scc-sponsored-staff-surrey','Surrey 2026 commissioner tracker field 6.1a. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,132),
('7.1a — Formal complaints received','scc-complaints-received','Surrey 2026 commissioner tracker field 7.1a. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,133),
('7.1b — Formal complaints upheld','scc-complaints-upheld','Surrey 2026 commissioner tracker field 7.1b. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,134),
('7.1c — Formal complaints not upheld','scc-complaints-not-upheld','Surrey 2026 commissioner tracker field 7.1c. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,135),
('7.1d — Complaints open or pending','scc-complaints-open','Surrey 2026 commissioner tracker field 7.1d. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,136),
('7.1e — Complaints closed','scc-complaints-closed','Surrey 2026 commissioner tracker field 7.1e. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,137),
('8.1a — Safeguarding referrals received','scc-safeguarding-referrals','Surrey 2026 commissioner tracker field 8.1a. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,138),
('8.1b — Safeguarding referrals triggering Section 42','scc-section42-enquiries','Surrey 2026 commissioner tracker field 8.1b. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,139),
('8.1c — Section 42 outcomes: risk present','scc-section42-risk-present','Surrey 2026 commissioner tracker field 8.1c. Recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,140),
('8.1d — Section 42 outcomes: no risk','scc-section42-no-risk','Surrey 2026 commissioner tracker field 8.1d. Recorded through the Monthly KPI Return.','count','HIGHER_IS_BETTER',0,0,0,141),
('SCC — Section 42 enquiries open or pending','scc-section42-open','Surrey commissioner data item recorded through the Monthly KPI Return.','count','LOWER_IS_BETTER',0,0,0,142),
('Auto calc — call exception rate','scc-call-exception-rate','Workbook auto-calculation: late, missed, rescheduled, provider-cancelled and service-user-cancelled calls divided by total calls.','%','LOWER_IS_BETTER',0,0,5,143),
('Auto calc — successful restarts','scc-restart-acceptance-rate','Eligible restarts taken on divided by restarts offered.','%','HIGHER_IS_BETTER',100,100,90,144),
('Auto calc — new staff rate','scc-new-staff-rate','New direct-care and back-office staff divided by total staff at month end.','%','HIGHER_IS_BETTER',0,0,0,145),
('Auto calc — valid Care Certificate','scc-care-certificate-rate','Staff with a valid Care Certificate divided by total staff at month end.','%','HIGHER_IS_BETTER',100,100,90,146),
('KPI 4 — referral response rate','scc-referral-response-rate','POC requests answered positively or negatively divided by all POC requests. Surrey target: 100%.','%','HIGHER_IS_BETTER',100,100,95,147)
) AS v(name,slug,description,unit,direction,target,green_value,amber_value,sort_order)
ON CONFLICT ("organisationId","slug") DO NOTHING;
