import Link from "next/link";
import { requireAnyPermission } from "@/lib/auth/dal";
import { ACTION_CATEGORIES, ACTION_PRIORITIES, ACTION_STATUSES, actionDaysRemaining, actionLabel, actionScopeWhere, effectiveActionStatus, priorityClasses } from "@/lib/actions";
import { ASSURANCE_LIFECYCLE_STATUSES } from "@/lib/closure-loop";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

const PAGE_SIZE = 20;
export default async function ActionsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const context = await requireAnyPermission([PERMISSIONS.GOVERNANCE_VIEW, PERMISSIONS.ASSIGNED_TASKS_EDIT, PERMISSIONS.ACTIONS_MANAGE]);
  const query = await searchParams, q = field(query, "q"), status = field(query, "status"), priority = field(query, "priority"), owner = field(query, "owner"), category = field(query, "category"), location = field(query, "location"), client = field(query, "client"), staff = field(query, "staff"), lifecycle = field(query, "lifecycle"), recurrence = field(query, "recurrence"), dateFrom = field(query, "dateFrom"), dateTo = field(query, "dateTo"), page = Math.max(1, Number(field(query, "page")) || 1), now = new Date(), db = createDb();
  try {
    const base = actionScopeWhere(context), statusWhere = status === "OVERDUE" ? { status: { notIn: ["COMPLETED", "CANCELLED", "ARCHIVED"] as never[] }, dueDate: { lt: now } } : status ? { status: status as never } : {};
    const where = { AND: [base, ...(q ? [{ OR: [{ reference: { contains: q, mode: "insensitive" as const } }, { title: { contains: q, mode: "insensitive" as const } }, { description: { contains: q, mode: "insensitive" as const } }, { expectedOutcome: { contains: q, mode: "insensitive" as const } }] }] : [])], ...statusWhere, ...(priority ? { priority: priority as never } : {}), ...(owner ? { ownerId: owner } : {}), ...(category ? { category } : {}), ...(location ? { locationId: location } : {}), ...(client ? { clientId: client } : {}), ...(staff ? { staffMemberId: staff } : {}), ...(lifecycle ? { lifecycleStatus: lifecycle as never } : {}), ...(recurrence === "yes" ? { recurrenceCount: { gt: 0 } } : recurrence === "no" ? { recurrenceCount: 0 } : {}), ...(dateFrom || dateTo ? { lastSeenAt: { ...(dateFrom ? { gte: start(dateFrom) } : {}), ...(dateTo ? { lte: end(dateTo) } : {}) } } : {}) };
    const [actions, total, overdue, high, blocked, verification, memberships, clients, staffMembers] = await Promise.all([
      db.action.findMany({ where, include: { owner: { select: { name: true } }, location: { select: { name: true } }, client: { select: { firstName: true, lastName: true } }, staffMember: { select: { firstName: true, lastName: true } }, _count: { select: { evidenceLinks: true, updates: true, occurrences: true } } }, orderBy: [{ lastSeenAt: "desc" }, { dueDate: "asc" }], skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE }),
      db.action.count({ where }), db.action.count({ where: { ...base, status: { notIn: ["COMPLETED", "CANCELLED", "ARCHIVED"] }, dueDate: { lt: now } } }), db.action.count({ where: { ...base, status: { notIn: ["COMPLETED", "CANCELLED", "ARCHIVED"] }, priority: { in: ["HIGH", "CRITICAL"] } } }), db.action.count({ where: { ...base, status: "BLOCKED" } }), db.action.count({ where: { ...base, lifecycleStatus: "AWAITING_VERIFICATION" } }),
      db.organisationMembership.findMany({ where: { organisationId: context.organisation.id, status: "ACTIVE" }, select: { user: { select: { id: true, name: true } } }, orderBy: { user: { name: "asc" } } }),
      db.client.findMany({ where: { organisationId: context.organisation.id, archivedAt: null, ...(context.allLocations ? {} : { OR: [{ locationId: null }, { locationId: { in: context.locations.map((item) => item.id) } }] }) }, select: { id: true, firstName: true, lastName: true }, orderBy: [{ lastName: "asc" }, { firstName: "asc" }], take: 300 }),
      db.staffMember.findMany({ where: { organisationId: context.organisation.id, archivedAt: null, ...(context.allLocations ? {} : { OR: [{ locationId: null }, { locationId: { in: context.locations.map((item) => item.id) } }] }) }, select: { id: true, firstName: true, lastName: true }, orderBy: [{ lastName: "asc" }, { firstName: "asc" }], take: 300 }),
    ]);
    const canManage = hasPermission(context.permissions, PERMISSIONS.ACTIONS_MANAGE), pages = Math.max(1, Math.ceil(total / PAGE_SIZE)), input = "rounded-xl border border-slate-300 px-3 py-2 text-sm";
    return <main className="space-y-7"><header className="rounded-3xl bg-gradient-to-br from-emerald-950 to-emerald-800 p-7 text-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-200">Continuous assurance</p><h1 className="mt-1 text-3xl font-bold">Action Tracker</h1><p className="mt-2 max-w-3xl text-emerald-50">One record from finding through response, evidence, verified closure, recurrence monitoring and sustained improvement.</p></div>{canManage && <Link href="/actions/new" className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-emerald-900 shadow">Create action</Link>}</div></header>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Visible actions" value={total} /><Stat label="Overdue" value={overdue} warn={overdue > 0} /><Stat label="High or critical" value={high} warn={high > 0} /><Stat label="Blocked" value={blocked} warn={blocked > 0} /><Stat label="Awaiting verification" value={verification} /></section>
      <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-5"><input name="q" defaultValue={q} placeholder="Search action or reference" className={`${input} xl:col-span-2`} /><Select name="status" value={status} label="All action statuses" items={ACTION_STATUSES.filter((item) => item !== "ARCHIVED")} className={input} /><Select name="lifecycle" value={lifecycle} label="All lifecycle stages" items={[...ASSURANCE_LIFECYCLE_STATUSES]} className={input} /><Select name="priority" value={priority} label="All risk priorities" items={[...ACTION_PRIORITIES]} className={input} /><Select name="category" value={category} label="All categories" items={[...ACTION_CATEGORIES]} className={input} raw /><select name="location" defaultValue={location} className={input}><option value="">All branches</option>{context.locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="client" defaultValue={client} className={input}><option value="">All service users</option>{clients.map((item) => <option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</select><select name="staff" defaultValue={staff} className={input}><option value="">All staff members</option>{staffMembers.map((item) => <option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</select><select name="owner" defaultValue={owner} className={input}><option value="">All owners</option>{memberships.map(({ user }) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><select name="recurrence" defaultValue={recurrence} className={input}><option value="">All recurrence states</option><option value="yes">Repeat findings only</option><option value="no">No recurrence recorded</option></select><label className="text-xs font-bold text-slate-600">Finding date from<input type="date" name="dateFrom" defaultValue={dateFrom} className={`${input} mt-1 w-full`} /></label><label className="text-xs font-bold text-slate-600">Finding date to<input type="date" name="dateTo" defaultValue={dateTo} className={`${input} mt-1 w-full`} /></label><button className="rounded-xl bg-slate-800 px-4 py-2 text-sm font-semibold text-white">Apply filters</button><Link href="/actions" className="rounded-xl border border-slate-300 px-4 py-2 text-center text-sm font-semibold">Clear</Link>{canManage && <div className="flex gap-2 xl:col-span-5"><Link href="/api/actions/export?format=csv" className="rounded-lg border px-3 py-2 text-sm font-semibold">Export CSV</Link><Link href="/actions/report" className="rounded-lg border px-3 py-2 text-sm font-semibold">Print report</Link></div>}</form>
      {!actions.length ? <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-bold">No actions match this view</h2><p className="mt-1 text-sm text-slate-600">Adjust the assurance filters or create an action.</p></section> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-4">Action and scope</th><th className="p-4">Owner</th><th className="p-4">Lifecycle</th><th className="p-4">Progress</th><th className="p-4">Last finding</th><th className="p-4">Evidence</th></tr></thead><tbody>{actions.map((action) => { const effective = effectiveActionStatus(action.status, action.dueDate, now), days = actionDaysRemaining(action.dueDate, now); return <tr key={action.id} className="border-t border-slate-200 align-top hover:bg-slate-50"><td className="p-4"><p className="font-mono text-xs text-slate-500">{action.reference} · {action.category}</p><Link href={`/actions/${action.id}`} className="mt-1 block font-bold text-emerald-800">{action.title}</Link><p className="mt-1 text-xs text-slate-500">{action.location?.name ?? "Organisation-wide"}{action.client ? ` · ${action.client.firstName} ${action.client.lastName}` : ""}{action.staffMember ? ` · ${action.staffMember.firstName} ${action.staffMember.lastName}` : ""}</p></td><td className="p-4">{action.owner.name}<span className={`mt-2 block w-fit rounded-full px-2 py-1 text-xs font-bold ${priorityClasses(action.priority)}`}>{actionLabel(action.priority)}</span></td><td className="p-4"><strong>{actionLabel(action.lifecycleStatus)}</strong><p className="text-xs text-slate-500">{action._count.occurrences} occurrences · {action.recurrenceCount} recurrences</p></td><td className="min-w-40 p-4"><div className="flex justify-between text-xs font-semibold"><span className={effective === "OVERDUE" ? "text-red-700" : ""}>{actionLabel(effective)}</span><span>{action.progressPercent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${action.progressPercent}%` }} /></div><p className={days < 0 ? "mt-1 text-xs font-bold text-red-700" : "mt-1 text-xs text-slate-500"}>{days < 0 ? `${Math.abs(days)} days overdue` : `Due ${date(action.dueDate)}`}</p></td><td className="p-4">{date(action.lastSeenAt)}</td><td className="p-4"><strong>{action._count.evidenceLinks}</strong><p className="text-xs text-slate-500">linked items</p></td></tr>; })}</tbody></table></div>}
      <nav className="flex items-center justify-between text-sm"><span>Page {page} of {pages}</span><div className="flex gap-2">{page > 1 && <Link href={withPage(query, page - 1)} className="rounded-lg border bg-white px-3 py-2">Previous</Link>}{page < pages && <Link href={withPage(query, page + 1)} className="rounded-lg border bg-white px-3 py-2">Next</Link>}</div></nav>
    </main>;
  } finally { await db.$disconnect(); }
}
function Select({ name, value, label, items, className, raw = false }: { name: string; value: string; label: string; items: string[]; className: string; raw?: boolean }) { return <select name={name} defaultValue={value} className={className}><option value="">{label}</option>{items.map((item) => <option key={item} value={item}>{raw ? item : actionLabel(item)}</option>)}</select>; }
function Stat({ label, value, warn = false }: { label: string; value: number; warn?: boolean }) { return <div className={`rounded-2xl border p-5 ${warn ? "border-red-200 bg-red-50" : "border-slate-200 bg-white"}`}><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>; }
function field(query: Record<string, string | string[] | undefined>, key: string) { const value = query[key]; return String(Array.isArray(value) ? value[0] ?? "" : value ?? "").trim(); }
function date(value: Date) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(value); }
function start(value: string) { return new Date(`${value}T00:00:00.000Z`); }
function end(value: string) { return new Date(`${value}T23:59:59.999Z`); }
function withPage(query: Record<string, string | string[] | undefined>, page: number) { const params = new URLSearchParams(); for (const [key, value] of Object.entries(query)) if (value) params.set(key, Array.isArray(value) ? value[0] : value); params.set("page", String(page)); return `/actions?${params}`; }
