import Link from "next/link";
import { RiskFrameworkForm, RiskFrameworkStatusAction } from "@/components/risk-framework-form";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { PERMISSIONS } from "@/lib/permissions";

export default async function RiskFrameworkPage(){
  const context=await requirePermission(PERMISSIONS.ORGANISATION_MANAGE),db=createDb();
  try{
    const[frameworks,roles]=await Promise.all([
      db.riskFrameworkVersion.findMany({where:{organisationId:context.organisation.id},include:{rules:true,closurePolicyVersion:{include:{rules:true}},createdBy:{select:{name:true}},approvedBy:{select:{name:true}}},orderBy:{versionNumber:"desc"}}),
      db.role.findMany({orderBy:{name:"asc"},select:{key:true,name:true}}),
    ]);
    const open=frameworks.some(framework=>["DRAFT","IN_REVIEW","APPROVED"].includes(framework.status));
    return <main className="mx-auto max-w-6xl space-y-6">
      <header><Link href="/settings" className="text-sm font-bold text-emerald-700">← Settings</Link><p className="mt-4 text-xs font-bold uppercase tracking-widest text-emerald-700">Organisation governance</p><h1 className="text-3xl font-bold">Risk Framework</h1><p className="mt-2 max-w-4xl text-slate-600">Version appetite, tolerance and closure authority without rewriting historical Risk decisions. Approved versions are immutable; new policy means a new version.</p></header>
      {!open?<details className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><summary className="cursor-pointer text-lg font-bold">Draft new version</summary><div className="mt-5"><RiskFrameworkForm roles={roles}/></div></details>:null}
      <section className="space-y-4">{frameworks.length?frameworks.map(framework=><article key={framework.id} className="rounded-2xl border bg-white p-5">
        <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-emerald-700">Risk Framework v{framework.versionNumber}</p><h2 className="text-xl font-bold">{label(framework.status)}</h2><p className="text-sm text-slate-500">Effective {date(framework.effectiveFrom)} · Closure Policy v{framework.closurePolicyVersion.versionNumber} · created by {framework.createdBy.name}{framework.approvedBy?` · approved by ${framework.approvedBy.name}`:""}</p></div><div className="flex flex-wrap gap-2">{framework.status==="DRAFT"?<><RiskFrameworkStatusAction id={framework.id} intent="submit" label="Submit for review"/><RiskFrameworkStatusAction id={framework.id} intent="withdraw" label="Withdraw draft"/></>:null}{framework.status==="IN_REVIEW"?<RiskFrameworkStatusAction id={framework.id} intent="approve" label="Approve version"/>:null}{framework.status==="APPROVED"?<RiskFrameworkStatusAction id={framework.id} intent="activate" label="Make effective"/>:null}{["EFFECTIVE","SUPERSEDED"].includes(framework.status)?<RiskFrameworkStatusAction id={framework.id} intent="retire" label="Retire"/>:null}</div></div>
        <p className="mt-3 text-sm">{framework.changeRationale}</p><div className="mt-4 grid gap-3 md:grid-cols-3"><Stat label="Default appetite" value={label(framework.defaultAppetite)}/><Stat label="Default tolerance" value={String(framework.defaultToleranceScore)}/><Stat label="Category overrides" value={String(framework.rules.length)}/></div>
        {framework.status==="DRAFT"?<details className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-4"><summary className="cursor-pointer font-bold">Edit working draft</summary><div className="mt-5"><RiskFrameworkForm roles={roles} initial={{id:framework.id,effectiveFrom:inputDate(framework.effectiveFrom),defaultAppetite:framework.defaultAppetite,defaultToleranceScore:framework.defaultToleranceScore,defaultEscalation:framework.defaultEscalation??"",changeRationale:framework.changeRationale,categoryRules:framework.rules.map(rule=>({categoryKey:rule.categoryKey,appetite:rule.appetite,toleranceScore:rule.toleranceScore,escalationIndicator:rule.escalationIndicator??""})),closureRules:framework.closurePolicyVersion.rules.map(rule=>({riskLevel:rule.riskLevel,proposerRoleKeys:rule.proposerRoleKeys,approverRoleKeys:rule.approverRoleKeys,selfApprovalAllowed:rule.selfApprovalAllowed,requiredApprovalCount:rule.requiredApprovalCount,verifiedEvidenceRequired:rule.verifiedEvidenceRequired,effectivenessEvidenceRequired:rule.effectivenessEvidenceRequired,escalationRequirement:rule.escalationRequirement??""}))}}/></div></details>:null}
        <details className="mt-4"><summary className="cursor-pointer text-sm font-bold">View category and closure rules</summary><div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="bg-slate-50 text-left"><th className="p-2">Category</th><th className="p-2">Appetite</th><th className="p-2">Tolerance</th></tr></thead><tbody>{framework.rules.map(rule=><tr className="border-t" key={rule.id}><td className="p-2">{rule.categoryLabel}</td><td className="p-2">{label(rule.appetite)}</td><td className="p-2">{rule.toleranceScore}</td></tr>)}</tbody></table></div><div className="mt-4 grid gap-2 md:grid-cols-2">{framework.closurePolicyVersion.rules.map(rule=><div key={rule.id} className="rounded-lg bg-slate-50 p-3 text-xs"><strong>{label(rule.riskLevel)}</strong> · {rule.requiredApprovalCount} approval(s) · self {rule.selfApprovalAllowed?"permitted":"not permitted"} · verified evidence {rule.verifiedEvidenceRequired?"required":"proportionate"} · effectiveness {rule.effectivenessEvidenceRequired?"required":"proportionate"}</div>)}</div></details>
      </article>):<p className="rounded-2xl border bg-white p-6 text-slate-600">No Organisation Risk Framework exists. Existing Risks retain their recorded appetite and tolerance as legacy snapshots.</p>}</section>
    </main>;
  }finally{await db.$disconnect()}
}

function Stat({label:heading,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">{heading}</p><p className="mt-1 font-bold">{value}</p></div>}
function date(value:Date|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value):"Not set"}
function inputDate(value:Date|null){return value?.toISOString().slice(0,10)??""}
function label(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/^./,character=>character.toUpperCase())}
