import Link from "next/link";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";
import { isOutsideTolerance, levelClasses, RISK_CATEGORIES, RISK_LEVELS, RISK_STATUSES, riskScopeWhere, riskStatusLabel } from "@/lib/risks";

const PAGE_SIZE = 20;
export default async function RisksPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const context = await requirePermission(PERMISSIONS.GOVERNANCE_VIEW); const query = await searchParams;
  const q = String(query.q ?? "").trim(); const status = String(query.status ?? ""); const level = String(query.level ?? ""); const category = String(query.category ?? "");
  const page = Math.max(1, Number(query.page) || 1); const now = new Date(); const db = createDb();
  try {
    const where = { AND: [riskScopeWhere(context), ...(q ? [{ OR: [{ reference: { contains: q, mode: "insensitive" as const } }, { title: { contains: q, mode: "insensitive" as const } }, { description: { contains: q, mode: "insensitive" as const } }] }] : [])], ...(status ? { status: status as never } : {}), ...(level ? { residualLevel: level as never } : {}), ...(category ? { category } : {}) };
    const [risks,total,portfolioRisks,overdue] = await Promise.all([
      db.risk.findMany({ where, include: { location: { select: { name: true } }, owner: { select: { name: true } }, _count: { select: { evidenceLinks: true, reviews: true } } }, orderBy: [{ residualScore: "desc" }, { nextReviewDate: "asc" }], skip: (page-1)*PAGE_SIZE, take: PAGE_SIZE }),
      db.risk.count({ where }),
      db.risk.findMany({ where: { ...riskScopeWhere(context), status: { notIn: ["CLOSED","ARCHIVED"] } }, select: { residualLikelihood: true, residualImpact: true,residualScore:true,residualLevel:true,toleranceScore:true,ownerId:true,targetDate:true } }),
      db.risk.count({ where: { ...riskScopeWhere(context), status: { notIn: ["CLOSED","ARCHIVED"] }, nextReviewDate: { lt: now } } }),
    ]);
    const canEdit = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_EDIT); const pages = Math.max(1, Math.ceil(total/PAGE_SIZE));const high=portfolioRisks.filter(r=>["HIGH","CRITICAL"].includes(r.residualLevel)).length,outside=portfolioRisks.filter(r=>r.toleranceScore&&r.residualScore>r.toleranceScore).length,unassigned=portfolioRisks.filter(r=>!r.ownerId).length,treatmentOverdue=portfolioRisks.filter(r=>r.targetDate&&r.targetDate<now).length;
    return <main className="space-y-7">
      <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Risk Register</h1><p className="mt-1 max-w-3xl text-slate-600">See which risks need attention, check whether controls are working and follow agreed actions to the next review.</p></div>{canEdit && <Link href="/risks/new" className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white">Record a new risk</Link>}</header>
      <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-sm leading-6 text-blue-950"><h2 className="font-bold">How this register works</h2><p className="mt-1">Inherent score shows exposure before controls. Current residual shows what remains after existing controls. Target shows the intended position after treatment. A risk above its recorded tolerance needs treatment, escalation or formally authorised acceptance.</p><div className="mt-3 flex flex-wrap gap-4"><a href="https://www.cqc.org.uk/guidance-regulation/providers/regulations-service-providers-and-managers/health-social-care-act/regulation-12" target="_blank" rel="noreferrer" className="font-bold text-blue-800">CQC Regulation 12 ↗</a><a href="https://www.cqc.org.uk/guidance-providers/regulations/regulation-17-good-governance" target="_blank" rel="noreferrer" className="font-bold text-blue-800">CQC Regulation 17 ↗</a><a href="https://www.hse.gov.uk/simple-health-safety/risk/steps-needed-to-manage-risk.htm" target="_blank" rel="noreferrer" className="font-bold text-blue-800">HSE risk assessment steps ↗</a></div></section>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Open portfolio" value={portfolioRisks.length}/><Stat label="Outside tolerance" value={outside} warn={outside>0}/><Stat label="High or critical" value={high} warn={high>0}/><Stat label="Overdue reviews" value={overdue} warn={overdue>0}/><Stat label="Owner or treatment gap" value={unassigned+treatmentOverdue} warn={unassigned+treatmentOverdue>0}/></section>
      <section className="grid gap-5 xl:grid-cols-[1fr_1.4fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Current residual heat map</h2><p className="mt-1 text-sm text-slate-500">Numbers show active risks at each likelihood (L) and impact (I) position.</p><HeatMap risks={portfolioRisks}/><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded bg-emerald-100 px-2 py-1">1–4 Low</span><span className="rounded bg-amber-100 px-2 py-1">5–9 Moderate</span><span className="rounded bg-orange-100 px-2 py-1">10–16 High</span><span className="rounded bg-red-700 px-2 py-1 text-white">17–25 Critical</span></div></div>
      <form className="grid content-start gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-2"><input name="q" defaultValue={q} placeholder="Search reference, title or description" className="rounded-lg border border-slate-300 px-3 py-2 text-sm sm:col-span-2"/><select name="status" defaultValue={status} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All statuses</option>{RISK_STATUSES.map((item)=><option key={item} value={item}>{riskStatusLabel(item)}</option>)}</select><select name="level" defaultValue={level} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All levels</option>{RISK_LEVELS.map((item)=><option key={item}>{item}</option>)}</select><select name="category" defaultValue={category} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All categories</option>{RISK_CATEGORIES.map((item)=><option key={item}>{item}</option>)}</select><button className="rounded-lg bg-slate-800 px-4 py-2 text-sm font-semibold text-white">Filter</button><div className="flex flex-wrap gap-2 text-sm sm:col-span-2"><Link href="/api/risks/export?format=csv" className="rounded-lg border px-3 py-2 font-semibold">CSV</Link><Link href="/api/risks/export?format=xls" className="rounded-lg border px-3 py-2 font-semibold">Excel</Link><Link href="/risks/report" className="rounded-lg border px-3 py-2 font-semibold">Print / PDF</Link></div></form></section>
      {!risks.length ? <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-bold">No risks found</h2><p className="mt-1 text-sm text-slate-600">Record the first risk or adjust the filters.</p></section> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-4">Risk and source</th><th className="p-4">Inherent</th><th className="p-4">Current</th><th className="p-4">Target</th><th className="p-4">Management position</th><th className="p-4">Owner / review</th><th className="p-4"></th></tr></thead><tbody>{risks.map((risk)=>{const outside=isOutsideTolerance(risk.residualScore,risk.toleranceScore);return <tr key={risk.id} className="border-t border-slate-200 align-top"><td className="p-4"><p className="font-mono text-xs text-slate-500">{risk.reference}</p><Link href={`/risks/${risk.id}`} className="font-bold text-emerald-800">{risk.title}</Link><p className="text-xs text-slate-500">{risk.category} · {risk.sourceType??"Manual"} · {risk.location?.name??"Organisation-wide"}</p></td><td className="p-4">{risk.initialScore} <Level value={risk.initialLevel}/></td><td className="p-4">{risk.residualScore} <Level value={risk.residualLevel}/></td><td className="p-4">{risk.targetScore??risk.residualScore} <Level value={risk.targetLevel??risk.residualLevel}/></td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${outside?"bg-red-100 text-red-800":"bg-emerald-100 text-emerald-800"}`}>{outside?"Outside tolerance":"Within tolerance"}</span><p className="mt-2 text-xs text-slate-500">{riskStatusLabel(risk.status)} · controls {label(risk.controlEffectiveness??"NOT_TESTED")}</p></td><td className={`p-4 ${risk.nextReviewDate<now&&!["CLOSED","ARCHIVED"].includes(risk.status)?"font-bold text-red-700":""}`}><p>{risk.owner?.name??"Owner needed"}</p><p className="text-xs">{date(risk.nextReviewDate)}{risk.nextReviewDate<now&&!["CLOSED","ARCHIVED"].includes(risk.status)?" · Overdue":""}</p></td><td className="p-4"><Link href={`/risks/${risk.id}`} className="rounded-lg border border-emerald-700 px-3 py-2 text-xs font-bold text-emerald-800">Open risk</Link></td></tr>})}</tbody></table></div>}
      <nav className="flex items-center justify-between text-sm"><span>Page {page} of {pages}</span><div className="flex gap-2">{page>1&&<Link href={withPage(query,page-1)} className="rounded-lg border bg-white px-3 py-2">Previous</Link>}{page<pages&&<Link href={withPage(query,page+1)} className="rounded-lg border bg-white px-3 py-2">Next</Link>}</div></nav>
    </main>;
  } finally { await db.$disconnect(); }
}
function Stat({label,value,warn=false}:{label:string;value:number;warn?:boolean}){return <div className={`rounded-2xl border p-5 ${warn?"border-red-200 bg-red-50":"border-slate-200 bg-white"}`}><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>}
function Level({value}:{value:string}){return <span className={`ml-1 rounded-full px-2 py-1 text-[10px] font-bold ${levelClasses(value)}`}>{value}</span>}
function HeatMap({risks}:{risks:{residualLikelihood:number;residualImpact:number}[]}){const count=(l:number,i:number)=>risks.filter((risk)=>risk.residualLikelihood===l&&risk.residualImpact===i).length;return <div className="mt-5 grid grid-cols-[auto_repeat(5,1fr)] gap-1 text-center text-xs"><div/>{[1,2,3,4,5].map((impact)=><div key={impact} className="font-bold">I{impact}</div>)}{[5,4,3,2,1].map((likelihood)=><div key={likelihood} className="contents"><div className="grid place-items-center font-bold">L{likelihood}</div>{[1,2,3,4,5].map((impact)=>{const score=likelihood*impact;return <div key={`${likelihood}-${impact}`} title={`Likelihood ${likelihood}, impact ${impact}`} className={`grid aspect-square place-items-center rounded-md font-black ${levelClasses(score<=4?"LOW":score<=9?"MODERATE":score<=16?"HIGH":"CRITICAL")}`}>{count(likelihood,impact)}</div>})}</div>)}</div>}
function date(value:Date){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value)}
function withPage(query:Record<string,string|string[]|undefined>,page:number){const params=new URLSearchParams();for(const[key,value]of Object.entries(query))if(value)params.set(key,Array.isArray(value)?value[0]:value);params.set("page",String(page));return`/risks?${params}`}
function label(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/^\w/,c=>c.toUpperCase())}
