import Link from "next/link";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";
import { levelClasses, RISK_CATEGORIES, RISK_LEVELS, RISK_STATUSES, riskScopeWhere, riskStatusLabel } from "@/lib/risks";

const PAGE_SIZE = 20;
export default async function RisksPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const context = await requirePermission(PERMISSIONS.GOVERNANCE_VIEW); const query = await searchParams;
  const q = String(query.q ?? "").trim(); const status = String(query.status ?? ""); const level = String(query.level ?? ""); const category = String(query.category ?? "");
  const page = Math.max(1, Number(query.page) || 1); const now = new Date(); const db = createDb();
  try {
    const where = { AND: [riskScopeWhere(context), ...(q ? [{ OR: [{ reference: { contains: q, mode: "insensitive" as const } }, { title: { contains: q, mode: "insensitive" as const } }, { description: { contains: q, mode: "insensitive" as const } }] }] : [])], ...(status ? { status: status as never } : {}), ...(level ? { residualLevel: level as never } : {}), ...(category ? { category } : {}) };
    const [risks,total,heatRisks,overdue,high] = await Promise.all([
      db.risk.findMany({ where, include: { location: { select: { name: true } }, owner: { select: { name: true } }, _count: { select: { evidenceLinks: true, reviews: true } } }, orderBy: [{ residualScore: "desc" }, { nextReviewDate: "asc" }], skip: (page-1)*PAGE_SIZE, take: PAGE_SIZE }),
      db.risk.count({ where }),
      db.risk.findMany({ where: { ...riskScopeWhere(context), status: { notIn: ["CLOSED","ARCHIVED"] } }, select: { residualLikelihood: true, residualImpact: true } }),
      db.risk.count({ where: { ...riskScopeWhere(context), status: { notIn: ["CLOSED","ARCHIVED"] }, nextReviewDate: { lt: now } } }),
      db.risk.count({ where: { ...riskScopeWhere(context), status: { notIn: ["CLOSED","ARCHIVED"] }, residualLevel: { in: ["HIGH","CRITICAL"] } } }),
    ]);
    const canEdit = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_EDIT); const pages = Math.max(1, Math.ceil(total/PAGE_SIZE));
    return <main className="space-y-7">
      <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Organisational assurance</p><h1 className="text-3xl font-bold">Risk Register</h1><p className="mt-1 text-slate-600">Identify, assess, control and review risks across your service.</p></div>{canEdit && <Link href="/risks/new" className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white">Add risk</Link>}</header>
      <section className="grid gap-4 sm:grid-cols-3"><Stat label="Visible risks" value={total}/><Stat label="High or critical" value={high} warn/><Stat label="Overdue reviews" value={overdue} warn={overdue>0}/></section>
      <section className="grid gap-5 xl:grid-cols-[1fr_1.4fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Residual risk heat map</h2><p className="mt-1 text-sm text-slate-500">Open risks by likelihood and impact.</p><HeatMap risks={heatRisks}/></div>
      <form className="grid content-start gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-2"><input name="q" defaultValue={q} placeholder="Search reference, title or description" className="rounded-lg border border-slate-300 px-3 py-2 text-sm sm:col-span-2"/><select name="status" defaultValue={status} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All statuses</option>{RISK_STATUSES.map((item)=><option key={item} value={item}>{riskStatusLabel(item)}</option>)}</select><select name="level" defaultValue={level} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All levels</option>{RISK_LEVELS.map((item)=><option key={item}>{item}</option>)}</select><select name="category" defaultValue={category} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All categories</option>{RISK_CATEGORIES.map((item)=><option key={item}>{item}</option>)}</select><button className="rounded-lg bg-slate-800 px-4 py-2 text-sm font-semibold text-white">Filter</button><div className="flex flex-wrap gap-2 text-sm sm:col-span-2"><Link href="/api/risks/export?format=csv" className="rounded-lg border px-3 py-2 font-semibold">CSV</Link><Link href="/api/risks/export?format=xls" className="rounded-lg border px-3 py-2 font-semibold">Excel</Link><Link href="/risks/report" className="rounded-lg border px-3 py-2 font-semibold">Print / PDF</Link></div></form></section>
      {!risks.length ? <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-bold">No risks found</h2><p className="mt-1 text-sm text-slate-600">Add the first risk or adjust the filters.</p></section> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-4">Reference</th><th className="p-4">Risk</th><th className="p-4">Initial</th><th className="p-4">Residual</th><th className="p-4">Status</th><th className="p-4">Owner</th><th className="p-4">Next review</th></tr></thead><tbody>{risks.map((risk)=><tr key={risk.id} className="border-t border-slate-200"><td className="p-4 font-mono text-xs">{risk.reference}</td><td className="p-4"><Link href={`/risks/${risk.id}`} className="font-semibold text-emerald-800">{risk.title}</Link><p className="text-xs text-slate-500">{risk.category} · {risk.location?.name??"Organisation-wide"}</p></td><td className="p-4">{risk.initialScore} <Level value={risk.initialLevel}/></td><td className="p-4">{risk.residualScore} <Level value={risk.residualLevel}/></td><td className="p-4">{riskStatusLabel(risk.status)}</td><td className="p-4">{risk.owner?.name??"Unassigned"}</td><td className={`p-4 ${risk.nextReviewDate<now&& !["CLOSED","ARCHIVED"].includes(risk.status)?"font-bold text-red-700":""}`}>{date(risk.nextReviewDate)}{risk.nextReviewDate<now&& !["CLOSED","ARCHIVED"].includes(risk.status)?" · Overdue":""}</td></tr>)}</tbody></table></div>}
      <nav className="flex items-center justify-between text-sm"><span>Page {page} of {pages}</span><div className="flex gap-2">{page>1&&<Link href={withPage(query,page-1)} className="rounded-lg border bg-white px-3 py-2">Previous</Link>}{page<pages&&<Link href={withPage(query,page+1)} className="rounded-lg border bg-white px-3 py-2">Next</Link>}</div></nav>
    </main>;
  } finally { await db.$disconnect(); }
}
function Stat({label,value,warn=false}:{label:string;value:number;warn?:boolean}){return <div className={`rounded-2xl border p-5 ${warn?"border-red-200 bg-red-50":"border-slate-200 bg-white"}`}><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>}
function Level({value}:{value:string}){return <span className={`ml-1 rounded-full px-2 py-1 text-[10px] font-bold ${levelClasses(value)}`}>{value}</span>}
function HeatMap({risks}:{risks:{residualLikelihood:number;residualImpact:number}[]}){const count=(l:number,i:number)=>risks.filter((risk)=>risk.residualLikelihood===l&&risk.residualImpact===i).length;return <div className="mt-5 grid grid-cols-[auto_repeat(5,1fr)] gap-1 text-center text-xs"><div/>{[1,2,3,4,5].map((impact)=><div key={impact} className="font-bold">I{impact}</div>)}{[5,4,3,2,1].map((likelihood)=><div key={likelihood} className="contents"><div className="grid place-items-center font-bold">L{likelihood}</div>{[1,2,3,4,5].map((impact)=>{const score=likelihood*impact;return <div key={`${likelihood}-${impact}`} title={`Likelihood ${likelihood}, impact ${impact}`} className={`grid aspect-square place-items-center rounded-md font-black ${levelClasses(score<=4?"LOW":score<=9?"MODERATE":score<=16?"HIGH":"CRITICAL")}`}>{count(likelihood,impact)}</div>})}</div>)}</div>}
function date(value:Date){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value)}
function withPage(query:Record<string,string|string[]|undefined>,page:number){const params=new URLSearchParams();for(const[key,value]of Object.entries(query))if(value)params.set(key,Array.isArray(value)?value[0]:value);params.set("page",String(page));return`/risks?${params}`}
