UPDATE "RegisterDefinition"
SET "fieldSchema" = CASE "key"
  WHEN 'compliments' THEN '[{"key":"personReference","label":"Person, representative or source reference","type":"text"},{"key":"category","label":"Team, worker or service praised","type":"text"},{"key":"immediateResponse","label":"How recognition was shared","type":"textarea"},{"key":"outcome","label":"Positive impact described","type":"textarea"},{"key":"learning","label":"Good practice to retain or share","type":"textarea"}]'::jsonb
  WHEN 'accidents' THEN '[{"key":"personReference","label":"Person or staff reference","type":"text"},{"key":"category","label":"Accident type and location","type":"text","required":true},{"key":"immediateResponse","label":"Injury, treatment and immediate action","type":"textarea","required":true},{"key":"medicalAttention","label":"Medical attention required","type":"boolean"},{"key":"riddorConsidered","label":"RIDDOR reporting considered","type":"boolean"},{"key":"outcome","label":"Investigation outcome","type":"textarea"},{"key":"learning","label":"Preventive action and learning","type":"textarea"}]'::jsonb
  WHEN 'near-misses' THEN '[{"key":"personReference","label":"Person, staff or service reference","type":"text"},{"key":"category","label":"Hazard or near-miss type","type":"text","required":true},{"key":"immediateResponse","label":"How harm was prevented and the area made safe","type":"textarea","required":true},{"key":"potentialHarm","label":"Potential harm if the event had occurred","type":"textarea"},{"key":"outcome","label":"Review of contributory factors","type":"textarea"},{"key":"learning","label":"Preventive action and learning","type":"textarea"}]'::jsonb
  WHEN 'safeguarding' THEN '[{"key":"personReference","label":"Person affected reference","type":"text","required":true},{"key":"category","label":"Type of abuse or neglect suspected","type":"text","required":true},{"key":"immediateResponse","label":"Immediate protection and support","type":"textarea","required":true},{"key":"localAuthorityReferralDate","label":"Local authority referral date","type":"date"},{"key":"policeInvolved","label":"Police involved","type":"boolean"},{"key":"section42Enquiry","label":"Section 42 enquiry opened","type":"boolean"},{"key":"outcome","label":"Safeguarding outcome","type":"textarea"},{"key":"learning","label":"Learning and preventive action","type":"textarea"}]'::jsonb
  WHEN 'whistleblowing' THEN '[{"key":"personReference","label":"Confidential reporter reference","type":"text"},{"key":"category","label":"Concern category","type":"text","required":true},{"key":"immediateResponse","label":"Reporter protection and immediate safeguards","type":"textarea","required":true},{"key":"independentInvestigator","label":"Investigator or independent reviewer","type":"text"},{"key":"outcome","label":"Investigation outcome and feedback provided","type":"textarea"},{"key":"learning","label":"Organisational learning and action","type":"textarea"}]'::jsonb
  WHEN 'cqc-notifications' THEN '[{"key":"personReference","label":"Person or event reference","type":"text"},{"key":"category","label":"CQC notification type","type":"text","required":true},{"key":"immediateResponse","label":"Notification decision and rationale","type":"textarea","required":true},{"key":"notificationRequired","label":"Notification required","type":"boolean"},{"key":"submissionDate","label":"Date submitted to CQC","type":"date"},{"key":"notificationReference","label":"CQC notification reference","type":"text"},{"key":"outcome","label":"CQC response or follow-up","type":"textarea"},{"key":"learning","label":"Timeliness learning and action","type":"textarea"}]'::jsonb
  WHEN 'medicines-errors' THEN '[{"key":"personReference","label":"Person affected reference","type":"text","required":true},{"key":"category","label":"Medicine and error type","type":"text","required":true},{"key":"immediateResponse","label":"Clinical advice, monitoring and immediate safeguard","type":"textarea","required":true},{"key":"harmIdentified","label":"Known or suspected harm","type":"boolean"},{"key":"prescriberOrPharmacyContacted","label":"Prescriber or pharmacy contacted","type":"boolean"},{"key":"marCorrected","label":"MAR and care records updated","type":"boolean"},{"key":"outcome","label":"Investigation and competency outcome","type":"textarea"},{"key":"learning","label":"Learning and prevention","type":"textarea"}]'::jsonb
  WHEN 'falls' THEN '[{"key":"personReference","label":"Person affected reference","type":"text","required":true},{"key":"category","label":"Fall type, location and whether witnessed","type":"text","required":true},{"key":"immediateResponse","label":"Injury, observations, assistance and medical advice","type":"textarea","required":true},{"key":"injuryIdentified","label":"Injury identified","type":"boolean"},{"key":"postFallObservations","label":"Post-fall observations completed","type":"boolean"},{"key":"riskAssessmentUpdated","label":"Falls risk assessment updated","type":"boolean"},{"key":"outcome","label":"Clinical review and outcome","type":"textarea"},{"key":"learning","label":"Prevention plan and learning","type":"textarea"}]'::jsonb
  WHEN 'pressure-damage' THEN '[{"key":"personReference","label":"Person affected reference","type":"text","required":true},{"key":"category","label":"Site and pressure-damage category","type":"text","required":true},{"key":"immediateResponse","label":"Skin care, relief, equipment and clinical escalation","type":"textarea","required":true},{"key":"clinicalReviewDate","label":"Clinical review date","type":"date"},{"key":"safeguardingConsidered","label":"Safeguarding considered","type":"boolean"},{"key":"carePlanUpdated","label":"Care plan and body map updated","type":"boolean"},{"key":"outcome","label":"Healing progress and outcome","type":"textarea"},{"key":"learning","label":"Prevention and learning","type":"textarea"}]'::jsonb
  WHEN 'hospital-admissions' THEN '[{"key":"personReference","label":"Person admitted reference","type":"text","required":true},{"key":"category","label":"Reason and admission route","type":"text","required":true},{"key":"immediateResponse","label":"Symptoms, advice, transport and handover","type":"textarea","required":true},{"key":"hospital","label":"Hospital or receiving service","type":"text"},{"key":"familyNotified","label":"Family or representative notified","type":"boolean"},{"key":"dischargeDate","label":"Discharge date","type":"date"},{"key":"outcome","label":"Discharge changes and follow-up","type":"textarea"},{"key":"learning","label":"Learning for future care","type":"textarea"}]'::jsonb
  WHEN 'missed-visits' THEN '[{"key":"personReference","label":"Person affected reference","type":"text","required":true},{"key":"category","label":"Scheduled visit type and time","type":"text","required":true},{"key":"immediateResponse","label":"Welfare check, replacement care and communication","type":"textarea","required":true},{"key":"minutesMissed","label":"Minutes between scheduled call and response","type":"number"},{"key":"medicinesAffected","label":"Medicines support affected","type":"boolean"},{"key":"commissionerNotified","label":"Commissioner notified","type":"boolean"},{"key":"outcome","label":"Impact and investigation outcome","type":"textarea"},{"key":"learning","label":"Prevention and learning","type":"textarea"}]'::jsonb
  WHEN 'late-visits' THEN '[{"key":"personReference","label":"Person affected reference","type":"text","required":true},{"key":"category","label":"Scheduled visit type","type":"text","required":true},{"key":"scheduledTime","label":"Scheduled time","type":"text"},{"key":"actualArrivalTime","label":"Actual arrival time","type":"text"},{"key":"immediateResponse","label":"Communication and response to the delay","type":"textarea"},{"key":"impactOnPerson","label":"Impact on the person","type":"textarea"},{"key":"outcome","label":"Cause and management review","type":"textarea"},{"key":"learning","label":"Prevention and learning","type":"textarea"}]'::jsonb
  WHEN 'staff-concerns' THEN '[{"key":"personReference","label":"Staff member reference","type":"text","required":true},{"key":"category","label":"Conduct, capability or practice concern","type":"text","required":true},{"key":"immediateResponse","label":"Immediate management action and safeguards","type":"textarea","required":true},{"key":"hrAdviceTaken","label":"HR advice taken","type":"boolean"},{"key":"suspendedOrRestricted","label":"Duties suspended or restricted","type":"boolean"},{"key":"outcome","label":"Investigation or management outcome","type":"textarea"},{"key":"learning","label":"Support, development and learning","type":"textarea"}]'::jsonb
  WHEN 'service-user-feedback' THEN '[{"key":"personReference","label":"Person or representative reference","type":"text"},{"key":"category","label":"Feedback theme","type":"text","required":true},{"key":"immediateResponse","label":"Response given to the person","type":"textarea"},{"key":"consentToShare","label":"Consent to share feedback","type":"boolean"},{"key":"outcome","label":"Improvement or decision made","type":"textarea"},{"key":"learning","label":"You said, we did message","type":"textarea"}]'::jsonb
  WHEN 'staff-feedback' THEN '[{"key":"personReference","label":"Staff or anonymous source reference","type":"text"},{"key":"category","label":"Feedback theme or affected service","type":"text","required":true},{"key":"immediateResponse","label":"Management response","type":"textarea"},{"key":"raisedConfidentially","label":"Raised confidentially","type":"boolean"},{"key":"outcome","label":"Decision or improvement made","type":"textarea"},{"key":"learning","label":"Feedback communicated back to staff","type":"textarea"}]'::jsonb
  WHEN 'training-exceptions' THEN '[{"key":"personReference","label":"Staff member reference","type":"text","required":true},{"key":"category","label":"Training course or requirement","type":"text","required":true},{"key":"dueDate","label":"Training due or expiry date","type":"date"},{"key":"immediateResponse","label":"Reason, affected duties and interim control","type":"textarea","required":true},{"key":"authorisedBy","label":"Exception authorised by","type":"text"},{"key":"recoveryDate","label":"Planned completion date","type":"date"},{"key":"outcome","label":"Completion or review outcome","type":"textarea"},{"key":"learning","label":"Escalation and learning","type":"textarea"}]'::jsonb
  WHEN 'supervision-exceptions' THEN '[{"key":"personReference","label":"Staff member reference","type":"text","required":true},{"key":"category","label":"Supervision type and required frequency","type":"text","required":true},{"key":"dueDate","label":"Supervision due date","type":"date"},{"key":"immediateResponse","label":"Reason, wellbeing impact and interim support","type":"textarea","required":true},{"key":"rescheduledDate","label":"Rescheduled supervision date","type":"date"},{"key":"managerContactCompleted","label":"Interim manager contact completed","type":"boolean"},{"key":"outcome","label":"Completion or escalation outcome","type":"textarea"},{"key":"learning","label":"Workforce learning","type":"textarea"}]'::jsonb
  WHEN 'data-breaches' THEN '[{"key":"personReference","label":"Affected person, staff or system reference","type":"text"},{"key":"category","label":"Data categories and breach type","type":"text","required":true},{"key":"immediateResponse","label":"Containment, recovery and access removal","type":"textarea","required":true},{"key":"peopleAffected","label":"Number of people affected","type":"number"},{"key":"icoReportable","label":"ICO notification required","type":"boolean"},{"key":"icoNotificationDate","label":"ICO notification date","type":"date"},{"key":"individualsNotified","label":"Affected individuals notified","type":"boolean"},{"key":"outcome","label":"Risk assessment and investigation outcome","type":"textarea"},{"key":"learning","label":"Security improvement and learning","type":"textarea"}]'::jsonb
  ELSE "fieldSchema"
END,
"updatedAt" = CURRENT_TIMESTAMP
WHERE "organisationId" IS NULL
AND "key" IN (
  'compliments','accidents','near-misses','safeguarding','whistleblowing',
  'cqc-notifications','medicines-errors','falls','pressure-damage',
  'hospital-admissions','missed-visits','late-visits','staff-concerns',
  'service-user-feedback','staff-feedback','training-exceptions',
  'supervision-exceptions','data-breaches'
);
