import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth/dal";
import { loadCarePlan } from "@/lib/care-plan-data";
import { CARE_PLAN_SECTIONS } from "@/lib/care-plans";
import { createDb } from "@/lib/db";
import { PERMISSIONS } from "@/lib/permissions";

export default async function CompareCarePlanPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){const context=await requirePermission(PERMISSIONS.GOVERNANCE_VIEW),{id}=await params,query=await searchParams,db=createDb();try{const x=await loadCarePlan(db,context,id);if(!x)notFound();const versionId=String(query.versionId??x.proposed?.id??""),version=x.plan.versions.find((v)=>v.id===versionId);if(!version)notFound();const labels=new Map<string,string>(CARE_PLAN_SECTIONS.map(([k,v])=>[k,v]));return <main className="space-y-5"><header><Link href={`/care-plans/${id}`} className="text-sm font-semibold text-emerald-700">← Back to care plan</Link><p className="mt-3 text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Controlled comparison</p><h1 className="mt-1 text-3xl font-bold">CARE PLAN CHANGE SUMMARY</h1><p className="mt-1 text-slate-600">Current version v{x.current?.versionNumber??0} compared with proposed version v{version.versionNumber}. Unchanged sections are not duplicated.</p></header><div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[1200px] w-full text-left text-sm"><thead className="bg-slate-900 text-white"><tr>{["Section","Change","Previous position","Proposed position","Reason","Risk impact","Source","Approval"].map((h)=><th key={h} className="p-3 text-xs uppercase">{h}</th>)}</tr></thead><tbody>{version.changes.map((change)=><tr key={change.id} className="border-t align-top"><td className="p-3 font-bold">{labels.get(change.sectionKey)??change.sectionKey}</td><td className="p-3"><Tag value={change.changeType}/></td><td className="max-w-sm p-3"><Summary value={change.previousValue}/></td><td className="max-w-sm p-3"><Summary value={change.proposedValue}/></td><td className="p-3">{change.reason}</td><td className="p-3"><Tag value={change.riskImpact}/></td><td className="p-3">{change.source}</td><td className="p-3">{change.approvalStatus}</td></tr>)}</tbody></table></div><section className="grid gap-3 sm:grid-cols-4">{["UNCHANGED","ADDED","AMENDED","REMOVED"].map((type)=><article key={type} className="rounded-xl border bg-white p-4"><p className="text-xs font-bold text-slate-500">{type}</p><p className="text-2xl font-bold">{type==="UNCHANGED"?Math.max(0,15-version.changes.length):version.changes.filter((c)=>c.changeType===type).length}</p></article>)}</section></main>}finally{await db.$disconnect()}}
function Tag({value}:{value:string}){return <span className={`rounded-full px-2 py-1 text-xs font-bold ${value.includes("RISK")||value==="CRITICAL"?"bg-red-100 text-red-800":value==="AMENDED"||value==="HIGH"?"bg-amber-100 text-amber-900":"bg-emerald-100 text-emerald-800"}`}>{value.replaceAll("_"," ")}</span>}function Summary({value}:{value:unknown}){const text=JSON.stringify(value,null,2);return <pre className="max-h-48 overflow-auto whitespace-pre-wrap font-sans text-xs">{text&&text!=="null"?text:"Not recorded"}</pre>}
