import type { Metadata } from "next";
import Link from "next/link";
import { CTA, CheckList, PageHero, SiteShell } from "@/components/atom-website";
export const metadata: Metadata = { title: "Services | ATOM", description: "Choose the right level of governance support for your care service." };
const packages = [
  { name:"Compliance Foundation", price:"£995", copy:"For smaller providers that need one organised place for governance evidence and dependable monthly support.", items:["ATOM governance platform","Organisation and permission setup","Evidence, policy, audit, risk and action structure","Monthly compliance review","Monthly governance report","One consultancy meeting each month"] },
  { name:"Managed Governance", price:"£1,995", copy:"For providers that need help maintaining their governance system and keeping improvement activity moving.", items:["Everything in Compliance Foundation","Assigned Governance Coordinator","Initial evidence and compliance-gap review","Weekly system and action review","Monthly KPI and governance meeting pack","Two management-support meetings each month"], featured:true },
  { name:"Complete Governance Department", price:"From £4,995", copy:"For providers seeking an outsourced quality, compliance and governance department.", items:["Everything in Managed Governance","Dedicated Governance Manager","Agreed daily operational-record monitoring","Management alerts for urgent indicators","Weekly governance and risk packs","Monthly board-level reporting","Quarterly mock-inspection review"] },
];
export default function ServicesPage(){return <SiteShell><main><PageHero eyebrow="ATOM services" title="Governance support shaped around your organisation." copy="Choose organised foundations, ongoing managed support or a complete outsourced governance department." image /><section className="site-section"><div className="site-container service-cards">{packages.map(item=><article className={item.featured?"featured":""} key={item.name}>{item.featured?<p className="popular">Most popular</p>:null}<h2>{item.name}</h2><p>{item.copy}</p><div className="service-price"><strong>{item.price}</strong><span>per month</span></div><CheckList items={item.items}/><Link className="site-button" href="/contact">Discuss this package</Link></article>)}</div><p className="scope-note">Final scope and fees are confirmed following discovery and may vary by service size, locations, monitoring volume, complexity and governance risk. Prices exclude VAT where applicable.</p></section><CTA /></main></SiteShell>}
