INSERT INTO "AuditSection" ("id", "templateId", "title", "description", "sortOrder")
SELECT
  md5('audit-tailored-section:' || t."id"::text)::uuid,
  t."id",
  'Service-specific checks',
  'Complete each check using a recent sample and record what you found.',
  2
FROM "AuditTemplate" t
WHERE t."organisationId" IS NULL
ON CONFLICT ("templateId", "sortOrder") DO NOTHING;

WITH tailored(template_name, sort_order, question, evidence) AS (VALUES
  ('Governance audit',1,'Do governance meetings review quality, safety, workforce, complaints, incidents and risks?','Recent agendas, minutes and performance reports.'),
  ('Governance audit',2,'Are data trends analysed by location and followed by named actions?','Dashboards, trend reports and action plans.'),
  ('Governance audit',3,'Are overdue actions escalated and closure decisions supported by evidence?','Action tracker, escalation records and closure evidence.'),
  ('Governance audit',4,'Do records demonstrate effective Regulation 17 oversight and continuous improvement?','Governance reports, audits and improvement outcomes.'),
  ('Policy audit',1,'Are policies current, approved, version controlled and assigned to an owner?','Policy register, approval record and version history.'),
  ('Policy audit',2,'Can staff access and understand the policies relevant to their work?','Staff interviews, acknowledgements and access records.'),
  ('Policy audit',3,'Does sampled practice follow the current approved policy?','Observation, care records and audit samples.'),
  ('Policy audit',4,'Are review dates, legal changes and learning used to update policies promptly?','Review schedule, change log and lessons learned.'),
  ('Staff-file audit',1,'Do sampled files contain identity, references, DBS and right-to-work evidence?','Sampled personnel files and safer-recruitment checklist.'),
  ('Staff-file audit',2,'Are employment history gaps explored and recruitment decisions documented?','Applications, interview records and risk assessments.'),
  ('Staff-file audit',3,'Are induction, training, supervision and competency records current?','Training matrix, supervision and competency assessments.'),
  ('Staff-file audit',4,'Are missing or expired records assigned for prompt corrective action?','File audit actions and escalation records.'),
  ('Recruitment audit',1,'Were applications, interviews, references, DBS and right-to-work checks completed before deployment?','Recruitment file sample and start-date evidence.'),
  ('Recruitment audit',2,'Are role requirements and values-based decisions recorded consistently?','Job descriptions, interview scoring and decision record.'),
  ('Recruitment audit',3,'Are conditional starts or recruitment risks authorised and controlled?','Risk assessments, approvals and supervision controls.'),
  ('Recruitment audit',4,'Are recruitment themes and repeated gaps reviewed by management?','Recruitment audit trends and governance minutes.'),
  ('Training audit',1,'Does the training matrix identify every worker, requirement, completion and expiry date?','Current training matrix and staff roster.'),
  ('Training audit',2,'Is mandatory and role-specific learning current for sampled staff?','Certificates, attendance and learning records.'),
  ('Training audit',3,'Is learning translated into observed competence in practice?','Competency observations, spot checks and supervision.'),
  ('Training audit',4,'Are overdue courses risk assessed, escalated and given completion dates?','Exceptions report and recovery action plan.'),
  ('Supervision audit',1,'Are supervisions scheduled at the organisation’s required frequency?','Supervision schedule and overdue report.'),
  ('Supervision audit',2,'Do sampled records cover wellbeing, performance, safeguarding, learning and development?','Completed supervision records.'),
  ('Supervision audit',3,'Are agreed actions assigned, dated and followed through?','Supervision actions and completion evidence.'),
  ('Supervision audit',4,'Are missed sessions and recurring themes reviewed by managers?','Escalations and workforce governance minutes.'),
  ('Care-record audit',1,'Are care plans current, person-centred and based on assessed needs and outcomes?','Current care plans and review records.'),
  ('Care-record audit',2,'Are consent, capacity, communication and involvement recorded appropriately?','Consent records, MCA documentation and reviews.'),
  ('Care-record audit',3,'Are risks, medicines and clinical instructions consistent across the record?','Risk assessments, MAR and professional guidance.'),
  ('Care-record audit',4,'Do daily notes evidence delivery, changes, escalation and outcomes?','Daily records and escalation documentation.'),
  ('Medicines audit',1,'Are staff authorised, trained and competent for the medicines tasks they perform?','Training, competency and delegation records.'),
  ('Medicines audit',2,'Are medicines stored, administered, recorded and disposed of safely?','Storage checks, MAR sample and disposal records.'),
  ('Medicines audit',3,'Are errors, omissions and near misses reported, investigated and learned from?','Incident records, investigations and actions.'),
  ('Medicines audit',4,'Are PRN guidance, changes and reconciliations clear and current?','PRN protocols, prescriptions and reconciliation records.'),
  ('MAR audit',1,'Do MAR charts show correct identity, medicine, dose, time and allergy information?','Current MAR chart sample.'),
  ('MAR audit',2,'Are signatures, codes, refusals, omissions and variable doses complete and explained?','MAR entries and supporting daily notes.'),
  ('MAR audit',3,'Are gaps or repeated anomalies escalated and investigated promptly?','MAR audit actions and incident records.'),
  ('MAR audit',4,'Are PRN administrations supported by clear indications and effectiveness checks?','PRN protocol and outcome recording.'),
  ('Infection-control audit',1,'Are infection-prevention responsibilities, guidance and outbreak arrangements current?','IPC policy, lead responsibilities and outbreak plan.'),
  ('Infection-control audit',2,'Do observations show effective hand hygiene and correct PPE use?','Observation checks and staff competency.'),
  ('Infection-control audit',3,'Are cleaning, waste, laundry and equipment controls followed?','Cleaning schedules and environmental checks.'),
  ('Infection-control audit',4,'Are infections, exposures and outbreaks recorded, escalated and reviewed?','Incident records, notifications and learning.'),
  ('Health-and-safety audit',1,'Are premises, lone-working, moving-and-handling and equipment risks current?','Risk assessments and equipment checks.'),
  ('Health-and-safety audit',2,'Are accidents, hazards and near misses reported and investigated?','Accident records and investigation reports.'),
  ('Health-and-safety audit',3,'Are fire, emergency, first-aid and maintenance controls tested?','Drill records, certificates and maintenance logs.'),
  ('Health-and-safety audit',4,'Are actions assigned and tracked until the hazard is controlled?','Health-and-safety action plan and closure evidence.'),
  ('Complaints audit',1,'Is the complaints process accessible and explained to people using the service?','Complaints information and accessible formats.'),
  ('Complaints audit',2,'Are complaints acknowledged, investigated and answered within required timescales?','Complaint file sample and correspondence.'),
  ('Complaints audit',3,'Are outcomes, remedies and duty-of-candour considerations documented?','Final responses, apologies and remedy records.'),
  ('Complaints audit',4,'Are themes, equality issues and learning reported and acted upon?','Complaint trends and governance actions.'),
  ('Safeguarding audit',1,'Are concerns recognised, recorded and referred without avoidable delay?','Safeguarding records and referral timestamps.'),
  ('Safeguarding audit',2,'Are immediate protection, consent, capacity and information-sharing decisions clear?','Protection plan and decision records.'),
  ('Safeguarding audit',3,'Are Section 42 enquiries and partner communications tracked to outcome?','Authority correspondence and outcome records.'),
  ('Safeguarding audit',4,'Are learning, staff support and preventive actions completed?','Lessons learned, supervision and action evidence.'),
  ('Incident audit',1,'Are incidents and near misses recorded promptly with harm and immediate action?','Incident sample and contemporaneous records.'),
  ('Incident audit',2,'Are severity, escalation, notifications and duty of candour considered correctly?','Escalation and notification records.'),
  ('Incident audit',3,'Are investigations proportionate and do they identify root and contributory causes?','Investigation reports and statements.'),
  ('Incident audit',4,'Are recurring themes and actions reviewed for effectiveness?','Trend analysis and effectiveness reviews.'),
  ('Risk-management audit',1,'Does the risk register cover current organisational and service-level risks?','Current risk register and committee reports.'),
  ('Risk-management audit',2,'Are likelihood, impact, controls and residual risk supported by evidence?','Risk assessments and control assurance.'),
  ('Risk-management audit',3,'Are owners and review dates clear, with overdue reviews escalated?','Risk ownership and review history.'),
  ('Risk-management audit',4,'Are material changes and ineffective controls reflected promptly?','Risk updates, incidents and governance decisions.'),
  ('Business-continuity audit',1,'Is the continuity plan current, accessible and assigned to named leads?','Approved plan, distribution and contact list.'),
  ('Business-continuity audit',2,'Does it cover critical care, staffing, utilities, systems, suppliers and communications?','Scenario plans and dependency records.'),
  ('Business-continuity audit',3,'Has the plan been exercised with realistic scenarios?','Exercise records and participant feedback.'),
  ('Business-continuity audit',4,'Are exercise and real-event lessons incorporated and retested?','Improvement plan and retest evidence.'),
  ('CQC notification audit',1,'Are notifiable events identified correctly and without avoidable delay?','Incident-to-notification reconciliation.'),
  ('CQC notification audit',2,'Are notifications complete, accurate and submitted within required timescales?','Submission receipts and notification copies.'),
  ('CQC notification audit',3,'Is evidence retained for decisions not to notify?','Decision records and management review.'),
  ('CQC notification audit',4,'Are notification themes reviewed with related incidents and safeguarding matters?','Notification log and governance analysis.'),
  ('Service-user feedback audit',1,'Is feedback sought regularly through accessible and inclusive methods?','Survey plan, formats and participation data.'),
  ('Service-user feedback audit',2,'Are people supported to comment safely, including those with communication needs?','Communication plans and advocacy evidence.'),
  ('Service-user feedback audit',3,'Are themes and differences between groups analysed?','Feedback analysis and equality review.'),
  ('Service-user feedback audit',4,'Are people told what changed because of their feedback?','You said, we did communication and actions.'),
  ('Staff engagement audit',1,'Can staff raise ideas, risks and concerns through several safe routes?','Meeting records, surveys and whistleblowing information.'),
  ('Staff engagement audit',2,'Do staff report that leaders listen and respond without retaliation?','Survey findings, interviews and follow-up.'),
  ('Staff engagement audit',3,'Are workforce themes analysed by team, role and location?','Engagement analysis and governance reporting.'),
  ('Staff engagement audit',4,'Are agreed changes communicated and checked for impact?','Action plans, staff updates and pulse checks.'),
  ('Data-protection audit',1,'Are access, data minimisation, secure sharing and device controls working in practice?','Access reviews, sharing logs and device controls.'),
  ('Data-protection audit',2,'Are lawful basis, privacy information, retention and disposal documented?','ROPA, privacy notices and retention schedule.'),
  ('Data-protection audit',3,'Are breaches and data-subject requests identified, timed and managed correctly?','Breach log, DSAR log and decision records.'),
  ('Data-protection audit',4,'Are information-governance training and audits current and acted upon?','Training matrix, audit results and actions.')
)
INSERT INTO "AuditQuestion" (
  "id", "sectionId", "text", "guidance", "evidenceExpected", "responseType",
  "weighting", "mandatory", "requiresCommentNonCompliant", "requiresEvidence", "sortOrder"
)
SELECT
  md5('audit-tailored-question:' || t."id"::text || ':' || x.sort_order)::uuid,
  md5('audit-tailored-section:' || t."id"::text)::uuid,
  x.question,
  'Review a recent, representative sample. Record the sample size and explain any gap or exception.',
  x.evidence,
  'COMPLIANCE',
  2,
  true,
  true,
  false,
  x.sort_order
FROM tailored x
JOIN "AuditTemplate" t ON t."name" = x.template_name AND t."organisationId" IS NULL
ON CONFLICT ("sectionId", "sortOrder") DO NOTHING;
