import { expect, test, type Browser, type Page } from "@playwright/test";
import { signIn } from "./auth";
import { E2E_SETUP_TOKEN, E2E_USERS } from "./fixtures";

type Setup={evidenceId:string;audit:{template:{id:string;name:string};locationId:string}};

test("Medicines Audit closes the finding-to-Action-to-re-audit loop without score-based false assurance",async({page,browser,request})=>{test.setTimeout(720_000);const reset=await request.post("/api/test/e2e/setup",{headers:{"x-e2e-setup-token":E2E_SETUP_TOKEN}});expect(reset.status()).toBe(200);const setup=await (await request.get("/api/test/e2e/setup",{headers:{"x-e2e-setup-token":E2E_SETUP_TOKEN}})).json() as Setup;expect(setup.audit.template.id).toBeTruthy();
 await signIn(page,E2E_USERS.registeredManager);
 const first=await createAudit(page,setup,"E2E-AUDIT-MEDICINES-CRITICAL","NON_COMPLIANT");
 const findingLink=page.getByRole("link",{name:"Review and create corrective Action"});await expect(findingLink).toBeVisible();const findingId=new URL((await findingLink.getAttribute("href"))!,"http://local").searchParams.get("sourceId")!;
 let response=await findingPatch(page,first.auditId,findingId,{intent:"update",severity:"CRITICAL",recommendation:"Correct the medicines control and prove effectiveness through a targeted re-audit.",immediateControl:"Registered Manager immediately checks all current MAR exception records.",escalationRequired:"true",escalationRationale:"Escalate to provider governance today.",actionRequired:"true"});expect(response.status).toBe(200);
 await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByText("Critical finding overrides score")).toBeVisible();
 response=await auditPatch(page,first.auditId,"complete");expect(response.status).toBe(200);await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByText("Outstanding requirements",{exact:true})).toBeVisible();
 const blocked=await auditPatch(page,first.auditId,"close","A high percentage cannot bypass unresolved closed-loop requirements.");expect(blocked.status).toBe(409);expect(blocked.body.requirements.map((item:{key:string})=>item.key)).toContain("actions");
 await page.getByRole("link",{name:"Review and create corrective Action"}).click();await expect(page.getByRole("heading",{name:"Create improvement action"})).toBeVisible();await page.getByRole("button",{name:"Check and create action"}).click();if(await page.getByRole("button",{name:"Reject match"}).count())await page.getByRole("button",{name:"Reject match"}).first().click();await expect(page).toHaveURL(/\/actions\/[0-9a-f-]+$/,{timeout:30_000});const actionId=page.url().split("/").pop()!;
 response=await postForm(page,`/api/actions/${actionId}/updates`,{note:"Corrective work completed and ready for independent verification.",status:"IN_PROGRESS",progressPercent:"100",evidenceId:setup.evidenceId});expect(response.status).toBe(200);
 response=await postForm(page,`/api/actions/${actionId}/assurance/root-cause`,{method:"FIVE_WHYS",problemStatement:"The medicines exception control did not reliably identify repeat gaps.",immediateCauses:"Exception review was missed",contributingFactors:"Follow-up ownership was unclear",systemCauses:"The control lacked an effectiveness checkpoint",lessons:"Completion must remain separate from effectiveness.",preventiveControls:"Use targeted MAR re-audit after verified corrective work.",approve:"false"});expect(response.status).toBe(200);
 const owner=await signedPage(browser,page,E2E_USERS.organisationOwner);response=await postForm(owner,`/api/actions/${actionId}/assurance/root-cause`,{method:"FIVE_WHYS",problemStatement:"The medicines exception control did not reliably identify repeat gaps.",immediateCauses:"Exception review was missed",contributingFactors:"Follow-up ownership was unclear",systemCauses:"The control lacked an effectiveness checkpoint",lessons:"Completion must remain separate from effectiveness.",preventiveControls:"Use targeted MAR re-audit after verified corrective work.",approve:"true"});expect(response.status).toBe(200);
 const quality=await signedPage(browser,page,E2E_USERS.riskOwner);const verifierId=await currentUserId(quality,actionId);response=await postForm(quality,`/api/actions/${actionId}/assurance/verification`,{outcome:"VERIFIED",completedWork:"The agreed medicines corrective work was completed.",evidenceSummary:"The controlled completion record was checked.",successMeasureResult:"Implementation occurred; later observation remains required.",rationale:"Evidence supports completion but does not yet prove effectiveness.",verifierId,verifiedAt:today(),evidenceIds:[setup.evidenceId]});expect(response.status).toBe(200);
 response=await postForm(quality,`/api/actions/${actionId}/assurance/effectiveness`,{outcome:"EFFECTIVE",reviewDate:today(),observedResult:"The later controlled sample found no repeat exception.",decision:"The observed result supports proceeding to closure review.",recurrenceFound:"false",evidenceIds:[setup.evidenceId]});expect(response.status).toBe(200);
 response=await postForm(owner,`/api/actions/${actionId}/assurance/closure`,{intent:"close",rationale:"Completion, separate verification and effectiveness are evidenced with no unresolved dependency.",evidenceIds:[setup.evidenceId]});expect(response.status).toBe(200);
 await page.goto(`/audits/${first.auditId}`,{waitUntil:"domcontentloaded"});await expect(page.getByText(/canonical Action/i).first()).toBeVisible();const beforeReaudit=await findingPatch(page,first.auditId,findingId,{intent:"resolve",rationale:"Action closure alone must not resolve this Critical Audit Finding."});expect(beforeReaudit.status).toBe(400);expect(beforeReaudit.body.error).toMatch(/targeted re-audit/i);
 response=await postForm(page,`/api/audits/${first.auditId}/findings/${findingId}/reaudits`,{reviewDate:today(),outcome:"RESOLVED",sampleSize:"5",sampleDetails:"Targeted sample of five later MAR exception records.",result:"All five records met the corrected control with no repeat exception.",decision:"The targeted result supports resolving this finding.",evidenceIds:[setup.evidenceId]});expect(response.status).toBe(200);
 response=await findingPatch(page,first.auditId,findingId,{intent:"resolve",rationale:"Canonical Action closure and targeted re-audit provide sufficient evidence of resolution."});expect(response.status).toBe(200);
 response=await auditPatch(page,first.auditId,"close","All findings are resolved through verified Action and targeted re-audit evidence.");expect(response.status).toBe(200);await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByText(/closed/i).first()).toBeVisible();await page.goto(`/audits/${first.auditId}/report`,{waitUntil:"domcontentloaded"});await expect(page.getByText("Governance assurance decision")).toBeVisible();await expect(page.getByText(/targeted re-audit/i).first()).toBeVisible();
 await owner.context().close();await quality.context().close();
});

test("Audit recurrence is deterministic, Low findings remain proportionate, and tenant/location/API boundaries hold",async({page,browser,request})=>{test.setTimeout(600_000);const setup=await (await request.get("/api/test/e2e/setup",{headers:{"x-e2e-setup-token":E2E_SETUP_TOKEN}})).json() as Setup;await signIn(page,E2E_USERS.registeredManager);const recurring=await createAudit(page,setup,"E2E-AUDIT-MEDICINES-RECURRING","NON_COMPLIANT");await expect(page.getByText(/Recurring criterion:/)).toBeVisible();const highFinding=await sourceFindingId(page);expect(highFinding).toBeTruthy();
 const low=await createAudit(page,setup,"E2E-AUDIT-MEDICINES-LOW","PARTIALLY_COMPLIANT");const findingId=await sourceFindingId(page);let response=await findingPatch(page,low.auditId,findingId,{intent:"update",severity:"LOW",recommendation:"Correct the minor indexing gap.",immediateControl:"No immediate safety impact identified.",escalationRequired:"false",actionRequired:"false"});expect(response.status).toBe(200);response=await findingPatch(page,low.auditId,findingId,{intent:"resolve",rationale:"Low administrative gap corrected with linked controlled response Evidence."});expect(response.status).toBe(200);response=await auditPatch(page,low.auditId,"complete");expect(response.status).toBe(200);response=await auditPatch(page,low.auditId,"close","The proportionate Low finding is resolved and sufficient Evidence is linked.");expect(response.status).toBe(200);
 const other=await signedPage(browser,page,E2E_USERS.otherTenant);await other.goto(`/audits/${recurring.auditId}`,{waitUntil:"domcontentloaded"});await expect(other.getByText(/page could not be found/i)).toBeVisible();const cross=await findingPatch(other,recurring.auditId,highFinding,{intent:"resolve",rationale:"Deliberate cross-tenant attempt must fail."});expect(cross.status).toBe(404);
 const restricted=await signedPage(browser,page,E2E_USERS.locationRestricted);const locationAttempt=await auditPatch(restricted,recurring.auditId,"close","Deliberate out-of-location attempt must fail.");expect(locationAttempt.status).toBe(404);
 const viewer=await signedPage(browser,page,E2E_USERS.viewer);const capability=await findingPatch(viewer,recurring.auditId,highFinding,{intent:"resolve",rationale:"Read-only role cannot resolve a finding."});expect(capability.url).toMatch(/\/forbidden$/);
 await other.context().close();await restricted.context().close();await viewer.context().close();
});

async function createAudit(page:Page,setup:Setup,title:string,firstAnswer:"NON_COMPLIANT"|"PARTIALLY_COMPLIANT"){await page.goto(`/audits/new?template=${setup.audit.template.id}`,{waitUntil:"domcontentloaded"});await page.getByText("Optional setup").click();await page.getByLabel("Custom audit title").fill(title);await page.getByRole("button",{name:"Start audit now"}).click();await expect(page).toHaveURL(/\/audits\/[0-9a-f-]+#audit-form/);await expect(page.locator("#audit-form")).toBeVisible({timeout:30_000});const auditId=page.url().match(/\/audits\/([0-9a-f-]+)/)![1],checks=page.locator("#audit-form fieldset");await expect(checks.first()).toBeVisible();const count=await checks.count();for(let index=0;index<count;index++){const check=checks.nth(index);await check.getByLabel("Finding or response").selectOption(index===0?firstAnswer:"COMPLIANT");await check.getByLabel("What you checked and found").fill(index===0?"A controlled sample identified the stated medicines gap.":"The controlled sample met the expected standard.");await check.getByLabel("Controlled Evidence Library record").selectOption(setup.evidenceId);}const submission=page.waitForResponse(response=>response.url().endsWith(`/api/audits/${auditId}/responses`)&&response.request().method()==="POST");await page.getByRole("button",{name:"Submit completed form for review"}).click();expect((await submission).status()).toBe(200);await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByRole("heading",{name:"Closed-loop Audit Findings"})).toBeVisible();return{auditId};}
function sourceFindingId(page:Page){return page.locator('a[href*="/actions/new?sourceType=AUDIT"]').first().getAttribute("href").then(value=>new URL(value!,"http://local").searchParams.get("sourceId")!)}
async function findingPatch(page:Page,auditId:string,findingId:string,fields:Record<string,string>){return page.evaluate(async({auditId,findingId,fields})=>{const form=new FormData();for(const[key,value]of Object.entries(fields))form.set(key,value);const response=await fetch(`/api/audits/${auditId}/findings/${findingId}`,{method:"PATCH",body:form});return{status:response.status,url:response.url,body:await response.json().catch(()=>({}))}}, {auditId,findingId,fields});}
async function auditPatch(page:Page,id:string,intent:string,rationale=""){return page.evaluate(async({id,intent,rationale})=>{const form=new FormData();form.set("intent",intent);if(rationale)form.set("rationale",rationale);const response=await fetch(`/api/audits/${id}`,{method:"PATCH",body:form});return{status:response.status,url:response.url,body:await response.json().catch(()=>({}))}},{id,intent,rationale});}
async function postForm(page:Page,url:string,fields:Record<string,string|string[]>){return page.evaluate(async({url,fields})=>{const form=new FormData();for(const[key,value]of Object.entries(fields))for(const item of Array.isArray(value)?value:[value])form.append(key,item);const response=await fetch(url,{method:"POST",body:form});return{status:response.status,url:response.url,body:await response.json().catch(()=>({}))}},{url,fields});}
async function signedPage(browser:Browser,source:Page,user:Parameters<typeof signIn>[1]){const context=await browser.newContext({baseURL:new URL(source.url()).origin});const page=await context.newPage();await signIn(page,user);return page;}
async function currentUserId(page:Page,actionId:string){await page.goto(`/actions/${actionId}/assurance`,{waitUntil:"domcontentloaded"});return page.locator('input[name="verifierId"]').inputValue();}
function today(){return new Date().toISOString().slice(0,10)}
