import Link from "next/link";
import { AlertTriangle, BookOpenCheck, Bot, Flag, MessageSquareWarning, ShieldCheck, ThumbsUp } from "lucide-react";
import { AssistantEscalationReview } from "@/components/assistant-assurance-controls";
import { assistantClassificationLabel } from "@/lib/assistant-governance";
import { TRUSTED_ASSISTANT_SOURCES } from "@/lib/assistant-knowledge";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

export default async function AbiAssurancePage() {
  const context = await requirePermission(PERMISSIONS.GOVERNANCE_VIEW), db = createDb(), now = new Date(), since = new Date(now.getTime() - 30 * 86_400_000), locationIds = context.locations.map((item) => item.id), scope = context.allLocations ? {} : { OR: [{ locationId: null }, { locationId: { in: locationIds } }] };
  try {
    const [interactions, escalations, feedbackCounts, classCounts] = await Promise.all([
      db.aIInteractionLog.findMany({ where: { organisationId: context.organisation.id, createdAt: { gte: since }, ...scope }, include: { user: { select: { name: true } }, sources: true, feedback: true, escalation: { select: { reference: true, status: true } } }, orderBy: { createdAt: "desc" }, take: 60 }),
      db.assistantEscalation.findMany({ where: { organisationId: context.organisation.id, status: { in: ["OPEN", "ACKNOWLEDGED"] }, ...scope }, include: { raisedBy: { select: { name: true } }, assignedTo: { select: { name: true } }, interaction: { select: { confidence: true, responseClass: true, sources: { select: { label: true, href: true } } } } }, orderBy: { createdAt: "asc" }, take: 50 }),
      db.assistantFeedback.groupBy({ by: ["rating"], where: { organisationId: context.organisation.id, createdAt: { gte: since } }, _count: { _all: true } }),
      db.aIInteractionLog.groupBy({ by: ["responseClass"], where: { organisationId: context.organisation.id, createdAt: { gte: since }, ...scope }, _count: { _all: true } }),
    ]);
    const priorityRank = { IMMEDIATE: 0, HIGH: 1, ROUTINE: 2 } as const;
    escalations.sort((left, right) => priorityRank[left.priority] - priorityRank[right.priority] || left.createdAt.getTime() - right.createdAt.getTime());
    const feedback = new Map(feedbackCounts.map((item) => [item.rating, item._count._all])), classes = new Map(classCounts.map((item) => [item.responseClass, item._count._all])), canManage = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_EDIT) || hasPermission(context.permissions, PERMISSIONS.ORGANISATION_MANAGE), known = (classes.get("KNOWN") ?? 0) + (classes.get("NAVIGATION") ?? 0), uncertain = classes.get("UNCERTAIN") ?? 0, prohibited = classes.get("PROHIBITED") ?? 0, totalQuestions = classCounts.reduce((sum, item) => sum + item._count._all, 0);
    return <main className="space-y-7">
      <header className="rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-emerald-900 p-7 text-white shadow-lg"><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-200">Phase 9 · trustworthy Abi</p><h1 className="mt-2 text-3xl font-black">Source-cited guidance with visible limits</h1><p className="mt-3 max-w-4xl text-emerald-50">Abi answers only from controlled QCGMS guidance and named official sources. Every answer shows its class and confidence; uncertainty and prohibited requests create a management escalation instead of an invented response.</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/activity?recordType=AssistantEscalation" className="rounded-xl bg-white/10 px-3 py-2 text-sm font-bold">Escalation audit trail</Link><Link href="/assurance" className="rounded-xl bg-white/10 px-3 py-2 text-sm font-bold">Security assurance</Link></div></header>

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Stat icon={Bot} label="Questions · 30 days" value={totalQuestions} /><Stat icon={ShieldCheck} label="Known answers" value={known} good /><Stat icon={AlertTriangle} label="Uncertain" value={uncertain} warn /><Stat icon={MessageSquareWarning} label="Outside Abi remit" value={prohibited} warn /><Stat icon={ThumbsUp} label="Helpful feedback" value={feedback.get("HELPFUL") ?? 0} good /><Stat icon={Flag} label="Unsafe flags" value={feedback.get("UNSAFE") ?? 0} warn /></section>

      <section className="grid gap-4 lg:grid-cols-3"><Control title="Known" tone="green" text="A controlled module capability or named official source directly supports the answer. Abi displays high confidence and the sources used." /><Control title="Uncertain" tone="amber" text="The controlled guidance does not confirm the requested capability. Abi does not guess and creates a routine management escalation." /><Control title="Prohibited" tone="red" text="Clinical decisions, legal assurance, rating predictions, emergencies and security or record tampering are outside Abi’s remit and are escalated." /></section>

      <section className="space-y-3"><Heading title="Management escalation queue" count={escalations.length} /><div className="grid gap-4 xl:grid-cols-2">{escalations.length ? escalations.map((item) => <article key={item.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${item.priority === "IMMEDIATE" ? "border-red-400" : item.priority === "HIGH" ? "border-amber-400" : ""}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-teal-700">{item.reference} · {assistantClassificationLabel(item.reasonCode)}</p><h3 className="mt-1 text-lg font-black">{item.questionRedacted}</h3></div><div className="flex gap-2"><Badge value={item.priority} warn={item.priority !== "ROUTINE"} /><Badge value={item.status} /></div></div><dl className="mt-4 grid gap-3 text-xs sm:grid-cols-2"><Meta label="Raised by" value={item.raisedBy.name} /><Meta label="Assigned to" value={item.assignedTo?.name ?? "Management queue"} /><Meta label="Raised" value={dateTime(item.createdAt)} /><Meta label="Abi confidence" value={assistantClassificationLabel(item.interaction.confidence)} /></dl><p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-950">This is a redacted summary. Review the operational record and speak with the person who raised it before making a decision.</p>{canManage ? <AssistantEscalationReview id={item.id} /> : null}</article>) : <Empty text="No uncertain or prohibited Abi questions are waiting for management review." />}</div></section>

      <section className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-3"><Heading title="Authorised source register" count={TRUSTED_ASSISTANT_SOURCES.length} /><div className="grid gap-3">{TRUSTED_ASSISTANT_SOURCES.map((source) => <article key={source.href} className="rounded-2xl border bg-white p-4 shadow-sm"><BookOpenCheck size={19} className="text-emerald-700" /><h3 className="mt-2 font-black">{source.label}</h3><p className="text-xs text-slate-500">{source.authority}{source.versionLabel ? ` · ${source.versionLabel}` : ""}{source.checkedAt ? ` · checked ${date(new Date(`${source.checkedAt}T00:00:00Z`))}` : ""}</p>{source.href.startsWith("http") ? <a href={source.href} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm font-black text-emerald-800">Open official source ↗</a> : <Link href={source.href} className="mt-2 inline-block text-sm font-black text-emerald-800">Open controlled source →</Link>}</article>)}</div></div><div className="space-y-3"><Heading title="Recent audited answers" count={interactions.length} /><div className="grid gap-3">{interactions.length ? interactions.map((item) => <article key={item.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-teal-700">{item.user.name} · {dateTime(item.createdAt)}</p><h3 className="mt-1 font-black">{item.queryRedacted}</h3></div><div className="flex gap-2"><Badge value={item.responseClass} warn={["UNCERTAIN", "PROHIBITED"].includes(item.responseClass)} /><Badge value={`${item.confidence}_CONFIDENCE`} /></div></div><p className="mt-2 line-clamp-3 text-sm text-slate-600">{item.answerText}</p><p className="mt-3 text-xs text-slate-500">{item.sources.length} cited source{item.sources.length === 1 ? "" : "s"}{item.feedback ? ` · feedback: ${assistantClassificationLabel(item.feedback.rating)}` : " · no feedback"}{item.escalation ? ` · ${item.escalation.reference}: ${assistantClassificationLabel(item.escalation.status)}` : ""}</p></article>) : <Empty text="No Abi questions have been audited in the last 30 days." />}</div></div></section>

      <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-sm text-blue-950"><strong>Privacy control:</strong> QCGMS stores a cryptographic question hash and a redacted question summary, not the raw question. Email addresses, phone numbers, record references and long identifiers are removed before audit storage. Users should still avoid entering names or unnecessary personal details into Abi.</section>
    </main>;
  } finally { await db.$disconnect(); }
}

function Stat({ icon: Icon, label, value, warn = false, good = false }: { icon: typeof Bot; label: string; value: number; warn?: boolean; good?: boolean }) { return <div className={`rounded-2xl border p-5 shadow-sm ${warn && value ? "border-red-200 bg-red-50" : good && value ? "border-emerald-200 bg-emerald-50" : "bg-white"}`}><Icon size={20} className={warn && value ? "text-red-700" : "text-emerald-700"} /><p className="mt-2 text-sm text-slate-600">{label}</p><p className="text-3xl font-black">{value}</p></div>; }
function Control({ title, text, tone }: { title: string; text: string; tone: "green" | "amber" | "red" }) { const style = { green: "border-emerald-200 bg-emerald-50 text-emerald-950", amber: "border-amber-200 bg-amber-50 text-amber-950", red: "border-red-200 bg-red-50 text-red-950" }; return <article className={`rounded-2xl border p-4 ${style[tone]}`}><h2 className="font-black">{title}</h2><p className="mt-1 text-sm">{text}</p></article>; }
function Heading({ title, count }: { title: string; count: number }) { return <div><h2 className="text-xl font-black">{title}</h2><p className="text-sm text-slate-500">{count} controlled record{count === 1 ? "" : "s"}</p></div>; }
function Badge({ value, warn = false }: { value: string; warn?: boolean }) { return <span className={`h-fit rounded-full px-2.5 py-1 text-[10px] font-black ${warn ? "bg-red-100 text-red-800" : "bg-slate-100 text-slate-700"}`}>{assistantClassificationLabel(value)}</span>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><dt className="font-black uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-0.5 font-semibold text-slate-800">{value}</dd></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed bg-slate-50 p-6 text-sm text-slate-500">{text}</div>; }
function date(value: Date) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(value); }
function dateTime(value: Date) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(value); }
