ALTER TABLE "AuditTemplate" ADD COLUMN IF NOT EXISTS "key" TEXT;
ALTER TABLE "AuditTemplate" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'Governance';
ALTER TABLE "AuditTemplate" ADD COLUMN IF NOT EXISTS "standardRefs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "AuditTemplate" ADD COLUMN IF NOT EXISTS "frequency" TEXT;
ALTER TABLE "AuditTemplate" ADD COLUMN IF NOT EXISTS "serviceSpecific" BOOLEAN NOT NULL DEFAULT false;

UPDATE "AuditTemplate"
SET "key" = trim(both '-' from regexp_replace(lower(regexp_replace("name", '[^a-zA-Z0-9]+', '-', 'g')), '-+', '-', 'g'));
ALTER TABLE "AuditTemplate" ALTER COLUMN "key" SET NOT NULL;

ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "objective" TEXT;
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "sampleMethod" TEXT;
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "sampleSize" INTEGER;
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "sampleDetails" TEXT;
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "standardApplied" TEXT;
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "limitations" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "AuditTemplate_organisationId_key_version_key" ON "AuditTemplate"("organisationId", "key", "version");
CREATE INDEX IF NOT EXISTS "AuditTemplate_category_isPublished_idx" ON "AuditTemplate"("category", "isPublished");

WITH metadata(name, category, standards, frequency, service_specific) AS (VALUES
  ('Governance audit','Leadership and governance',ARRAY['CQC Regulation 17','CQC Well-led']::TEXT[],'Quarterly',false),
  ('Policy audit','Leadership and governance',ARRAY['CQC Regulation 17']::TEXT[],'Quarterly',false),
  ('Staff-file audit','Workforce',ARRAY['CQC Regulations 18 and 19']::TEXT[],'Quarterly',false),
  ('Recruitment audit','Workforce',ARRAY['CQC Regulation 19','Schedule 3']::TEXT[],'Quarterly',false),
  ('Training audit','Workforce',ARRAY['CQC Regulation 18']::TEXT[],'Monthly',false),
  ('Supervision audit','Workforce',ARRAY['CQC Regulation 18']::TEXT[],'Monthly',false),
  ('Care-record audit','Care delivery',ARRAY['CQC Regulations 9, 11, 12 and 17']::TEXT[],'Monthly',false),
  ('Medicines audit','Medicines',ARRAY['CQC Regulation 12','NICE SC1']::TEXT[],'Monthly',false),
  ('MAR audit','Medicines',ARRAY['CQC Regulation 12','NICE SC1']::TEXT[],'Monthly',false),
  ('Infection-control audit','Safety',ARRAY['CQC Regulation 12']::TEXT[],'Quarterly and after an outbreak',false),
  ('Health-and-safety audit','Safety',ARRAY['CQC Regulation 12','Health and Safety at Work etc. Act 1974']::TEXT[],'Quarterly',false),
  ('Complaints audit','People experience',ARRAY['CQC Regulations 16 and 17']::TEXT[],'Monthly',false),
  ('Safeguarding audit','Safety',ARRAY['CQC Regulation 13','Care Act 2014']::TEXT[],'Monthly',false),
  ('Incident audit','Safety',ARRAY['CQC Regulations 12, 17 and 20']::TEXT[],'Monthly',false),
  ('Risk-management audit','Leadership and governance',ARRAY['CQC Regulations 12 and 17']::TEXT[],'Monthly',false),
  ('Business-continuity audit','Leadership and governance',ARRAY['CQC Regulations 12 and 17']::TEXT[],'Annual and after activation',false),
  ('CQC notification audit','Regulatory assurance',ARRAY['Care Quality Commission (Registration) Regulations 2009']::TEXT[],'Monthly',false),
  ('Service-user feedback audit','People experience',ARRAY['CQC Regulations 9 and 17']::TEXT[],'Quarterly',false),
  ('Staff engagement audit','Workforce',ARRAY['CQC Regulations 17 and 18']::TEXT[],'Six-monthly',false),
  ('Data-protection audit','Information governance',ARRAY['UK GDPR','Data Protection Act 2018']::TEXT[],'Annual and after material change',false)
)
UPDATE "AuditTemplate" t SET "category"=m.category,"standardRefs"=m.standards,"frequency"=m.frequency,"serviceSpecific"=m.service_specific
FROM metadata m WHERE t."name"=m.name AND t."organisationId" IS NULL;

WITH templates(key,name,description,category,standards,frequency,service_specific) AS (VALUES
 ('cqc-self-assessment','CQC quality self-assessment','A structured internal review across Safe, Effective, Caring, Responsive and Well-led. It supports assurance but does not predict a CQC rating.','Regulatory assurance',ARRAY['CQC assessment framework','Health and Social Care Act 2008 regulations']::TEXT[],'Quarterly and before inspection',false),
 ('care-call-delivery','Care call delivery audit','Tests punctuality, duration, continuity, missed-call controls, records and follow-up using a representative call sample.','Care delivery',ARRAY['CQC Regulations 9, 12 and 17']::TEXT[],'Monthly',false),
 ('care-planning-risk','Care planning and risk audit','Checks whether assessments, care plans and risk controls are person-centred, consistent, current and reflected in daily care.','Care delivery',ARRAY['CQC Regulations 9, 11, 12 and 17']::TEXT[],'Monthly',false),
 ('consent-capacity','Consent and mental capacity audit','Reviews decision-specific consent, capacity assessments, best-interest decisions and lawful representative involvement.','Care delivery',ARRAY['CQC Regulation 11','Mental Capacity Act 2005']::TEXT[],'Quarterly',false),
 ('staff-competency','Staff competency and observed-practice audit','Checks that staff are assessed as competent for the duties they perform and that gaps lead to supervision and reassessment.','Workforce',ARRAY['CQC Regulations 12 and 18']::TEXT[],'Monthly',false),
 ('spot-check','Home-care spot-check audit','Provides direct assurance of punctuality, identity, dignity, infection control, medicines practice, documentation and person experience.','Care delivery',ARRAY['CQC Regulations 9, 10, 12 and 18']::TEXT[],'Risk-based and scheduled',false),
 ('nutrition-hydration','Nutrition and hydration audit','Checks assessment, individual support, monitoring, escalation and professional referral for nutrition and hydration risks.','Clinical governance',ARRAY['CQC Regulation 14']::TEXT[],'Quarterly and risk-based',true),
 ('delegated-healthcare','Delegated healthcare task audit','Checks clinical delegation, instructions, staff competence, monitoring, escalation and review for delegated healthcare tasks.','Clinical governance',ARRAY['CQC Regulations 12 and 18']::TEXT[],'Monthly when applicable',true),
 ('equality-accessible-information','Equality and accessible information audit','Tests whether protected characteristics, communication needs, reasonable adjustments and inequalities are identified and acted upon.','People experience',ARRAY['Equality Act 2010','Accessible Information Standard','CQC Regulations 9 and 10']::TEXT[],'Six-monthly',false),
 ('commissioner-contract','Commissioner contract and KPI audit','Assures the completeness, traceability and timely submission of contractual performance and quality information.','Leadership and governance',ARRAY['CQC Regulation 17','Local contract requirements']::TEXT[],'Monthly',false)
)
INSERT INTO "AuditTemplate" ("id","key","name","description","category","standardRefs","frequency","serviceSpecific","version","isPublished","updatedAt")
SELECT md5('audit-template-v2:'||key)::uuid,key,name,description,category,standards,frequency,service_specific,'1.0',true,CURRENT_TIMESTAMP FROM templates
ON CONFLICT DO NOTHING;

WITH sections(template_key,sort_order,title,description) AS (VALUES
 ('cqc-self-assessment',1,'Quality and safety','Review the evidence across the five key questions, including records, people experience, staff feedback, observation and outcomes.'),('cqc-self-assessment',2,'Leadership, learning and improvement','Test whether leaders understand risk, act on concerns and can demonstrate sustained improvement.'),
 ('care-call-delivery',1,'Call delivery sample','Reconcile planned and delivered visits using a representative sample.'),('care-call-delivery',2,'Exceptions and learning','Test how exceptions were identified, communicated, investigated and prevented.'),
 ('care-planning-risk',1,'Assessment and plan quality','Review whether plans accurately reflect assessed needs, preferences, outcomes and risks.'),('care-planning-risk',2,'Delivery and review','Compare the plan with daily records, feedback, changes and review actions.'),
 ('consent-capacity',1,'Consent and decision making','Review whether consent is informed, current and specific to the decision.'),('consent-capacity',2,'Capacity and best interests','Test the quality of capacity assessments and best-interest decision records.'),
 ('staff-competency',1,'Authorisation and assessment','Review competency requirements and assessor sign-off for the staff sample.'),('staff-competency',2,'Practice and follow-up','Confirm competence in practice and follow-up of gaps or restrictions.'),
 ('spot-check',1,'Observed visit','Observe professional, safe and person-centred practice.'),('spot-check',2,'Records and feedback','Compare observed practice with care records and the person’s experience.'),
 ('nutrition-hydration',1,'Assessment and planning','Review nutritional risks, preferences and individual support instructions.'),('nutrition-hydration',2,'Monitoring and escalation','Test monitoring, response to deterioration and professional involvement.'),
 ('delegated-healthcare',1,'Delegation and competence','Confirm lawful, person-specific delegation and staff competence.'),('delegated-healthcare',2,'Delivery and clinical oversight','Test recording, monitoring, escalation and clinical review.'),
 ('equality-accessible-information',1,'Needs and adjustments','Review equality, communication, cultural and accessibility needs.'),('equality-accessible-information',2,'Experience and outcomes','Test whether adjustments work and whether unequal outcomes are identified.'),
 ('commissioner-contract',1,'Data quality and traceability','Reconcile reported measures to named source systems and evidence.'),('commissioner-contract',2,'Submission and improvement','Review timeliness, validation, variance explanations and actions.')
)
INSERT INTO "AuditSection" ("id","templateId","title","description","sortOrder")
SELECT md5('audit-v2-section:'||s.template_key||':'||s.sort_order)::uuid,t."id",s.title,s.description,s.sort_order
FROM sections s JOIN "AuditTemplate" t ON t."key"=s.template_key AND t."organisationId" IS NULL ON CONFLICT DO NOTHING;

WITH questions(template_key,section_order,sort_order,question,evidence,weighting) AS (VALUES
 ('cqc-self-assessment',1,1,'Safe: do records, observations and people’s experience show risks are identified and care is delivered safely?','Risk records, incident themes, observations and people’s feedback.',3),('cqc-self-assessment',1,2,'Effective: do assessments, care records and outcomes show evidence-based care that meets people’s needs?','Assessments, care plans, outcomes, training and professional input.',3),('cqc-self-assessment',1,3,'Caring: do people consistently describe kind, respectful care that protects dignity, choice and independence?','People’s experience, observations, compliments and concerns.',3),('cqc-self-assessment',1,4,'Responsive: is care personalised, accessible and adjusted promptly when needs or circumstances change?','Reviews, communication plans, complaints and service changes.',3),('cqc-self-assessment',2,1,'Well-led: can leaders demonstrate reliable oversight, open culture and clear accountability at every location?','Governance minutes, dashboards, role accountability and staff feedback.',3),('cqc-self-assessment',2,2,'Are concerns, inequalities and recurring themes converted into owned actions with deadlines and evidence of impact?','Trend analysis, action tracker and effectiveness checks.',2),('cqc-self-assessment',2,3,'Does the evidence include people’s experience and observation, rather than relying only on policies and documents?','Interviews, surveys, direct observation and accessible feedback.',2),('cqc-self-assessment',2,4,'Can leaders explain remaining gaps, limitations and the improvement plan honestly?','Risk register, improvement plan and governance challenge.',2),
 ('care-call-delivery',1,1,'Does the planned-versus-delivered sample reconcile to the care management system and rota?','Planned rota, electronic call monitoring and daily records.',3),('care-call-delivery',1,2,'Are missed, late, short and long visits identified consistently using defined tolerances?','Exception report, contract definitions and call data.',3),('care-call-delivery',1,3,'Do visit records show the required care and outcomes were delivered for the sampled calls?','Visit notes, tasks, medication records and outcome notes.',3),('care-call-delivery',1,4,'Is continuity monitored and are avoidable changes or unfamiliar staff followed up?','Continuity report, rota changes and people’s feedback.',2),('care-call-delivery',2,1,'Were people or representatives contacted promptly when visits changed or were delayed?','Call log, messages and escalation timestamps.',2),('care-call-delivery',2,2,'Were missed or materially late calls risk assessed, escalated and reported correctly?','Incident record, safeguarding decision and commissioner notification.',3),('care-call-delivery',2,3,'Are repeated exceptions analysed by worker, route, time, person and root cause?','Monthly trends and investigation notes.',2),('care-call-delivery',2,4,'Are improvement actions checked to confirm call delivery became safer and more reliable?','Closed actions, repeat data and effectiveness review.',2),
 ('care-planning-risk',1,1,'Does each sampled care plan reflect a current, holistic assessment and outcomes important to the person?','Assessment, care plan and person/representative involvement.',3),('care-planning-risk',1,2,'Are risks specific, proportionate and linked to practical controls without unnecessarily restricting choice?','Risk assessments, consent and least-restrictive alternatives.',3),('care-planning-risk',1,3,'Are medicines, clinical, communication, cultural and equality needs consistent across the record?','Care plan, MAR, communication plan and professional guidance.',3),('care-planning-risk',1,4,'Are review dates and triggers clear for scheduled and change-led review?','Review schedule and change records.',2),('care-planning-risk',2,1,'Do daily records demonstrate delivery against the plan and meaningful outcomes rather than generic task statements?','Daily notes and outcome records.',3),('care-planning-risk',2,2,'Were deterioration, refusals, concerns and changing needs escalated and reflected in updated plans?','Escalations, professional advice and plan versions.',3),('care-planning-risk',2,3,'Can the person or representative confirm the plan reflects their choices and current support?','Interview, feedback or signed review.',2),('care-planning-risk',2,4,'Are gaps assigned, corrected and rechecked within risk-based timescales?','Actions and follow-up sample.',2),
 ('consent-capacity',1,1,'Is consent recorded for the specific care, treatment, information sharing or restriction being reviewed?','Consent records and care documentation.',3),('consent-capacity',1,2,'Was the person given accessible information and genuine choice before consent was recorded?','Accessible information, communication support and discussion record.',3),('consent-capacity',1,3,'Are refusals and withdrawal of consent respected, recorded and escalated safely?','Daily records, risk response and professional advice.',3),('consent-capacity',1,4,'Is any representative’s authority verified and relevant to the decision?','LPA, deputyship or other authority evidence.',2),('consent-capacity',2,1,'Where capacity is in doubt, is there a decision-specific assessment with clear evidence?','Mental capacity assessment.',3),('consent-capacity',2,2,'Does the best-interest record show consultation, alternatives and the least restrictive option?','Best-interest decision and consultation.',3),('consent-capacity',2,3,'Are restrictions reviewed and escalated to the correct legal route where required?','Restriction review and legal authorisation.',3),('consent-capacity',2,4,'Are staff able to explain how consent and capacity apply in the sampled situations?','Staff interview, training and supervision.',2),
 ('staff-competency',1,1,'Is there a role-specific competency profile covering every task the sampled worker performs?','Role profile and competency matrix.',3),('staff-competency',1,2,'Was competence assessed before unsupervised practice by an appropriately skilled assessor?','Assessment, assessor details and authorisation date.',3),('staff-competency',1,3,'Does the assessment use direct observation and knowledge checks rather than training completion alone?','Observation form and knowledge questions.',3),('staff-competency',1,4,'Are expiry, reassessment and change-of-role triggers visible and monitored?','Competency tracker and alerts.',2),('staff-competency',2,1,'Does observed practice match the signed competency and current procedure?','Spot check, supervision or direct observation.',3),('staff-competency',2,2,'Are competency restrictions communicated to scheduling and operational staff?','Restrictions, rota controls and handover.',3),('staff-competency',2,3,'Do failed or partial assessments produce a development plan and supervised reassessment?','Development action and reassessment.',3),('staff-competency',2,4,'Are competency themes reviewed for training, policy or system improvement?','Trend report and governance minutes.',2),
 ('spot-check',1,1,'Did the worker arrive as expected, identify themselves and follow entry, lone-working and infection controls?','Observed visit and call-monitoring record.',2),('spot-check',1,2,'Was care respectful, unhurried, person-centred and protective of privacy and dignity?','Direct observation and person feedback.',3),('spot-check',1,3,'Were medicines or delegated tasks carried out exactly as authorised and recorded?','Observation, MAR and competency record.',3),('spot-check',1,4,'Did the worker recognise and respond appropriately to changes, risks or concerns?','Observed response and escalation route.',3),('spot-check',2,1,'Were visit notes accurate, timely and consistent with what happened?','Daily notes and call record.',3),('spot-check',2,2,'Could the person explain who to contact and raise concerns in an accessible way?','Person interview and service information.',2),('spot-check',2,3,'Did the worker demonstrate knowledge of the current care plan and relevant risks?','Staff discussion and care-plan access.',3),('spot-check',2,4,'Were feedback and required actions shared promptly with the worker and manager?','Spot-check feedback and action record.',2),
 ('nutrition-hydration',1,1,'Are nutritional and hydration needs, preferences, allergies and risks assessed using suitable tools?','Assessment and clinical information.',3),('nutrition-hydration',1,2,'Does the plan state practical, person-centred support and monitoring requirements?','Care plan and communication needs.',3),('nutrition-hydration',1,3,'Are texture, swallowing and specialist instructions current and consistent?','Speech and language or dietetic guidance.',3),('nutrition-hydration',1,4,'Are staff competent for the support they provide, including specialist needs?','Training, competency and observation.',2),('nutrition-hydration',2,1,'Are intake, weight or other monitoring records complete when required?','Food/fluid chart, weights and daily notes.',3),('nutrition-hydration',2,2,'Are deterioration and thresholds for escalation recognised and acted on promptly?','Escalation record and professional advice.',3),('nutrition-hydration',2,3,'Are refusals, capacity, choice and risk decisions documented appropriately?','Consent, capacity and risk record.',3),('nutrition-hydration',2,4,'Are outcomes reviewed and plans updated after professional advice or change?','Review and updated plan.',2),
 ('delegated-healthcare',1,1,'Is the task delegated by a named competent health professional for this person and this worker or role?','Delegation record and named clinician.',3),('delegated-healthcare',1,2,'Are current instructions, limits, contraindications and escalation routes unambiguous?','Person-specific protocol and contact route.',3),('delegated-healthcare',1,3,'Was competency assessed in practice before authorisation and at required intervals?','Competency assessment and review date.',3),('delegated-healthcare',1,4,'Are changes, absences and substitute staff controlled so only authorised workers perform the task?','Rota controls and contingency plan.',3),('delegated-healthcare',2,1,'Do records show the task was delivered, monitored and evaluated as instructed?','Task record, observations and outcomes.',3),('delegated-healthcare',2,2,'Were exceptions, deterioration or failed tasks escalated immediately and recorded?','Clinical escalation and incident record.',3),('delegated-healthcare',2,3,'Does the delegating professional review the arrangement after change or at the agreed frequency?','Clinical review and renewed authorisation.',3),('delegated-healthcare',2,4,'Are incidents and learning shared with the delegating professional and governance lead?','Investigation, learning and governance record.',2),
 ('equality-accessible-information',1,1,'Are protected characteristics, communication needs, culture, faith and reasonable adjustments identified sensitively?','Assessment, communication plan and equality information.',3),('equality-accessible-information',1,2,'Is information offered in a format and language the person can understand and use?','Accessible documents, interpreter or communication support.',3),('equality-accessible-information',1,3,'Are adjustments visible to relevant staff and consistently delivered?','Care plan, alerts and observation.',3),('equality-accessible-information',1,4,'Are consent, confidentiality and people’s preferences respected when recording equality information?','Consent and privacy records.',2),('equality-accessible-information',2,1,'Can people confirm communication and adjustments work for them in practice?','People’s experience and representative feedback.',3),('equality-accessible-information',2,2,'Are access, complaints, incidents and outcomes analysed for unequal experience between groups?','Equality analysis and trends.',3),('equality-accessible-information',2,3,'Are barriers and inequalities converted into owned improvement actions?','Equality action plan and completion evidence.',2),('equality-accessible-information',2,4,'Are staff confident in respectful, inclusive and anti-discriminatory practice?','Staff feedback, training and observation.',2),
 ('commissioner-contract',1,1,'Does every reported KPI have a definition, owner, reporting period and named source system?','KPI dictionary and source register.',3),('commissioner-contract',1,2,'Can the reported totals be reproduced from source records without unsupported manual adjustment?','Source export, reconciliation and calculation.',3),('commissioner-contract',1,3,'Are exemptions, exclusions and denominators documented and consistently applied?','Calculation rules and exception evidence.',3),('commissioner-contract',1,4,'Are data completeness, duplicates and material variances checked before approval?','Validation checklist and variance review.',3),('commissioner-contract',2,1,'Was the return reviewed, approved and submitted within the contractual timescale?','Approval and submission receipt.',3),('commissioner-contract',2,2,'Are adverse results explained honestly with linked risks and actions?','Management commentary, risk and action records.',3),('commissioner-contract',2,3,'Are corrections and commissioner queries logged with a traceable response?','Correspondence and corrected return.',2),('commissioner-contract',2,4,'Are trends used in governance meetings and checked for improvement impact?','Trend dashboard, minutes and effectiveness review.',2)
)
INSERT INTO "AuditQuestion" ("id","sectionId","text","guidance","evidenceExpected","responseType","weighting","mandatory","requiresCommentNonCompliant","requiresEvidence","sortOrder")
SELECT md5('audit-v2-question:'||q.template_key||':'||q.section_order||':'||q.sort_order)::uuid,
       md5('audit-v2-section:'||q.template_key||':'||q.section_order)::uuid,q.question,
       'Use a recent representative sample. Record exactly what was checked, the result and any limitation.',q.evidence,'COMPLIANCE',q.weighting,true,true,false,q.sort_order
FROM questions q ON CONFLICT DO NOTHING;

INSERT INTO "Evidence" (
  "id","organisationId","locationId","title","description","category","evidenceType","ownerId",
  "evidenceDate","reviewExpiryDate","tags","relatedModule","relatedRecordId","confidentiality","status",
  "notes","archivedAt","uploadedById","createdAt","updatedAt"
)
SELECT md5('audit-evidence:'||a."id"::text)::uuid,a."organisationId",a."locationId",
  left('Completed audit: '||a."title",180),
  t."name"||' v'||a."templateVersion"||'. '||CASE WHEN a."overallScore" IS NULL THEN 'No overall score was calculated.' ELSE 'Overall assurance score: '||a."overallScore"||'%.' END,
  'Audits','Audit assurance record',a."auditorId",a."auditDate",a."reviewDate",
  ARRAY['system-generated','audit','audit:'||t."key",'audit-status:'||lower(a."status"::text)],
  'Audit',a."id",'CONFIDENTIAL'::"EvidenceConfidentiality",
  CASE WHEN a."status"='ARCHIVED' THEN 'ARCHIVED'::"EvidenceWorkflowStatus" ELSE 'ACTIVE'::"EvidenceWorkflowStatus" END,
  'Generated from a submitted audit and kept in sync with the signed governance record. Open the source audit for responses, linked evidence, findings and sign-off.',
  CASE WHEN a."status"='ARCHIVED' THEN COALESCE(a."archivedAt",CURRENT_TIMESTAMP) ELSE NULL END,
  a."auditorId",a."createdAt",CURRENT_TIMESTAMP
FROM "Audit" a JOIN "AuditTemplate" t ON t."id"=a."templateId"
WHERE a."status" IN ('AWAITING_REVIEW','COMPLETED','CLOSED','ARCHIVED')
  AND NOT EXISTS (SELECT 1 FROM "Evidence" e WHERE e."organisationId"=a."organisationId" AND e."relatedModule"='Audit' AND e."relatedRecordId"=a."id"::text);
