import Link from "next/link";
import { notFound } from "next/navigation";
import { RiskArchiveAction, RiskClosurePanel, RiskReviewForm } from "@/components/risk-actions";
import { RiskControlAssurance } from "@/components/risk-control-assurance";
import { RiskEvidenceSearch } from "@/components/risk-evidence-search";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { evidenceAssuranceState } from "@/lib/evidence-assurance";
import { evidenceScopeWhere } from "@/lib/evidence";
import { evidenceTaxonomySuggestions, taxonomyLabels } from "@/lib/evidence-taxonomy";
import { controlSuggestions } from "@/lib/governance-catalogues";
import { riskManagementAssurance } from "@/lib/management-assurance";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";
import { controlApplicationAssurance, providerControlApplies } from "@/lib/provider-controls";
import { isOutsideTolerance, levelClasses, riskScopeWhere, riskStatusLabel } from "@/lib/risks";
import { evaluateRiskClosure, resolveCurrentClosureRule, resolveCurrentRiskFramework, stableRiskCategoryKey, strongestRecordedRiskLevel } from "@/lib/risk-framework";

export default async function RiskPage({params}:{params:Promise<{id:string}>}){
  const context=await requirePermission(PERMISSIONS.GOVERNANCE_VIEW),{id}=await params,db=createDb();
  try{
    const risk=await db.risk.findFirst({where:{id,...riskScopeWhere(context)},include:{location:{select:{name:true}},owner:{select:{name:true}},createdBy:{select:{name:true}},closureApprovedBy:{select:{name:true}},evidenceLinks:{include:{evidence:{select:{id:true,title:true,relatedModule:true,status:true,reviewExpiryDate:true,updatedAt:true,currentVersionId:true,currentnessMode:true,currentnessStatus:true,verifications:{orderBy:{verifiedAt:"desc"},take:1,select:{outcome:true,verifiedAt:true,evidenceVersionId:true,reviewDueAt:true}}}}}},controlApplications:{include:{controlVersion:{select:{status:true,expectedEvidenceFamilyKeys:true,expectedEvidenceTypeKeys:true}},evidenceLinks:{include:{evidence:{select:{id:true,title:true,taxonomyFamilyKey:true,taxonomyTypeKey:true,status:true,reviewExpiryDate:true,updatedAt:true,currentVersionId:true,currentnessMode:true,currentnessStatus:true,verifications:{orderBy:{verifiedAt:"desc"},take:1,select:{outcome:true,verifiedAt:true,evidenceVersionId:true,reviewDueAt:true}}}}}},effectivenessReviews:{orderBy:{reviewDate:"desc"}}},orderBy:{appliedAt:"desc"}},reviews:{include:{reviewedBy:{select:{name:true}}},orderBy:{reviewDate:"desc"}},closureProposals:{include:{proposedBy:{select:{id:true,name:true}},withdrawnBy:{select:{name:true}},approvals:{include:{approver:{select:{name:true}}},orderBy:{createdAt:"asc"}}},orderBy:{proposedAt:"desc"}}}});if(!risk)notFound();
    const canEdit=hasPermission(context.permissions,PERMISSIONS.GOVERNANCE_EDIT),canActions=hasPermission(context.permissions,PERMISSIONS.ACTIONS_MANAGE),outside=isOutsideTolerance(risk.residualScore,risk.toleranceScore);
    const authorityLevel=strongestRecordedRiskLevel([risk.initialLevel,risk.residualLevel,...risk.reviews.map(review=>review.level)]);
    const[actions,generatedEvidence,currentFramework,currentClosure,availableControls,evidenceCandidates]=await Promise.all([db.action.findMany({where:{organisationId:context.organisation.id,sourceType:"RISK",sourceRecordId:id,status:{not:"ARCHIVED"}},select:{id:true,reference:true,title:true,status:true,dueDate:true,updatedAt:true,evidenceRequired:true,owner:{select:{name:true}},_count:{select:{evidenceLinks:{where:{retiredAt:null}},effectivenessReviews:true}}},orderBy:{createdAt:"desc"}}),db.evidence.findFirst({where:{organisationId:context.organisation.id,relatedModule:"Risk",relatedRecordId:id},select:{id:true}}),resolveCurrentRiskFramework(db,context.organisation.id,risk.category),resolveCurrentClosureRule(db,context.organisation.id,authorityLevel,stableRiskCategoryKey(risk.category)),db.providerControlVersion.findMany({where:{organisationId:context.organisation.id,status:"EFFECTIVE"},include:{control:true,locations:true},orderBy:{approvedAt:"desc",},take:50}),db.evidence.findMany({where:{...evidenceScopeWhere(context),status:"ACTIVE",NOT:{relatedModule:"Risk",relatedRecordId:id}},select:{id:true,title:true,locationId:true,taxonomyFamilyKey:true,taxonomyTypeKey:true,taxonomyFamilySnapshot:true,taxonomyTypeSnapshot:true,category:true,evidenceType:true,status:true,reviewExpiryDate:true,updatedAt:true,currentVersionId:true,currentnessMode:true,currentnessStatus:true,verifications:{orderBy:{verifiedAt:"desc"},take:1,select:{outcome:true,verifiedAt:true,evidenceVersionId:true,reviewDueAt:true}}},orderBy:{updatedAt:"desc"},take:40})]);
    const evidenceWithAssurance=[...new Map(risk.evidenceLinks.map(({evidence})=>[evidence.id,{...evidence,assuranceState:evidenceAssuranceState({status:evidence.status,reviewExpiryDate:evidence.reviewExpiryDate,updatedAt:evidence.updatedAt,currentVersionId:evidence.currentVersionId,currentnessMode:evidence.currentnessMode,currentnessStatus:evidence.currentnessStatus,verification:evidence.verifications[0]})}])).values()];
    const independentEvidence=evidenceWithAssurance.filter((evidence)=>!(evidence.relatedModule==="Risk"&&evidence.id===generatedEvidence?.id));
    const controlAssurance=risk.controlApplications.map(application=>({application,assessment:controlApplicationAssurance({status:application.status,controlStatus:application.controlVersion.status,expectedFamilyKeys:application.controlVersion.expectedEvidenceFamilyKeys,expectedTypeKeys:application.controlVersion.expectedEvidenceTypeKeys,evidenceLinks:application.evidenceLinks,latestEffectiveness:application.effectivenessReviews[0]})}));
    const assurance=riskManagementAssurance({risk,independentEvidence:independentEvidence.map(({title,assuranceState})=>({title,assuranceState})),actions:actions.map(action=>({reference:action.reference,status:action.status,dueDate:action.dueDate,evidenceCount:action._count.evidenceLinks,evidenceRequired:action.evidenceRequired,effectivenessCount:action._count.effectivenessReviews})),controlApplications:controlAssurance.map(({application,assessment})=>({title:application.titleSnapshot,gaps:assessment.gaps,conflicts:assessment.conflicts}))});
    const latestReview=risk.reviews[0],pendingProposal=risk.closureProposals.find(proposal=>proposal.status==="PENDING"),verifiedEvidenceCount=independentEvidence.filter(item=>["CURRENT_VERIFIED","VERIFIED_WITH_LIMITATIONS","EXPIRING_SOON"].includes(item.assuranceState)).length,effectivenessCount=actions.reduce((total,action)=>total+action._count.effectivenessReviews,0)+(latestReview?.controlsEffective&&latestReview?.assuranceChecked?1:0),unresolvedActionCount=actions.filter(action=>!["COMPLETED","CANCELLED","ARCHIVED"].includes(action.status)).length,closureEvaluation=evaluateRiskClosure(currentClosure.rule,{actorRoleKey:context.role.key,actorId:context.user.id,ownerId:risk.ownerId,proposerId:pendingProposal?.proposedById,residualScore:risk.residualScore,toleranceScore:currentFramework?.toleranceScore??risk.toleranceScore,supportingEvidenceCount:independentEvidence.length,verifiedCurrentEvidenceCount:verifiedEvidenceCount,unresolvedActionCount,effectivenessReviewCount:effectivenessCount,approvalCount:pendingProposal?.approvals.filter(approval=>approval.decision==="APPROVED").length??0});
    const since=risk.lastReviewDate??risk.createdAt,sinceActions=actions.filter(action=>action.updatedAt>since),sinceEvidence=independentEvidence.filter(evidence=>evidence.updatedAt>since);
    const relevantEvidenceKeys=new Set(evidenceTaxonomySuggestions(risk.category).map(item=>`${item.familyKey}:${item.key}`));const rankedEvidence=[...evidenceCandidates].sort((a,b)=>{const aRelevant=relevantEvidenceKeys.has(`${a.taxonomyFamilyKey}:${a.taxonomyTypeKey}`)?1:0,bRelevant=relevantEvidenceKeys.has(`${b.taxonomyFamilyKey}:${b.taxonomyTypeKey}`)?1:0;if(aRelevant!==bRelevant)return bRelevant-aRelevant;const aLocation=a.locationId===risk.locationId?1:0,bLocation=b.locationId===risk.locationId?1:0;return bLocation-aLocation||b.updatedAt.getTime()-a.updatedAt.getTime()});
    return <main className="space-y-6">
      <header><Link href="/risks" className="text-sm font-semibold text-emerald-700">← Risk Register</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-sm text-emerald-700">{risk.reference}</p><h1 className="text-3xl font-bold">{risk.title}</h1><p className="mt-1 text-slate-600">{risk.category} · {riskStatusLabel(risk.status)} · {risk.location?.name??"Organisation-wide"}</p></div><div className="flex flex-wrap gap-2">{generatedEvidence?<Link href={`/evidence/${generatedEvidence.id}`} className="rounded-lg border border-emerald-700 bg-white px-4 py-2 text-sm font-semibold text-emerald-800">Open synced evidence</Link>:null}{canActions?<Link href={`/actions/new?sourceType=RISK&sourceId=${id}`} className="rounded-lg bg-amber-800 px-4 py-2 text-sm font-semibold text-white">Create treatment action</Link>:null}{canEdit?<><Link href={`/risks/${id}/edit`} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Edit assessment</Link><RiskArchiveAction id={id} archived={risk.status==="ARCHIVED"}/></>:null}</div></div></header>
      <section className={`rounded-2xl border p-5 ${outside?"border-red-300 bg-red-50":"border-emerald-200 bg-emerald-50"}`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest">Management position</p><h2 className="mt-1 text-xl font-bold">{outside?"Current risk is outside tolerance":"Current risk is within the recorded tolerance"}</h2><p className="mt-1 text-sm">Residual score {risk.residualScore}; tolerance {risk.toleranceScore??"not set"}. {outside?"Treatment, escalation or formally authorised acceptance is required.":"Continue monitoring controls and warning indicators."}</p></div><span className={`rounded-full px-3 py-2 text-sm font-black text-white ${outside?"bg-red-700":"bg-emerald-700"}`}>{outside?"ESCALATE / TREAT":"MONITOR"}</span></div></section>
      {currentFramework&&(risk.riskFrameworkVersionId!==currentFramework.frameworkVersionId||risk.frameworkToleranceSnapshot!==currentFramework.toleranceScore)?<section className={`rounded-2xl border p-5 ${risk.residualScore>currentFramework.toleranceScore?"border-red-300 bg-red-50":"border-blue-200 bg-blue-50"}`}><p className="text-xs font-bold uppercase tracking-widest">Framework change exception</p><h2 className="mt-1 text-lg font-bold">A newer organisation Risk Framework applies</h2><p className="mt-1 text-sm">Framework v{currentFramework.frameworkVersionNumber} now records {currentFramework.appetite.replaceAll("_"," ").toLowerCase()} appetite and tolerance {currentFramework.toleranceScore} for {risk.category}. The historical Risk has not been rewritten. Apply the current framework deliberately at the next formal review.{risk.residualScore>currentFramework.toleranceScore?" The residual score is outside the current organisation tolerance.":""}</p></section>:null}
      <AssurancePanel assurance={assurance}/>
      <RiskControlAssurance riskId={risk.id} canEdit={canEdit&&!['CLOSED','ARCHIVED','CLOSURE_PROPOSED'].includes(risk.status)} providerControls={availableControls.filter(version=>providerControlApplies({status:version.status,scopeType:version.scopeType,locationIds:version.locations.map(item=>item.locationId),riskLocationId:risk.locationId,categoryKeys:version.applicableRiskCategoryKeys,riskCategory:risk.category})&&!risk.controlApplications.some(application=>application.controlVersionId===version.id)).map(version=>({id:version.id,reference:version.control.stableKey,title:version.title,description:version.description,family:version.family,reason:`Approved Provider Control matched to ${risk.category} and ${risk.location?.name??"organisation-wide"} scope.`}))} coreSuggestions={controlSuggestions(risk.category,risk.sourceType??"").map(item=>({family:"QCGMS",label:item.label,reason:item.wording}))} evidence={rankedEvidence.map(item=>{const state=evidenceAssuranceState({...item,verification:item.verifications[0]}),labels=item.taxonomyFamilyKey&&item.taxonomyTypeKey?taxonomyLabels(item.taxonomyFamilyKey,item.taxonomyTypeKey):null,relevant=relevantEvidenceKeys.has(`${item.taxonomyFamilyKey}:${item.taxonomyTypeKey}`);return{id:item.id,title:item.title,taxonomy:labels?`${labels.familyLabel} · ${labels.typeLabel}`:`Legacy: ${item.category} · ${item.evidenceType}`,assurance:label(state),reason:relevant?`Contextual Evidence type matched to the ${risk.category} Risk category.`:item.locationId===risk.locationId?"Same location and available within your authorised Evidence scope.":"Authorised organisation Evidence, ranked by recent update."}}).slice(0,12)} applications={controlAssurance.map(({application,assessment})=>({id:application.id,reference:application.controlKeySnapshot,version:application.versionNumberSnapshot,title:application.titleSnapshot,description:application.descriptionSnapshot,family:application.familySnapshot,status:application.status,effectivenessMethod:application.effectivenessMethodSnapshot,latestEffectiveness:application.effectivenessReviews[0]?.outcome??"NOT_TESTED",gaps:assessment.gaps,conflicts:assessment.conflicts,evidence:application.evidenceLinks.map(link=>({id:link.evidence.id,title:link.evidence.title,role:link.role,assurance:label(evidenceAssuranceState({...link.evidence,verification:link.evidence.verifications[0]}))}))}))}/>
      {canEdit&&!['CLOSED','ARCHIVED','CLOSURE_PROPOSED'].includes(risk.status)?<RiskEvidenceSearch riskId={risk.id} applications={controlAssurance.map(({application})=>({id:application.id,title:application.titleSnapshot}))}/>:null}
      <RiskClosurePanel id={risk.id} status={risk.status} canPropose={currentClosure.rule.proposerRoleKeys.includes(context.role.key)&&closureEvaluation.checks.filter(check=>!["role","self"].includes(check.key)).every(check=>check.met)} canApprove={currentClosure.rule.approverRoleKeys.includes(context.role.key)&&closureEvaluation.checks.filter(check=>["role","self"].includes(check.key)).every(check=>check.met)&&!pendingProposal?.approvals.some(approval=>approval.approverId===context.user.id)} canWithdraw={pendingProposal?.proposedById===context.user.id} proposal={pendingProposal?{proposedBy:pendingProposal.proposedBy.name,proposedAt:date(pendingProposal.proposedAt),approvalCount:pendingProposal.approvals.filter(approval=>approval.decision==="APPROVED").length,requiredApprovalCount:currentClosure.rule.requiredApprovalCount}:undefined} policy={{versionLabel:currentClosure.policyVersion?`v${currentClosure.policyVersion.versionNumber}`:"legacy proportional fallback",checks:closureEvaluation.checks,readyToClose:closureEvaluation.readyToClose,outstanding:closureEvaluation.outstanding}} decision={{reference:risk.reference,title:risk.title,category:risk.category,residual:`${risk.residualScore} · ${risk.residualLevel}`,tolerance:String(currentFramework?.toleranceScore??risk.toleranceScore??"Not set"),frameworkVersion:risk.riskFrameworkVersionId?`v${currentFramework?.frameworkVersionNumber??"recorded"}`:"Legacy Risk-level position",actionsCompleted:actions.filter(action=>["COMPLETED","CANCELLED","ARCHIVED"].includes(action.status)).length,actionsUnresolved:unresolvedActionCount,supportingEvidence:independentEvidence.map(item=>item.title),verifiedEvidenceCount,effectivenessCount,currentRole:context.role.name}}/>
      {risk.closureProposals.length?<Card title="Closure decision history"><ol className="space-y-4">{risk.closureProposals.map(proposal=><li key={proposal.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-bold">Proposed {date(proposal.proposedAt)} by {proposal.proposedBy.name}</p><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{label(proposal.status)}</span></div><p className="mt-2">{proposal.rationale}</p><p className="mt-2 text-xs text-slate-500">Residual snapshot {proposal.residualScoreSnapshot} · tolerance {proposal.toleranceScoreSnapshot??"not set"} · proposer role {label(proposal.proposedRoleKeySnapshot)}</p>{proposal.approvals.length?<ul className="mt-3 space-y-2">{proposal.approvals.map(approval=><li key={approval.id} className={`rounded-lg p-3 ${approval.decision==="REJECTED"?"bg-red-50":"bg-emerald-50"}`}><strong>{label(approval.decision)}</strong> by {approval.approver.name} on {date(approval.createdAt)} · {label(approval.roleKeySnapshot)}{approval.rationale?<p className="mt-1">{approval.rationale}</p>:null}<p className="mt-1 text-xs text-slate-500">Authority: {approval.authoritySnapshot}</p></li>)}</ul>:null}{proposal.status==="WITHDRAWN"?<div className="mt-3 rounded-lg bg-amber-50 p-3"><strong>Withdrawn by {proposal.withdrawnBy?.name??"recorded proposer"} on {date(proposal.withdrawnAt)}</strong><p className="mt-1">{proposal.withdrawalReason??"No withdrawal rationale was retained by the previous workflow."}</p></div>:null}</li>)}</ol></Card>:null}
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Score label="Inherent" score={risk.initialScore} level={risk.initialLevel}/><Score label="Current residual" score={risk.residualScore} level={risk.residualLevel}/><Score label="Target" score={risk.targetScore??risk.residualScore} level={risk.targetLevel??risk.residualLevel}/><Info label="Owner" value={risk.owner?.name??"Unassigned"}/><Info label="Next review" value={date(risk.nextReviewDate)} warning={risk.nextReviewDate<new Date()&&!['CLOSED','ARCHIVED'].includes(risk.status)}/></section>
      <Card title="Risk statement"><p className="text-base"><strong>Because</strong> {risk.cause??"the recorded cause"}, <strong>there is a risk that</strong> {risk.riskEvent??risk.title}, <strong>resulting in</strong> {risk.consequence??risk.description}.</p><dl className="mt-5 grid gap-3 md:grid-cols-4"><Dt label="Who may be affected" value={risk.peopleAffected??"Not recorded"}/><Dt label="Source" value={risk.sourceType??"Manual identification"}/><Dt label="Source reference" value={risk.sourceReference??"Not recorded"}/><Dt label="Date identified" value={date(risk.identifiedDate)}/></dl></Card>
      <section className="grid gap-5 lg:grid-cols-2"><Card title="Existing controls"><p>{risk.existingControls}</p><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Dt label="Effectiveness" value={label(risk.controlEffectiveness??"NOT_TESTED")}/><Dt label="Assurance checked" value={risk.controlAssurance??"Not recorded"}/></dl></Card><Card title="Treatment and target"><p>{risk.furtherControls??"No further treatment recorded."}</p><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Dt label="Strategy" value={label(risk.treatmentStrategy??"REDUCE")}/><Dt label="Target date" value={date(risk.targetDate)}/><Dt label="Appetite" value={label(risk.appetite??"LOW")}/>{risk.frameworkOverrideRationale?<><Dt label="Inherited framework position" value={`${label(risk.frameworkInheritedAppetiteSnapshot??"Not recorded")} · tolerance ${risk.frameworkInheritedToleranceSnapshot??"not recorded"}`}/><Dt label="Authorised override rationale" value={risk.frameworkOverrideRationale}/></>:null}<Dt label="Acceptance rationale" value={risk.acceptanceRationale??"Not applicable"}/></dl></Card><Card title="Early warning and escalation"><dl className="grid gap-3"><Dt label="Key risk indicator" value={risk.keyRiskIndicator??"Not set"}/><Dt label="Warning threshold" value={risk.indicatorThreshold??"Not set"}/><Dt label="Escalation route" value={risk.escalationRoute??"Not recorded"}/><Dt label="Immediate review triggers" value={risk.reviewTriggers??"Not recorded"}/></dl></Card><Card title="Closure control"><dl className="grid grid-cols-2 gap-3"><Dt label="Closure date" value={date(risk.closureDate)}/><Dt label="Approved by" value={risk.closureApprovedBy?.name??"Not approved"}/></dl><p className="mt-4">{risk.closureRationale??"No closure rationale recorded."}</p></Card></section>
      <Card title="Treatment actions">{actions.length?<ul className="space-y-2">{actions.map(action=><li key={action.id}><Link href={`/actions/${action.id}`} className="font-bold text-emerald-800">{action.reference} · {action.title}</Link><span className="text-slate-500"> · {riskStatusLabel(action.status)} · {action.owner.name}</span></li>)}</ul>:<div><p className="text-slate-500">No Action Tracker items are linked to this risk.</p>{canActions?<Link href={`/actions/new?sourceType=RISK&sourceId=${id}`} className="mt-3 inline-flex font-bold text-emerald-800">Create a treatment action →</Link>:null}</div>}</Card>
      <Card title="Assurance evidence"><div className="flex flex-wrap gap-2">{risk.evidenceLinks.length?risk.evidenceLinks.map(({evidence,role})=><Link key={`${evidence.id}-${role}`} href={`/evidence/${evidence.id}`} className="rounded-lg bg-emerald-50 px-3 py-2 font-semibold text-emerald-800">{evidence.title}{evidence.relatedModule==="Risk"?" · live record":` · ${label(role)}`}</Link>):<p className="text-slate-500">No evidence linked.</p>}</div></Card>
      <Card title="Since the last formal review"><p className="text-slate-600">QCGMS found changes since {date(since)}. Confirm their significance; presence of a record does not determine the risk decision.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><ChangeCount label="Linked actions changed" value={sinceActions.length}/><ChangeCount label="Evidence changed" value={sinceEvidence.length}/><ChangeCount label="Overdue actions" value={actions.filter(action=>!["COMPLETED","CANCELLED"].includes(action.status)&&action.dueDate<new Date()).length}/></div>{sinceEvidence.length?<ul className="mt-4 list-disc space-y-1 pl-5">{sinceEvidence.slice(0,5).map(evidence=><li key={evidence.id}>{evidence.title} · {label(evidence.assuranceState)}</li>)}</ul>:null}</Card>
      {canEdit&&!['CLOSED','ARCHIVED','CLOSURE_PROPOSED'].includes(risk.status)?<Card title="Formal risk review"><RiskReviewForm id={id} defaults={{likelihood:risk.residualLikelihood,impact:risk.residualImpact,nextReviewDate:risk.nextReviewDate.toISOString().slice(0,10)}} evidence={independentEvidence.map(({title,assuranceState})=>({title,assuranceState}))} framework={currentFramework?{versionNumber:currentFramework.frameworkVersionNumber,appetite:currentFramework.appetite,toleranceScore:currentFramework.toleranceScore,alreadyApplied:risk.riskFrameworkVersionId===currentFramework.frameworkVersionId}:undefined} canOverride={hasPermission(context.permissions,PERMISSIONS.ORGANISATION_MANAGE)}/></Card>:null}
      <Card title="Review history">{risk.reviews.length?<ol className="space-y-5">{risk.reviews.map(review=><li key={review.id} className="border-l-4 border-emerald-600 pl-4"><div className="flex flex-wrap items-center gap-2"><strong>{date(review.reviewDate)}</strong><span className={`rounded-full px-2 py-1 text-xs font-bold ${levelClasses(review.level)}`}>{review.score} · {review.level}</span>{review.trend?<span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{label(review.trend)}</span>:null}{review.escalated?<span className="rounded-full bg-red-100 px-2 py-1 text-xs font-bold text-red-800">Escalated</span>:null}</div><p className="mt-2 whitespace-pre-wrap">{review.notes}</p>{review.assuranceChecked?<p className="mt-2 rounded-lg bg-slate-50 p-3"><strong>Assurance checked:</strong> {review.assuranceChecked}</p>:null}{review.controlChanges?<p className="mt-2"><strong>Control changes:</strong> {review.controlChanges}</p>:null}<p className="mt-2 text-xs text-slate-500">{review.reviewedBy.name} · Controls {review.controlsEffective?"effective":"need improvement"} · Decision {label(review.decision??"CONTINUE_MONITORING")} · Next review {date(review.nextReviewDate)}</p></li>)}</ol>:<p className="text-slate-500">No formal reviews recorded yet.</p>}</Card>
      <p className="text-xs text-slate-500">Created by {risk.createdBy.name} on {date(risk.createdAt)}. Updates and reviews are recorded in the Activity Log.</p>
    </main>;
  }finally{await db.$disconnect()}
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">{title}</h2><div className="mt-3 whitespace-pre-wrap text-sm leading-6">{children}</div></section>}
function Score({label:heading,score,level}:{label:string;score:number;level:string}){return <div className={`rounded-2xl p-5 ${levelClasses(level)}`}><p className="text-xs font-bold uppercase tracking-wider">{heading}</p><p className="mt-1 text-3xl font-black">{score}</p><p className="text-sm font-bold">{level}</p></div>}
function Info({label:heading,value,warning=false}:{label:string;value:string;warning?:boolean}){return <div className={`rounded-2xl border p-5 ${warning?"border-red-200 bg-red-50 text-red-800":"border-slate-200 bg-white"}`}><p className="text-xs font-bold uppercase tracking-wider">{heading}</p><p className="mt-2 font-bold">{value}{warning?" · Overdue":""}</p></div>}
function Dt({label:heading,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase text-slate-500">{heading}</dt><dd className="mt-1">{value}</dd></div>}
function ChangeCount({label:heading,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">{heading}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function AssurancePanel({assurance}:{assurance:ReturnType<typeof riskManagementAssurance>}){const ready=assurance.state==="READY_FOR_ASSURANCE";return <section className={`rounded-2xl border p-5 ${ready?"border-emerald-200 bg-emerald-50":"border-amber-300 bg-amber-50"}`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest">Management assurance test</p><h2 className="mt-1 text-xl font-bold">{ready?"Ready for management assurance":"Outstanding assurance requirements"}</h2><p className="mt-1 max-w-3xl text-sm">Internal scrutiny aid only. QCGMS organises the evidence and highlights gaps; the authorised manager makes the assurance and closure decision.</p></div><span className={`rounded-full px-3 py-2 text-xs font-black ${ready?"bg-emerald-700 text-white":"bg-amber-200 text-amber-950"}`}>{ready?"READY FOR RM DECISION":"REVIEW REQUIRED"}</span></div><div className="mt-5 grid gap-2 md:grid-cols-2">{assurance.checks.map(check=><div key={check.key} className="rounded-xl border border-white/70 bg-white/75 p-3"><p className="font-bold"><span className={check.met?"text-emerald-700":"text-amber-800"}>{check.met?"✓":"⚠"}</span> {check.label}</p>{!check.met?<p className="mt-1 text-sm text-slate-700">{check.reason}</p>:null}<p className="mt-1 text-xs text-slate-500">Source: {check.provenance}</p></div>)}</div>{assurance.conflicts.length?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4"><p className="font-bold text-red-900">Potential assurance conflict</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-red-900">{assurance.conflicts.map(conflict=><li key={conflict}>{conflict} Review the evidence and retain the RM decision.</li>)}</ul></div>:null}<details className="mt-4 rounded-xl border border-slate-200 bg-white p-3"><summary className="cursor-pointer font-bold">What would an external reviewer ask for?</summary><p className="mt-2 text-sm text-slate-600">A clear risk, accountable ownership, current controls, reliable evidence, action ownership, effectiveness testing, a current review and a defensible closure trail. This view does not imply regulator endorsement.</p></details></section>}
function date(value:Date|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value):"Not set"}
function label(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/^\w/,c=>c.toUpperCase())}
