import Link from "next/link";
import { notFound } from "next/navigation";
import { RiskArchiveAction, RiskReviewForm } from "@/components/risk-actions";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";
import { isOutsideTolerance, levelClasses, riskScopeWhere, riskStatusLabel } from "@/lib/risks";

export default async function RiskPage({params}:{params:Promise<{id:string}>}){
  const context=await requirePermission(PERMISSIONS.GOVERNANCE_VIEW),{id}=await params,db=createDb();
  try{
    const risk=await db.risk.findFirst({where:{id,...riskScopeWhere(context)},include:{location:{select:{name:true}},owner:{select:{name:true}},createdBy:{select:{name:true}},closureApprovedBy:{select:{name:true}},evidenceLinks:{include:{evidence:{select:{id:true,title:true,relatedModule:true}}}},reviews:{include:{reviewedBy:{select:{name:true}}},orderBy:{reviewDate:"desc"}}}});if(!risk)notFound();
    const canEdit=hasPermission(context.permissions,PERMISSIONS.GOVERNANCE_EDIT),canActions=hasPermission(context.permissions,PERMISSIONS.ACTIONS_MANAGE),outside=isOutsideTolerance(risk.residualScore,risk.toleranceScore);
    const[actions,generatedEvidence]=await Promise.all([db.action.findMany({where:{organisationId:context.organisation.id,sourceType:"RISK",sourceRecordId:id,status:{not:"ARCHIVED"}},select:{id:true,reference:true,title:true,status:true,owner:{select:{name:true}}},orderBy:{createdAt:"desc"}}),db.evidence.findFirst({where:{organisationId:context.organisation.id,relatedModule:"Risk",relatedRecordId:id},select:{id:true}})]);
    return <main className="space-y-6">
      <header><Link href="/risks" className="text-sm font-semibold text-emerald-700">← Risk Register</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-sm text-emerald-700">{risk.reference}</p><h1 className="text-3xl font-bold">{risk.title}</h1><p className="mt-1 text-slate-600">{risk.category} · {riskStatusLabel(risk.status)} · {risk.location?.name??"Organisation-wide"}</p></div><div className="flex flex-wrap gap-2">{generatedEvidence?<Link href={`/evidence/${generatedEvidence.id}`} className="rounded-lg border border-emerald-700 bg-white px-4 py-2 text-sm font-semibold text-emerald-800">Open synced evidence</Link>:null}{canActions?<Link href={`/actions/new?sourceType=RISK&sourceId=${id}`} className="rounded-lg bg-amber-800 px-4 py-2 text-sm font-semibold text-white">Create treatment action</Link>:null}{canEdit?<><Link href={`/risks/${id}/edit`} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Edit assessment</Link><RiskArchiveAction id={id} archived={risk.status==="ARCHIVED"}/></>:null}</div></div></header>
      <section className={`rounded-2xl border p-5 ${outside?"border-red-300 bg-red-50":"border-emerald-200 bg-emerald-50"}`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest">Management position</p><h2 className="mt-1 text-xl font-bold">{outside?"Current risk is outside tolerance":"Current risk is within the recorded tolerance"}</h2><p className="mt-1 text-sm">Residual score {risk.residualScore}; tolerance {risk.toleranceScore??"not set"}. {outside?"Treatment, escalation or formally authorised acceptance is required.":"Continue monitoring controls and warning indicators."}</p></div><span className={`rounded-full px-3 py-2 text-sm font-black text-white ${outside?"bg-red-700":"bg-emerald-700"}`}>{outside?"ESCALATE / TREAT":"MONITOR"}</span></div></section>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Score label="Inherent" score={risk.initialScore} level={risk.initialLevel}/><Score label="Current residual" score={risk.residualScore} level={risk.residualLevel}/><Score label="Target" score={risk.targetScore??risk.residualScore} level={risk.targetLevel??risk.residualLevel}/><Info label="Owner" value={risk.owner?.name??"Unassigned"}/><Info label="Next review" value={date(risk.nextReviewDate)} warning={risk.nextReviewDate<new Date()&&!['CLOSED','ARCHIVED'].includes(risk.status)}/></section>
      <Card title="Risk statement"><p className="text-base"><strong>Because</strong> {risk.cause??"the recorded cause"}, <strong>there is a risk that</strong> {risk.riskEvent??risk.title}, <strong>resulting in</strong> {risk.consequence??risk.description}.</p><dl className="mt-5 grid gap-3 md:grid-cols-4"><Dt label="Who may be affected" value={risk.peopleAffected??"Not recorded"}/><Dt label="Source" value={risk.sourceType??"Manual identification"}/><Dt label="Source reference" value={risk.sourceReference??"Not recorded"}/><Dt label="Date identified" value={date(risk.identifiedDate)}/></dl></Card>
      <section className="grid gap-5 lg:grid-cols-2"><Card title="Existing controls"><p>{risk.existingControls}</p><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Dt label="Effectiveness" value={label(risk.controlEffectiveness??"NOT_TESTED")}/><Dt label="Assurance checked" value={risk.controlAssurance??"Not recorded"}/></dl></Card><Card title="Treatment and target"><p>{risk.furtherControls??"No further treatment recorded."}</p><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Dt label="Strategy" value={label(risk.treatmentStrategy??"REDUCE")}/><Dt label="Target date" value={date(risk.targetDate)}/><Dt label="Appetite" value={label(risk.appetite??"LOW")}/><Dt label="Acceptance rationale" value={risk.acceptanceRationale??"Not applicable"}/></dl></Card><Card title="Early warning and escalation"><dl className="grid gap-3"><Dt label="Key risk indicator" value={risk.keyRiskIndicator??"Not set"}/><Dt label="Warning threshold" value={risk.indicatorThreshold??"Not set"}/><Dt label="Escalation route" value={risk.escalationRoute??"Not recorded"}/><Dt label="Immediate review triggers" value={risk.reviewTriggers??"Not recorded"}/></dl></Card><Card title="Closure control"><dl className="grid grid-cols-2 gap-3"><Dt label="Closure date" value={date(risk.closureDate)}/><Dt label="Approved by" value={risk.closureApprovedBy?.name??"Not approved"}/></dl><p className="mt-4">{risk.closureRationale??"No closure rationale recorded."}</p></Card></section>
      <Card title="Treatment actions">{actions.length?<ul className="space-y-2">{actions.map(action=><li key={action.id}><Link href={`/actions/${action.id}`} className="font-bold text-emerald-800">{action.reference} · {action.title}</Link><span className="text-slate-500"> · {riskStatusLabel(action.status)} · {action.owner.name}</span></li>)}</ul>:<div><p className="text-slate-500">No Action Tracker items are linked to this risk.</p>{canActions?<Link href={`/actions/new?sourceType=RISK&sourceId=${id}`} className="mt-3 inline-flex font-bold text-emerald-800">Create a treatment action →</Link>:null}</div>}</Card>
      <Card title="Assurance evidence"><div className="flex flex-wrap gap-2">{risk.evidenceLinks.length?risk.evidenceLinks.map(({evidence})=><Link key={evidence.id} href={`/evidence/${evidence.id}`} className="rounded-lg bg-emerald-50 px-3 py-2 font-semibold text-emerald-800">{evidence.title}{evidence.relatedModule==="Risk"?" · live record":""}</Link>):<p className="text-slate-500">No evidence linked.</p>}</div></Card>
      {canEdit&&!['CLOSED','ARCHIVED'].includes(risk.status)?<Card title="Formal risk review"><RiskReviewForm id={id} defaults={{likelihood:risk.residualLikelihood,impact:risk.residualImpact,nextReviewDate:risk.nextReviewDate.toISOString().slice(0,10)}}/></Card>:null}
      <Card title="Review history">{risk.reviews.length?<ol className="space-y-5">{risk.reviews.map(review=><li key={review.id} className="border-l-4 border-emerald-600 pl-4"><div className="flex flex-wrap items-center gap-2"><strong>{date(review.reviewDate)}</strong><span className={`rounded-full px-2 py-1 text-xs font-bold ${levelClasses(review.level)}`}>{review.score} · {review.level}</span>{review.trend?<span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{label(review.trend)}</span>:null}{review.escalated?<span className="rounded-full bg-red-100 px-2 py-1 text-xs font-bold text-red-800">Escalated</span>:null}</div><p className="mt-2 whitespace-pre-wrap">{review.notes}</p>{review.assuranceChecked?<p className="mt-2 rounded-lg bg-slate-50 p-3"><strong>Assurance checked:</strong> {review.assuranceChecked}</p>:null}{review.controlChanges?<p className="mt-2"><strong>Control changes:</strong> {review.controlChanges}</p>:null}<p className="mt-2 text-xs text-slate-500">{review.reviewedBy.name} · Controls {review.controlsEffective?"effective":"need improvement"} · Decision {label(review.decision??"CONTINUE_MONITORING")} · Next review {date(review.nextReviewDate)}</p></li>)}</ol>:<p className="text-slate-500">No formal reviews recorded yet.</p>}</Card>
      <p className="text-xs text-slate-500">Created by {risk.createdBy.name} on {date(risk.createdAt)}. Updates and reviews are recorded in the Activity Log.</p>
    </main>;
  }finally{await db.$disconnect()}
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">{title}</h2><div className="mt-3 whitespace-pre-wrap text-sm leading-6">{children}</div></section>}
function Score({label:heading,score,level}:{label:string;score:number;level:string}){return <div className={`rounded-2xl p-5 ${levelClasses(level)}`}><p className="text-xs font-bold uppercase tracking-wider">{heading}</p><p className="mt-1 text-3xl font-black">{score}</p><p className="text-sm font-bold">{level}</p></div>}
function Info({label:heading,value,warning=false}:{label:string;value:string;warning?:boolean}){return <div className={`rounded-2xl border p-5 ${warning?"border-red-200 bg-red-50 text-red-800":"border-slate-200 bg-white"}`}><p className="text-xs font-bold uppercase tracking-wider">{heading}</p><p className="mt-2 font-bold">{value}{warning?" · Overdue":""}</p></div>}
function Dt({label:heading,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase text-slate-500">{heading}</dt><dd className="mt-1">{value}</dd></div>}
function date(value:Date|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value):"Not set"}
function label(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/^\w/,c=>c.toUpperCase())}
