import Link from "next/link";
import { notFound } from "next/navigation";
import { RiskArchiveAction, RiskReviewForm } from "@/components/risk-actions";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";
import { levelClasses, riskScopeWhere, riskStatusLabel } from "@/lib/risks";

export default async function RiskPage({ params }: { params: Promise<{ id: string }> }) {
  const context = await requirePermission(PERMISSIONS.GOVERNANCE_VIEW); const { id } = await params; const db = createDb();
  try {
    const risk = await db.risk.findFirst({ where: { id, ...riskScopeWhere(context) }, include: { location: { select: { name: true } }, owner: { select: { name: true } }, createdBy: { select: { name: true } }, closureApprovedBy: { select: { name: true } }, evidenceLinks: { include: { evidence: { select: { id: true, title: true } } } }, reviews: { include: { reviewedBy: { select: { name: true } } }, orderBy: { reviewDate: "desc" } } } });
    if (!risk) notFound(); const canEdit = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_EDIT);
    return <main className="space-y-6">
      <header><Link href="/risks" className="text-sm font-semibold text-emerald-700">← Risk Register</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-sm text-emerald-700">{risk.reference}</p><h1 className="text-3xl font-bold">{risk.title}</h1><p className="mt-1 text-slate-600">{risk.category} · {riskStatusLabel(risk.status)} · {risk.location?.name??"Organisation-wide"}</p></div>{canEdit&&<div className="flex gap-2"><Link href={`/risks/${id}/edit`} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Edit risk</Link><RiskArchiveAction id={id} archived={risk.status==="ARCHIVED"}/></div>}</div></header>
      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Score label="Initial score" score={risk.initialScore} level={risk.initialLevel}/><Score label="Residual score" score={risk.residualScore} level={risk.residualLevel}/><Info label="Owner" value={risk.owner?.name??"Unassigned"}/><Info label="Next review" value={date(risk.nextReviewDate)} warning={risk.nextReviewDate<new Date()&&!["CLOSED","ARCHIVED"].includes(risk.status)}/></section>
      <section className="grid gap-5 lg:grid-cols-2"><Card title="Risk description"><p>{risk.description}</p></Card><Card title="Existing controls"><p>{risk.existingControls}</p></Card><Card title="Further controls required"><p>{risk.furtherControls??"No further controls recorded."}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Dt label="Target date" value={date(risk.targetDate)}/><Dt label="Review frequency" value={risk.reviewFrequency}/></dl></Card><Card title="Closure control"><dl className="grid grid-cols-2 gap-3 text-sm"><Dt label="Closure date" value={date(risk.closureDate)}/><Dt label="Approved by" value={risk.closureApprovedBy?.name??"Not approved"}/></dl><p className="mt-4 text-sm">{risk.closureRationale??"No closure rationale recorded."}</p></Card></section>
      <Card title="Evidence"><div className="flex flex-wrap gap-2">{risk.evidenceLinks.length?risk.evidenceLinks.map(({evidence})=><Link key={evidence.id} href={`/evidence/${evidence.id}`} className="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-800">{evidence.title}</Link>):<p className="text-sm text-slate-500">No evidence linked.</p>}</div></Card>
      {canEdit&&!["CLOSED","ARCHIVED"].includes(risk.status)&&<Card title="Review risk"><p className="mb-4 text-sm text-slate-500">Recording a review updates the residual score and next review date.</p><RiskReviewForm id={id} defaults={{likelihood:risk.residualLikelihood,impact:risk.residualImpact,nextReviewDate:risk.nextReviewDate.toISOString().slice(0,10)}}/></Card>}
      <Card title="Review history">{risk.reviews.length?<ol className="space-y-4">{risk.reviews.map((review)=><li key={review.id} className="border-l-4 border-emerald-600 pl-4"><div className="flex flex-wrap items-center gap-2"><strong>{date(review.reviewDate)}</strong><span className={`rounded-full px-2 py-1 text-xs font-bold ${levelClasses(review.level)}`}>{review.score} · {review.level}</span></div><p className="mt-1 text-sm whitespace-pre-wrap">{review.notes}</p><p className="mt-1 text-xs text-slate-500">{review.reviewedBy.name} · Controls {review.controlsEffective?"effective":"need improvement"} · Next review {date(review.nextReviewDate)}</p></li>)}</ol>:<p className="text-sm text-slate-500">No formal reviews recorded yet.</p>}</Card>
      <p className="text-xs text-slate-500">Created by {risk.createdBy.name} on {date(risk.createdAt)}. Updates and reviews are recorded in the activity log.</p>
    </main>;
  } finally { await db.$disconnect(); }
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">{title}</h2><div className="mt-3 whitespace-pre-wrap text-sm leading-6">{children}</div></section>}
function Score({label,score,level}:{label:string;score:number;level:string}){return <div className={`rounded-2xl p-5 ${levelClasses(level)}`}><p className="text-xs font-bold uppercase tracking-wider">{label}</p><p className="mt-1 text-3xl font-black">{score}</p><p className="text-sm font-bold">{level}</p></div>}
function Info({label,value,warning=false}:{label:string;value:string;warning?:boolean}){return <div className={`rounded-2xl border p-5 ${warning?"border-red-200 bg-red-50 text-red-800":"border-slate-200 bg-white"}`}><p className="text-xs font-bold uppercase tracking-wider">{label}</p><p className="mt-2 font-bold">{value}{warning?" · Overdue":""}</p></div>}
function Dt({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd className="mt-1">{value}</dd></div>}
function date(value:Date|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value):"Not set"}
