import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth/dal";
import { carePlanReviewData, parseReviewActions } from "@/lib/care-plan-reviews";
import { clientName } from "@/lib/clients";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";
import { registerScopeWhere } from "@/lib/registers";

export default async function CarePlanReviewsPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const context = await requirePermission(PERMISSIONS.GOVERNANCE_VIEW);
  const query = await searchParams;
  const db = createDb();
  try {
    const definition = await db.registerDefinition.findFirst({ where: { key: "care-plan-reviews", isPublished: true, OR: [{ organisationId: context.organisation.id }, { organisationId: null }] } });
    if (!definition) notFound();
    const entries = await db.registerEntry.findMany({ where: { ...registerScopeWhere(context), definitionId: definition.id }, include: { client: true, location: { select: { id: true, name: true } }, owner: { select: { id: true, name: true } } }, orderBy: { eventDate: "desc" }, take: 1000 });
    const actionIds = [...new Set(entries.flatMap((entry)=>entry.linkedActionIds))];
    const centralActions = actionIds.length ? await db.action.findMany({ where: { id: { in: actionIds }, organisationId: context.organisation.id }, select: { id: true, status: true, priority: true } }) : [];
    const actionMap = new Map(centralActions.map((action)=>[action.id,action]));
    const now = new Date(); const month = now.toISOString().slice(0,7);
    const rows = entries.map((entry)=>{const data=carePlanReviewData(entry.data);const actions=parseReviewActions(data.reviewActions).map((item)=>item.actionId? actionMap.get(item.actionId):undefined).filter(Boolean);const due=dateValue(data.reviewDueDate);const completed=dateValue(data.reviewCompletedAt);return{entry,data,actions,due,completed,openActions:actions.filter((action)=>action&&!['COMPLETED','CANCELLED','ARCHIVED'].includes(action.status)).length};});
    const q=String(query.q??"").toLowerCase();const location=String(query.location??"");const risk=String(query.risk??"");const status=String(query.status??"");const reviewer=String(query.reviewer??"");const reviewType=String(query.reviewType??"");const authority=String(query.authority??"").toLowerCase();
    const filtered=rows.filter(({entry,data})=>(!q||[entry.reference,entry.title,entry.summary,entry.client?clientName(entry.client):""].some((value)=>value.toLowerCase().includes(q)))&&(!location||entry.locationId===location)&&(!risk||entry.riskLevel===risk)&&(!status||data.workflowStatus===status)&&(!reviewer||entry.ownerId===reviewer)&&(!reviewType||data.reviewType===reviewType)&&(!authority||String(data.localAuthorityName??data.otherCommissioner??"").toLowerCase().includes(authority)));
    const kpis=[
      ["Reviews due",rows.filter(({due})=>due&&due>=startOfToday(now)&&due<=addDays(now,30)).length,"Next 30 days"],
      ["Overdue reviews",rows.filter(({due,data})=>due&&due<startOfToday(now)&&data.workflowStatus!=="Approved / Closed").length,"Requires attention"],
      ["Completed this month",rows.filter(({completed})=>completed?.toISOString().startsWith(month)).length,"Signed or completed"],
      ["Awaiting actions",rows.filter(({data,openActions})=>data.workflowStatus==="Awaiting Actions"||openActions>0).length,"Open follow-up"],
      ["High / Critical open",rows.filter(({entry,data})=>["HIGH","CRITICAL"].includes(entry.riskLevel)&&data.workflowStatus!=="Approved / Closed").length,"Risk oversight"],
      ["Awaiting RM assurance",rows.filter(({data})=>!data.rmDecision||data.workflowStatus==="Awaiting RM Assurance").length,"Professional sign-off"],
    ] as const;
    const canEdit=hasPermission(context.permissions,PERMISSIONS.GOVERNANCE_EDIT);
    return <main className="space-y-6"><header><Link href="/registers" className="text-sm font-semibold text-emerald-700">← Registers</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-700">People’s rights, care and outcomes</p><h1 className="mt-1 text-3xl font-bold">CARE PLAN REVIEWS</h1><p className="mt-1 max-w-4xl text-slate-600">Review changing needs, outcomes, risks and care arrangements with accountable follow-up and management assurance.</p></div><div className="flex flex-wrap gap-2">{canEdit?<Link href="/registers/care-plan-reviews/new" className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white">+ New care-plan review</Link>:null}<Link href="/api/registers/care-plan-reviews/export" className="rounded-xl border bg-white px-4 py-3 text-sm font-semibold">Export</Link><Link href="/registers/care-plan-reviews/report" target="_blank" className="rounded-xl border bg-white px-4 py-3 text-sm font-semibold">Print / Reports</Link></div></div></header>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{kpis.map(([label,value,help])=><article key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-500">{help}</p></article>)}</section>
      <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-2 xl:grid-cols-4"><input name="q" defaultValue={String(query.q??"")} placeholder="Reference, person or care plan" className="rounded-xl border px-3 py-2.5 text-sm"/><select name="location" defaultValue={location} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">All service locations</option>{context.locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="authority" defaultValue={String(query.authority??"")} placeholder="Local authority / commissioner" className="rounded-xl border px-3 py-2.5 text-sm"/><select name="reviewer" defaultValue={reviewer} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">All reviewers</option>{[...new Map(entries.filter((e)=>e.owner).map((e)=>[e.owner!.id,e.owner!])).values()].map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="reviewType" defaultValue={reviewType} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">All review types</option>{[...new Set(rows.map(({data})=>String(data.reviewType??"")).filter(Boolean))].map((item)=><option key={item}>{item}</option>)}</select><select name="risk" defaultValue={risk} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">All risks</option>{["LOW","MEDIUM","HIGH","CRITICAL"].map((item)=><option key={item}>{item}</option>)}</select><select name="status" defaultValue={status} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">All statuses</option>{[...new Set(rows.map(({data})=>String(data.workflowStatus??"Draft")))].map((item)=><option key={item}>{item}</option>)}</select><button className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Apply filters</button></form>
      <div className="flex items-center justify-between"><p className="text-sm text-slate-600">{filtered.length} reviews</p><p className="text-xs text-slate-500">Organisation: {context.organisation.name}</p></div>
      {!filtered.length?<section className="rounded-2xl border border-dashed bg-white p-10 text-center"><h2 className="font-bold">No care-plan reviews match these filters</h2><p className="mt-1 text-sm text-slate-600">Adjust the filters or start a new review.</p></section>:<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-[1250px] w-full text-left text-sm"><thead className="bg-slate-900 text-white"><tr>{["Reference","Person","Care plan","Service","Review type","Review due","Completed","Current risk","Open actions","RM assurance","Status","Reviewer"].map((heading)=><th key={heading} className="p-3 text-xs uppercase tracking-wide">{heading}</th>)}</tr></thead><tbody>{filtered.map(({entry,data,due,completed,openActions})=><tr key={entry.id} className="border-t hover:bg-emerald-50/40"><td className="p-3"><Link href={`/registers/care-plan-reviews/${entry.id}`} className="font-mono text-xs font-bold text-emerald-800">{entry.reference}</Link></td><td className="p-3 font-semibold">{entry.client?clientName(entry.client):"Not linked"}</td><td className="p-3">{String(data.carePlanReference??entry.title)}</td><td className="p-3">{entry.location?.name??"Organisation"}</td><td className="p-3">{String(data.reviewType??"Not recorded")}</td><td className="p-3">{formatDate(due)}</td><td className="p-3">{formatDate(completed)}</td><td className="p-3"><Chip value={entry.riskLevel}/></td><td className="p-3"><span className={openActions?"font-bold text-red-700":"text-slate-500"}>{openActions}</span></td><td className="p-3">{String(data.rmDecision??"Outstanding")}</td><td className="p-3"><Chip value={String(data.workflowStatus??"Draft")}/></td><td className="p-3">{entry.owner?.name??"Unassigned"}</td></tr>)}</tbody></table></div>}
    </main>;
  } finally { await db.$disconnect(); }
}

function dateValue(value:unknown){const raw=String(value??"");if(!raw)return null;const date=new Date(raw);return Number.isNaN(date.getTime())?null:date;}
function formatDate(value:Date|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value):"Not set";}
function startOfToday(now:Date){return new Date(now.getFullYear(),now.getMonth(),now.getDate());}
function addDays(value:Date,days:number){const result=new Date(value);result.setDate(result.getDate()+days);return result;}
function Chip({value}:{value:string}){const danger=/CRITICAL|URGENT/.test(value),warning=/HIGH|AWAITING|RETURNED|ACTIONS/.test(value);return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${danger?"bg-red-700 text-white":warning?"bg-amber-100 text-amber-900":"bg-emerald-100 text-emerald-900"}`}>{value}</span>;}
