import { BarChart3, BriefcaseBusiness, CheckCircle2, FlaskConical, LockKeyhole, ShieldCheck, Target, UsersRound } from "lucide-react";
import {
  BenchmarkRequestForm,
  BenchmarkReviewForm,
  BenchmarkWithdrawForm,
  CommercialIntentForm,
  CreatePilotForm,
  MeasureForm,
  MeasureVerificationForm,
  PilotStatusForm,
  ServiceReadinessForm,
  StartServiceReadinessButton,
} from "@/components/launch-readiness-controls";
import { isExternalPayingIntent, label, measureResult, serviceReadinessSummary } from "@/lib/launch-readiness";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { PERMISSIONS } from "@/lib/permissions";

export default async function LaunchReadinessPage() {
  const context = await requirePermission(PERMISSIONS.ORGANISATION_MANAGE), db = createDb();
  try {
    const [pilots, serviceItems, benchmarkConsent, implementationPlan, evidenceRows] = await Promise.all([
      db.launchPilot.findMany({ where: { organisationId: context.organisation.id }, include: { owner: { select: { name: true } }, measures: { include: { recordedBy: { select: { name: true } }, verifiedBy: { select: { name: true } } }, orderBy: { createdAt: "asc" } }, commercialIntent: true }, orderBy: [{ cohort: "asc" }, { startDate: "desc" }] }),
      db.serviceReadinessItem.findMany({ where: { organisationId: context.organisation.id }, include: { completedBy: { select: { name: true } }, evidence: { select: { title: true } } }, orderBy: { key: "asc" } }),
      db.benchmarkConsent.findUnique({ where: { organisationId: context.organisation.id }, include: { requestedBy: { select: { name: true } }, reviewedBy: { select: { name: true } } } }),
      db.implementationPlan.findUnique({ where: { organisationId: context.organisation.id }, select: { stage: true, liveAt: true } }),
      db.evidence.findMany({ where: { organisationId: context.organisation.id, status: "ACTIVE", currentVersionId: { not: null } }, select: { id: true, title: true, currentVersionId: true, verifications: { select: { evidenceVersionId: true, outcome: true }, orderBy: { verifiedAt: "desc" }, take: 1 } }, orderBy: { title: "asc" }, take: 200 }),
    ]);
    const eligibleEvidence = evidenceRows.filter((item) => { const latest = item.verifications[0]; return latest?.evidenceVersionId === item.currentVersionId && ["VERIFIED", "VERIFIED_WITH_LIMITATIONS"].includes(latest.outcome); }).map(({ id, title }) => ({ id, title }));
    const service = serviceReadinessSummary(serviceItems), internalComplete = pilots.some((item) => item.cohort === "INTERNAL_DBAM" && item.status === "COMPLETE"), externalComplete = pilots.some((item) => item.cohort === "EXTERNAL_PROVIDER" && item.status === "COMPLETE"), verifiedExternalMeasures = pilots.flatMap((pilot) => pilot.measures.map((measure) => ({ pilot, measure }))).filter(({ pilot, measure }) => pilot.cohort === "EXTERNAL_PROVIDER" && pilot.status === "COMPLETE" && measure.status === "VERIFIED" && measure.outcomeValue !== null), verifiedBenefit = verifiedExternalMeasures.some(({ measure }) => measureResult(Number(measure.baselineValue), measure.outcomeValue === null ? null : Number(measure.outcomeValue), measure.direction).improved === true), externalPayingIntent = pilots.filter((pilot) => pilot.status === "COMPLETE" && pilot.commercialIntent && isExternalPayingIntent(pilot.cohort, pilot.commercialIntent.status)).length, securityEvidence = serviceItems.some((item) => item.key === "SECURITY_ASSURANCE_PACK" && item.status === "EVIDENCED" && Boolean(item.evidenceId));
    const gates = [
      { label: "DBAM pilot completed", met: internalComplete, detail: "Internal use proves the operating workflow before relying on external evidence." },
      { label: "External provider pilot completed", met: externalComplete, detail: "At least one external provider has completed a controlled pilot." },
      { label: "Verified measurable benefit", met: verifiedBenefit, detail: "An external baseline-to-outcome measure improved and was checked by a different manager." },
      { label: "Commercial service evidenced", met: service.ready, detail: "Every required support, security, privacy, continuity and exit control has evidence." },
      { label: "Security evidence current", met: securityEvidence, detail: "The security assurance pack is specifically evidenced." },
      { label: "External paying intent recorded", met: externalPayingIntent > 0, detail: "Budget, contract review or ready-to-buy intent is recorded for an external provider." },
    ], metGates = gates.filter((item) => item.met).length, launchValidated = metGates === gates.length;

    return <main className="space-y-8">
      <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-emerald-900 p-7 text-white shadow-xl">
        <div className="grid gap-7 xl:grid-cols-[1.35fr_.65fr] xl:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Phase 11 · validated launch</p><h1 className="mt-3 max-w-4xl text-3xl font-black md:text-4xl">Launch Assurance Centre</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-200">Turn beta activity into defensible evidence: who piloted, what changed, how the outcome was measured, who verified it, whether the service can be supported, and whether an external buyer has stated credible intent.</p><div className="mt-5 flex flex-wrap gap-2"><Pill icon={LockKeyhole} text="No invented validation" /><Pill icon={ShieldCheck} text="Independent outcome checks" /><Pill icon={UsersRound} text="External evidence separated" /></div></div><div className="rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur"><p className="text-xs font-black uppercase tracking-wide text-emerald-200">Validated-launch gate</p><p className="mt-2 text-4xl font-black">{metGates}/{gates.length}</p><p className="mt-1 text-sm text-slate-200">{launchValidated ? "All current evidence gates are met." : "Evidence remains incomplete. The product must not be described as externally validated yet."}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${Math.round((metGates / gates.length) * 100)}%` }} /></div></div></div>
      </header>

      <section className="space-y-4"><Heading title="Release evidence gate" subtitle="These gates are calculated only from controlled Phase 11 records. Missing evidence remains visibly incomplete." /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{gates.map((gate) => <article key={gate.label} className={`rounded-2xl border p-4 ${gate.met ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}><div className="flex items-center gap-2">{gate.met ? <CheckCircle2 className="text-emerald-700" size={20} /> : <Target className="text-amber-700" size={20} />}<h3 className="font-black">{gate.label}</h3></div><p className="mt-2 text-sm text-slate-600">{gate.detail}</p><p className={`mt-3 text-xs font-black uppercase tracking-wide ${gate.met ? "text-emerald-700" : "text-amber-800"}`}>{gate.met ? "Evidence gate met" : "Evidence required"}</p></article>)}</div><p className="text-xs text-slate-500">Implementation stage: {implementationPlan ? label(implementationPlan.stage) : "No implementation plan"}. Phase 10 go-live does not itself satisfy external validation.</p></section>

      <section className="space-y-4"><Heading title="Controlled pilot portfolio" subtitle="Record DBAM as the internal proving pilot and each external provider separately. Agree the outcome and calculation before the pilot begins." /><div className="rounded-3xl border bg-white p-5 shadow-sm"><CreatePilotForm /></div>{pilots.length ? <div className="space-y-5">{pilots.map((pilot) => <article key={pilot.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className={`border-b p-5 ${pilot.cohort === "EXTERNAL_PROVIDER" ? "bg-indigo-50" : "bg-slate-50"}`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wide text-indigo-700">{label(pilot.cohort)} · {pilot.locationCount} location{pilot.locationCount === 1 ? "" : "s"}</p><h3 className="mt-1 text-xl font-black">{pilot.name}</h3><p className="mt-1 text-sm text-slate-600">{pilot.serviceType} · {formatDate(pilot.startDate)} to {formatDate(pilot.targetEndDate)} · owner {pilot.owner.name}</p></div><Badge value={pilot.status} /></div><div className="mt-4"><PilotStatusForm id={pilot.id} status={pilot.status} /></div></div><div className="grid gap-4 p-5 lg:grid-cols-3"><Info title="Primary outcome" value={pilot.primaryOutcome} /><Info title="Pre-agreed success criteria" value={pilot.successCriteria} /><Info title="Risks and controls" value={pilot.riskControls} /></div><div className="space-y-4 border-t p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h4 className="font-black">Baseline and follow-up measures</h4><p className="text-sm text-slate-500">Outcome figures contribute to launch evidence only after independent verification.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{pilot.measures.length} measure{pilot.measures.length === 1 ? "" : "s"}</span></div>{pilot.measures.length ? <div className="grid gap-4 xl:grid-cols-2">{pilot.measures.map((measure) => <MeasureCard key={measure.id} measure={measure} currentUserId={context.user.id} />)}</div> : <Empty text="No baseline recorded for this pilot." />} {!['COMPLETE','WITHDRAWN'].includes(pilot.status) ? <MeasureForm pilotId={pilot.id} existingTypes={pilot.measures.map((item) => item.type)} /> : null}{pilot.cohort === "EXTERNAL_PROVIDER" ? <CommercialIntentForm pilotId={pilot.id} initial={pilot.commercialIntent ? { status: pilot.commercialIntent.status, buyerRole: pilot.commercialIntent.buyerRole, proposedPlan: pilot.commercialIntent.proposedPlan, licenceEstimate: pilot.commercialIntent.licenceEstimate, targetDecisionDate: pilot.commercialIntent.targetDecisionDate ? toDateInput(pilot.commercialIntent.targetDecisionDate) : "", evidenceNote: pilot.commercialIntent.evidenceNote } : undefined} /> : null}</div></article>)}</div> : <Empty text="No pilot evidence recorded. Create the internal DBAM pilot before claiming beta validation." />}</section>

      <section className="space-y-4"><Heading title="Commercial service operations" subtitle="A sellable product needs evidenced support, security, data protection, continuity, onboarding, exit and service-level operations—not only working features." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={BriefcaseBusiness} label="Required controls" value={service.required || "Not started"} /><Stat icon={CheckCircle2} label="Evidenced" value={service.evidenced || "No data"} good={service.ready} /><Stat icon={ShieldCheck} label="Blocked" value={service.blocked || "None recorded"} warn={service.blocked > 0} /><Stat icon={BarChart3} label="Readiness" value={service.required ? `${service.percentage}%` : "No data"} /></div>{serviceItems.length ? <div className="grid gap-4 xl:grid-cols-2">{serviceItems.map((item) => <article key={item.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${item.status === "BLOCKED" ? "border-red-300" : item.status === "EVIDENCED" ? "border-emerald-300" : ""}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-emerald-700">Commercial operating control</p><h3 className="mt-1 font-black">{item.title}</h3></div><Badge value={item.status} /></div><p className="mt-2 text-sm text-slate-600">{item.description}</p>{item.completedBy ? <p className="mt-2 text-xs text-slate-500">Evidenced by {item.completedBy.name} · {item.completedAt ? formatDate(item.completedAt) : "date unavailable"}{item.evidence ? ` · ${item.evidence.title}` : ""}</p> : null}<ServiceReadinessForm id={item.id} status={item.status} evidenceNote={item.evidenceNote} evidenceId={item.evidenceId} evidenceOptions={eligibleEvidence} /></article>)}</div> : <div className="rounded-2xl border border-indigo-200 bg-indigo-50 p-5"><h3 className="font-black text-indigo-950">Create the service-readiness register</h3><p className="mb-4 mt-1 text-sm text-indigo-900">Starts six controlled evidence checks. No item is pre-completed.</p><StartServiceReadinessButton /></div>}</section>

      <section className="space-y-4"><Heading title="Privacy-preserving benchmark boundary" subtitle="Benchmarking remains a later capability. Phase 11 records permission and safeguards only; it does not expose another provider’s data or produce a league table." /><article className="rounded-3xl border bg-white p-5 shadow-sm"><div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><div><div className="flex items-center gap-2"><FlaskConical className="text-indigo-700" size={22} /><h3 className="font-black">Controlled future participation</h3></div><ul className="mt-3 space-y-2 text-sm text-slate-600"><li>• Explicit organisation permission and independent review.</li><li>• Aggregated measures only; direct identifiers and free text excluded.</li><li>• A minimum cohort of ten organisations.</li><li>• No output until a DPIA, metric definitions and disclosure controls are approved.</li><li>• Withdrawal stops future aggregate processing.</li></ul></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Current permission</p><p className="mt-1 text-2xl font-black">{benchmarkConsent ? label(benchmarkConsent.status) : "Not considered"}</p>{benchmarkConsent ? <p className="mt-2 text-sm text-slate-600">Minimum cohort: {benchmarkConsent.minimumCohortSize} · {benchmarkConsent.permittedMetricKeys.length} permitted metric{benchmarkConsent.permittedMetricKeys.length === 1 ? "" : "s"}</p> : <p className="mt-2 text-sm text-slate-600">No benchmark processing is authorised.</p>}</div></div>{!benchmarkConsent || ["NOT_CONSIDERED", "DECLINED", "WITHDRAWN"].includes(benchmarkConsent.status) ? <div className="mt-5 border-t pt-5"><BenchmarkRequestForm /></div> : null}{benchmarkConsent?.status === "REQUESTED" ? benchmarkConsent.requestedById !== context.user.id ? <BenchmarkReviewForm /> : <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-900">Waiting for a different authorised manager to review this request.</p> : null}{benchmarkConsent && ["REQUESTED", "APPROVED"].includes(benchmarkConsent.status) ? <BenchmarkWithdrawForm /> : null}</article></section>

      <aside className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><strong>Evidence boundary:</strong> A completed checklist or pilot record does not prove regulatory compliance, customer satisfaction or commercial success. QCGMS may describe launch validation only when the calculated gates above are met and the underlying evidence remains current and reviewable.</aside>
    </main>;
  } finally { await db.$disconnect(); }
}

type MeasureCardProps = { measure: { id: string; label: string; unit: string; direction: "LOWER_IS_BETTER" | "HIGHER_IS_BETTER"; baselineValue: unknown; outcomeValue: unknown | null; sampleSize: number; measurementMethod: string; evidenceReference: string; status: string; recordedById: string; recordedBy: { name: string }; verifiedBy: { name: string } | null; verificationNote: string | null }; currentUserId: string };
function MeasureCard({ measure, currentUserId }: MeasureCardProps) {
  const baseline = Number(measure.baselineValue), outcome = measure.outcomeValue === null ? null : Number(measure.outcomeValue), result = measureResult(baseline, outcome, measure.direction);
  return <article className="rounded-2xl border bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><h5 className="font-black">{measure.label}</h5><p className="text-xs text-slate-500">Sample {measure.sampleSize} · evidence {measure.evidenceReference}</p></div><Badge value={measure.status} /></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Baseline" value={`${number(baseline)} ${measure.unit}`} /><Metric label="Follow-up" value={outcome === null ? "Not recorded" : `${number(outcome)} ${measure.unit}`} /><Metric label="Observed change" value={result.absoluteChange === null ? "Not available" : `${result.absoluteChange > 0 ? "+" : ""}${number(result.absoluteChange)} ${measure.unit}`} /></div><p className="mt-3 text-sm text-slate-600">{measure.measurementMethod}</p>{measure.status === "VERIFIED" ? <p className={`mt-3 rounded-xl p-3 text-sm font-bold ${result.improved ? "bg-emerald-100 text-emerald-900" : "bg-amber-100 text-amber-950"}`}>{result.improved ? "Verified improvement against the declared direction." : "Verified result, but no improvement against the declared direction."} Checked by {measure.verifiedBy?.name ?? "authorised reviewer"}.</p> : null}{measure.status === "REJECTED" ? <p className="mt-3 rounded-xl bg-red-100 p-3 text-sm font-bold text-red-900">Rejected: {measure.verificationNote}</p> : null}{measure.status === "OUTCOME_RECORDED" && measure.recordedById !== currentUserId ? <MeasureVerificationForm id={measure.id} /> : measure.status === "OUTCOME_RECORDED" ? <p className="mt-3 text-xs font-bold text-amber-800">Waiting for a different authorised manager to verify this measure.</p> : null}</article>;
}

function Pill({ icon: Icon, text }: { icon: typeof LockKeyhole; text: string }) { return <span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-xs font-black"><Icon size={15} />{text}</span>; }
function Heading({ title, subtitle }: { title: string; subtitle: string }) { return <div><h2 className="text-xl font-black">{title}</h2><p className="mt-1 max-w-5xl text-sm text-slate-600">{subtitle}</p></div>; }
function Badge({ value }: { value: string }) { const warn = ["BLOCKED", "REJECTED", "WITHDRAWN", "DECLINED"].includes(value), good = ["COMPLETE", "VERIFIED", "EVIDENCED", "APPROVED"].includes(value); return <span className={`h-fit rounded-full px-2.5 py-1 text-[10px] font-black ${warn ? "bg-red-100 text-red-800" : good ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-700"}`}>{label(value)}</span>; }
function Info({ title, value }: { title: string; value: string }) { return <div className="rounded-2xl border bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{title}</p><p className="mt-2 text-sm leading-6 text-slate-700">{value}</p></div>; }
function Metric({ label: metricLabel, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl bg-white p-3"><p className="text-[10px] font-black uppercase tracking-wide text-slate-500">{metricLabel}</p><p className="mt-1 break-words text-sm font-black">{value}</p></div>; }
function Stat({ icon: Icon, label: statLabel, value, good = false, warn = false }: { icon: typeof BriefcaseBusiness; label: string; value: string | number; good?: boolean; warn?: boolean }) { return <article className={`rounded-2xl border p-5 shadow-sm ${warn ? "border-red-200 bg-red-50" : good ? "border-emerald-200 bg-emerald-50" : "bg-white"}`}><Icon size={20} className={warn ? "text-red-700" : "text-emerald-700"} /><p className="mt-2 text-sm text-slate-500">{statLabel}</p><p className="mt-1 text-xl font-black">{value}</p></article>; }
function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed bg-slate-50 p-5 text-sm text-slate-500">{text}</p>; }
function formatDate(value: Date) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(value); }
function toDateInput(value: Date) { return value.toISOString().slice(0, 10); }
function number(value: number) { return new Intl.NumberFormat("en-GB", { maximumFractionDigits: 2 }).format(value); }
