import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { CQC_KEY_QUESTIONS, INSPECTION_DISCLAIMER, inspectionLabel, inspectionScopeWhere, readinessSummary } from "@/lib/inspection";
import { PERMISSIONS } from "@/lib/permissions";

export default async function InspectionPackPage() {
  const context = await requirePermission(PERMISSIONS.REPORTS_EXPORT), db = createDb();
  try {
    const requirements = await db.complianceRequirement.findMany({ where: inspectionScopeWhere(context), include: { owner: { select: { name: true } }, location: { select: { name: true } }, evidenceLinks: { include: { evidence: { select: { title: true } } } }, auditLinks: { include: { audit: { select: { title: true } } } }, registerLinks: { include: { registerEntry: { select: { reference: true, title: true } } } }, actionLinks: { include: { action: { select: { reference: true, title: true } } } } }, orderBy: [{ keyQuestion: "asc" }, { title: "asc" }] });
    const summary = readinessSummary(requirements.map((item) => item.evidenceStatus));
    return <main className="mx-auto max-w-6xl bg-white p-8 text-slate-900 print:p-0"><header className="flex items-start justify-between border-b-4 border-emerald-800 pb-5"><div><p className="font-bold uppercase tracking-widest text-emerald-800">{context.organisation.name}</p><h1 className="mt-2 text-4xl font-bold">Inspection Evidence Pack</h1><p className="mt-1 text-slate-600">Internal evidence-readiness index · {summary.coverage}% evidence coverage</p></div><p className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white print:hidden">Press Ctrl+P to save PDF</p></header><p className="mt-5 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm font-semibold">{INSPECTION_DISCLAIMER}</p>{CQC_KEY_QUESTIONS.map((question) => <section key={question} className="mt-8 break-before-auto"><h2 className="border-b-2 border-emerald-700 pb-2 text-2xl font-bold">{inspectionLabel(question)}</h2><div className="mt-4 space-y-4">{requirements.filter((item) => item.keyQuestion === question).map((item) => <article key={item.id} className="break-inside-avoid rounded-lg border p-4"><div className="flex justify-between gap-4"><h3 className="font-bold">{item.title}</h3><span className="text-xs font-bold">{inspectionLabel(item.evidenceStatus)}</span></div><p className="mt-1 text-xs text-slate-500">{item.qualityStatement} · Owner: {item.owner?.name ?? "Unassigned"} · {item.location?.name ?? "Organisation-wide"}</p><p className="mt-2 text-sm">{item.explanation}</p><div className="mt-3 grid grid-cols-2 gap-4 text-xs"><List title="Documents" values={item.evidenceLinks.map(({ evidence }) => evidence.title)} /><List title="Audits" values={item.auditLinks.map(({ audit }) => audit.title)} /><List title="Register entries" values={item.registerLinks.map(({ registerEntry }) => `${registerEntry.reference} - ${registerEntry.title}`)} /><List title="Actions" values={item.actionLinks.map(({ action }) => `${action.reference} - ${action.title}`)} /></div>{item.confidenceNote ? <p className="mt-3 text-xs"><strong>Confidence note:</strong> {item.confidenceNote}</p> : null}</article>)}</div></section>)}<footer className="mt-8 border-t pt-3 text-xs text-slate-500">Care Governance Hub · Internal governance record · Generated {new Date().toLocaleDateString("en-GB")}</footer></main>;
  } finally { await db.$disconnect(); }
}
function List({ title, values }: { title: string; values: string[] }) { return <div><strong>{title} ({values.length})</strong><ul className="mt-1 list-disc pl-4">{values.length ? values.map((value) => <li key={value}>{value}</li>) : <li>None linked</li>}</ul></div>; }
