import Link from "next/link";
import { OrganisationDocumentBrand } from "@/components/organisation-document-brand";
import { requirePermission } from "@/lib/auth/dal";
import { assuranceLabel } from "@/lib/inspection-assurance";
import { getInspectionRequirements } from "@/lib/inspection-data";
import { getCommissionerReadinessExceptions } from "@/lib/inspection-commissioner-exceptions";
import { CQC_KEY_QUESTIONS, INSPECTION_DISCLAIMER, inspectionLabel } from "@/lib/inspection";
import { PERMISSIONS } from "@/lib/permissions";

export default async function InspectionPackPage() {
  const context = await requirePermission(PERMISSIONS.REPORTS_EXPORT);
  const now = new Date();
  const [requirements, commissionerExceptions] = await Promise.all([getInspectionRequirements(context), getCommissionerReadinessExceptions(context, now)]);
  const sourceExceptions = commissionerExceptions.sort((a,b) => riskPriority(b.seriousRiskLevel) - riskPriority(a.seriousRiskLevel) || Number(b.overdue) - Number(a.overdue) || b.dataCheckCount - a.dataCheckCount || a.title.localeCompare(b.title));
  const attention = requirements.filter((item) => item.assurance.blockers.length || item.assurance.warnings.length || Boolean(item.reviewDate && item.reviewDate < now));
  return <main className="mx-auto max-w-6xl bg-white p-5 text-slate-900 sm:p-8 print:p-0">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b-4 border-emerald-800 pb-5">
      <div><OrganisationDocumentBrand name={context.organisation.name} hasLogo={Boolean(context.organisation.policyLogoStorageKey)}/><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Registered Manager Inspection Assurance Pack</h1><p className="mt-2 text-sm text-slate-600">Compiled {date(now)} · {context.allLocations ? "All authorised locations" : context.locations.map((item) => item.name).join(", ") || "No authorised locations"} · {requirements.length} sourced requirements</p></div>
      <p className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white print:hidden">Use your browser’s print command to save this pack as PDF</p>
    </header>
    <p className="mt-5 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm font-semibold">{INSPECTION_DISCLAIMER} This compilation shows recorded information and outstanding work. It is not a regulator judgement or a new RM assurance decision.</p>
    <section aria-labelledby="pack-attention" className="mt-6"><h2 id="pack-attention" className="text-2xl font-bold">What needs attention</h2><p className="mt-1 text-sm text-slate-600">Review each source and record any required judgement in the linked requirement record.</p>
      {attention.length ? <div className="mt-3 space-y-3">{attention.map((item) => <article key={item.id} className="break-inside-avoid rounded-lg border border-amber-300 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-bold">{item.title}</h3><p className="text-xs text-slate-600">{inspectionLabel(item.keyQuestion)} · RM decision: {assuranceLabel(item.managementDecision)}{item.reviewDate && item.reviewDate < now ? " · Review overdue" : ""}</p></div><Link href={`/inspection/${item.id}`} className="text-sm font-semibold text-emerald-800 underline">Open requirement and sources</Link></div><ul className="mt-2 list-disc pl-5 text-sm">{[...item.assurance.blockers, ...item.assurance.warnings].map((reason) => <li key={reason}>{reason}</li>)}</ul></article>)}</div> : <p className="mt-3 rounded-lg border p-4 text-sm">No calculated blockers, warnings or overdue reviews appear in the authorised scope. RM judgement remains separate.</p>}
    </section>
    <section aria-labelledby="pack-commissioner" className="mt-8"><h2 id="pack-commissioner" className="text-2xl font-bold">Serious risks, commissioner and return work</h2><p className="mt-1 text-sm text-slate-600">Current source statuses in the authorised scope. Risk levels are recorded assessments. Open work is not a submission, acceptance or compliance finding.</p>{sourceExceptions.length?<ul className="mt-3 space-y-2">{sourceExceptions.map((item)=><li key={`${item.source}:${item.id}`} className="break-inside-avoid rounded-lg border p-3"><strong>{item.title}</strong><p className="text-xs text-slate-600">{item.source}{item.seriousRiskLevel?` · ${item.seriousRiskLevel} residual risk`:""} · {item.location} · {assuranceLabel(item.status)}{item.overdue?" · Overdue":""}{item.dataCheckCount?` · ${item.dataCheckCount} data check${item.dataCheckCount===1?"":"s"} to resolve`:""}{item.dueAt?` · Due ${date(item.dueAt)}`:""}</p><Link href={item.href} className="text-sm font-semibold text-emerald-800 underline">Open source</Link></li>)}</ul>:<p className="mt-3 text-sm">No open High/Critical risk, commissioner or return exceptions appear in the authorised scope.</p>}</section>
    <section aria-labelledby="pack-records" className="mt-8"><h2 id="pack-records" className="text-2xl font-bold">Sourced requirement record</h2><p className="mt-1 text-sm text-slate-600">Calculated percentages below organise information only. Verification, suitability and sign-off remain governed decisions.</p>
      {CQC_KEY_QUESTIONS.map((question) => <section key={question} className="mt-7"><h3 className="border-b-2 border-emerald-700 pb-2 text-xl font-bold">{inspectionLabel(question)}</h3><div className="mt-4 space-y-4">{requirements.filter((item) => item.keyQuestion === question).map((item) => <article key={item.id} className="break-inside-avoid rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-4"><div><h4 className="font-bold">{item.title}</h4><p className="text-xs text-slate-500">{item.qualityStatement} · {item.regulations.join(" · ")}</p></div><div className="text-right"><strong>{item.assurance.score}% calculated</strong><p className="text-xs font-bold">{assuranceLabel(item.assurance.status)}</p></div></div><p className="mt-2 text-sm">{item.explanation}</p><div className="mt-3 grid gap-3 text-xs md:grid-cols-3"><Fact title="Owner / review" value={`${item.owner?.name ?? "Unassigned"} · ${item.reviewDate ? date(item.reviewDate) : "not set"}`}/><Fact title="RM decision" value={`${assuranceLabel(item.managementDecision)}${item.signedOffAt ? ` · signed ${date(item.signedOffAt)}` : " · not signed"}`}/><Fact title="Evidence categories" value={`${item.assurance.categoryCoverage}% (${item.coveredCategories.map(assuranceLabel).join(", ") || "none"})`}/></div><div className="mt-3 grid gap-3 text-xs md:grid-cols-3"><Fact title="Strengths" value={item.strengths ?? "Not recorded"}/><Fact title="Improvement" value={item.areasForImprovement ?? "Not recorded"}/><Fact title="Impact on people" value={item.impactOnPeople ?? "Not recorded"}/></div>{item.assurance.blockers.length ? <p className="mt-3 rounded bg-red-50 p-2 text-xs"><strong>Blockers:</strong> {item.assurance.blockers.join("; ")}</p> : null}<div className="mt-3"><strong className="text-xs">Connected records ({item.connectedRecords.length})</strong><ul className="mt-1 grid list-disc gap-x-6 pl-4 text-xs md:grid-cols-2">{item.connectedRecords.length ? item.connectedRecords.map((record, index) => <li key={`${record.id}:${index}`}><Link href={record.href} className="text-emerald-800 underline">{record.type}: {record.label}</Link> [{assuranceLabel(record.status)}]</li>) : <li>None connected</li>}</ul></div></article>)}</div></section>)}
    </section>
    <footer className="mt-8 border-t pt-3 text-xs text-slate-500">QCGMS · Internal governance record · Generated {date(now)}</footer>
  </main>;
}
function Fact({ title, value }: { title: string; value: string }) { return <div className="rounded bg-slate-50 p-2"><strong>{title}</strong><p className="mt-1 whitespace-pre-wrap">{value}</p></div>; }
function date(value: Date) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(value); }
function riskPriority(level: "HIGH" | "CRITICAL" | null) { return level === "CRITICAL" ? 2 : level === "HIGH" ? 1 : 0; }
