import { NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { PERMISSIONS, ROLE_KEYS } from "@/lib/permissions";

const rule=z.object({priority:z.enum(["LOW","MEDIUM","HIGH","CRITICAL"]),verificationRequired:z.boolean(),effectivenessRequired:z.boolean(),separateVerifierRequired:z.boolean(),separateCloserRequired:z.boolean(),rootCauseRequired:z.boolean(),closureRoleKeys:z.array(z.string()).min(1)});
const schema=z.object({effectiveFrom:z.string().min(10),changeRationale:z.string().trim().min(12).max(1000),rules:z.array(rule).length(4)});

export async function POST(request:Request){const context=await requirePermission(PERMISSIONS.ORGANISATION_MANAGE),db=createDb();try{const input=schema.parse(await request.json()),priorities=new Set(input.rules.map(item=>item.priority));if(priorities.size!==4)throw new Error("Configure each Audit Action priority once.");const allowed=new Set(Object.values(ROLE_KEYS));if(input.rules.some(item=>item.closureRoleKeys.some(key=>!allowed.has(key as never))))throw new Error("Choose valid provider roles.");const latest=await db.actionAssurancePolicyVersion.aggregate({where:{organisationId:context.organisation.id},_max:{versionNumber:true}}),versionNumber=(latest._max.versionNumber??0)+1,effectiveFrom=new Date(`${input.effectiveFrom}T00:00:00.000Z`);const created=await db.$transaction(async tx=>{const version=await tx.actionAssurancePolicyVersion.create({data:{organisationId:context.organisation.id,versionNumber,effectiveFrom,changeRationale:input.changeRationale,createdById:context.user.id,rules:{create:input.rules.map(item=>({organisationId:context.organisation.id,sourceType:"AUDIT" as const,...item}))}}});await tx.activityLog.create({data:{organisationId:context.organisation.id,userId:context.user.id,action:"CREATE",recordType:"ActionAssurancePolicyVersion",recordId:version.id,summary:`Created Audit Action Assurance Policy v${versionNumber} draft`,afterValue:{effectiveFrom,changeRationale:input.changeRationale,rules:input.rules}}});return version});return NextResponse.json({id:created.id},{status:201})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?error.issues[0]?.message:error instanceof Error?error.message:"Could not create Action Assurance policy."},{status:400})}finally{await db.$disconnect()}}
