CREATE TYPE "TemplateStatus" AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');
CREATE TABLE "Template" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),"organisationId" UUID,"title" TEXT NOT NULL,"category" TEXT NOT NULL,
  "description" TEXT NOT NULL,"version" TEXT NOT NULL,"reviewDate" TIMESTAMP(3),"authorId" UUID,"tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
  "status" "TemplateStatus" NOT NULL DEFAULT 'PUBLISHED',"fileName" TEXT NOT NULL,"contentType" TEXT NOT NULL,
  "sizeBytes" INTEGER NOT NULL,"checksum" TEXT NOT NULL,"storageKey" TEXT,"bodyText" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Template_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Template_storageKey_key" ON "Template"("storageKey");
CREATE INDEX "Template_organisationId_category_status_idx" ON "Template"("organisationId","category","status");
CREATE INDEX "Template_title_idx" ON "Template"("title");
ALTER TABLE "Template" ADD CONSTRAINT "Template_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Template" ADD CONSTRAINT "Template_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

INSERT INTO "Template" ("title","category","description","version","tags","status","fileName","contentType","sizeBytes","checksum","bodyText","updatedAt")
SELECT v.title,v.category,v.description,'1.0',v.tags,'PUBLISHED',v.filename,'text/plain',length(v.body),md5(v.body),v.body,CURRENT_TIMESTAMP
FROM (VALUES
('Safeguarding Policy Template','Policies','Structure for an adult safeguarding policy.',ARRAY['safeguarding','policy'],'safeguarding-policy-template.txt','SAFEGUARDING POLICY TEMPLATE\n\nPurpose\nScope\nDefinitions\nRecognising abuse\nReporting and escalation\nLocal authority referrals\nRecord keeping\nTraining\nReview and approval'),
('Quality Audit Form','Audit forms','General care-quality audit structure.',ARRAY['audit','quality'],'quality-audit-form.txt','QUALITY AUDIT FORM\n\nAudit scope:\nLocation:\nAuditor:\nDate:\n\n1. Leadership and governance\n2. Care records\n3. Medicines\n4. Workforce\n5. People''s experience\n\nFindings:\nActions:\nSign-off:'),
('Operational Risk Assessment','Risk assessments','Five-by-five operational risk assessment template.',ARRAY['risk','assessment'],'operational-risk-assessment.txt','RISK ASSESSMENT\n\nHazard or risk:\nPeople affected:\nExisting controls:\nLikelihood (1-5):\nImpact (1-5):\nInitial score:\nFurther controls:\nOwner:\nTarget date:\nResidual score:\nReview date:'),
('Governance Meeting Agenda','Governance meetings','Structured monthly governance meeting agenda.',ARRAY['governance','meeting'],'governance-meeting-agenda.txt','GOVERNANCE MEETING AGENDA\n\nDate and time:\nChair:\nAttendees:\nApologies:\n\n1. Previous actions\n2. KPI review\n3. Audit findings\n4. Complaints and incidents\n5. Safeguarding\n6. Workforce\n7. Risks\n8. Quality improvement\n9. Decisions\n10. Any other business'),
('Quality Improvement Action Plan','Action plans','Accountable action-plan template.',ARRAY['action','improvement'],'quality-improvement-action-plan.txt','QUALITY IMPROVEMENT ACTION PLAN\n\nIssue:\nSource:\nRequired outcome:\nActions:\nOwner:\nPriority:\nDue date:\nEvidence required:\nProgress updates:\nVerification:\nClosure note:'),
('Incident Investigation Form','Investigation forms','Structured investigation and learning review.',ARRAY['incident','investigation'],'incident-investigation-form.txt','INCIDENT INVESTIGATION\n\nIncident reference:\nDate and location:\nInvestigator:\nSummary:\nImmediate response:\nPeople involved:\nEvidence reviewed:\nContributory factors:\nRoot cause:\nDuty of Candour:\nLessons learned:\nActions:\nApproval:'),
('Complaint Acknowledgement and Investigation','Complaints','Complaint handling record and response structure.',ARRAY['complaint','response'],'complaint-investigation-template.txt','COMPLAINT RECORD\n\nReference:\nReceived from:\nDate received:\nAcknowledgement date:\nIssues raised:\nConsent and confidentiality:\nInvestigation steps:\nFindings:\nOutcome:\nResponse date:\nLearning and actions:'),
('Incident Management Checklist','Incident management','Immediate response and notification checklist.',ARRAY['incident','checklist'],'incident-management-checklist.txt','INCIDENT MANAGEMENT CHECKLIST\n\n[ ] Make the situation safe\n[ ] Provide immediate care\n[ ] Inform manager\n[ ] Record facts\n[ ] Preserve evidence\n[ ] Notify relevant people\n[ ] Consider Duty of Candour\n[ ] Consider external notification\n[ ] Start investigation\n[ ] Record learning and actions'),
('Safeguarding Referral Checklist','Safeguarding','Safeguarding response and referral checklist.',ARRAY['safeguarding','referral'],'safeguarding-referral-checklist.txt','SAFEGUARDING REFERRAL CHECKLIST\n\n[ ] Ensure immediate safety\n[ ] Record the concern and source\n[ ] Inform safeguarding lead\n[ ] Preserve evidence\n[ ] Contact local authority where required\n[ ] Consider police or emergency services\n[ ] Notify regulator where required\n[ ] Support the person\n[ ] Record decisions and outcome'),
('Safer Recruitment Checklist','Recruitment','Pre-employment compliance checklist.',ARRAY['recruitment','workforce'],'safer-recruitment-checklist.txt','SAFER RECRUITMENT CHECKLIST\n\n[ ] Application and employment history\n[ ] Interview and identity checks\n[ ] Right to work\n[ ] DBS check\n[ ] References verified\n[ ] Qualifications verified\n[ ] Health declaration\n[ ] Risk assessment for any gaps\n[ ] Contract and induction\n[ ] File audit complete'),
('Supervision Record','Supervision','Structured staff supervision record.',ARRAY['supervision','workforce'],'supervision-record.txt','SUPERVISION RECORD\n\nEmployee:\nSupervisor:\nDate:\nWellbeing:\nPerformance and conduct:\nPeople supported:\nSafeguarding:\nTraining and competence:\nWorkload:\nFeedback:\nAgreed actions:\nNext supervision:'),
('Competency Assessment','Competency assessments','Observed-practice competency assessment.',ARRAY['competency','assessment'],'competency-assessment.txt','COMPETENCY ASSESSMENT\n\nEmployee:\nAssessor:\nCompetency:\nDate:\nKnowledge demonstrated:\nPractice observed:\nSafety steps followed:\nCommunication:\nOutcome:\nDevelopment required:\nReassessment date:\nSign-off:'),
('Quality Improvement Plan','Quality improvement','Plan-do-study-act improvement template.',ARRAY['quality','improvement'],'quality-improvement-plan.txt','QUALITY IMPROVEMENT PLAN\n\nImprovement aim:\nBaseline:\nWhy this matters:\nMeasures:\nPLAN:\nDO:\nSTUDY:\nACT:\nOwner:\nTimescale:\nEvidence:\nReview date:'),
('Business Continuity Test Record','Business continuity','Scenario test and lessons-learned record.',ARRAY['business continuity','test'],'business-continuity-test-record.txt','BUSINESS CONTINUITY TEST\n\nScenario:\nTest date:\nParticipants:\nCritical services tested:\nCommunications tested:\nSystems and records tested:\nWhat worked:\nGaps identified:\nActions:\nPlan update required:\nApproval:'),
('Monthly Governance Report','Reports','Monthly governance reporting structure.',ARRAY['report','governance'],'monthly-governance-report.txt','MONTHLY GOVERNANCE REPORT\n\nReporting period:\nExecutive summary:\nKPI overview:\nAudit assurance:\nComplaints and incidents:\nSafeguarding:\nWorkforce:\nRisks:\nActions:\nPolicies and evidence:\nQuality improvement:\nDecisions required:'),
('Duty of Candour Letter','Letters','Reference structure for a Duty of Candour communication.',ARRAY['letter','duty of candour'],'duty-of-candour-letter.txt','DUTY OF CANDOUR LETTER TEMPLATE\n\nDate:\nRecipient:\nIncident reference:\n\nDear [name],\n\nWe are writing regarding [factual description].\nWe are sorry that [apology].\nWe have taken the following immediate action: [actions].\nWe will investigate and keep you informed.\nContact: [details]\n\nYours sincerely,\n[authorised person]'),
('Inspection Readiness Checklist','Checklists','Internal evidence-readiness review checklist.',ARRAY['inspection','checklist'],'inspection-readiness-checklist.txt','INSPECTION READINESS CHECKLIST\n\n[ ] Registration details current\n[ ] Policies reviewed\n[ ] Training and competency evidence current\n[ ] Audits complete and actions tracked\n[ ] Complaints, incidents and safeguarding reviewed\n[ ] Risks reviewed\n[ ] Governance minutes approved\n[ ] KPI evidence current\n[ ] Evidence mapped to five key questions\n[ ] Staff understand inspection arrangements')
) AS v(title,category,description,tags,filename,body);
