import Link from "next/link";
import { notFound } from "next/navigation";
import { AcknowledgeCarePlan, PublishCarePlan } from "@/components/care-plan-controls";
import { CarePlanView } from "@/components/care-plan-view";
import { requirePermission } from "@/lib/auth/dal";
import { loadCarePlan } from "@/lib/care-plan-data";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS, ROLE_KEYS } from "@/lib/permissions";

export default async function CarePlanPage({params}:{params:Promise<{id:string}>}){const context=await requirePermission(PERMISSIONS.GOVERNANCE_VIEW),{id}=await params,db=createDb();try{const x=await loadCarePlan(db,context,id);if(!x)notFound();const canEdit=hasPermission(context.permissions,PERMISSIONS.GOVERNANCE_EDIT),canPublish=context.role.key===ROLE_KEYS.REGISTERED_MANAGER,canViewRestricted=new Set<string>([ROLE_KEYS.OWNER,ROLE_KEYS.REGISTERED_MANAGER,ROLE_KEYS.QUALITY_MANAGER]).has(context.role.key),approval=section(x.proposed?.snapshot,"approval");return <main className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3 print:hidden"><Link href="/care-plans" className="text-sm font-semibold text-emerald-700">← Care Plans</Link><div className="flex flex-wrap gap-2"><Link href={`/care-plans/${id}/quick-guide`} target="_blank" className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">Staff quick guide</Link><Link href={`/care-plans/${id}/report`} target="_blank" className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">Print / PDF</Link>{canEdit?<><Link href={`/registers/care-plan-reviews/new?carePlanId=${id}&clientId=${x.plan.clientId}`} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">Start review</Link><Link href={`/care-plans/${id}/edit`} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Quick update</Link></>:null}</div></div>{x.proposed&&x.proposed.id!==x.current?.id?<section className="rounded-2xl border border-amber-300 bg-amber-50 p-5 print:hidden"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-amber-800">Proposed version awaiting approval</p><h2 className="text-lg font-bold">Version {x.proposed.versionNumber} contains {x.proposed.changes.length} controlled section changes</h2><Link href={`/care-plans/${id}/compare?versionId=${x.proposed.id}`} className="text-sm font-bold text-amber-900 underline">Review side-by-side change summary</Link></div>{canPublish?<PublishCarePlan id={id} versionId={x.proposed.id} defaultDecision={String(approval.decision??"")}/>:<p className="text-sm font-semibold">Registered Manager publication required</p>}</div></section>:null}<CarePlanView plan={x.plan} version={x.display} person={x.person} organisation={{name:context.organisation.name,hasLogo:Boolean(context.organisation.policyLogoStorageKey)}} location={x.location} coordinator={x.coordinator} manager={x.manager} actions={x.actions} evidence={x.evidence} acknowledgements={x.acknowledgements} canViewRestricted={canViewRestricted}/>{x.current&&x.plan.staffAcknowledgementRequired?<AcknowledgeCarePlan id={id} staff={x.staff}/>:null}</main>}finally{await db.$disconnect()}}
function section(value:unknown,key:string){if(!value||typeof value!=="object"||Array.isArray(value))return{};const nested=(value as Record<string,unknown>)[key];return nested&&typeof nested==="object"&&!Array.isArray(nested)?nested as Record<string,unknown>:{};}
