import { NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { evidenceFamily, evidenceType } from "@/lib/evidence-taxonomy";
import { PERMISSIONS } from "@/lib/permissions";
import { PROVIDER_CONTROL_FAMILIES, providerControlScopeAllowed } from "@/lib/provider-controls";

const intentSchema=z.object({intent:z.enum(["ACTIVATE","CREATE_NEW_VERSION","RETIRE"]),changeRationale:z.string().trim().min(8).max(2000).optional()});
const editSchema=z.object({title:z.string().trim().min(3).max(180),description:z.string().trim().min(10).max(3000),family:z.enum(PROVIDER_CONTROL_FAMILIES),applicableRiskCategoryKeys:z.array(z.string()).default([]),scopeType:z.enum(["ORGANISATION","SELECTED_LOCATIONS"]),locationIds:z.array(z.string().uuid()).default([]),accountableOwnerId:z.string().uuid().nullable().optional(),expectedEvidenceFamilyKeys:z.array(z.string()).default([]),expectedEvidenceTypeKeys:z.array(z.string()).default([]),expectedEffectivenessMethod:z.string().trim().max(2000).nullable().optional(),effectiveFrom:z.string().date().nullable().optional(),reviewDueAt:z.string().date().nullable().optional(),changeRationale:z.string().trim().min(8).max(2000)});

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const context=await requirePermission(PERMISSIONS.CONTROLS_MANAGE),{id}=await params,db=createDb();try{const input=editSchema.parse(await request.json()),control=await db.providerControl.findFirst({where:{id,organisationId:context.organisation.id},include:{versions:{include:{locations:true},orderBy:{versionNumber:"desc"},take:1}}});if(!control)return NextResponse.json({error:"Provider Control not found."},{status:404});const draft=control.versions[0];if(!draft||draft.status!=="DRAFT")throw new Error("Only the latest Draft Provider Control can be edited.");if(!providerControlScopeAllowed(context,draft.scopeType,draft.locations.map(item=>item.locationId))||!providerControlScopeAllowed(context,input.scopeType,input.locationIds))throw new Error("This Provider Control scope is outside your authorised locations.");for(const key of input.expectedEvidenceFamilyKeys)if(!evidenceFamily(key))throw new Error("Choose a recognised Evidence family.");for(const compound of input.expectedEvidenceTypeKeys){const[familyKey,typeKey]=compound.split(":");if(!evidenceType(familyKey,typeKey))throw new Error("Choose a recognised contextual Evidence type.");}if(input.accountableOwnerId&&!(await db.organisationMembership.findFirst({where:{organisationId:context.organisation.id,userId:input.accountableOwnerId,status:"ACTIVE"}})))throw new Error("Choose an active Control owner.");await db.$transaction(async tx=>{await tx.providerControlVersion.update({where:{id:draft.id},data:{title:input.title,description:input.description,family:input.family,applicableRiskCategoryKeys:input.applicableRiskCategoryKeys,scopeType:input.scopeType,accountableOwnerId:input.accountableOwnerId||null,expectedEvidenceFamilyKeys:input.expectedEvidenceFamilyKeys,expectedEvidenceTypeKeys:input.expectedEvidenceTypeKeys,expectedEffectivenessMethod:input.expectedEffectivenessMethod||null,effectiveFrom:input.effectiveFrom?new Date(`${input.effectiveFrom}T00:00:00.000Z`):null,reviewDueAt:input.reviewDueAt?new Date(`${input.reviewDueAt}T00:00:00.000Z`):null,changeRationale:input.changeRationale,locations:{deleteMany:{},create:input.scopeType==="SELECTED_LOCATIONS"?input.locationIds.map(locationId=>({locationId})):[]}}});await tx.activityLog.create({data:{organisationId:context.organisation.id,userId:context.user.id,action:"UPDATE",recordType:"ProviderControlVersion",recordId:draft.id,summary:`Edited ${control.stableKey} v${draft.versionNumber} Draft`,beforeValue:{title:draft.title,scopeType:draft.scopeType,locationIds:draft.locations.map(item=>item.locationId)},afterValue:{title:input.title,scopeType:input.scopeType,locationIds:input.locationIds,actualEditorId:context.user.id}}})});return NextResponse.json({ok:true})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not edit Provider Control Draft."},{status:400})}finally{await db.$disconnect()}}

export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){
 const context=await requirePermission(PERMISSIONS.CONTROLS_MANAGE),{id}=await params,db=createDb();
 try{
  const input=intentSchema.parse(await request.json());const control=await db.providerControl.findFirst({where:{id,organisationId:context.organisation.id},include:{versions:{include:{locations:true},orderBy:{versionNumber:"desc"}}}});if(!control)return NextResponse.json({error:"Provider Control not found."},{status:404});
  const latest=control.versions[0];if(!latest)throw new Error("Provider Control version not found.");
  if(!providerControlScopeAllowed(context,latest.scopeType,latest.locations.map(item=>item.locationId)))throw new Error("This Provider Control is outside your authorised location scope.");
  if(input.intent==="ACTIVATE"){
   if(latest.status!=="DRAFT")throw new Error("Only the latest Draft can be activated.");if(!latest.effectiveFrom)throw new Error("Set an effective date before activation.");
   await db.$transaction(async tx=>{if(control.currentVersionId){await tx.providerControlVersion.update({where:{id:control.currentVersionId},data:{status:"SUPERSEDED"}});await tx.riskControlApplication.updateMany({where:{controlVersionId:control.currentVersionId,status:"APPLIED"},data:{status:"REVIEW_REQUIRED",reviewRequiredAt:new Date(),reviewReason:`Provider Control ${control.stableKey} was superseded by v${latest.versionNumber}.`}})}await tx.providerControlVersion.update({where:{id:latest.id},data:{status:"EFFECTIVE",approvedById:context.user.id,approvedAt:new Date()}});await tx.providerControl.update({where:{id},data:{currentVersionId:latest.id}});await tx.activityLog.create({data:{organisationId:context.organisation.id,userId:context.user.id,action:"APPROVAL",recordType:"ProviderControlVersion",recordId:latest.id,summary:`Activated ${control.stableKey} v${latest.versionNumber}`,afterValue:{actualApproverId:context.user.id}}})});
  }else if(input.intent==="CREATE_NEW_VERSION"){
   if(!["EFFECTIVE","SUPERSEDED"].includes(latest.status))throw new Error("Activate the current Draft before creating another version.");if(!input.changeRationale)throw new Error("Explain why a new Provider Control version is required.");const versionNumber=latest.versionNumber+1;
   await db.$transaction(async tx=>{const draft=await tx.providerControlVersion.create({data:{organisationId:context.organisation.id,controlId:id,versionNumber,status:"DRAFT",title:latest.title,description:latest.description,family:latest.family,applicableRiskCategoryKeys:latest.applicableRiskCategoryKeys,scopeType:latest.scopeType,accountableOwnerId:latest.accountableOwnerId,expectedEvidenceFamilyKeys:latest.expectedEvidenceFamilyKeys,expectedEvidenceTypeKeys:latest.expectedEvidenceTypeKeys,expectedEffectivenessMethod:latest.expectedEffectivenessMethod,effectiveFrom:null,reviewDueAt:latest.reviewDueAt,changeRationale:input.changeRationale!,createdById:context.user.id,locations:{create:latest.locations.map(item=>({locationId:item.locationId}))}}});await tx.activityLog.create({data:{organisationId:context.organisation.id,userId:context.user.id,action:"CREATE",recordType:"ProviderControlVersion",recordId:draft.id,summary:`Created ${control.stableKey} v${versionNumber} Draft`,afterValue:{basedOnVersion:latest.versionNumber}}})});
  }else{
   const active=control.versions.find(version=>version.id===control.currentVersionId);if(!active)throw new Error("No effective Provider Control version is available to retire.");
   await db.$transaction(async tx=>{await tx.providerControlVersion.update({where:{id:active.id},data:{status:"RETIRED"}});await tx.providerControl.update({where:{id},data:{currentVersionId:null}});await tx.riskControlApplication.updateMany({where:{controlVersionId:active.id,status:"APPLIED"},data:{status:"REVIEW_REQUIRED",reviewRequiredAt:new Date(),reviewReason:`Provider Control ${control.stableKey} was retired.`}});await tx.activityLog.create({data:{organisationId:context.organisation.id,userId:context.user.id,action:"ARCHIVE",recordType:"ProviderControlVersion",recordId:active.id,summary:`Retired ${control.stableKey} v${active.versionNumber}`}})});
  }
  return NextResponse.json({ok:true});
 }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not update Provider Control."},{status:400})}finally{await db.$disconnect()}
}
