import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { EvidenceActions, EvidenceVersionUpload } from "@/components/evidence-actions";
import { requireAuthorisedContext } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { evidenceDisplayStatus, evidenceScopeWhere } from "@/lib/evidence";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";
import { registerScopeWhere } from "@/lib/registers";
import { auditScopeWhere } from "@/lib/audits";
import { riskScopeWhere } from "@/lib/risks";
import { EvidenceVerificationForm } from "@/components/evidence-assurance-controls";
import { evidenceAssuranceLabel, evidenceAssuranceState } from "@/lib/evidence-assurance";

export default async function EvidenceDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const context = await requireAuthorisedContext();
  const canViewAll = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_VIEW);
  const canUpload = hasPermission(context.permissions, PERMISSIONS.EVIDENCE_UPLOAD);
  if (!canViewAll && !canUpload) redirect("/forbidden");
  const { id } = await params; const db = createDb();
  try {
    const item = await db.evidence.findFirst({
      where: { id, AND: [evidenceScopeWhere(context), ...(!canViewAll ? [{ OR: [{ ownerId: context.user.id }, { uploadedById: context.user.id }] }] : [])] },
      include: { owner:{select:{name:true}},uploadedBy:{select:{name:true}},location:{select:{name:true}},currentVersion:true,versions:{include:{uploadedBy:{select:{name:true}}},orderBy:{createdAt:"desc"}},verifications:{include:{verifiedBy:{select:{name:true}}},orderBy:{verifiedAt:"desc"}} },
    });
    if (!item) notFound();
    const relatedPolicyId = item.generatedPolicyId ?? (item.relatedModule === "Policy" ? item.relatedRecordId : null);
    const relatedPolicy = relatedPolicyId ? await db.policy.findFirst({ where: { id:relatedPolicyId,organisationId:context.organisation.id }, select:{id:true,title:true} }) : null;
    const relatedRegister = item.relatedModule === "RegisterEntry" && item.relatedRecordId ? await db.registerEntry.findFirst({ where: { id:item.relatedRecordId,...registerScopeWhere(context) }, select:{id:true,reference:true,title:true,definition:{select:{key:true,name:true}}} }) : null;
    const relatedAudit = item.relatedModule === "Audit" && item.relatedRecordId ? await db.audit.findFirst({where:{id:item.relatedRecordId,...auditScopeWhere(context)},select:{id:true,title:true,status:true,template:{select:{name:true}}}}):null;
    const relatedRisk=item.relatedModule==="Risk"&&item.relatedRecordId?await db.risk.findFirst({where:{id:item.relatedRecordId,...riskScopeWhere(context)},select:{id:true,reference:true,title:true}}):null;
    const generatedPolicy = Boolean(item.generatedPolicyId);
    const systemRecord = generatedPolicy || ["RegisterEntry","Audit","Risk"].includes(item.relatedModule??"");
    const canEdit = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_EDIT);
    const canReplace = !systemRecord && canUpload && (canEdit || item.ownerId === context.user.id || item.uploadedById === context.user.id);
    const fileUrl = item.currentVersion ? `/api/evidence/${id}/versions/${item.currentVersion.id}/file` : null;
    const previewable = item.currentVersion && (item.currentVersion.contentType === "application/pdf" || item.currentVersion.contentType.startsWith("image/"));
    const assuranceState=evidenceAssuranceState({status:item.status,reviewExpiryDate:item.reviewExpiryDate,updatedAt:item.updatedAt,currentVersionId:item.currentVersionId,verification:item.verifications[0]});
    return <main className="space-y-6">
      <div><Link href="/evidence" className="text-sm font-semibold text-emerald-700">← Evidence Library</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">{item.category} · {item.evidenceType}</p><h1 className="text-3xl font-bold">{item.title}</h1><p className="mt-1 text-slate-600">{generatedPolicy ? "Opens the current policy · no separate file" : systemRecord ? "Linked to its original record" : `Version ${item.currentVersion?.versionNumber ?? "—"}`} · {evidenceDisplayStatus(item.status,item.reviewExpiryDate)}</p></div>{canEdit && !systemRecord && <div className="flex gap-2"><Link href={`/evidence/${id}/edit`} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Edit details</Link><EvidenceActions id={id} archived={item.status === "ARCHIVED"} /></div>}</div></div>
      <section className="grid gap-4 lg:grid-cols-[1.25fr_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">{systemRecord ? "Original record" : "Current file"}</h2>{systemRecord ? <><p className="mt-3 text-sm leading-6 text-slate-600">{generatedPolicy ? "Open the policy below to see the current wording, owner, approval and review date. The Evidence Library does not keep a second copy." : "This entry follows the original record, including its status and review date. Make changes in the original record."}</p>{generatedPolicy && relatedPolicy ? <Link href={`/policies/${relatedPolicy.id}/document`} className="mt-4 inline-flex rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Open policy: {relatedPolicy.title}</Link> : relatedRegister ? <Link href={`/registers/${relatedRegister.definition.key}/${relatedRegister.id}`} className="mt-4 inline-flex rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Open {relatedRegister.definition.name}: {relatedRegister.reference}</Link> : relatedAudit ? <Link href={`/audits/${relatedAudit.id}`} className="mt-4 inline-flex rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Open audit: {relatedAudit.title}</Link> : relatedRisk ? <Link href={`/risks/${relatedRisk.id}`} className="mt-4 inline-flex rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Open risk: {relatedRisk.reference}</Link> : <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">The original record is no longer available within your authorised locations.</p>}</> : fileUrl ? <><div className="mt-4 flex gap-2"><a href={fileUrl} target="_blank" className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Open file</a><a href={`${fileUrl}?download=1`} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Download</a></div>{previewable && <iframe title="Evidence preview" src={fileUrl} className="mt-4 h-[520px] w-full rounded-xl border border-slate-200" />}</> : <p className="mt-3 text-slate-600">No file is available.</p>}</div>
        <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">Evidence details</h2><dl className="mt-4 space-y-3 text-sm">{[["Owner",item.owner.name],["Location",item.location?.name ?? "Organisation-wide"],["Evidence date",formatDate(item.evidenceDate)],["Review or expiry",systemRecord ? "Live" : formatDate(item.reviewExpiryDate)],["Confidentiality",item.confidentiality.toLowerCase()],[systemRecord ? "Recorded by" : "Uploaded by",item.uploadedBy.name],["Created",formatDate(item.createdAt)]].map(([term,value]) => <div key={term} className="flex justify-between gap-4 border-b border-slate-100 pb-2"><dt className="text-slate-500">{term}</dt><dd className="text-right font-medium capitalize">{value}</dd></div>)}</dl>{item.description && <p className="mt-4 text-sm text-slate-600">{item.description}</p>}{relatedPolicy && <Link href={`/policies/${relatedPolicy.id}`} className="mt-4 block rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">Related policy: {relatedPolicy.title}</Link>}</section></section>
      {canReplace && <section className="space-y-3"><h2 className="text-xl font-bold">Replace current version</h2><EvidenceVersionUpload id={id} /></section>}
      <section className="grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">Source and provenance</h2><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-900">{evidenceAssuranceLabel(item.sourceType)}</span></div><dl className="mt-4 space-y-3 text-sm">{[["Source",item.sourceName??"Not recorded"],["Source reference",item.sourceReference??"Not recorded"],["Original author or issuer",item.originalAuthor??"Not recorded"],["Captured or received",formatDate(item.capturedAt)]].map(([term,value])=><div key={term} className="flex justify-between gap-4 border-b pb-2"><dt className="text-slate-500">{term}</dt><dd className="text-right font-semibold">{value}</dd></div>)}</dl>{item.sourceUrl?<a href={item.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-bold text-blue-800 underline">Open recorded source</a>:null}<p className="mt-4 whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-sm text-slate-600">{item.provenanceNote??"No provenance note recorded."}</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-bold">Verification</h2><span className={`rounded-full px-3 py-1 text-xs font-bold ${assuranceState==="CURRENT_VERIFIED"?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{evidenceAssuranceLabel(assuranceState)}</span></div>{item.verifications.length?<div className="mt-4 space-y-3">{item.verifications.map((verification)=><div key={verification.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{evidenceAssuranceLabel(verification.outcome)}</strong><p className="text-xs text-slate-500">{verification.verifiedBy.name} · {formatDate(verification.verifiedAt)} · review {formatDate(verification.reviewDueAt)}</p><p className="mt-2 text-xs"><strong>Relevance:</strong> {verification.relevance}</p>{verification.limitations?<p className="mt-1 text-xs text-amber-900"><strong>Limitations:</strong> {verification.limitations}</p>:null}</div>)}</div>:<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm font-semibold text-amber-900">Uploaded evidence has not yet received a named verification decision.</p>}{canEdit?<details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-blue-900">Record new verification</summary><div className="mt-3"><EvidenceVerificationForm evidenceId={item.id}/></div></details>:null}</article></section>
      {!systemRecord && <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Version history</h2><div className="mt-4 divide-y divide-slate-200">{item.versions.map((version) => <div key={version.id} className="grid gap-2 py-4 text-sm md:grid-cols-[1fr_1fr_1fr_auto]"><div><strong>Version {version.versionNumber}</strong><p className="text-slate-500">{version.fileName}</p></div><div><span className="text-slate-500">Uploaded by</span><p>{version.uploadedBy.name}</p></div><div><span className="text-slate-500">Uploaded</span><p>{formatDate(version.createdAt)}</p></div><a href={`/api/evidence/${id}/versions/${version.id}/file?download=1`} className="font-semibold text-emerald-700">Download</a>{version.changeNotes && <p className="md:col-span-4 text-slate-600">{version.changeNotes}</p>}</div>)}</div></section>}
    </main>;
  } finally { await db.$disconnect(); }
}
function formatDate(value: Date | null) { return value ? new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value) : "Not set"; }
