import { NextResponse } from "next/server";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { CQC_KEY_QUESTIONS, inspectionScopeWhere, splitEvidenceExamples } from "@/lib/inspection";
import { PERMISSIONS } from "@/lib/permissions";
import { parseOptionalDate } from "@/lib/policies";
import { rmFields, validatedLinks } from "@/app/api/inspection/route";

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const context=await requirePermission(PERMISSIONS.GOVERNANCE_EDIT),{id}=await params,form=await request.formData(),db=createDb();try{const existing=await db.complianceRequirement.findFirst({where:{id,...inspectionScopeWhere(context)}});if(!existing)return NextResponse.json({error:"Requirement not found."},{status:404});const locationId=String(form.get("locationId")??"")||null,ownerId=String(form.get("ownerId")??"")||null;if(locationId&&!context.locations.some(x=>x.id===locationId))throw new Error("Choose an authorised location.");if(ownerId&&!(await db.organisationMembership.findFirst({where:{organisationId:context.organisation.id,userId:ownerId,status:"ACTIVE"}})))throw new Error("Choose an active owner.");const links=await validatedLinks(db,context,form,locationId),rm=rmFields(form,context.user.id);const custom=!existing.catalogueKey;const keyQuestion=String(form.get("keyQuestion")??existing.keyQuestion),title=String(form.get("title")??existing.title).trim(),explanation=String(form.get("explanation")??existing.explanation).trim();if(custom&&(!CQC_KEY_QUESTIONS.includes(keyQuestion as never)||title.length<3||explanation.length<10))throw new Error("Enter valid requirement details.");await db.$transaction(async(tx)=>{await tx.complianceRequirement.update({where:{id},data:{locationId,ownerId,reviewDate:parseOptionalDate(form.get("reviewDate")),confidenceNote:optional(form,"confidenceNote"),...(custom?{keyQuestion:keyQuestion as never,qualityStatement:optional(form,"qualityStatement"),title,explanation,evidenceExamples:splitEvidenceExamples(form.get("evidenceExamples"))}:{}),...rm,evidenceLinks:{deleteMany:{},create:links.evidenceIds.map(evidenceId=>({evidenceId}))},auditLinks:{deleteMany:{},create:links.auditIds.map(auditId=>({auditId}))},registerLinks:{deleteMany:{},create:links.registerEntryIds.map(registerEntryId=>({registerEntryId}))},actionLinks:{deleteMany:{},create:links.actionIds.map(actionId=>({actionId}))}}});await tx.activityLog.create({data:{organisationId:context.organisation.id,locationId,userId:context.user.id,action:"UPDATE",recordType:"ComplianceRequirement",recordId:id,summary:`RM reviewed inspection requirement: ${existing.title}`,beforeValue:{managementDecision:existing.managementDecision,signedOffAt:existing.signedOffAt},afterValue:{managementDecision:rm.managementDecision,signedOff:Boolean(rm.signedOffAt),coveredEvidenceCategories:rm.coveredEvidenceCategories}}})});return NextResponse.json({ok:true})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not update requirement."},{status:400})}finally{await db.$disconnect()}}
function optional(form:FormData,name:string){return String(form.get(name)??"").trim()||null}
