import Link from "next/link";
import { notFound } from "next/navigation";
import { CarePlanReviewView } from "@/components/care-plan-review-view";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";
import { registerScopeWhere } from "@/lib/registers";

export default async function CarePlanReviewPage({params}:{params:Promise<{id:string}>}){const context=await requirePermission(PERMISSIONS.GOVERNANCE_VIEW);const{id}=await params;const db=createDb();try{const entry=await db.registerEntry.findFirst({where:{id,...registerScopeWhere(context),definition:{key:"care-plan-reviews"}},include:{client:true,location:{select:{name:true}},owner:{select:{name:true}},createdBy:{select:{name:true}},evidenceLinks:{include:{evidence:{select:{id:true,title:true}}}},history:{include:{user:{select:{name:true}}},orderBy:{createdAt:"desc"}}}});if(!entry)notFound();const actions=entry.linkedActionIds.length?await db.action.findMany({where:{id:{in:entry.linkedActionIds},organisationId:context.organisation.id},select:{id:true,reference:true,title:true,priority:true,status:true,dueDate:true,owner:{select:{name:true}}}}):[];const canEdit=hasPermission(context.permissions,PERMISSIONS.GOVERNANCE_EDIT);return <main className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><Link href="/registers/care-plan-reviews" className="text-sm font-semibold text-emerald-700">← Care Plan Reviews</Link><div className="flex gap-2">{canEdit?<Link href={`/registers/care-plan-reviews/${id}/edit`} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">Edit / reopen</Link>:null}<Link href={`/registers/care-plan-reviews/${id}/report`} target="_blank" className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Print / PDF</Link></div></div><CarePlanReviewView entry={entry} organisation={{name:context.organisation.name,hasLogo:Boolean(context.organisation.policyLogoStorageKey)}} actions={actions}/></main>}finally{await db.$disconnect();}}
