"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ROLE_KEYS } from "@/lib/permissions";

const priorities=["LOW","MEDIUM","HIGH","CRITICAL"] as const,roles=[ROLE_KEYS.OWNER,ROLE_KEYS.NOMINATED_INDIVIDUAL,ROLE_KEYS.REGISTERED_MANAGER,ROLE_KEYS.QUALITY_MANAGER];
const defaults={LOW:{verificationRequired:true,effectivenessRequired:false,separateVerifierRequired:false,separateCloserRequired:false,rootCauseRequired:false},MEDIUM:{verificationRequired:true,effectivenessRequired:true,separateVerifierRequired:false,separateCloserRequired:false,rootCauseRequired:false},HIGH:{verificationRequired:true,effectivenessRequired:true,separateVerifierRequired:true,separateCloserRequired:true,rootCauseRequired:true},CRITICAL:{verificationRequired:true,effectivenessRequired:true,separateVerifierRequired:true,separateCloserRequired:true,rootCauseRequired:true}};
export function ActionAssurancePolicyForm(){const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget),rules=priorities.map(priority=>({priority,...defaults[priority],closureRoleKeys:form.getAll(`roles-${priority}`).map(String)})),response=await fetch("/api/settings/action-assurance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({effectiveFrom:form.get("effectiveFrom"),changeRationale:form.get("changeRationale"),rules})}),result=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(result.error??"Could not create policy draft.");return;}router.refresh()}return <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Create Audit Action policy draft</h2><p className="mt-1 text-sm text-slate-600">Safe defaults define verification, effectiveness and separation. Choose which provider roles may make the final closure decision.</p>{error?<p className="mt-3 text-sm font-bold text-red-700">{error}</p>:null}<div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Effective from<input type="date" name="effectiveFrom" required className="mt-1 w-full rounded-lg border p-2"/></label><label className="text-sm font-bold">Governance rationale<textarea name="changeRationale" required minLength={12} className="mt-1 min-h-20 w-full rounded-lg border p-2"/></label></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{priorities.map(priority=><fieldset key={priority} className="rounded-xl border border-slate-200 p-4"><legend className="px-1 font-black">{priority}</legend><p className="text-xs text-slate-600">{Object.entries(defaults[priority]).filter(([,value])=>value).map(([key])=>key.replaceAll(/([A-Z])/g," $1").toLowerCase()).join(" · ")||"Proportionate basic closure"}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{roles.map(role=><label key={role} className="flex gap-2 text-xs"><input type="checkbox" name={`roles-${priority}`} value={role} defaultChecked={priority==="LOW"||role===ROLE_KEYS.REGISTERED_MANAGER||role===ROLE_KEYS.QUALITY_MANAGER||(priority==="CRITICAL"&&[ROLE_KEYS.OWNER,ROLE_KEYS.NOMINATED_INDIVIDUAL].includes(role as never))}/>{role.replaceAll("-"," ")}</label>)}</div></fieldset>)}</div><button disabled={busy} className="mt-5 rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white">{busy?"Creating…":"Create governed draft"}</button></form>}

export function ActionAssurancePolicyStatus({id,intent,label}:{id:string;intent:"submit"|"approve"|"activate"|"retire";label:string}){const router=useRouter(),[error,setError]=useState("");async function act(){const comment=prompt(`${label}: record the governance reason.`);if(!comment)return;const response=await fetch(`/api/settings/action-assurance/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({intent,comment})}),result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error??"Could not update policy.");return;}router.refresh()}return <span><button type="button" onClick={act} className="rounded-lg border border-emerald-700 px-3 py-2 text-xs font-bold text-emerald-800">{label}</button>{error?<span className="ml-2 text-xs text-red-700">{error}</span>:null}</span>}
