"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ACTION_CATEGORIES, ACTION_PRIORITIES, ACTION_STATUSES, actionLabel } from "@/lib/actions";
import { FormPurpose } from "@/components/form-purpose";
type Option={id:string;name:string}; type Source={type:string;id:string;label:string};
type Initial={id:string;reference:string;title:string;description:string;category:string;rootCause:string;expectedOutcome:string;successMeasure:string;sourceType:string;sourceRecordId:string;ownerId:string;locationId:string;priority:string;dueDate:string;reviewDate:string;status:string;progressPercent:number;progressNote:string;escalationRequired:boolean;escalationReason:string;evidenceRequired:boolean;evidenceWaiverExplanation:string;completionDate:string;verifiedById:string;verificationDate:string;closureNote:string;evidenceIds:string[]};
export function ActionForm({locations,owners,evidence,sources,initial,preselectedSource}:{locations:Option[];owners:Option[];evidence:Option[];sources:Source[];initial?:Initial;preselectedSource?:string}){
 const router=useRouter(),[error,setError]=useState(""),[busy,setBusy]=useState(false); const cls="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm shadow-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-100";
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const response=await fetch(initial?`/api/actions/${initial.id}`:"/api/actions",{method:initial?"PATCH":"POST",body:new FormData(event.currentTarget)});const result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error??"Could not save action.");setBusy(false);return;}router.push(`/actions/${initial?.id??result.id}`);router.refresh();}
 const defaultDue=initial?.dueDate??future(30),defaultReview=initial?.reviewDate??future(14);
 return <form onSubmit={submit} className="space-y-7"><div className="rounded-2xl border border-emerald-200 bg-gradient-to-br from-emerald-950 to-emerald-800 p-6 text-white"><FormPurpose title="Improvement action" description="Turn a finding into a measurable result, with one accountable owner, clear milestones and evidence for independent closure." steps={["Define the outcome", "Connect the source and owner", "Track progress and evidence", "Verify before closure"]}/></div>{error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-800">{error}</p>}
 <Section number="1" title="Outcome and success" copy="Be specific enough that another manager can judge whether the action worked."><div className="grid gap-4 md:grid-cols-2"><Field label="Action reference" hint="created automatically if blank"><input className={cls} name="reference" defaultValue={initial?.reference} readOnly={Boolean(initial)}/></Field><Field label="Improvement category"><select className={cls} name="category" defaultValue={initial?.category??ACTION_CATEGORIES[0]}>{ACTION_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="What must be achieved?" wide><input className={cls} name="title" required minLength={3} defaultValue={initial?.title} placeholder="Complete all overdue medicines competencies"/></Field><Field label="Work required" wide><textarea className={`${cls} min-h-24`} name="description" required defaultValue={initial?.description} placeholder="Describe the practical work, people affected and scope."/></Field><Field label="Root cause or contributing factors" wide><textarea className={`${cls} min-h-20`} name="rootCause" defaultValue={initial?.rootCause} placeholder="What allowed the gap to occur?"/></Field><Field label="Expected outcome" wide><textarea className={`${cls} min-h-20`} name="expectedOutcome" required defaultValue={initial?.expectedOutcome} placeholder="What should be different for people using the service?"/></Field><Field label="How will success be measured?" wide><textarea className={`${cls} min-h-20`} name="successMeasure" required defaultValue={initial?.successMeasure} placeholder="For example: 100% competency completion, confirmed by spot check."/></Field></div></Section>
 <Section number="2" title="Source, ownership and milestones" copy="Connect this action to the record that raised it so evidence remains traceable."><div className="grid gap-4 md:grid-cols-2"><Field label="Source record" wide><select className={cls} name="source" defaultValue={initial?`${initial.sourceType}:${initial.sourceRecordId}`:preselectedSource??"MANUAL:"}><option value="MANUAL:">Manual improvement action</option>{sources.map(s=><option key={`${s.type}:${s.id}`} value={`${s.type}:${s.id}`}>{actionLabel(s.type)} · {s.label}</option>)}</select></Field><Field label="Accountable owner"><select className={cls} name="ownerId" required defaultValue={initial?.ownerId??""}><option value="">Choose owner</option>{owners.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Service or branch"><select className={cls} name="locationId" defaultValue={initial?.locationId??""}><option value="">Organisation-wide</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Priority"><select className={cls} name="priority" defaultValue={initial?.priority??"MEDIUM"}>{ACTION_PRIORITIES.map(x=><option key={x}>{actionLabel(x)}</option>)}</select></Field><Field label="Due date"><input className={cls} type="date" name="dueDate" required defaultValue={defaultDue}/></Field><Field label="Checkpoint / review date"><input className={cls} type="date" name="reviewDate" defaultValue={defaultReview}/></Field></div></Section>
 <Section number="3" title="Current position and escalation" copy="Keep the headline position visible without opening every update."><div className="grid gap-4 md:grid-cols-2"><Field label="Status"><select className={cls} name="status" defaultValue={initial?.status??"OPEN"}>{ACTION_STATUSES.filter(x=>!["OVERDUE","ARCHIVED"].includes(x)).map(x=><option key={x} value={x}>{actionLabel(x)}</option>)}</select></Field><Field label="Progress completed (%)"><input className={cls} type="number" min="0" max="100" step="5" name="progressPercent" defaultValue={initial?.progressPercent??0}/></Field><Field label="Current progress summary" wide><textarea className={`${cls} min-h-20`} name="progressNote" defaultValue={initial?.progressNote} placeholder="What is the latest position?"/></Field><Field label="Does this need escalation?"><select className={cls} name="escalationRequired" defaultValue={String(initial?.escalationRequired??false)}><option value="false">No</option><option value="true">Yes — management attention required</option></select></Field><Field label="Reason for escalation"><textarea className={`${cls} min-h-20`} name="escalationReason" defaultValue={initial?.escalationReason}/></Field></div></Section>
 <Section number="4" title="Evidence and independent closure" copy="Completion is not closure. Attach proof and record independent verification."><div className="grid gap-4 md:grid-cols-2"><Field label="Evidence required?"><select className={cls} name="evidenceRequired" defaultValue={String(initial?.evidenceRequired??true)}><option value="true">Yes</option><option value="false">No — waiver explanation required</option></select></Field><Field label="Completion date"><input className={cls} type="date" name="completionDate" defaultValue={initial?.completionDate}/></Field><Field label="Evidence attached" wide><p className="mt-1 text-xs text-slate-500">Hold Ctrl or Command to choose more than one item.</p><select multiple className={`${cls} min-h-32`} name="evidenceIds" defaultValue={initial?.evidenceIds??[]}>{evidence.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Evidence waiver explanation" wide><textarea className={`${cls} min-h-20`} name="evidenceWaiverExplanation" defaultValue={initial?.evidenceWaiverExplanation}/></Field><Field label="Verified by"><select className={cls} name="verifiedById" defaultValue={initial?.verifiedById??""}><option value="">Not verified</option>{owners.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Verification date"><input className={cls} type="date" name="verificationDate" defaultValue={initial?.verificationDate}/></Field><Field label="Closure note" wide><textarea className={`${cls} min-h-20`} name="closureNote" defaultValue={initial?.closureNote} placeholder="State the outcome and any follow-up monitoring."/></Field></div></Section>
 <div className="sticky bottom-4 flex justify-end rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-xl backdrop-blur"><button disabled={busy} className="rounded-xl bg-emerald-700 px-6 py-3 text-sm font-bold text-white shadow-sm disabled:opacity-60">{busy?"Saving action…":initial?"Save action":"Create and connect action"}</button></div></form>
}
function Section({number,title,copy,children}:{number:string;title:string;copy:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-100 font-black text-emerald-800">{number}</span><div><h2 className="text-lg font-bold">{title}</h2><p className="text-sm text-slate-600">{copy}</p></div></div><div className="mt-5">{children}</div></section>}
function Field({label,hint,wide,children}:{label:string;hint?:string;wide?:boolean;children:React.ReactNode}){return <label className={`${wide?"md:col-span-2 ":""}text-sm font-semibold text-slate-800`}>{label}{hint&&<span className="font-normal text-slate-500"> ({hint})</span>}{children}</label>}
function future(days:number){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
