"use client";
import{useRouter}from"next/navigation";import{useState}from"react";import{ACTION_PRIORITIES,ACTION_STATUSES,actionLabel}from"@/lib/actions";
type Option={id:string;name:string};type Source={type:string;id:string;label:string};type Initial={id:string;reference:string;title:string;description:string;sourceType:string;sourceRecordId:string;ownerId:string;locationId:string;priority:string;dueDate:string;status:string;progressNote:string;evidenceRequired:boolean;evidenceWaiverExplanation:string;completionDate:string;verifiedById:string;verificationDate:string;closureNote:string;evidenceIds:string[]};
export function ActionForm({locations,owners,evidence,sources,initial,preselectedSource}:{locations:Option[];owners:Option[];evidence:Option[];sources:Source[];initial?:Initial;preselectedSource?:string}){
  const router=useRouter();const[error,setError]=useState("");const[busy,setBusy]=useState(false);const cls="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm";
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const response=await fetch(initial?`/api/actions/${initial.id}`:"/api/actions",{method:initial?"PATCH":"POST",body:new FormData(event.currentTarget)});const result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error??"Could not save action.");setBusy(false);return;}router.push(`/actions/${initial?.id??result.id}`);router.refresh();}
  const defaultDue=initial?.dueDate??(()=>{const date=new Date();date.setDate(date.getDate()+30);return date.toISOString().slice(0,10)})();
  return <form onSubmit={submit} className="space-y-7 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  <Section title="Action details"><div className="grid gap-4 md:grid-cols-2"><Field label="Action reference" hint="auto-generated if blank"><input className={cls} name="reference" defaultValue={initial?.reference} readOnly={Boolean(initial)}/></Field><Field label="Priority"><select className={cls} name="priority" defaultValue={initial?.priority??"MEDIUM"}>{ACTION_PRIORITIES.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="Action title" wide><input className={cls} name="title" required minLength={3} defaultValue={initial?.title}/></Field><Field label="Description" wide><textarea className={`${cls} min-h-24`} name="description" required defaultValue={initial?.description}/></Field></div></Section>
  <Section title="Source and accountability"><div className="grid gap-4 md:grid-cols-2"><Field label="Source record" wide><select className={cls} name="source" defaultValue={initial?`${initial.sourceType}:${initial.sourceRecordId}`:preselectedSource??"MANUAL:"}><option value="MANUAL:">Manual entry</option>{sources.map((source)=><option key={`${source.type}:${source.id}`} value={`${source.type}:${source.id}`}>{actionLabel(source.type)} · {source.label}</option>)}</select></Field><Field label="Owner"><select className={cls} name="ownerId" required defaultValue={initial?.ownerId??""}><option value="">Choose owner</option>{owners.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Location"><select className={cls} name="locationId" defaultValue={initial?.locationId??""}><option value="">Organisation-wide</option>{locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Due date"><input className={cls} type="date" name="dueDate" required defaultValue={defaultDue}/></Field><Field label="Status"><select className={cls} name="status" defaultValue={initial?.status??"OPEN"}>{ACTION_STATUSES.filter((item)=>item!=="OVERDUE"&&item!=="ARCHIVED").map((item)=><option key={item} value={item}>{actionLabel(item)}</option>)}</select></Field><Field label="Current progress note" wide><textarea className={`${cls} min-h-20`} name="progressNote" defaultValue={initial?.progressNote}/></Field></div></Section>
  <Section title="Evidence and closure"><div className="grid gap-4 md:grid-cols-2"><Field label="Evidence required?"><select className={cls} name="evidenceRequired" defaultValue={String(initial?.evidenceRequired??true)}><option value="true">Yes</option><option value="false">No — waiver explanation required</option></select></Field><Field label="Completion date"><input className={cls} type="date" name="completionDate" defaultValue={initial?.completionDate}/></Field><Field label="Evidence waiver explanation" wide><textarea className={`${cls} min-h-20`} name="evidenceWaiverExplanation" defaultValue={initial?.evidenceWaiverExplanation}/></Field><Field label="Evidence attached" wide><p className="mt-1 text-xs text-slate-500">Use Ctrl or Command to select more than one item.</p><select multiple className={`${cls} min-h-32`} name="evidenceIds" defaultValue={initial?.evidenceIds??[]}>{evidence.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Verified by"><select className={cls} name="verifiedById" defaultValue={initial?.verifiedById??""}><option value="">Not verified</option>{owners.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Verification date"><input className={cls} type="date" name="verificationDate" defaultValue={initial?.verificationDate}/></Field><Field label="Closure note" wide><textarea className={`${cls} min-h-20`} name="closureNote" defaultValue={initial?.closureNote}/></Field></div></Section>
  <button disabled={busy} className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy?"Saving…":initial?"Save action":"Create action"}</button></form>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="text-lg font-bold">{title}</h2><div className="mt-4">{children}</div></section>}function Field({label,hint,wide,children}:{label:string;hint?:string;wide?:boolean;children:React.ReactNode}){return <label className={`${wide?"md:col-span-2 ":""}text-sm font-medium`}>{label}{hint&&<span className="font-normal text-slate-500"> ({hint})</span>}{children}</label>}
