"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Option = { id: string; name: string };
const input = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm";

function useSubmit(url: string) {
  const router = useRouter(), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const response = await fetch(url, { method: "POST", body: new FormData(event.currentTarget) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setError(body.error ?? "The record could not be saved."); setBusy(false); return; } router.refresh(); setBusy(false); }
  return { submit, busy, error };
}

export function RootCauseControl({ id, initial, canApprove }: { id: string; initial?: { method: string; problemStatement: string; immediateCauses: string[]; contributingFactors: string[]; systemCauses: string[]; lessons: string; preventiveControls: string }; canApprove: boolean }) {
  const state = useSubmit(`/api/actions/${id}/assurance/root-cause`);
  return <form onSubmit={state.submit} className="grid gap-3 md:grid-cols-2"><Field label="Review method"><select name="method" defaultValue={initial?.method ?? "FIVE_WHYS"} className={input}><option value="FIVE_WHYS">Five Whys</option><option value="FISHBONE">Fishbone / contributing factors</option><option value="SYSTEMS_REVIEW">Systems review</option><option value="SIGNIFICANT_EVENT">Significant event analysis</option><option value="OTHER">Other structured method</option></select></Field><Field label="Problem statement"><textarea name="problemStatement" defaultValue={initial?.problemStatement} className={input} rows={3}/></Field><Field label="Immediate causes" hint="one per line"><textarea name="immediateCauses" defaultValue={initial?.immediateCauses.join("\n")} className={input} rows={4}/></Field><Field label="Contributing factors" hint="one per line"><textarea name="contributingFactors" defaultValue={initial?.contributingFactors.join("\n")} className={input} rows={4}/></Field><Field label="System causes" hint="one per line"><textarea name="systemCauses" defaultValue={initial?.systemCauses.join("\n")} className={input} rows={4}/></Field><Field label="Learning"><textarea name="lessons" defaultValue={initial?.lessons} className={input} rows={4}/></Field><Field label="Prevention and detection controls" wide><textarea name="preventiveControls" defaultValue={initial?.preventiveControls} className={input} rows={4}/></Field>{canApprove ? <label className="md:col-span-2 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="approve" value="true"/> Approve this review as the accountable manager</label> : null}<Submit state={state} label="Save root-cause review"/></form>;
}

export function VerificationControl({ id, members, evidence, ownerId, currentUserId, today }: { id: string; members: Option[]; evidence: Option[]; ownerId: string; currentUserId: string; today: string }) {
  const state = useSubmit(`/api/actions/${id}/assurance/verification`);
  const verifier = members.find((item) => item.id === currentUserId);
  return <form onSubmit={state.submit} className="grid gap-3 md:grid-cols-2"><Field label="Verification outcome"><select name="outcome" className={input}><option value="VERIFIED">Verified</option><option value="PARTIALLY_VERIFIED">Partially verified</option><option value="FAILED">Failed verification</option></select></Field><Field label="Verification date"><input type="date" name="verifiedAt" defaultValue={today} className={input}/></Field><Field label="Verifier"><input type="hidden" name="verifierId" value={currentUserId}/><div className={`${input} bg-slate-50`}>{verifier?.name ?? "Current signed-in user"}{currentUserId === ownerId ? " · action owner" : " · independent of owner"}</div><p className="mt-1 text-xs font-normal text-slate-500">Verification is attributed to the signed-in account and cannot be recorded for someone else.</p></Field><Field label="Evidence checked" hint="choose one or more"><select multiple name="evidenceIds" className={`${input} min-h-28`}>{evidence.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Work completed"><textarea name="completedWork" className={input} rows={3}/></Field><Field label="Evidence summary"><textarea name="evidenceSummary" className={input} rows={3}/></Field><Field label="Result against the predefined success measure" wide><textarea name="successMeasureResult" className={input} rows={3}/></Field><Field label="Independent verification rationale" wide><textarea name="rationale" className={input} rows={3}/></Field><Submit state={state} label="Record verification"/></form>;
}

export function EffectivenessControl({ id, evidence, today }: { id: string; evidence: Option[]; today: string }) {
  const state = useSubmit(`/api/actions/${id}/assurance/effectiveness`);
  return <form onSubmit={state.submit} className="grid gap-3 md:grid-cols-2"><Field label="Effectiveness outcome"><select name="outcome" className={input}><option value="EFFECTIVE">Effective and sustained</option><option value="PARTIALLY_EFFECTIVE">Partially effective</option><option value="INEFFECTIVE">Ineffective — reopen</option><option value="TOO_EARLY">Too early to judge</option></select></Field><Field label="Review date"><input type="date" name="reviewDate" defaultValue={today} className={input}/></Field><Field label="Baseline"><input name="baseline" className={input}/></Field><Field label="Target"><input name="target" className={input}/></Field><Field label="Observed result" wide><textarea name="observedResult" className={input} rows={3}/></Field><Field label="Supporting evidence"><select multiple name="evidenceIds" className={`${input} min-h-24`}>{evidence.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Recurrence identified?"><select name="recurrenceFound" className={input}><option value="false">No</option><option value="true">Yes — reopen and escalate</option></select></Field><Field label="Management decision" wide><textarea name="decision" className={input} rows={3}/></Field><Field label="Next review date"><input type="date" name="nextReviewDate" className={input}/></Field><Field label="Immediate control if recurrence"><textarea name="immediateControl" className={input} rows={3}/></Field><Field label="Management escalation if recurrence" wide><textarea name="managementEscalation" className={input} rows={3}/></Field><Submit state={state} label="Record effectiveness review"/></form>;
}

export function ExternalDependencyControl({ id, members, today }: { id: string; members: Option[]; today: string }) {
  const state = useSubmit(`/api/actions/${id}/assurance/dependencies`);
  return <form onSubmit={state.submit} className="grid gap-3 md:grid-cols-2"><Field label="External organisation"><input name="partyName" className={input}/></Field><Field label="Contact person"><input name="contactName" className={input}/></Field><Field label="Email"><input type="email" name="contactEmail" className={input}/></Field><Field label="Phone number"><input type="tel" name="contactPhone" className={input}/></Field><Field label="Request made" wide><textarea name="request" className={input} rows={3}/></Field><Field label="External reference"><input name="externalReference" className={input}/></Field><Field label="Requested date"><input type="date" name="requestedAt" defaultValue={today} className={input}/></Field><Field label="Response due"><input type="date" name="dueDate" className={input}/></Field><Field label="Internal owner"><select name="ownerId" className={input}><option value="">Choose owner</option>{members.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Interim control while waiting" wide><textarea name="interimControl" className={input} rows={3}/></Field><Field label="Escalation route if delayed" wide><textarea name="escalationRoute" className={input} rows={3}/></Field><Submit state={state} label="Add external dependency"/></form>;
}

export function DependencyDecision({ actionId, dependencyId }: { actionId: string; dependencyId: string }) {
  const router = useRouter(), [summary, setSummary] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function save(intent: "chase" | "resolve") { setBusy(true); setError(""); const form = new FormData(); form.set("intent", intent); form.set("summary", summary); const response = await fetch(`/api/actions/${actionId}/assurance/dependencies/${dependencyId}`, { method: "PATCH", body: form }); const body = await response.json().catch(() => ({})); if (!response.ok) { setError(body.error ?? "Could not update dependency."); setBusy(false); return; } router.refresh(); setBusy(false); }
  return <div className="mt-3"><textarea value={summary} onChange={(event) => setSummary(event.target.value)} className={input} rows={2} placeholder="Record contact attempt, response or resolution."/>{error ? <p className="mt-1 text-xs font-bold text-red-700">{error}</p> : null}<div className="mt-2 flex gap-2"><button disabled={busy} onClick={() => save("chase")} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Record chase</button><button disabled={busy} onClick={() => save("resolve")} className="rounded-lg bg-emerald-700 px-3 py-1.5 text-xs font-bold text-white">Resolve</button></div></div>;
}

export function ImprovementPlanControl({ members, locations, actions }: { members: Option[]; locations: Option[]; actions: Option[] }) {
  const state = useSubmit("/api/improvement-plans");
  return <form onSubmit={state.submit} className="grid gap-3 md:grid-cols-2"><Field label="Plan title"><input name="title" className={input}/></Field><Field label="Plan owner"><select name="ownerId" className={input}><option value="">Choose owner</option>{members.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Location"><select name="locationId" className={input}><option value="">Organisation-wide</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Target date"><input type="date" name="targetDate" className={input}/></Field><Field label="Improvement objective" wide><textarea name="objective" className={input} rows={3}/></Field><Field label="Why these findings belong together" wide><textarea name="rationale" className={input} rows={3}/></Field><Field label="Success measures" hint="one per line"><textarea name="successMeasures" className={input} rows={4}/></Field><Field label="Baseline"><textarea name="baseline" className={input} rows={3}/></Field><Field label="Target"><textarea name="target" className={input} rows={3}/></Field><Field label="Linked actions" wide><select multiple name="actionIds" className={`${input} min-h-36`}>{actions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Submit state={state} label="Create improvement plan"/></form>;
}

export function ImprovementPlanUpdate({ id, status, progressSummary, outcome }: { id: string; status: string; progressSummary: string; outcome: string }) {
  const router = useRouter(), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const response = await fetch(`/api/improvement-plans/${id}`, { method: "PATCH", body: new FormData(event.currentTarget) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setError(body.error ?? "Could not update plan."); setBusy(false); return; } router.refresh(); setBusy(false); }
  return <form onSubmit={submit} className="mt-3 grid gap-2"><select name="status" defaultValue={status} className={input}><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option><option value="AT_RISK">At risk</option><option value="COMPLETED">Completed</option></select><textarea name="progressSummary" defaultValue={progressSummary} className={input} rows={2} placeholder="Progress, barriers and next decision"/><textarea name="outcome" defaultValue={outcome} className={input} rows={2} placeholder="Measured outcome (required for completion)"/>{error?<p className="text-xs font-bold text-red-700">{error}</p>:null}<button disabled={busy} className="justify-self-start rounded-lg border border-emerald-700 px-3 py-2 text-xs font-bold text-emerald-800">{busy?"Saving…":"Update plan"}</button></form>;
}

function Field({ label, hint, wide, children }: { label: string; hint?: string; wide?: boolean; children: React.ReactNode }) { return <label className={`${wide ? "md:col-span-2 " : ""}text-sm font-semibold`}>{label}{hint ? <span className="font-normal text-slate-500"> ({hint})</span> : null}{children}</label>; }
function Submit({ state, label }: { state: { busy: boolean; error: string }; label: string }) { return <div className="md:col-span-2">{state.error ? <p role="alert" className="mb-2 rounded-lg bg-red-50 p-2 text-xs font-bold text-red-700">{state.error}</p> : null}<button disabled={state.busy} className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{state.busy ? "Saving…" : label}</button></div>; }
