"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { COMPLIANCE_ANSWERS } from "@/lib/audits";

type Question={id:string;text:string;guidance:string|null;evidenceExpected:string|null;responseType:string;mandatory:boolean;requiresEvidence:boolean;weighting:number};
type Section={id:string;title:string;description:string|null;questions:Question[]};
type Saved={questionId:string;answer:string|null;comment:string|null;evidenceId:string|null};
type ResponseValue={answer:string;comment:string;evidenceId:string};
export function AuditAssessmentForm({auditId,sections,saved,evidence,summary,readOnly}:{auditId:string;sections:Section[];saved:Saved[];evidence:{id:string;title:string}[];summary:{strengths:string;risks:string;recommendations:string;reviewDate:string};readOnly:boolean}) {
  const router=useRouter(); const initial=Object.fromEntries(saved.map((item)=>[item.questionId,{answer:item.answer??"",comment:item.comment??"",evidenceId:item.evidenceId??""}]));
  const [values,setValues]=useState<Record<string,ResponseValue>>(initial); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const update=(id:string,key:keyof ResponseValue,value:string)=>setValues((current)=>{const existing=current[id]??{answer:"",comment:"",evidenceId:""};return {...current,[id]:{...existing,[key]:value}};});
  async function save(intent:"save"|"submit",form:HTMLFormElement){setBusy(true);setError("");const data=new FormData(form);const response=await fetch(`/api/audits/${auditId}/responses`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({intent,responses:sections.flatMap((section)=>section.questions).map((question)=>({questionId:question.id,...(values[question.id]??{answer:"",comment:"",evidenceId:""})})),strengths:data.get("strengths"),risks:data.get("risks"),recommendations:data.get("recommendations"),reviewDate:data.get("reviewDate")})});const result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error??"Could not save audit.");setBusy(false);return;}setBusy(false);router.refresh();}
  return <form onSubmit={(event)=>{event.preventDefault();void save("save",event.currentTarget);}} className="space-y-6">{error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{sections.map((section)=><section key={section.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{section.title}</h2>{section.description&&<p className="mt-1 text-sm text-slate-600">{section.description}</p>}<div className="mt-5 divide-y divide-slate-200">{section.questions.map((question,index)=><div key={question.id} className="py-6"><div className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-800">{index+1}</span><div><h3 className="font-semibold">{question.text}{question.mandatory&&<span className="text-red-600"> *</span>}</h3>{question.guidance&&<p className="mt-1 text-sm text-slate-500">{question.guidance}</p>}<p className="mt-1 text-xs text-slate-400">Expected evidence: {question.evidenceExpected??"Relevant supporting records"}</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1.3fr_1fr]"><AnswerControl question={question} value={values[question.id]?.answer??""} onChange={(value)=>update(question.id,"answer",value)} disabled={readOnly}/><textarea disabled={readOnly} value={values[question.id]?.comment??""} onChange={(event)=>update(question.id,"comment",event.target.value)} className="min-h-20 rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100" placeholder="Comment, finding or context" /><select disabled={readOnly} value={values[question.id]?.evidenceId??""} onChange={(event)=>update(question.id,"evidenceId",event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm disabled:bg-slate-100"><option value="">No evidence linked</option>{evidence.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></div></div>)}</div></section>)}
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Audit summary</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{[["strengths","Strengths"],["risks","Risks"],["recommendations","Recommendations"]].map(([name,label])=><label key={name} className="text-sm font-medium">{label}<textarea disabled={readOnly} name={name} defaultValue={summary[name as keyof typeof summary]} className="mt-1 min-h-24 w-full rounded-lg border border-slate-300 px-3 py-2 disabled:bg-slate-100" /></label>)}<label className="text-sm font-medium">Review date<input disabled={readOnly} name="reviewDate" type="date" defaultValue={summary.reviewDate} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 disabled:bg-slate-100" /></label></div></section>
    {!readOnly&&<div className="flex flex-wrap gap-3"><button disabled={busy} className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-semibold">{busy?"Saving…":"Save progress"}</button><button disabled={busy} type="button" onClick={(event)=>void save("submit",event.currentTarget.form!)} className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white">Submit for review</button></div>}
  </form>;
}
function AnswerControl({question,value,onChange,disabled}:{question:Question;value:string;onChange:(value:string)=>void;disabled:boolean}) {
  const options=question.responseType==="COMPLIANCE"?COMPLIANCE_ANSWERS:question.responseType==="YES_NO"?["YES","NO","NOT_APPLICABLE"]:null;
  if(options)return <select disabled={disabled} value={value} onChange={(event)=>onChange(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm disabled:bg-slate-100"><option value="">Choose response</option>{options.map((item)=><option key={item} value={item}>{item.replaceAll("_"," ").toLowerCase()}</option>)}</select>;
  return <input disabled={disabled} value={value} onChange={(event)=>onChange(event.target.value)} type={question.responseType==="NUMBER"?"number":question.responseType==="DATE"?"date":"text"} className="rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100" placeholder="Enter response" />;
}
