"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Evidence={id:string;title:string};
const input="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm";

export function AuditFindingControls({auditId,findingId,severity,recommendation,immediateControl,escalationRequired,escalationRationale,resolved,evidence}:{auditId:string;findingId:string;severity:string;recommendation:string;immediateControl:string;escalationRequired:boolean;escalationRationale:string;resolved:boolean;evidence:Evidence[]}){
 const router=useRouter(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function send(path:string,form:HTMLFormElement){setBusy(true);setError("");const response=await fetch(path,{method:"POST",body:new FormData(form)});const result=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(result.error??"Could not save.");return;}form.reset();router.refresh();}
 async function patch(form:HTMLFormElement){setBusy(true);setError("");const response=await fetch(`/api/audits/${auditId}/findings/${findingId}`,{method:"PATCH",body:new FormData(form)});const result=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(result.error??"Could not update finding.");return;}router.refresh();}
 return <div className="mt-4 space-y-3 border-t border-slate-200 pt-4">
  <details><summary className="cursor-pointer text-sm font-bold text-emerald-800">Review finding and immediate control</summary><form onSubmit={e=>{e.preventDefault();void patch(e.currentTarget)}} className="mt-3 grid gap-3 md:grid-cols-2"><input type="hidden" name="intent" value="update"/><label className="text-xs font-bold">Severity<select name="severity" defaultValue={severity} className={input}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(value=><option key={value}>{value}</option>)}</select></label><label className="text-xs font-bold">Corrective Action required?<select name="actionRequired" defaultValue="true" className={input}><option value="true">Yes</option><option value="false">No — justify at resolution</option></select></label><label className="text-xs font-bold md:col-span-2">Required improvement<textarea name="recommendation" defaultValue={recommendation} className={input}/></label><label className="text-xs font-bold md:col-span-2">Immediate safety/control response<textarea name="immediateControl" defaultValue={immediateControl} className={input} placeholder="Required for Critical findings"/></label><label className="text-xs font-bold">Escalation<select name="escalationRequired" defaultValue={String(escalationRequired)} className={input}><option value="false">Not required</option><option value="true">Required</option></select></label><label className="text-xs font-bold">Escalation route and reason<input name="escalationRationale" defaultValue={escalationRationale} className={input}/></label><button disabled={busy} className="justify-self-start rounded-lg border border-emerald-700 px-3 py-2 text-sm font-bold text-emerald-800">Save finding</button></form></details>
  <details><summary className="cursor-pointer text-sm font-bold text-emerald-800">Link governed Evidence</summary><form onSubmit={e=>{e.preventDefault();void send(`/api/audits/${auditId}/findings/${findingId}/evidence`,e.currentTarget)}} className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Evidence record<select name="evidenceId" required className={input}><option value="">Choose Evidence</option>{evidence.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="text-xs font-bold">Evidence role<select name="role" className={input}>{["FINDING","SUPPORTING","SAMPLE","RESPONSE","EFFECTIVENESS"].map(value=><option key={value}>{value.replaceAll("_"," ")}</option>)}</select></label><button disabled={busy} className="justify-self-start rounded-lg border border-emerald-700 px-3 py-2 text-sm font-bold text-emerald-800">Link Evidence</button></form></details>
  <details><summary className="cursor-pointer text-sm font-bold text-emerald-800">Record targeted re-audit</summary><form onSubmit={e=>{e.preventDefault();void send(`/api/audits/${auditId}/findings/${findingId}/reaudits`,e.currentTarget)}} className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Review date<input type="date" name="reviewDate" required className={input}/></label><label className="text-xs font-bold">Outcome<select name="outcome" required className={input}>{["RESOLVED","IMPROVED_NOT_RESOLVED","UNCHANGED","DETERIORATED","INSUFFICIENT_EVIDENCE"].map(value=><option key={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label className="text-xs font-bold">Targeted sample size<input type="number" min="1" name="sampleSize" className={input}/></label><label className="text-xs font-bold">Sample selection/details<input name="sampleDetails" className={input}/></label><label className="text-xs font-bold md:col-span-2">What the targeted sample found<textarea name="result" required minLength={12} className={input}/></label><label className="text-xs font-bold md:col-span-2">Governance decision and next step<textarea name="decision" required minLength={12} className={input}/></label><label className="text-xs font-bold md:col-span-2">Evidence checked<select multiple name="evidenceIds" required className={`${input} min-h-28`}>{evidence.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><button disabled={busy} className="justify-self-start rounded-lg border border-emerald-700 px-3 py-2 text-sm font-bold text-emerald-800">Record re-audit</button></form></details>
  <form onSubmit={e=>{e.preventDefault();void patch(e.currentTarget)}} className="flex flex-wrap items-end gap-2"><input type="hidden" name="intent" value={resolved?"reopen":"resolve"}/>{!resolved?<label className="grow text-xs font-bold">Resolution rationale<input name="rationale" required minLength={12} className={input}/></label>:null}<button disabled={busy} className="rounded-lg bg-slate-800 px-3 py-2 text-sm font-bold text-white">{resolved?"Reopen finding":"Resolve finding"}</button></form>{error?<p role="alert" className="text-sm font-semibold text-red-700">{error}</p>:null}
 </div>;
}
