"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function AuditActions({id,status,outstanding=[]}:{id:string;status:string;outstanding?:{label:string;reason:string}[]}){
  const router=useRouter(),[error,setError]=useState(""),[busy,setBusy]=useState(false),[showClose,setShowClose]=useState(false);
  async function act(intent:string,form?:HTMLFormElement){setBusy(true);setError("");const payload=form?new FormData(form):new FormData();payload.set("intent",intent);const response=await fetch(`/api/audits/${id}`,{method:"PATCH",body:payload});const result=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(result.error??"Action failed.");return;}setShowClose(false);router.refresh();}
  return <div className="min-w-64"><div className="flex flex-wrap gap-2">{status==="AWAITING_REVIEW"&&<button disabled={busy} onClick={()=>act("complete")} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Complete fieldwork</button>}{status==="COMPLETED"&&<button onClick={()=>setShowClose(value=>!value)} className="rounded-lg bg-slate-800 px-4 py-2 text-sm font-semibold text-white">Management assurance</button>}<button disabled={busy} onClick={()=>act(status==="ARCHIVED"?"restore":"archive")} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">{status==="ARCHIVED"?"Restore":"Archive"}</button></div>{showClose?<form onSubmit={(event)=>{event.preventDefault();void act("close",event.currentTarget);}} className="mt-3 rounded-xl border border-slate-200 bg-white p-4 shadow-lg"><p className="text-sm font-bold">Authorised governance closure</p>{outstanding.length?<div className="mt-2 rounded-lg bg-amber-50 p-3 text-xs text-amber-900"><strong>Not ready:</strong><ul className="mt-1 list-disc space-y-1 pl-4">{outstanding.map(item=><li key={item.label}>{item.label}: {item.reason}</li>)}</ul></div>:<p className="mt-1 text-xs text-emerald-700">All current assurance conditions are satisfied.</p>}<textarea name="rationale" required minLength={12} className="mt-3 min-h-20 w-full rounded-lg border border-slate-300 p-2 text-sm" placeholder="Why is there sufficient appropriate evidence and authority to close this audit?"/><button disabled={busy||outstanding.length>0} className="mt-2 rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-50">Confirm assurance and close</button></form>:null}{error&&<p className="mt-2 max-w-md text-sm text-red-700">{error}</p>}</div>;
}
