"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

async function send(url: string, method: string, form: HTMLFormElement | FormData) {
  const response = await fetch(url, { method, body: form instanceof FormData ? form : new FormData(form) });
  const body = await response.json().catch(() => ({})) as { error?: string };
  if (!response.ok) throw new Error(body.error ?? "The record could not be updated.");
}

export function UnderstandingResponseForm({ carePlanId, prompt, submitted }: { carePlanId: string; prompt: string; submitted: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  return <form className="rounded-2xl border border-blue-200 bg-blue-50 p-4" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { await send(`/api/care-plans/${carePlanId}/understanding`, "POST", event.currentTarget); setMessage("Submitted for manager review."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not submit."); } finally { setBusy(false); } }}><h3 className="font-bold text-blue-950">Understanding check</h3><p className="mt-2 text-sm text-blue-950">{prompt}</p><label className="mt-3 block text-sm font-semibold">Your answer<textarea name="response" required minLength={20} maxLength={2000} rows={5} disabled={submitted} className="mt-1 w-full rounded-xl border border-blue-200 bg-white p-3 disabled:opacity-60" placeholder="Explain the instruction, what you must not do and when you would escalate."/></label><button disabled={busy || submitted} className="mt-3 rounded-xl bg-blue-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{submitted ? "Awaiting manager review" : busy ? "Submitting…" : "Submit understanding check"}</button>{message ? <p role="status" className="mt-2 text-sm text-blue-950">{message}</p> : null}</form>;
}

export function UnderstandingReviewForm({ carePlanId, checkId }: { carePlanId: string; checkId: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  return <form className="mt-3 space-y-3 rounded-xl bg-slate-50 p-3" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { await send(`/api/care-plans/${carePlanId}/understanding/${checkId}`, "PATCH", event.currentTarget); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not review."); } finally { setBusy(false); } }}><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Method<select name="method" className="mt-1 w-full rounded-lg border bg-white p-2 text-sm"><option value="KNOWLEDGE_QUESTION">Knowledge question</option><option value="DISCUSSION">Manager discussion</option><option value="MANAGER_OBSERVATION">Manager observation</option></select></label><label className="text-xs font-bold">Outcome<select name="outcome" className="mt-1 w-full rounded-lg border bg-white p-2 text-sm"><option value="SATISFACTORY">Satisfactory</option><option value="SUPPORT_REQUIRED">Support required</option><option value="OBSERVATION_REQUIRED">Observation required</option></select></label></div><label className="block text-xs font-bold">Decision evidence<textarea name="notes" required minLength={10} rows={3} className="mt-1 w-full rounded-lg border bg-white p-2 text-sm" placeholder="Record what was checked, observed or discussed and why the outcome is justified."/></label><button disabled={busy} className="rounded-lg bg-emerald-800 px-3 py-2 text-xs font-bold text-white">{busy ? "Saving…" : "Record manager decision"}</button>{message ? <p role="alert" className="text-xs text-red-700">{message}</p> : null}</form>;
}

export function CompetencyRequirementForm({ carePlanId, courses }: { carePlanId: string; courses: { id: string; title: string }[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  return <form className="space-y-3" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { await send(`/api/care-plans/${carePlanId}/competencies`, "POST", event.currentTarget); event.currentTarget.reset(); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not add requirement."); } finally { setBusy(false); } }}><label className="block text-sm font-semibold">Required verified competency<select name="trainingCourseId" required className="mt-1 w-full rounded-xl border bg-white p-2.5"><option value="">Choose from workforce catalogue</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.title}</option>)}</select></label><label className="block text-sm font-semibold">Why it is required<textarea name="instructions" required minLength={10} rows={3} className="mt-1 w-full rounded-xl border p-2.5" placeholder="Link the competency to the current approved instruction and safe delivery."/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="critical" className="size-4"/> Missing competency is a critical deployment gap</label><button disabled={busy || !courses.length} className="rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy ? "Saving…" : "Add competency requirement"}</button>{message ? <p role="alert" className="text-sm text-red-700">{message}</p> : null}</form>;
}

export function RemoveCompetencyRequirement({ carePlanId, requirementId }: { carePlanId: string; requirementId: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false);
  return <button disabled={busy} onClick={async () => { setBusy(true); try { await send(`/api/care-plans/${carePlanId}/competencies/${requirementId}`, "DELETE", new FormData()); router.refresh(); } finally { setBusy(false); } }} className="text-xs font-bold text-red-700 disabled:opacity-50">{busy ? "Removing…" : "Remove"}</button>;
}

export function StaffAccountLinkForm({ staffId, users, currentUserId }: { staffId: string; users: { id: string; name: string; email: string }[]; currentUserId: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  return <form className="flex flex-wrap gap-2" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { await send(`/api/workforce/${staffId}/account-link`, "PATCH", event.currentTarget); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not link login."); } finally { setBusy(false); } }}><select name="userId" defaultValue={currentUserId} className="min-w-64 flex-1 rounded-xl border bg-white p-2.5 text-sm"><option value="">No linked login</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select><button disabled={busy} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">{busy ? "Saving…" : "Save login link"}</button>{message ? <p role="alert" className="w-full text-sm text-red-700">{message}</p> : null}</form>;
}
