import Image from "next/image";
import Link from "next/link";
import { CARE_PLAN_SECTIONS, carePlanStatusLabel, parseCarePlanSnapshot } from "@/lib/care-plans";

export function CarePlanView({plan,version,person,organisation,location,coordinator,manager,actions,evidence,acknowledgements,quick=false,print=false,canViewRestricted=false}:{
  plan:{id:string;reference:string;status:string;overallRisk:string;effectiveDate:Date|null;nextReviewDate:Date|null;currentVersionNumber:number;localAuthorityName:string|null;commissioner:string|null;linkedActionIds:string[]};
  version:{versionNumber:number;snapshot:unknown;status:string;publishedAt:Date|null;materialSections:string[];sourceReviewEntryId:string|null};
  person:{name:string;preferredName:string;reference:string;phone:string;address:string;communicationSummary:string;emergencyContact:string;allergies?:string};
  organisation:{name:string;hasLogo:boolean};location:string;coordinator:string;manager:string;
  actions:{id:string;reference:string;title:string;priority:string;status:string}[]; evidence:{id:string;title:string}[];
  acknowledgements:{name:string;at:Date}[];quick?:boolean;print?:boolean;canViewRestricted?:boolean;
}){
  const snapshot=parseCarePlanSnapshot(version.snapshot),about=object(snapshot.aboutMe),communication=object(snapshot.communication),medication=object(snapshot.medication),deterioration=object(snapshot.deterioration),implementation=object(snapshot.implementation),safeguarding=object(snapshot.safeguarding),risks=array(snapshot.risks);
  if(quick)return <article className="mx-auto max-w-5xl bg-white text-slate-950"><Brand organisation={organisation}/><h1 className="mt-6 border-b-4 border-emerald-700 pb-2 text-3xl font-bold">WHAT STAFF NEED TO KNOW TODAY</h1><div className="mt-5 grid gap-4 md:grid-cols-3"><Card title="Person"><Line label="Preferred name" value={person.preferredName}/><Line label="Reference" value={person.reference}/><Line label="Communication" value={text(communication.staffApproach)||person.communicationSummary}/></Card><Card title="Current plan"><Line label="Version" value={`v${version.versionNumber}`}/><Line label="Effective" value={date(plan.effectiveDate)}/><Line label="Overall risk" value={plan.overallRisk}/><Line label="Acknowledged" value={`${acknowledgements.length} staff`}/></Card><Card title="Emergency"><Line label="Contact" value={person.emergencyContact}/><Line label="Escalation" value={text(deterioration.redFlags)||"Follow emergency escalation plan"}/></Card></div><div className="mt-5 grid gap-5 md:grid-cols-2"><Block title="What matters and how to support me" value={`${text(about.ownWords)}\n\n${text(about.independence)}`}/><Block title="Critical allergies and medication" value={`${text(object(snapshot.healthSummary).allergies)}\nMedication responsibility: ${text(medication.responsibility)}\n${text(medication.exceptions)}`}/><Block title="Key risks and controls" value={risks.map((risk)=>`${text(risk.title)} (${text(risk.riskLevel)}): ${text(risk.preventiveControls)}. Response: ${text(risk.response)}`).join("\n\n")}/><Block title="Today's essential care" value={text(implementation.dailyInstructions)}/><Block title="Current safeguarding controls" value={`Preventive measures: ${text(safeguarding.preventiveMeasures)}\nStaff boundaries: ${text(safeguarding.staffBoundaries)}\nLook for: ${text(safeguarding.whatStaffShouldLookFor)}\nRecord: ${text(safeguarding.whatStaffMustRecord)}\nImmediate action: ${text(safeguarding.immediateSafetyAction)}\nInternal escalation: ${text(safeguarding.internalEscalation)}`}/><Block title="Clinical alerts" value={`Warning signs: ${text(deterioration.warningSigns)}\nRed flags: ${text(deterioration.redFlags)}`}/><Block title="Recent material changes" value={text(implementation.materialChanges)||version.materialSections.join(", ")}/></div><p className="mt-6 rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-900">Generated from approved Care Plan {plan.reference} v{version.versionNumber}. This guide is not an independent clinical record. Open the full plan for complete instructions.</p></article>;
  return <article className={`bg-white text-slate-950 ${print?"mx-auto max-w-[190mm]":"rounded-2xl border shadow-sm"}`}><Brand organisation={organisation}/><div className="border-b bg-slate-50 px-6 py-4 text-xs"><span className="font-bold">{organisation.name}</span><span className="mx-3">•</span>Confidential person-centred care record<span className="mx-3">•</span>{plan.reference} v{version.versionNumber}</div><header className="bg-gradient-to-br from-emerald-950 to-emerald-700 p-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.2em]">Person-centred care plan</p><h1 className="mt-2 text-3xl font-bold">{person.preferredName}</h1><p className="mt-1 text-emerald-100">{person.reference} • {location} • {carePlanStatusLabel(plan.status)}</p><div className="mt-5 grid gap-3 text-sm sm:grid-cols-3 lg:grid-cols-6"><Fact label="Version" value={`v${version.versionNumber}`}/><Fact label="Effective" value={date(plan.effectiveDate)}/><Fact label="Next review" value={date(plan.nextReviewDate)}/><Fact label="Overall risk" value={plan.overallRisk}/><Fact label="Open actions" value={String(actions.filter((a)=>!["COMPLETED","CANCELLED","ARCHIVED"].includes(a.status)).length)}/><Fact label="Acknowledged" value={String(acknowledgements.length)}/></div></header><div className="p-6">
    <section className="grid gap-4 md:grid-cols-2"><Card title="Plan control"><Line label="Organisation" value={organisation.name}/><Line label="Service" value={location}/><Line label="Care Coordinator" value={coordinator}/><Line label="Registered Manager" value={manager}/><Line label="Local Authority" value={plan.localAuthorityName||"Not recorded"}/><Line label="Commissioner" value={plan.commissioner||"Not recorded"}/></Card><Card title="Live person master data"><Line label="Name" value={person.name}/><Line label="Preferred name" value={person.preferredName}/><Line label="Telephone" value={person.phone}/><Line label="Address" value={person.address}/><Line label="Emergency contact" value={person.emergencyContact}/></Card></section>
    <Contents/>{CARE_PLAN_SECTIONS.map(([key,label],index)=><PlanSection key={key} number={index+1} title={label} value={key==="safeguarding"&&!canViewRestricted?{restricted:"Restricted safeguarding information. Ask an authorised manager if these instructions are required for your role."}:snapshot[key]} />)}
    <section className="mt-7 break-inside-avoid"><Heading title="Linked evidence"/><ul className="mt-3 grid gap-2 md:grid-cols-2">{evidence.length?evidence.map((item)=><li key={item.id}><Link href={`/evidence/${item.id}`} className="text-sm font-semibold text-emerald-800">{item.title}</Link></li>):<li className="text-sm text-slate-500">No Evidence Library records linked.</li>}</ul></section>
    <section className="mt-7 break-inside-avoid"><Heading title="Open and linked actions"/><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-100"><tr><th className="p-2">Reference</th><th className="p-2">Action</th><th className="p-2">Priority</th><th className="p-2">Status</th></tr></thead><tbody>{actions.map((action)=><tr key={action.id} className="border-t"><td className="p-2"><Link href={`/actions/${action.id}`} className="font-mono text-emerald-800">{action.reference}</Link></td><td className="p-2">{action.title}</td><td className="p-2">{action.priority}</td><td className="p-2">{action.status}</td></tr>)}</tbody></table></div></section>
    <section className="mt-7 break-inside-avoid"><Heading title="Version acknowledgement"/>{acknowledgements.length?<ul className="mt-3 text-sm">{acknowledgements.map((item,index)=><li key={`${item.name}-${index}`}>{item.name} • {dateTime(item.at)}</li>)}</ul>:<p className="mt-3 text-sm text-slate-500">No acknowledgement recorded for this version.</p>}</section>
  </div><footer className="border-t px-6 py-4 text-center text-xs text-slate-500">CONFIDENTIAL • {plan.reference} • Version {version.versionNumber} • Controlled copy when viewed in QCGMS</footer></article>;
}

function Brand({organisation}:{organisation:{name:string;hasLogo:boolean}}){return <div className="flex items-center gap-4 bg-white px-6 py-4">{organisation.hasLogo?<Image src="/api/settings/policy-branding/logo" alt={`${organisation.name} logo`} width={120} height={56} className="max-h-14 w-auto object-contain"/>:<div className="grid size-12 place-items-center rounded-xl bg-emerald-800 text-lg font-bold text-white">{organisation.name.slice(0,2).toUpperCase()}</div>}<div><p className="font-bold">{organisation.name}</p><p className="text-xs text-slate-500">Controlled clinical care record</p></div></div>}
function Contents(){return <section className="mt-7 break-inside-avoid"><Heading title="Contents"/><ol className="mt-3 grid gap-1 text-sm md:grid-cols-2">{CARE_PLAN_SECTIONS.map(([,label],index)=><li key={label}>{index+1}. {label}</li>)}</ol></section>}
function PlanSection({number,title,value}:{number:number;title:string;value:unknown}){return <section className="mt-7 break-inside-avoid"><Heading title={`${number}. ${title}`}/><Render value={value}/></section>}
function Render({value}:{value:unknown}):React.ReactNode{if(value==null||value==="")return <p className="mt-3 text-sm text-slate-500">Not recorded.</p>;if(Array.isArray(value))return value.length?<div className="mt-3 space-y-3">{value.map((item,index)=><div key={index} className="rounded-xl border p-4"><Render value={item}/></div>)}</div>:<p className="mt-3 text-sm text-slate-500">No items recorded.</p>;if(typeof value==="object")return <dl className="mt-3 grid gap-x-5 gap-y-3 md:grid-cols-2">{Object.entries(value as Record<string,unknown>).filter(([,v])=>v!==""&&v!=null&&!(Array.isArray(v)&&!v.length)).map(([key,item])=><div key={key} className={Array.isArray(item)||typeof item==="object"?"md:col-span-2":""}><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{pretty(key)}</dt><dd className="mt-1 whitespace-pre-wrap text-sm"><RenderInline value={item}/></dd></div>)}</dl>;return <p className="mt-3 whitespace-pre-wrap text-sm">{String(value)}</p>}
function RenderInline({value}:{value:unknown}){if(Array.isArray(value)||typeof value==="object")return <Render value={value}/>;return String(value)}
function Heading({title}:{title:string}){return <h2 className="border-b-2 border-emerald-700 pb-2 text-lg font-bold text-emerald-900">{title}</h2>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border p-4"><h2 className="font-bold text-emerald-900">{title}</h2><div className="mt-3 space-y-2 text-sm">{children}</div></div>}
function Block({title,value}:{title:string;value:string}){return <section className="rounded-2xl border p-4"><h2 className="font-bold text-emerald-900">{title}</h2><p className="mt-2 whitespace-pre-wrap text-sm">{value||"Not recorded"}</p></section>}
function Line({label,value}:{label:string;value:string}){return <p><strong>{label}:</strong> {value||"Not recorded"}</p>}
function Fact({label,value}:{label:string;value:string}){return <div><p className="text-[10px] uppercase tracking-widest text-emerald-200">{label}</p><p className="font-bold">{value}</p></div>}
function object(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}function array(value:unknown):Record<string,unknown>[]{return Array.isArray(value)?value.filter((x):x is Record<string,unknown>=>Boolean(x&&typeof x==="object"&&!Array.isArray(x))):[]}function text(value:unknown){return String(value??"")}function pretty(value:string){return value.replace(/([A-Z])/g," $1").replace(/^./,(c)=>c.toUpperCase())}function date(value:Date|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeZone:"Europe/London"}).format(value):"Not set"}function dateTime(value:Date){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/London"}).format(value)}
