"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, Plus, Trash2 } from "lucide-react";
import { CARE_PLAN_ASSURANCE_TESTS, CARE_PLAN_DOMAINS, type CarePlanSnapshot } from "@/lib/care-plans";

type Option = { id: string; name: string };
type Initial = {
  id: string; reference: string; locationId: string; clientId: string; careCoordinatorId: string;
  registeredManagerId: string; status: string; overallRisk: string; nextReviewDate: string;
  serviceType: string; fundingType: string; localAuthorityCode: string; localAuthorityName: string;
  commissioner: string; snapshot: CarePlanSnapshot; evidenceIds: string[]; staffIds: string[];
};

const STEPS = ["Plan control", "About me", "Communication & consent", "Outcomes & package", "Health & domains", "Medication & deterioration", "Risks & safeguarding", "Staff implementation", "Assurance"];
const input = "mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:border-emerald-600 focus:outline-none";

export function CarePlanForm({ organisationName, person, locations, users, staff, evidence, initial }: {
  organisationName: string;
  person: { id: string; name: string; reference: string; preferredName: string; dateOfBirth: string; phone: string; address: string; communicationSummary: string; emergencyContact: string; representative: string };
  locations: Option[]; users: Option[]; staff: Option[]; evidence: Option[]; initial?: Initial;
}) {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [snapshot, setSnapshot] = useState<CarePlanSnapshot>(() => initial?.snapshot ?? { schemaVersion: 1, aboutMe: {}, communication: {}, capacityConsent: {}, outcomes: [], carePackage: { visits: [] }, healthSummary: {}, domains: [], medication: {}, deterioration: { escalationRows: [] }, risks: [], safeguarding: {}, professionals: {}, implementation: {}, actions: {}, approval: { assurance: {} } });
  const [evidenceIds, setEvidenceIds] = useState(initial?.evidenceIds ?? []);
  const [staffIds, setStaffIds] = useState(initial?.staffIds ?? []);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  const section = (key: string) => object(snapshot[key]);
  const setSection = (key: string, patch: Record<string, unknown>) => setSnapshot((current) => ({ ...current, [key]: { ...object(current[key]), ...patch } }));
  const list = (key: string) => Array.isArray(snapshot[key]) ? snapshot[key] as Record<string, unknown>[] : [];
  const setList = (key: string, value: Record<string, unknown>[]) => setSnapshot((current) => ({ ...current, [key]: value }));

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    const form = new FormData(event.currentTarget);
    form.set("snapshot", JSON.stringify(snapshot));
    evidenceIds.forEach((id) => form.append("evidenceIds", id));
    staffIds.forEach((id) => form.append("staffIds", id));
    const response = await fetch(initial ? `/api/care-plans/${initial.id}` : "/api/care-plans", { method: initial ? "PATCH" : "POST", body: form });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) { setError(result.error ?? "Could not save the care plan."); setBusy(false); return; }
    router.push(`/care-plans/${initial?.id ?? result.id}`); router.refresh();
  }

  const domains = list("domains"), outcomes = list("outcomes"), risks = list("risks");
  const visits = Array.isArray(section("carePackage").visits) ? section("carePackage").visits as Record<string, unknown>[] : [];
  const escalationRows = Array.isArray(section("deterioration").escalationRows) ? section("deterioration").escalationRows as Record<string, unknown>[] : [];
  const assurance = object(section("approval").assurance);

  return <form onSubmit={submit} className="space-y-5">
    <div className="sticky top-0 z-20 rounded-2xl border border-slate-700 bg-slate-950 p-4 text-white shadow-xl print:hidden">
      <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Fact label="Person" value={person.name}/><Fact label="Reference" value={initial?.reference || "Generated on save"}/><Fact label="Organisation" value={organisationName}/><Fact label="Version" value={initial ? "Controlled draft" : "Initial draft"}/><Fact label="Next review" value={initial?.nextReviewDate || "Set below"}/><Fact label="Status" value={initial?.status || "Draft"}/></div>
    </div>
    {error ? <div role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm font-bold text-red-800">{error}</div> : null}
    <div className="grid gap-5 xl:grid-cols-[240px_minmax(0,1fr)_280px]">
      <nav className="rounded-2xl border bg-white p-3 xl:sticky xl:top-28 xl:self-start"><p className="px-3 pb-2 text-xs font-bold uppercase tracking-widest text-emerald-700">Care-plan pathway</p>{STEPS.map((name, index) => <button key={name} type="button" onClick={() => setStep(index)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left text-xs font-semibold ${step === index ? "bg-emerald-800 text-white" : "hover:bg-slate-100"}`}><span className="grid size-6 place-items-center rounded-full bg-white/15">{index < step ? <CheckCircle2 size={14}/> : index + 1}</span>{name}</button>)}</nav>
      <div className="min-w-0 rounded-2xl border bg-white p-5 shadow-sm sm:p-7">
        <Panel active={step===0} eyebrow="Controlled record" title="Plan control and person master data" description="Select accountable roles and review dates. Person details below remain live from the Client Directory and are not duplicated into this version.">
          <div className="mb-6 grid gap-3 rounded-2xl bg-slate-50 p-4 text-sm md:grid-cols-2"><Read label="Person reference" value={person.reference}/><Read label="Preferred name" value={person.preferredName}/><Read label="Date of birth" value={person.dateOfBirth}/><Read label="Telephone" value={person.phone}/><Read label="Address" value={person.address}/><Read label="Representative" value={person.representative}/></div>
          <input type="hidden" name="clientId" value={person.id}/><div className="grid gap-4 md:grid-cols-2"><Select name="locationId" label="Service location" options={locations} initial={initial?.locationId} required/><Select name="careCoordinatorId" label="Care Coordinator" options={users} initial={initial?.careCoordinatorId} required/><Select name="registeredManagerId" label="Registered Manager" options={users} initial={initial?.registeredManagerId} required/><Field name="nextReviewDate" label="Next review date" type="date" initial={initial?.nextReviewDate} required/><Field name="serviceType" label="Service type" initial={initial?.serviceType} placeholder="For example, domiciliary care"/><Select name="fundingType" label="Funding arrangement" values={["Self-funded","Local Authority","NHS / ICB","Joint funded","Other"]} initial={initial?.fundingType}/><Field name="localAuthorityName" label="Responsible Local Authority" initial={initial?.localAuthorityName}/><Field name="localAuthorityCode" label="Authority GSS code" initial={initial?.localAuthorityCode}/><Field name="commissioner" label="Commissioner / social worker" initial={initial?.commissioner}/><Select name="overallRisk" label="Overall risk" values={["LOW","MEDIUM","HIGH","CRITICAL"]} initial={initial?.overallRisk || "LOW"}/><Select name="status" label="Plan status" values={["DRAFT","AWAITING_PERSON_AGREEMENT","AWAITING_CLINICAL_INFORMATION","AWAITING_APPROVAL"]} initial={initial?.status || "DRAFT"}/><Area name="reason" label="Reason for this version" initial="Initial person-centred care plan" required/></div>
        </Panel>

        <Panel active={step===1} eyebrow="Section 1" title="About Me & what matters to me" description="Write in the person's own language wherever possible.">
          <Grid><Field label="How I prefer to be known" value={text(section("aboutMe").preferredName)} onChange={(v)=>setSection("aboutMe",{preferredName:v})}/><Area label="What is important to me" value={text(section("aboutMe").importantToMe)} onChange={(v)=>setSection("aboutMe",{importantToMe:v})} wide/><Area label="People important to me" value={text(section("aboutMe").importantPeople)} onChange={(v)=>setSection("aboutMe",{importantPeople:v})}/><Area label="My background, culture, religion and beliefs" value={text(section("aboutMe").background)} onChange={(v)=>setSection("aboutMe",{background:v})}/><Area label="My routines, interests and preferred activities" value={text(section("aboutMe").routines)} onChange={(v)=>setSection("aboutMe",{routines:v})}/><Area label="Things I enjoy / dislike" value={text(section("aboutMe").likesDislikes)} onChange={(v)=>setSection("aboutMe",{likesDislikes:v})}/><Area label="What makes a good or difficult day" value={text(section("aboutMe").goodDifficultDay)} onChange={(v)=>setSection("aboutMe",{goodDifficultDay:v})}/><Area label="Anxiety, distress and reassurance" value={text(section("aboutMe").reassurance)} onChange={(v)=>setSection("aboutMe",{reassurance:v})}/><Area label="Independence and support I need" value={text(section("aboutMe").independence)} onChange={(v)=>setSection("aboutMe",{independence:v})}/><Area label="Things staff must not do" value={text(section("aboutMe").mustNotDo)} onChange={(v)=>setSection("aboutMe",{mustNotDo:v})}/><Area label="Privacy, home, pets and community connections" value={text(section("aboutMe").privacyHomeCommunity)} onChange={(v)=>setSection("aboutMe",{privacyHomeCommunity:v})}/><Area label="What I want the people supporting me to know" value={text(section("aboutMe").ownWords)} onChange={(v)=>setSection("aboutMe",{ownWords:v})} wide highlight/></Grid>
        </Panel>

        <Panel active={step===2} eyebrow="Sections 2–3" title="Communication, capacity and consent" description="Capacity is decision-specific. Record lawful authority and least-restrictive controls, not blanket statements.">
          <Grid><Field label="Preferred method and primary language" value={text(section("communication").methodLanguage)} onChange={(v)=>setSection("communication",{methodLanguage:v})}/><Area label="How I express pain, distress, choices, consent and refusal" value={text(section("communication").expression)} onChange={(v)=>setSection("communication",{expression:v})}/><Area label="Aids, interpreter, hearing, visual and Easy Read support" value={text(section("communication").adjustments)} onChange={(v)=>setSection("communication",{adjustments:v})}/><Area label="How staff should speak with me" value={text(section("communication").staffApproach)} onChange={(v)=>setSection("communication",{staffApproach:v})}/><Area label="What staff should avoid and escalation if communication changes" value={text(section("communication").avoidEscalation)} onChange={(v)=>setSection("communication",{avoidEscalation:v})}/><Area label="Decision-specific capacity records" value={text(section("capacityConsent").decisions)} onChange={(v)=>setSection("capacityConsent",{decisions:v})} placeholder="Decision; assessment date; outcome; assessor; review date; linked evidence"/><Area label="Representative and verified authority" value={text(section("capacityConsent").representativeAuthority)} onChange={(v)=>setSection("capacityConsent",{representativeAuthority:v})}/><Area label="Consent arrangements, best interests and advance decisions" value={text(section("capacityConsent").consentArrangements)} onChange={(v)=>setSection("capacityConsent",{consentArrangements:v})}/><Area label="Restrictions and least-restrictive controls" value={text(section("capacityConsent").restrictions)} onChange={(v)=>setSection("capacityConsent",{restrictions:v})}/><Area label="Staff instructions and review triggers" value={text(section("capacityConsent").staffInstructions)} onChange={(v)=>setSection("capacityConsent",{staffInstructions:v})}/></Grid>
        </Panel>

        <Panel active={step===3} eyebrow="Sections 4–5" title="Outcomes and commissioned care package" description="Outcomes retain history. Package concerns become proposals and actions; commissioned hours are never silently changed.">
          <Repeater title="Outcome cards" items={outcomes} setItems={(v)=>setList("outcomes",v)} template={{ outcome:"", whyItMatters:"", currentPosition:"", independence:"", supportRequired:"", staffActions:"", measure:"", target:"", reviewDate:"", progress:"Not started" }} fields={["outcome","whyItMatters","currentPosition","independence","supportRequired","staffActions","measure","target","reviewDate","progress"]}/>
          <div className="mt-6"><Grid><SelectValue label="Package sufficiency" value={text(section("carePackage").sufficiency)} values={["Safe and sufficient","Review required","Insufficient / unsafe"]} onChange={(v)=>setSection("carePackage",{sufficiency:v})}/><Field label="Commissioned start date" type="date" value={text(section("carePackage").startDate)} onChange={(v)=>setSection("carePackage",{startDate:v})}/><Area label="Commissioned package and funding limits" value={text(section("carePackage").commissionedPackage)} onChange={(v)=>setSection("carePackage",{commissionedPackage:v})} wide/></Grid></div>
          <Repeater title="Visits and support periods" items={visits} setItems={(v)=>setSection("carePackage",{visits:v})} template={{ visitName:"", scheduledWindow:"", duration:"", workers:"1", competencies:"", purpose:"", essentialTasks:"", optionalTasks:"", responsibilities:"", escalation:"", documentation:"", refusalNotHome:"", lateMissedCall:"" }} fields={["visitName","scheduledWindow","duration","workers","competencies","purpose","essentialTasks","optionalTasks","responsibilities","escalation","documentation","refusalNotHome","lateMissedCall"]}/>
        </Panel>

        <Panel active={step===4} eyebrow="Sections 6–7" title="Health summary and dynamic care domains" description="Select only applicable domains. Each domain follows one consistent operational structure.">
          <Grid><Area label="Conditions, diagnoses, symptoms and baseline" value={text(section("healthSummary").conditionsBaseline)} onChange={(v)=>setSection("healthSummary",{conditionsBaseline:v})}/><Area label="Recent changes and relevant history" value={text(section("healthSummary").recentChanges)} onChange={(v)=>setSection("healthSummary",{recentChanges:v})}/><Area label="Allergies and intolerances" value={text(section("healthSummary").allergies)} onChange={(v)=>setSection("healthSummary",{allergies:v})}/><Area label="Pain, vision, hearing, oral care, sleep and infection risks" value={text(section("healthSummary").otherHealth)} onChange={(v)=>setSection("healthSummary",{otherHealth:v})}/><Area label="Healthcare professionals and services" value={text(section("healthSummary").professionals)} onChange={(v)=>setSection("healthSummary",{professionals:v})} wide/></Grid>
          <div className="mt-6 rounded-2xl border p-4"><h3 className="font-bold">Applicable care domains</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{CARE_PLAN_DOMAINS.map((name)=><label key={name} className="flex gap-2 text-xs"><input type="checkbox" checked={domains.some((d)=>d.name===name)} onChange={(e)=>setList("domains",e.target.checked?[...domains,{name,riskLevel:"LOW",currentNeed:"",strengths:"",independence:"",support:"",preferences:"",triggers:"",warningSigns:"",staffInstructions:"",mustNotDo:"",controls:"",escalationThreshold:"",emergencyResponse:"",professionals:"",outcome:"",measure:"",reviewFrequency:""}]:domains.filter((d)=>d.name!==name))}/>{name}</label>)}</div></div>
          {domains.map((domain,index)=><div key={`${domain.name}-${index}`} className="mt-4 rounded-2xl border-2 border-emerald-100 p-4"><div className="flex justify-between"><h3 className="font-bold text-emerald-900">{text(domain.name)}</h3><SelectValue label="Risk" value={text(domain.riskLevel)||"LOW"} values={["LOW","MEDIUM","HIGH","CRITICAL"]} onChange={(v)=>update(list("domains"),setList,index,{riskLevel:v})}/></div><Grid><Area label="Current need / clinical information" value={text(domain.currentNeed)} onChange={(v)=>update(list("domains"),setList,index,{currentNeed:v})}/><Area label="Strengths and what I manage independently" value={text(domain.independence)} onChange={(v)=>update(list("domains"),setList,index,{independence:v})}/><Area label="Support and preferences" value={text(domain.support)} onChange={(v)=>update(list("domains"),setList,index,{support:v})}/><Area label="Triggers, warning signs and deterioration" value={text(domain.warningSigns)} onChange={(v)=>update(list("domains"),setList,index,{warningSigns:v})}/><Area label="Specific staff instructions" value={text(domain.staffInstructions)} onChange={(v)=>update(list("domains"),setList,index,{staffInstructions:v})}/><Area label="What staff must NOT do" value={text(domain.mustNotDo)} onChange={(v)=>update(list("domains"),setList,index,{mustNotDo:v})}/><Area label="Controls and preventive support" value={text(domain.controls)} onChange={(v)=>update(list("domains"),setList,index,{controls:v})}/><Area label="Escalation threshold, contacts and emergency response" value={text(domain.escalationThreshold)} onChange={(v)=>update(list("domains"),setList,index,{escalationThreshold:v})}/><Area label="Outcome and progress measure" value={text(domain.outcome)} onChange={(v)=>update(list("domains"),setList,index,{outcome:v})}/><Field label="Review frequency" value={text(domain.reviewFrequency)} onChange={(v)=>update(list("domains"),setList,index,{reviewFrequency:v})}/></Grid></div>)}
        </Panel>

        <Panel active={step===5} eyebrow="Sections 8–10" title="Medication and clinical deterioration" description="Reference live eMAR where available. A medicines change triggers reconciliation rather than unsafe assumptions.">
          <Grid><SelectValue label="Medication responsibility" value={text(section("medication").responsibility)} values={["Provider administers","Provider prompts","Person self-administers","Family","Mixed","Other"]} onChange={(v)=>setSection("medication",{responsibility:v})}/><Field label="Authoritative medication source" value={text(section("medication").source)||"LIVE eMAR"} onChange={(v)=>setSection("medication",{source:v})}/><Area label="Storage, access, prompting, witnessing and PRN arrangements" value={text(section("medication").arrangements)} onChange={(v)=>setSection("medication",{arrangements:v})}/><Area label="Time-critical, controlled, topical, PEG or covert medicines" value={text(section("medication").specialRequirements)} onChange={(v)=>setSection("medication",{specialRequirements:v})}/><Area label="Refusal, out-of-stock, missed-dose and error process" value={text(section("medication").exceptions)} onChange={(v)=>setSection("medication",{exceptions:v})}/><Area label="Clinical advice, pharmacy contact and competency requirements" value={text(section("medication").escalationCompetency)} onChange={(v)=>setSection("medication",{escalationCompetency:v})}/><SelectValue label="Medication reconciliation" value={text(section("medication").reconciliation)} values={["Not required","Required","Completed and verified"]} onChange={(v)=>setSection("medication",{reconciliation:v})}/></Grid>
          <div className="mt-6 rounded-2xl border-2 border-red-200 bg-red-50/40 p-4"><h3 className="font-bold text-red-900">WHEN I BECOME UNWELL</h3><Grid><Area label="My normal baseline" value={text(section("deterioration").baseline)} onChange={(v)=>setSection("deterioration",{baseline:v})}/><Area label="Warning signs" value={text(section("deterioration").warningSigns)} onChange={(v)=>setSection("deterioration",{warningSigns:v})}/><Area label="Red flags and 999 triggers" value={text(section("deterioration").redFlags)} onChange={(v)=>setSection("deterioration",{redFlags:v})}/><Area label="111, GP, community, crisis and on-call routes" value={text(section("deterioration").routes)} onChange={(v)=>setSection("deterioration",{routes:v})}/></Grid><Repeater title="Escalation table" items={escalationRows} setItems={(v)=>setSection("deterioration",{escalationRows:v})} template={{trigger:"",expectedRange:"",concernLevel:"Monitor",immediateAction:"",contact:"",timescale:"",information:"",documentation:""}} fields={["trigger","expectedRange","concernLevel","immediateAction","contact","timescale","information","documentation"]}/></div>
        </Panel>

        <Panel active={step===6} eyebrow="Sections 10–11" title="Structured risks and safeguarding" description="Risks remain structured and versioned. Confidential safeguarding instructions are restricted by role permissions.">
          <Repeater title="Care-plan risks" items={risks} setItems={(v)=>setList("risks",v)} template={{title:"",domain:"",hazard:"",whoMayBeHarmed:"",likelihood:"1",impact:"1",riskLevel:"LOW",preventiveControls:"",warningSigns:"",response:"",escalation:"",residualRisk:"LOW",owner:"",reviewDate:"",evidence:""}} fields={["title","domain","hazard","whoMayBeHarmed","likelihood","impact","riskLevel","preventiveControls","warningSigns","response","escalation","residualRisk","owner","reviewDate","evidence"]}/>
          <div className="mt-6"><Grid><Area label="Vulnerabilities and current safeguarding context" value={text(section("safeguarding").vulnerabilities)} onChange={(v)=>setSection("safeguarding",{vulnerabilities:v})}/><Area label="Exploitation, financial, domestic abuse and self-neglect risks" value={text(section("safeguarding").riskAreas)} onChange={(v)=>setSection("safeguarding",{riskAreas:v})}/><Area label="Preventive controls and staff boundaries" value={text(section("safeguarding").controls)} onChange={(v)=>setSection("safeguarding",{controls:v})}/><Area label="What staff must look for and record" value={text(section("safeguarding").staffInstructions)} onChange={(v)=>setSection("safeguarding",{staffInstructions:v})}/><Area label="Immediate safety, internal and external escalation" value={text(section("safeguarding").escalation)} onChange={(v)=>setSection("safeguarding",{escalation:v})} wide/></Grid></div>
        </Panel>

        <Panel active={step===7} eyebrow="Sections 12–14" title="Evidence and staff implementation" description="Link existing evidence, assign relevant workers and identify competency requirements without duplicating files or training records.">
          <Grid><Area label="Professional / MDT advice reflected in this plan" value={text(section("professionals").advice)} onChange={(v)=>setSection("professionals",{advice:v})}/><Area label="Outstanding professional referrals" value={text(section("professionals").referrals)} onChange={(v)=>setSection("professionals",{referrals:v})}/><Area label="Daily visit implementation instructions" value={text(section("implementation").dailyInstructions)} onChange={(v)=>setSection("implementation",{dailyInstructions:v})}/><Area label="Required competencies and supervision" value={text(section("implementation").competencies)} onChange={(v)=>setSection("implementation",{competencies:v})}/><Area label="Recent material changes staff must read" value={text(section("implementation").materialChanges)} onChange={(v)=>setSection("implementation",{materialChanges:v})}/><SelectValue label="Read & Understood required?" value={text(section("implementation").acknowledgementRequired)} values={["No","Yes"]} onChange={(v)=>setSection("implementation",{acknowledgementRequired:v})}/></Grid>
          <Multi title="Assigned staff" options={staff} selected={staffIds} setSelected={setStaffIds}/><Multi title="Linked Evidence Library records" options={evidence} selected={evidenceIds} setSelected={setEvidenceIds}/>
        </Panel>

        <Panel active={step===8} eyebrow="Section 15" title="Care Plan Assurance" description="This supports accountable professional judgement. It cannot be used to bypass incomplete clinical or safeguarding controls.">
          <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3">Assurance test</th><th className="p-3">Result</th><th className="p-3">Rationale / evidence</th></tr></thead><tbody>{CARE_PLAN_ASSURANCE_TESTS.map((test)=><tr key={test} className="border-t"><td className="p-3 font-semibold">{test}</td><td className="p-3"><select className="rounded-lg border p-2" value={text(assurance[test])} onChange={(e)=>setSection("approval",{assurance:{...assurance,[test]:e.target.value}})}><option value="">Choose</option><option>MET</option><option>PARTIAL</option><option>NOT MET</option><option>N/A</option></select></td><td className="p-3"><input className="w-full rounded-lg border p-2" value={text(assurance[`${test}__rationale`])} onChange={(e)=>setSection("approval",{assurance:{...assurance,[`${test}__rationale`]:e.target.value}})}/></td></tr>)}</tbody></table></div>
          <div className="mt-5 grid gap-4 md:grid-cols-2"><SelectValue label="Final decision" value={text(section("approval").decision)} values={["APPROVE AND PUBLISH","APPROVE WITH ACTIONS","RETURN FOR AMENDMENT","URGENT CLINICAL / MANAGEMENT REVIEW"]} onChange={(v)=>setSection("approval",{decision:v})}/><Area label="Approval rationale and outstanding controls" value={text(section("approval").rationale)} onChange={(v)=>setSection("approval",{rationale:v})}/></div>
          {risks.some((risk)=>risk.riskLevel==="CRITICAL") ? <div className="mt-4 flex gap-2 rounded-xl border border-red-300 bg-red-50 p-4 text-sm font-bold text-red-800"><AlertTriangle size={18}/>Critical risks require explicit Registered Manager assurance before publication.</div> : null}
        </Panel>

        <div className="mt-7 flex items-center justify-between border-t pt-5"><button type="button" disabled={step===0} onClick={()=>setStep((n)=>Math.max(0,n-1))} className="rounded-xl border px-4 py-2 text-sm font-semibold disabled:opacity-40"><ChevronLeft className="inline" size={16}/> Previous</button>{step<STEPS.length-1?<button type="button" onClick={()=>setStep((n)=>Math.min(STEPS.length-1,n+1))} className="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-bold text-white">Next <ChevronRight className="inline" size={16}/></button>:<button disabled={busy} className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?"Saving…":initial?"Save proposed version":"Create care plan"}</button>}</div>
      </div>
      <aside className="space-y-3 rounded-2xl border bg-white p-4 xl:sticky xl:top-28 xl:self-start"><h2 className="font-bold">Plan completeness</h2><Summary label="Applicable domains" value={String(domains.length)}/><Summary label="Outcomes" value={String(outcomes.length)}/><Summary label="Structured risks" value={String(risks.length)}/><Summary label="Critical risks" value={String(risks.filter((r)=>r.riskLevel==="CRITICAL").length)}/><Summary label="Evidence links" value={String(evidenceIds.length)}/><Summary label="Assigned staff" value={String(staffIds.length)}/><Summary label="Assurance tests" value={`${CARE_PLAN_ASSURANCE_TESTS.filter((test)=>assurance[test]).length}/${CARE_PLAN_ASSURANCE_TESTS.length}`}/><p className="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600">Master data remains controlled in the Client Directory. Clinical changes create a new version and comparison before publication.</p></aside>
    </div>
  </form>;
}

function object(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function text(value: unknown) { return String(value ?? ""); }
function Panel({active,eyebrow,title,description,children}:{active:boolean;eyebrow:string;title:string;description:string;children:React.ReactNode}) { return <section className={active?"":"hidden"}><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">{eyebrow}</p><h2 className="mt-1 text-2xl font-bold">{title}</h2><p className="mb-6 mt-1 text-sm leading-6 text-slate-600">{description}</p>{children}</section>; }
function Grid({children}:{children:React.ReactNode}) { return <div className="grid gap-4 md:grid-cols-2">{children}</div>; }
function Fact({label,value}:{label:string;value:string}) { return <div><p className="text-[10px] uppercase tracking-widest text-slate-400">{label}</p><p className="truncate text-xs font-bold">{value||"Not recorded"}</p></div>; }
function Read({label,value}:{label:string;value:string}) { return <p><span className="block text-xs font-semibold text-slate-500">{label}</span><strong>{value||"Not recorded"}</strong></p>; }
function Summary({label,value}:{label:string;value:string}) { return <p className="flex justify-between border-b pb-2 text-xs"><span className="text-slate-500">{label}</span><strong>{value}</strong></p>; }
function Field(props:{name?:string;label:string;initial?:string;value?:string;onChange?:(v:string)=>void;type?:string;placeholder?:string;required?:boolean}) { return <label className="text-sm font-semibold">{props.label}{props.required?" *":""}<input name={props.name} type={props.type??"text"} defaultValue={props.onChange?undefined:props.initial} value={props.onChange?props.value:undefined} onChange={props.onChange?(e)=>props.onChange?.(e.target.value):undefined} placeholder={props.placeholder} required={props.required} className={input}/></label>; }
function Area(props:{name?:string;label:string;initial?:string;value?:string;onChange?:(v:string)=>void;placeholder?:string;required?:boolean;wide?:boolean;highlight?:boolean}) { return <label className={`text-sm font-semibold ${props.wide?"md:col-span-2":""}`}>{props.label}{props.required?" *":""}<textarea name={props.name} defaultValue={props.onChange?undefined:props.initial} value={props.onChange?props.value:undefined} onChange={props.onChange?(e)=>props.onChange?.(e.target.value):undefined} placeholder={props.placeholder} required={props.required} className={`${input} min-h-28 ${props.highlight?"border-amber-400 bg-amber-50 text-lg font-semibold":""}`}/></label>; }
function Select({name,label,options,values,initial,required}:{name:string;label:string;options?:Option[];values?:string[];initial?:string;required?:boolean}) { return <label className="text-sm font-semibold">{label}{required?" *":""}<select name={name} defaultValue={initial??""} required={required} className={input}><option value="">Choose</option>{options?.map((o)=><option key={o.id} value={o.id}>{o.name}</option>)}{values?.map((v)=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label>; }
function SelectValue({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}) { return <label className="text-sm font-semibold">{label}<select value={value} onChange={(e)=>onChange(e.target.value)} className={input}><option value="">Choose</option>{values.map((v)=><option key={v}>{v}</option>)}</select></label>; }
function Multi({title,options,selected,setSelected}:{title:string;options:Option[];selected:string[];setSelected:(v:string[])=>void}) { return <fieldset className="mt-6 rounded-2xl border p-4"><legend className="px-1 font-bold">{title}</legend><div className="grid max-h-56 gap-2 overflow-y-auto sm:grid-cols-2">{options.map((o)=><label key={o.id} className="flex gap-2 rounded-lg p-2 text-xs hover:bg-slate-50"><input type="checkbox" checked={selected.includes(o.id)} onChange={(e)=>setSelected(e.target.checked?[...selected,o.id]:selected.filter((id)=>id!==o.id))}/>{o.name}</label>)}</div></fieldset>; }
function Repeater({title,items,setItems,template,fields}:{title:string;items:Record<string,unknown>[];setItems:(v:Record<string,unknown>[])=>void;template:Record<string,unknown>;fields:string[]}) { return <div className="mt-6"><div className="flex items-center justify-between"><h3 className="font-bold">{title}</h3><button type="button" onClick={()=>setItems([...items,{...template}])} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Plus className="inline" size={14}/> Add</button></div>{!items.length?<p className="mt-2 rounded-xl border border-dashed p-4 text-sm text-slate-500">No items added.</p>:items.map((item,index)=><div key={index} className="mt-3 rounded-2xl border p-4"><button type="button" onClick={()=>setItems(items.filter((_,i)=>i!==index))} className="float-right text-red-700" aria-label={`Remove ${title} item`}><Trash2 size={17}/></button><div className="grid gap-3 md:grid-cols-2">{fields.map((field)=><Field key={field} label={field.replace(/([A-Z])/g," $1").replace(/^./,(c)=>c.toUpperCase())} value={text(item[field])} onChange={(value)=>setItems(items.map((current,i)=>i===index?{...current,[field]:value}:current))}/>)}</div></div>)}</div>; }
function update(items:Record<string,unknown>[],setter:(key:string,value:Record<string,unknown>[])=>void,index:number,patch:Record<string,unknown>) { setter("domains",items.map((item,i)=>i===index?{...item,...patch}:item)); }
