import Link from "next/link";
import { OrganisationDocumentBrand } from "@/components/organisation-document-brand";
import { EVIDENCE_SOURCES, RM_ASSURANCE_TESTS, carePlanReviewData, parseReviewActions } from "@/lib/care-plan-reviews";
import { clientName } from "@/lib/clients";

type Entry = {
  id:string;reference:string;title:string;summary:string;riskLevel:string;status:string;eventDate:Date;
  data:unknown;linkedActionIds:string[];client:{id:string;firstName:string;lastName:string;preferredName:string|null;clientReference:string}|null;
  location:{name:string}|null;owner:{name:string}|null;createdBy:{name:string};
  evidenceLinks:Array<{evidence:{id:string;title:string}}>;
  history:Array<{id:string;action:string;createdAt:Date;user:{name:string}|null}>;
};
type Action = {id:string;reference:string;title:string;priority:string;status:string;dueDate:Date;owner:{name:string}};

export function CarePlanReviewView({ entry, organisation, actions, print=false }: { entry:Entry; organisation:{name:string;hasLogo:boolean}; actions:Action[]; print?:boolean }) {
  const data=carePlanReviewData(entry.data);const actionInputs=parseReviewActions(data.reviewActions);const actionMap=new Map(actions.map((action)=>[action.id,action]));
  return <div className={`space-y-6 ${print?"mx-auto max-w-[210mm] bg-white text-slate-950":""}`}>
    <header className={print?"border-b-4 border-emerald-800 pb-5":"rounded-2xl bg-slate-950 p-6 text-white"}><OrganisationDocumentBrand name={organisation.name} hasLogo={organisation.hasLogo}/><p className={`mt-4 text-xs font-bold uppercase tracking-[0.2em] ${print?"text-emerald-800":"text-emerald-300"}`}>Care plan review & Registered Manager assurance</p><h1 className="mt-1 text-3xl font-bold">{entry.reference}</h1><p className={`mt-2 ${print?"text-slate-600":"text-slate-300"}`}>{entry.client?`${clientName(entry.client)} · ${entry.client.clientReference}`:"Person not linked"} · {entry.location?.name??"Organisation-wide"}</p></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Fact label="Care plan" value={show(data.carePlanReference)}/><Fact label="Review type" value={show(data.reviewType)}/><Fact label="Review due" value={date(data.reviewDueDate)}/><Fact label="Current risk" value={entry.riskLevel}/><Fact label="Status" value={show(data.workflowStatus,"Draft")}/><Fact label="RM decision" value={show(data.rmDecision,"Outstanding")}/></section>
    <ReviewSection number="1" title="Review details"><KeyTable rows={[["Reason for review",data.reasonForReview],["Main decision required",data.mainDecisionRequired],["Review completed",date(data.reviewCompletedAt)],["Lead reviewer",entry.owner?.name],["Other professionals / staff",data.otherProfessionals],["Local authority / commissioner",data.localAuthorityName||data.otherCommissioner],["Immediate concern",data.immediateConcern],["Immediate action and outcome",join(data.immediateActionTaken,data.immediateRiskOutcome,data.rmInterimControlDecision)]]}/></ReviewSection>
    <ReviewSection number="2" title="Evidence reviewed"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="bg-slate-100"><th className="p-2">Source</th><th className="p-2">Reference</th><th className="p-2">Finding / relevance</th><th className="p-2">Current</th></tr></thead><tbody>{EVIDENCE_SOURCES.filter((source)=>array(data.evidenceReviewed).includes(source)).map((source)=>{const id=slug(source);return <tr key={source} className="border-t"><td className="p-2 font-semibold">{source}</td><td className="p-2">{show(data[`evidence_${id}_reference`])}</td><td className="p-2">{show(data[`evidence_${id}_finding`])}</td><td className="p-2">{show(data[`evidence_${id}_current`])}</td></tr>})}</tbody></table></div><KeyTable rows={[["Evidence conflict",data.evidenceConflict],["Authoritative source",data.authoritativeSource],["Records requiring reconciliation",data.recordsForReconciliation]]}/></ReviewSection>
    <ReviewSection number="3" title="Person involvement, capacity and consent"><KeyTable rows={[["Person involved",data.personInvolved],["Reason / support",join(data.involvementReason,data.involvementSupport)],["Communication support",array(data.communicationSupport).join(", ")],["Representative",join(data.representativeName,data.representativeRelationship,data.representativeAuthority)],["Capacity position",join(data.capacityConcern,data.capacityDecision,data.capacityOutcome)],["Consent",data.consentPosition],["Person's comments",data.personComments],["WHAT I WANT STAFF TO KNOW",data.whatIWantStaffToKnow]]}/></ReviewSection>
    <ReviewSection number="4" title="What matters to the person"><KeyTable rows={[["Working well",data.whatWorkingWell],["Not working well",data.whatNotWorking],["What changed",data.whatChanged],["Important now",data.importantNow],["Independence",data.independence],["Helpful support",data.supportHelps],["Distress / discomfort",data.distressTriggers],["Communication",data.communicationPreference],["Staff must not",data.staffMustNot],["Preferences reviewed",array(data.preferences).join(", ")]]}/></ReviewSection>
    <ReviewSection number="5" title="Needs and risk domains">
      <div className="space-y-3">
        {array(data.domains).map((domain) => {
          const id = slug(domain);
          const rows: Array<[string, unknown]> = [
            ["Current need", data[`domain_${id}_currentNeed`]],
            ["Change", data[`domain_${id}_change`]],
            ["Current risk", data[`domain_${id}_risk`]],
            ["Controls effective", data[`domain_${id}_controlsEffective`]],
            ["Controls", data[`domain_${id}_controls`]],
            ["Person's view", data[`domain_${id}_personView`]],
            ["Evidence", data[`domain_${id}_evidence`]],
            ["Referral / escalation", data[`domain_${id}_referral`]],
            ["Outcome and success measure", data[`domain_${id}_outcome`]],
          ];
          return <article key={domain} className="break-inside-avoid rounded-xl border p-4"><h3 className="font-bold text-emerald-900">{domain}</h3><KeyTable rows={rows}/></article>;
        })}
      </div>
    </ReviewSection>
    <ReviewSection number="6" title="Clinical escalation"><KeyTable rows={[["Baseline presentation",data.baselinePresentation],["Warning signs",data.warningSigns],["Red flags",data.redFlags],["Escalation plan",data.escalationTable],["Escalation during review",data.escalationRequired],["Concern, advice, action and outcome",data.escalationConcern],["Outcome status",data.escalationOutcomeStatus]]}/></ReviewSection>
    <ReviewSection number="7" title="Medication assurance"><KeyTable rows={[["Medication applies",data.medicationApplies],["Responsibility",data.medicationResponsibility],["Medication changed",data.medicationChanged],["Reconciliation checks",array(data.medicationChecks).join(", ")],["Discrepancy",data.medicationDiscrepancy],["Discrepancy detail",data.medicationDiscrepancyDetail]]}/></ReviewSection>
    <ReviewSection number="8" title="Safeguarding, restrictions and rights"><KeyTable rows={[["Safeguarding concern",data.safeguardingConcern],["Safeguarding record",data.safeguardingDetail],["Restrictive practice",data.restrictivePractice],["Restriction assurance",data.restrictionDetail],["Rights reviewed",array(data.rightsReviewed).join(", ")]]}/></ReviewSection>
    <ReviewSection number="9" title="Care-package sufficiency"><KeyTable rows={[["Commissioned package",data.commissionedPackage],["Actual support",data.actualSupport],["Delivery exceptions",array(data.deliveryExceptions).join(", ")],["Visit duration sufficient",data.visitDurationSufficient],["Skill mix sufficient",data.skillMixSufficient],["Continuity sufficient",data.continuitySufficient],["Overall package",data.packageOverall],["Review / interim controls",data.packageInterimControls]]}/></ReviewSection>
    <ReviewSection number="10" title="Outcomes"><KeyTable rows={[["Outcome review",data.outcomeTable],["Overall progress",data.overallProgress],["Reason",data.overallProgressReason]]}/></ReviewSection>
    <ReviewSection number="11" title="Agreed changes"><KeyTable rows={[["Changes required",data.changesRequired],["Why current plan remains suitable",data.currentPlanSuitableReason],["Agreed changes",data.agreedChanges],["Linked-record assurance",array(data.linkedRecordChecks).join(", ")],["Version control",join(data.previousPlanVersion,data.newPlanVersion,data.planEffectiveFrom)]]}/></ReviewSection>
    <ReviewSection number="12" title="Action and evidence tracker"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="bg-slate-100"><th className="p-2">Priority</th><th className="p-2">Finding / action</th><th className="p-2">Owner</th><th className="p-2">Due</th><th className="p-2">Evidence required</th><th className="p-2">Central status</th></tr></thead><tbody>{actionInputs.map((input,index)=>{const action=input.actionId?actionMap.get(input.actionId):undefined;return <tr key={input.actionId??index} className="border-t"><td className="p-2 font-bold">{input.priority}</td><td className="p-2">{input.finding}</td><td className="p-2">{action?.owner.name??"Assigned"}</td><td className="p-2">{date(input.dueDate)}</td><td className="p-2">{input.evidenceRequired}</td><td className="p-2">{action?<Link href={`/actions/${action.id}`} className="font-bold text-emerald-800">{action.reference} · {action.status}</Link>:"Awaiting creation"}</td></tr>})}</tbody></table></div></ReviewSection>
    <ReviewSection number="13" title="Staff implementation"><KeyTable rows={[["Who needs to know",array(data.staffGroups).join(", ")],["Material change",data.materialChange],["Read & Understood required",data.readUnderstoodRequired],["Acknowledgement tracker",data.readUnderstoodTable],["Competency",join(data.competencyRequired,data.competencyTable)],["Supervision",join(data.supervisionRequired,data.supervisionTable)]]}/></ReviewSection>
    <ReviewSection number="14" title="Evidence index"><div className="grid gap-2 sm:grid-cols-2">{entry.evidenceLinks.map(({evidence})=><Link key={evidence.id} href={`/evidence/${evidence.id}`} className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">{evidence.title}</Link>)}</div><p className="mt-3 whitespace-pre-wrap text-sm">{show(data.evidenceIndexNotes)}</p></ReviewSection>
    <ReviewSection number="15" title="Registered Manager assurance"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="bg-emerald-900 text-white"><th className="p-2">Test</th><th className="p-2">Result</th><th className="p-2">Comment</th></tr></thead><tbody>{RM_ASSURANCE_TESTS.map((test)=>{const id=slug(test);return <tr key={test} className="border-t"><td className="p-2 font-semibold">{test}</td><td className="p-2">{show(data[`assurance_${id}_result`])}</td><td className="p-2">{show(data[`assurance_${id}_comment`])}</td></tr>})}</tbody></table></div><KeyTable rows={[["Final RM decision",data.rmDecision],["RM rationale",data.rmRationale],["Outstanding actions",data.outstandingActions],["Interim safety controls",data.interimSafetyControls],["Next review",date(data.nextReviewDate)],["RM name",data.rmName],["Electronic sign-off",dateTime(data.rmSignOffAt)]]}/></ReviewSection>
    {!print?<ReviewSection number="" title="Immutable review history"><div className="divide-y">{entry.history.map((item)=><div key={item.id} className="flex justify-between gap-4 py-3 text-sm"><div><strong>{item.action}</strong><p className="text-slate-500">{item.user?.name??"System"}</p></div><time>{dateTime(item.createdAt)}</time></div>)}</div></ReviewSection>:null}
    {print?<footer className="mt-8 border-t pt-3 text-xs text-slate-500">Confidential care governance record · {organisation.name} · {entry.reference}</footer>:null}
  </div>;
}

function ReviewSection({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="break-inside-avoid rounded-2xl border border-slate-200 bg-white p-5 print:rounded-none print:border-x-0 print:px-0"><h2 className="border-b-2 border-emerald-700 pb-2 text-lg font-bold">{number?`${number}. `:""}{title}</h2><div className="mt-4">{children}</div></section>;}
function Fact({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-white p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>;}
function KeyTable({rows}:{rows:Array<[string,unknown]>}){return <dl className="grid gap-px overflow-hidden rounded-xl border bg-slate-200 md:grid-cols-2">{rows.filter(([,value])=>show(value)!=="Not recorded").map(([label,value])=><div key={label} className="bg-white p-3"><dt className="text-xs font-semibold text-slate-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{show(value)}</dd></div>)}</dl>;}
function show(value:unknown,fallback="Not recorded"){const text=String(value??"").trim();return text||fallback;}
function array(value:unknown){return Array.isArray(value)?value.map(String):[];}
function slug(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
function date(value:unknown){const raw=String(value??"");if(!raw)return"Not set";const parsed=new Date(raw);return Number.isNaN(parsed.getTime())?raw:new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(parsed);}
function dateTime(value:unknown){const raw=String(value??"");if(!raw)return"Not set";const parsed=new Date(raw);return Number.isNaN(parsed.getTime())?raw:new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(parsed);}
function join(...values:unknown[]){return values.map((value)=>String(value??"").trim()).filter(Boolean).join("\n");}
