"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { EVIDENCE_CONFIDENTIALITY, EVIDENCE_STATUSES } from "@/lib/evidence";
import { CORE_EVIDENCE_FAMILIES } from "@/lib/evidence-taxonomy";
import { FormPurpose } from "@/components/form-purpose";
import { evidenceRequirementByKey, type EvidenceRequirement } from "@/lib/evidence-requirements";
import { EVIDENCE_SOURCE_TYPES, evidenceAssuranceLabel } from "@/lib/evidence-assurance";

type Option = { id: string; name: string };
type PolicyOption = { id: string; title: string };
type Initial = { id: string; title: string; description: string; category: string; evidenceType: string; taxonomyFamilyKey:string; taxonomyTypeKey:string; providerEvidenceTypeId:string; currentnessStatus:string; ownerId: string; locationId: string; evidenceDate: string; reviewExpiryDate: string; tags: string; relatedModule: string; relatedRecordId: string; confidentiality: string; status: string; notes: string; sourceType: string; sourceName: string; sourceReference: string; sourceUrl: string; originalAuthor: string; capturedAt: string; provenanceNote: string };
const field = "mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900";

export function EvidenceForm({ owners, locations, policies, providerTypes, initial, requirement }: { owners: Option[]; locations: Option[]; policies: PolicyOption[]; providerTypes:{id:string;familyKey:string;label:string}[]; initial?: Initial; requirement?: EvidenceRequirement }) {
  const router = useRouter();
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [familyKey,setFamilyKey]=useState(initial?.taxonomyFamilyKey??"");
  const linkedRequirement = requirement ?? (initial?.relatedModule === "EvidenceRequirement" ? evidenceRequirementByKey(initial.relatedRecordId) : undefined);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    const response = await fetch(initial ? `/api/evidence/${initial.id}` : "/api/evidence", { method: initial ? "PATCH" : "POST", body: new FormData(event.currentTarget) });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) { setError(result.error ?? "We couldn’t save this evidence. Please check the details and try again."); setBusy(false); return; }
    router.push(`/evidence/${initial?.id ?? result.id}`); router.refresh();
  }
  return <form onSubmit={submit} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
    <FormPurpose title={linkedRequirement ? linkedRequirement.title : "Governance evidence record"} description={linkedRequirement ? linkedRequirement.description : "Upload the actual source document, describe what it proves and assign the right owner, location, date and confidentiality."} steps={["Describe the evidence", "Classify and assign it", "Upload and set review dates"]} />
    {linkedRequirement ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><p><strong>Regulatory basis:</strong> {linkedRequirement.regulations.join(" · ")}</p><p className="mt-1"><strong>Expected review:</strong> {linkedRequirement.frequency}</p><input type="hidden" name="relatedModule" value="EvidenceRequirement" /><input type="hidden" name="relatedRecordId" value={linkedRequirement.key} /></div> : null}
    {error && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="grid gap-4 md:grid-cols-2">
      <label className="md:col-span-2 text-sm font-medium">Title {initial ? null : <span className="font-normal text-slate-500">(optional for a single file; filenames are used for multiple files)</span>}<input className={field} name="title" defaultValue={initial?.title ?? requirement?.title} required={Boolean(initial || requirement)} maxLength={180} /></label>
      <label className="md:col-span-2 text-sm font-medium">What does this evidence demonstrate?<textarea className={`${field} min-h-20`} name="description" defaultValue={initial?.description ?? requirement?.description} placeholder="For example, completed competency observations show staff can administer medicines safely." /></label>
      <fieldset className="md:col-span-2 grid gap-4 rounded-xl border border-blue-200 bg-blue-50 p-4 md:grid-cols-2"><legend className="px-2 text-sm font-bold text-blue-950">Source and provenance</legend><p className="md:col-span-2 text-xs text-blue-900">Record where the evidence came from. Uploading a file does not verify its authenticity, currency or relevance.</p><label className="text-sm font-medium">Source type<select className={field} name="sourceType" defaultValue={initial?.sourceType ?? "UPLOADED_DOCUMENT"} required>{EVIDENCE_SOURCE_TYPES.map((value)=><option key={value} value={value}>{evidenceAssuranceLabel(value)}</option>)}</select></label><label className="text-sm font-medium">Source organisation or system<input className={field} name="sourceName" defaultValue={initial?.sourceName} required minLength={2} maxLength={180} placeholder="For example, branch audit, NHS, local authority"/></label><label className="text-sm font-medium">Source reference<input className={field} name="sourceReference" defaultValue={initial?.sourceReference} maxLength={180} placeholder="Report, case or document reference"/></label><label className="text-sm font-medium">Original author or issuer<input className={field} name="originalAuthor" defaultValue={initial?.originalAuthor} maxLength={180}/></label><label className="text-sm font-medium">Captured or received date<input className={field} name="capturedAt" type="date" defaultValue={initial?.capturedAt}/></label><label className="text-sm font-medium">Official source URL, if applicable<input className={field} name="sourceUrl" type="url" defaultValue={initial?.sourceUrl} placeholder="https://..."/></label><label className="md:col-span-2 text-sm font-medium">Provenance and chain-of-custody note<textarea className={`${field} min-h-20`} name="provenanceNote" defaultValue={initial?.provenanceNote} placeholder="How it was obtained, whether it is complete and any handling or transformation applied."/></label></fieldset>
      {initial&&!initial.taxonomyFamilyKey?<div className="md:col-span-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><strong>Legacy classification preserved:</strong> {initial.category} · {initial.evidenceType}. Choose a core classification only if you can do so accurately; QCGMS has not remapped the historical value.</div>:null}
      <label className="text-sm font-medium">Core Evidence family<select className={field} name="taxonomyFamilyKey" value={familyKey} onChange={event=>setFamilyKey(event.target.value)} required={!initial}><option value="">{initial?"Keep legacy classification":"Choose family"}</option>{CORE_EVIDENCE_FAMILIES.map((value) => <option key={value.key} value={value.key}>{value.label}</option>)}</select></label>
      <label className="text-sm font-medium">Contextual Evidence type<select className={field} name="taxonomyTypeKey" defaultValue={initial?.taxonomyTypeKey??""} required={!initial}><option value="">{initial?"Keep legacy classification":"Choose type"}</option>{CORE_EVIDENCE_FAMILIES.find(item=>item.key===familyKey)?.types.map(value=><option key={value.key} value={value.key}>{value.label}</option>)}</select></label>
      <label className="text-sm font-medium">Provider subtype <span className="font-normal text-slate-500">(optional)</span><select className={field} name="providerEvidenceTypeId" defaultValue={initial?.providerEvidenceTypeId??""}><option value="">None</option>{providerTypes.filter(item=>item.familyKey===familyKey).map(value=><option key={value.id} value={value.id}>{value.label}</option>)}</select></label>
      <label className="text-sm font-medium">Currentness position<select className={field} name="currentnessStatus" defaultValue={initial?.currentnessStatus||"CURRENT"}><option value="CURRENT">Current where this type represents a current source</option><option value="HISTORICAL">Historical evidence of what was known or done</option>{initial?<option value="SUPERSEDED">Superseded by a later authorised source</option>:null}</select></label>
      <label className="text-sm font-medium">Record owner<select className={field} name="ownerId" defaultValue={initial?.ownerId ?? owners[0]?.id} required>{owners.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label>
      <label className="text-sm font-medium">Service location<select className={field} name="locationId" defaultValue={initial?.locationId ?? ""}><option value="">Organisation-wide</option>{locations.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label>
      {!initial && <label className="md:col-span-2 rounded-xl border-2 border-dashed border-emerald-300 bg-emerald-50 p-5 text-sm font-medium">Evidence files <span className="font-normal text-slate-600">(up to 10; PDF, Office, CSV, JPG or PNG; 10 MB each)</span><input className={`${field} border-0`} name="documents" type="file" multiple required accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.jpg,.jpeg,.png" /></label>}
      <label className="text-sm font-medium">Evidence date<input className={field} name="evidenceDate" type="date" defaultValue={initial?.evidenceDate} /></label>
      <label className="text-sm font-medium">Review or expiry date<input className={field} name="reviewExpiryDate" type="date" defaultValue={initial?.reviewExpiryDate} /></label>
      <label className="text-sm font-medium">Confidentiality<select className={field} name="confidentiality" defaultValue={initial?.confidentiality ?? "INTERNAL"}>{EVIDENCE_CONFIDENTIALITY.map((value) => <option key={value}>{value.toLowerCase()}</option>)}</select></label>
      {initial && <label className="text-sm font-medium">Record status<select className={field} name="status" defaultValue={initial.status}>{EVIDENCE_STATUSES.map((value) => <option key={value}>{value.toLowerCase()}</option>)}</select></label>}
      <label className="text-sm font-medium">Tags <span className="font-normal text-slate-500">(comma-separated)</span><input className={field} name="tags" defaultValue={initial?.tags ?? (requirement ? `${requirement.keyQuestion.toLowerCase()}, ${requirement.qualityStatement.toLowerCase()}, evidence requirement` : "")} /></label>
      {!linkedRequirement ? <><label className="text-sm font-medium">Related module<select className={field} name="relatedModule" defaultValue={initial?.relatedModule ?? ""}><option value="">Not linked</option><option>Policy</option></select></label><label className="md:col-span-2 text-sm font-medium">Related policy<select className={field} name="relatedRecordId" defaultValue={initial?.relatedRecordId ?? ""}><option value="">None</option>{policies.map((value) => <option key={value.id} value={value.id}>{value.title}</option>)}</select></label></> : null}
      <label className="md:col-span-2 text-sm font-medium">Review notes<textarea className={`${field} min-h-24`} name="notes" defaultValue={initial?.notes} placeholder="Record limitations, follow-up needed or why this evidence remains current." /></label>
    </div>
    <button disabled={busy} className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Saving…" : initial ? "Save evidence" : "Upload evidence"}</button>
  </form>;
}
