"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { CQC_EVIDENCE_CATEGORIES } from "@/lib/inspection-framework";
import { EVIDENCE_MAPPING_DECISIONS, EVIDENCE_VERIFICATION_OUTCOMES, evidenceAssuranceLabel } from "@/lib/evidence-assurance";

const field = "mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm";
type Option = { id: string; name: string };

async function send(url: string, method: string, form: HTMLFormElement) {
  const response = await fetch(url, { method, body: new FormData(form) });
  const body = await response.json().catch(() => ({})) as { error?: string; id?: string };
  if (!response.ok) throw new Error(body.error ?? "The assurance record could not be saved.");
  return body;
}

function useFormState() {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  return { router, busy, message, async submit(event: React.FormEvent<HTMLFormElement>, url: string, method = "POST", redirectTo?: (id: string) => string) { event.preventDefault(); setBusy(true); setMessage(""); try { const result = await send(url, method, event.currentTarget); if (redirectTo && result.id) router.push(redirectTo(result.id)); else router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save."); } finally { setBusy(false); } } };
}

export function EvidenceVerificationForm({ evidenceId }: { evidenceId: string }) {
  const state = useFormState();
  return <form className="space-y-3 rounded-xl border border-blue-200 bg-blue-50 p-4" onSubmit={(event) => state.submit(event, `/api/evidence/${evidenceId}/verify`)}><h3 className="font-bold text-blue-950">Named evidence verification</h3><p className="text-xs text-blue-900">The decision applies to the current file version or current live source state. A replacement or source update makes it stale.</p><label className="text-sm font-semibold">Outcome<select name="outcome" className={field} defaultValue="VERIFIED">{EVIDENCE_VERIFICATION_OUTCOMES.map((value)=><option key={value} value={value}>{evidenceAssuranceLabel(value)}</option>)}</select></label><label className="block text-sm font-semibold">Relevance to the claimed requirement<textarea name="relevance" required minLength={10} rows={3} className={field}/></label><label className="block text-sm font-semibold">Currency check<textarea name="currencyAssessment" required minLength={10} rows={3} className={field} placeholder="Confirm the evidence period, expiry and whether practice may have changed."/></label><label className="block text-sm font-semibold">Authenticity and integrity check<textarea name="authenticityCheck" required minLength={10} rows={3} className={field} placeholder="Confirm source, issuer and checksum or live-record trace."/></label><label className="block text-sm font-semibold">Limitations<textarea name="limitations" rows={2} className={field}/></label><label className="block text-sm font-semibold">Verification review due<input name="reviewDueAt" type="date" className={field}/></label><button disabled={state.busy} className="rounded-xl bg-blue-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{state.busy ? "Recording…" : "Record verification"}</button>{state.message ? <p role="alert" className="text-sm text-red-700">{state.message}</p> : null}</form>;
}

export function EvidenceMappingReviewForm({ requirementId, evidenceId, initialDecision, initialRationale, initialCategories }: { requirementId: string; evidenceId: string; initialDecision: string; initialRationale: string; initialCategories: string[] }) {
  const state = useFormState();
  return <form className="mt-3 space-y-3 rounded-xl bg-slate-50 p-3" onSubmit={(event) => state.submit(event, `/api/inspection/${requirementId}/evidence-mappings/${evidenceId}`, "PATCH")}><label className="text-xs font-bold">Suitability decision<select name="decision" defaultValue={initialDecision} className={field}>{EVIDENCE_MAPPING_DECISIONS.map((value)=><option key={value} value={value}>{evidenceAssuranceLabel(value)}</option>)}</select></label><label className="block text-xs font-bold">Mapping rationale<textarea name="rationale" defaultValue={initialRationale} rows={3} className={field}/></label><fieldset><legend className="text-xs font-bold">Evidence categories actually supported</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{CQC_EVIDENCE_CATEGORIES.map((category)=><label key={category} className="flex items-center gap-2 rounded-lg bg-white p-2 text-xs"><input type="checkbox" name="evidenceCategories" value={category} defaultChecked={initialCategories.includes(category)}/>{evidenceAssuranceLabel(category)}</label>)}</div></fieldset><button disabled={state.busy} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">{state.busy ? "Saving…" : "Save suitability review"}</button>{state.message ? <p role="alert" className="text-xs text-red-700">{state.message}</p> : null}</form>;
}

export function ControlledMappingForm({ policies, templates, requirements }: { policies: Option[]; templates: Option[]; requirements: Option[] }) {
  const state = useFormState(); const [kind, setKind] = useState("POLICY"); const options = kind === "POLICY" ? policies : templates;
  return <form className="space-y-3" onSubmit={(event) => state.submit(event, "/api/evidence-assurance/controlled-mappings")}><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Controlled record type<select name="sourceType" value={kind} onChange={(event)=>setKind(event.target.value)} className={field}><option value="POLICY">Policy</option><option value="TEMPLATE">Template</option></select></label><label className="text-sm font-semibold">Record<select name="sourceId" required className={field} defaultValue=""><option value="">Choose record</option>{options.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-semibold">Requirement<select name="requirementId" required className={field} defaultValue=""><option value="">Choose requirement</option>{requirements.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-semibold">Decision<select name="decision" className={field} defaultValue="SUITABLE">{EVIDENCE_MAPPING_DECISIONS.map((value)=><option key={value} value={value}>{evidenceAssuranceLabel(value)}</option>)}</select></label></div><label className="block text-sm font-semibold">Why this controlled record addresses the requirement<textarea name="rationale" required minLength={10} rows={3} className={field}/></label><button disabled={state.busy} className="rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white">{state.busy ? "Saving…" : "Save controlled mapping"}</button>{state.message ? <p role="alert" className="text-sm text-red-700">{state.message}</p> : null}</form>;
}

export function FrameworkChangeForm({ members, locations, requirements, policies, templates }: { members: Option[]; locations: Option[]; requirements: Option[]; policies: Option[]; templates: Option[] }) {
  const state = useFormState();
  return <form className="space-y-4" onSubmit={(event) => state.submit(event, "/api/evidence-assurance/framework-reviews")}><div className="grid gap-3 sm:grid-cols-2"><Field name="jurisdiction" label="UK jurisdiction" placeholder="England, Wales, Scotland or Northern Ireland"/><Field name="regulator" label="Regulator or authority"/><Field name="name" label="Framework or guidance name"/><Field name="versionLabel" label="Published version or date"/><Field name="sourceUrl" label="Official HTTPS source" type="url"/><Field name="publishedAt" label="Published date" type="date"/><Field name="effectiveFrom" label="Effective from" type="date"/><label className="text-sm font-semibold">Owner<select name="ownerId" required className={field} defaultValue=""><option value="">Choose owner</option>{members.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-semibold">Location<select name="locationId" className={field} defaultValue=""><option value="">Organisation-wide</option>{locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field name="reviewDueAt" label="Impact review due" type="date"/></div><label className="block text-sm font-semibold">Framework summary<textarea name="summary" required minLength={10} rows={3} className={field}/></label><label className="block text-sm font-semibold">What changed<textarea name="changeSummary" required minLength={10} rows={3} className={field}/></label><div className="grid gap-3 lg:grid-cols-3"><Multi name="affectedRequirementIds" label="Affected requirements" options={requirements}/><Multi name="affectedPolicyIds" label="Affected policies" options={policies}/><Multi name="affectedTemplateIds" label="Affected templates" options={templates}/></div><button disabled={state.busy} className="rounded-xl bg-blue-900 px-4 py-2.5 text-sm font-bold text-white">{state.busy ? "Creating…" : "Create controlled change review"}</button>{state.message ? <p role="alert" className="text-sm text-red-700">{state.message}</p> : null}</form>;
}

export function FrameworkReviewUpdateForm({ id, initialStatus, initialImpact, initialActions }: { id: string; initialStatus: string; initialImpact: string; initialActions: string }) {
  const state = useFormState();
  return <form className="mt-3 space-y-3" onSubmit={(event) => state.submit(event, `/api/evidence-assurance/framework-reviews/${id}`, "PATCH")}><label className="text-xs font-bold">Review status<select name="status" defaultValue={initialStatus} className={field}>{["NEW","UNDER_REVIEW","ACTIONS_REQUIRED","IMPLEMENTED","NO_ACTION_REQUIRED"].map((value)=><option key={value} value={value}>{evidenceAssuranceLabel(value)}</option>)}</select></label><label className="block text-xs font-bold">Impact assessment<textarea name="impactAssessment" defaultValue={initialImpact} rows={3} className={field}/></label><label className="block text-xs font-bold">Actions or implementation record<textarea name="actionSummary" defaultValue={initialActions} rows={3} className={field}/></label><button disabled={state.busy} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">{state.busy ? "Saving…" : "Update review"}</button>{state.message ? <p role="alert" className="text-xs text-red-700">{state.message}</p> : null}</form>;
}

export function MockInspectionForm({ members, locations, requirements }: { members: Option[]; locations: Option[]; requirements: Option[] }) {
  const state = useFormState();
  return <form className="space-y-4" onSubmit={(event) => state.submit(event, "/api/evidence-assurance/mock-inspections", "POST", (id)=>`/evidence-assurance/mock-inspections/${id}`)}><div className="grid gap-3 sm:grid-cols-2"><Field name="title" label="Mock inspection title"/><Field name="frameworkLabel" label="Framework used"/><Field name="plannedAt" label="Planned date" type="date"/><label className="text-sm font-semibold">Lead reviewer<select name="leadId" required className={field} defaultValue=""><option value="">Choose lead</option>{members.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-semibold">Location<select name="locationId" className={field} defaultValue=""><option value="">Organisation-wide</option>{locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><label className="block text-sm font-semibold">Inspection scope<textarea name="scope" required minLength={10} rows={3} className={field}/></label><Multi name="requirementIds" label="Requirements to sample" options={requirements}/><button disabled={state.busy} className="rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white">{state.busy ? "Planning…" : "Plan mock inspection"}</button>{state.message ? <p role="alert" className="text-sm text-red-700">{state.message}</p> : null}</form>;
}

export function MockSampleReviewForm({ inspectionId, sampleId, evidence, initial }: { inspectionId: string; sampleId: string; evidence: Option[]; initial: { outcome: string; sampledEvidenceIds: string[]; observation: string; peopleExperience: string; staffFeedback: string; finding: string } }) {
  const state = useFormState();
  return <form className="mt-4 space-y-3" onSubmit={(event) => state.submit(event, `/api/evidence-assurance/mock-inspections/${inspectionId}/samples/${sampleId}`, "PATCH")}><label className="text-sm font-semibold">Sample outcome<select name="outcome" defaultValue={initial.outcome} className={field}>{["NOT_TESTED","ASSURED","PARTIALLY_ASSURED","GAP","NOT_APPLICABLE"].map((value)=><option key={value} value={value}>{evidenceAssuranceLabel(value)}</option>)}</select></label><Multi name="sampledEvidenceIds" label="Evidence actually sampled" options={evidence} defaults={initial.sampledEvidenceIds}/><Area name="observation" label="Observed process or practice" value={initial.observation}/><Area name="peopleExperience" label="People's experience sampled" value={initial.peopleExperience}/><Area name="staffFeedback" label="Staff or leader feedback sampled" value={initial.staffFeedback}/><Area name="finding" label="Finding or gap" value={initial.finding}/><button disabled={state.busy} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">{state.busy ? "Saving…" : "Save sample"}</button>{state.message ? <p role="alert" className="text-xs text-red-700">{state.message}</p> : null}</form>;
}

export function CompleteMockInspectionForm({ id }: { id: string }) { const state = useFormState(); return <form className="rounded-xl border border-emerald-200 bg-emerald-50 p-4" onSubmit={(event)=>state.submit(event, `/api/evidence-assurance/mock-inspections/${id}/complete`, "PATCH")}><label className="block text-sm font-semibold">Overall conclusion and required follow-up<textarea name="summary" required minLength={20} rows={4} className={field}/></label><button disabled={state.busy} className="mt-3 rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white">{state.busy ? "Completing…" : "Complete mock inspection"}</button>{state.message ? <p role="alert" className="mt-2 text-sm text-red-700">{state.message}</p> : null}</form>; }

function Field({ name, label, type="text", placeholder }: { name: string; label: string; type?: string; placeholder?: string }) { return <label className="text-sm font-semibold">{label}<input name={name} type={type} placeholder={placeholder} required className={field}/></label>; }
function Area({ name, label, value }: { name: string; label: string; value: string }) { return <label className="block text-sm font-semibold">{label}<textarea name={name} defaultValue={value} rows={3} className={field}/></label>; }
function Multi({ name, label, options, defaults=[] }: { name: string; label: string; options: Option[]; defaults?: string[] }) { return <label className="block text-sm font-semibold">{label}<span className="block text-xs font-normal text-slate-500">Choose one or more using Ctrl or Command.</span><select name={name} multiple defaultValue={defaults} className={`${field} min-h-32`}>{options.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }
