"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

type Option = { id: string; name: string };
const field = "mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm";

function useSubmit(url: string, method: "POST" | "PATCH" = "POST") {
  const router = useRouter(), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const response = await fetch(url, { method, body: new FormData(event.currentTarget) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setError(body.error ?? "The record could not be saved."); setBusy(false); return; } event.currentTarget.reset(); router.refresh(); setBusy(false); }
  return { submit, busy, error };
}

export function ExternalPartyForm({ locations }: { locations: Option[] }) {
  const state = useSubmit("/api/governance-control/external-parties");
  return <form onSubmit={state.submit} className="grid gap-3 md:grid-cols-2"><Field label="Organisation / agency"><input name="name" className={field}/></Field><Field label="Party type"><select name="partyType" className={field}><option value="COMMISSIONER">Commissioner</option><option value="LOCAL_AUTHORITY">Local authority</option><option value="REGULATOR">Regulator</option><option value="NHS_OR_CLINICAL">NHS / clinical partner</option><option value="SUPPLIER">Supplier</option><option value="OTHER">Other</option></select></Field><Field label="Email"><input type="email" name="email" className={field}/></Field><Field label="Phone"><input type="tel" name="phone" className={field}/></Field><Field label="Location"><select name="locationId" className={field}><option value="">Organisation-wide</option>{locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Address"><input name="address" className={field}/></Field><Field label="Notes" wide><textarea name="notes" rows={2} className={field}/></Field><Submit {...state} label="Add controlled party"/></form>;
}

export function ObligationForm({ parties, members, locations }: { parties: Option[]; members: Option[]; locations: Option[] }) {
  const state = useSubmit("/api/governance-control/obligations");
  return <form onSubmit={state.submit} className="grid gap-3 md:grid-cols-2"><Field label="Obligation / return"><input name="title" className={field}/></Field><Field label="Type"><select name="obligationType" className={field}><option value="COMMISSIONER_RETURN">Commissioner return</option><option value="REGULATORY_NOTIFICATION">Regulatory notification</option><option value="CONTRACT_REVIEW">Contract review</option><option value="INFORMATION_REQUEST">Information request</option><option value="OTHER">Other</option></select></Field><Field label="External party"><select name="externalPartyId" className={field}><option value="">Choose controlled party</option>{parties.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Accountable owner"><select name="ownerId" className={field}><option value="">Choose owner</option>{members.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Location"><select name="locationId" className={field}><option value="">Organisation-wide</option>{locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Submission deadline"><input type="date" name="dueAt" className={field}/></Field><Field label="External response expected"><input type="date" name="responseDueAt" className={field}/></Field><Field label="Interim safety / governance control" wide><textarea name="interimControl" rows={3} className={field}/></Field><Field label="Escalation route if delayed" wide><textarea name="escalationRoute" rows={3} className={field}/></Field><Submit {...state} label="Open obligation"/></form>;
}

export function DecisionRegisterForm({ agendaItems, members, parties }: { agendaItems: Option[]; members: Option[]; parties: Option[] }) {
  const state = useSubmit("/api/governance-control/decisions");
  return <form onSubmit={state.submit} className="grid gap-3 md:grid-cols-2"><Field label="Approved meeting decision" wide><select name="agendaItemId" className={field}><option value="">Choose an unregistered decision</option>{agendaItems.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Accountable owner"><select name="ownerId" className={field}><option value="">Choose owner</option>{members.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Impact"><select name="impact" className={field}><option value="LOW">Low</option><option value="MODERATE">Moderate</option><option value="HIGH">High</option><option value="CRITICAL">Critical</option></select></Field><Field label="Effective date"><input type="date" name="effectiveDate" className={field}/></Field><Field label="Review due"><input type="date" name="reviewDueAt" className={field}/></Field><Field label="External party (if involved)"><select name="externalPartyId" className={field}><option value="">None</option>{parties.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Submit {...state} label="Register controlled decision"/></form>;
}

export function DecisionUpdate({ id, status, evidence }: { id: string; status: string; evidence: Option[] }) {
  const state = useSubmit(`/api/governance-control/decisions/${id}`, "PATCH");
  return <form onSubmit={state.submit} className="mt-3 grid gap-2"><input type="hidden" name="intent" value={status === "IMPLEMENTED" ? "review" : "implement"}/>{status !== "IMPLEMENTED" ? <label className="text-xs font-bold">Implementation evidence<select name="evidenceId" className={field}><option value="">No evidence selected</option>{evidence.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : null}<textarea name="note" rows={2} className={field} placeholder={status === "IMPLEMENTED" ? "Measured independent review outcome" : "What changed and how it was implemented"}/><Submit {...state} label={status === "IMPLEMENTED" ? "Record independent review" : "Record implementation"}/></form>;
}

export function ObligationUpdate({ id, status, evidence }: { id: string; status: string; evidence: Option[] }) {
  const state = useSubmit(`/api/governance-control/obligations/${id}`, "PATCH");
  return <form onSubmit={state.submit} className="mt-3 grid gap-2 md:grid-cols-2"><Field label="Chronology event"><select name="updateType" className={field}><option value="NOTE">Note</option><option value="CHASE">Chase</option><option value="SUBMISSION">Submission</option><option value="QUERY">External query</option><option value="RESPONSE">Response</option><option value="ACCEPTANCE">Acceptance</option><option value="CLOSURE">Closure</option><option value="ESCALATION">Escalation</option></select></Field><Field label="Resulting status"><select name="nextStatus" defaultValue={status} className={field}>{["OPEN","PREPARING","SUBMITTED","QUERY_RECEIVED","ACCEPTED","CLOSED","CANCELLED"].map((value)=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></Field><Field label="Submission / external reference"><input name="submissionReference" className={field}/></Field><Field label="Evidence"><select name="evidenceId" className={field}><option value="">None</option>{evidence.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Chronology note" wide><textarea name="note" rows={2} className={field}/></Field><Submit {...state} label="Add controlled update"/></form>;
}

function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`${wide ? "md:col-span-2 " : ""}text-sm font-semibold`}>{label}{children}</label>; }
function Submit({ busy, error, label }: { busy: boolean; error: string; label: string }) { return <div className="md:col-span-2">{error?<p role="alert" className="mb-2 rounded-lg bg-red-50 p-2 text-xs font-bold text-red-700">{error}</p>:null}<button disabled={busy} className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy?"Saving…":label}</button></div>; }
