"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Option={id:string;name:string};
type Family={key:string;label:string;types:{key:string;label:string;currentnessMode:string}[]};
type Control={id:string;stableKey:string;currentVersionId:string|null;versions:{id:string;versionNumber:number;status:string;title:string;description:string;family:string;scopeType:string;effectiveFrom:string|null;reviewDueAt:string|null;changeRationale:string;locations:{location:{id:string;name:string}}[]}[]};
type Extension={id:string;familyKey:string;label:string;currentnessMode:string;status:string};
const RISK_CATEGORIES=[["CARE_QUALITY","Care quality"],["CLINICAL","Clinical"],["SAFEGUARDING","Safeguarding"],["MEDICINES","Medicines"],["WORKFORCE","Workforce"],["OPERATIONAL","Operational"],["BUSINESS_CONTINUITY","Business continuity"],["FINANCIAL","Financial"],["INFORMATION_GOVERNANCE","Information governance"],["CYBER_SECURITY","Cyber security"],["HEALTH_AND_SAFETY","Health and safety"],["COMPLIANCE","Compliance"],["COMMISSIONER_CONTRACT","Commissioner contract"],["REPUTATIONAL","Reputational"],["STRATEGIC","Strategic"],["OTHER","Other"]] as const;
export function ProviderControlLibrary({locations,members,families,controls,extensions,canOrganisationWide}:{locations:Option[];members:Option[];families:Family[];controls:Control[];extensions:Extension[];canOrganisationWide:boolean}){
 const router=useRouter(),[error,setError]=useState(""),[busy,setBusy]=useState(false),[familyKey,setFamilyKey]=useState(families[0]?.key??"OTHER"),types=useMemo(()=>families.find(item=>item.key===familyKey)?.types??[],[familyKey,families]);
 async function send(url:string,body:unknown){setBusy(true);setError("");try{const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(result.error||"The change could not be saved.");router.refresh()}catch(value){setError(value instanceof Error?value.message:"The change could not be saved.")}finally{setBusy(false)}}
 async function createControl(formData:FormData){const scopeType=String(formData.get("scopeType")),locationIds=formData.getAll("locationIds").map(String),evidenceFamily=String(formData.get("evidenceFamily")),evidenceType=String(formData.get("evidenceType"));await send("/api/settings/provider-controls",{title:String(formData.get("title")),description:String(formData.get("description")),family:String(formData.get("family")),applicableRiskCategoryKeys:formData.getAll("riskCategories").map(String),scopeType,locationIds,accountableOwnerId:String(formData.get("ownerId"))||null,expectedEvidenceFamilyKeys:evidenceFamily?[evidenceFamily]:[],expectedEvidenceTypeKeys:evidenceType?[`${evidenceFamily}:${evidenceType}`]:[],expectedEffectivenessMethod:String(formData.get("method"))||null,effectiveFrom:String(formData.get("effectiveFrom"))||null,reviewDueAt:String(formData.get("reviewDueAt"))||null,changeRationale:String(formData.get("rationale"))})}
 async function createExtension(formData:FormData){await send("/api/settings/provider-evidence-types",{familyKey:String(formData.get("familyKey")),label:String(formData.get("label")),description:String(formData.get("description"))||null,currentnessMode:String(formData.get("currentnessMode")),ownerId:String(formData.get("ownerId"))})}
 async function retireExtension(id:string){await send(`/api/settings/provider-evidence-types/${id}`,{})}
 return <div className="space-y-6">
  {error?<div role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 font-semibold text-red-900">{error}</div>:null}
  <details className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><summary className="cursor-pointer text-lg font-bold">Create a Provider Control draft</summary><p className="mt-2 text-sm text-slate-700">Record a control your organisation genuinely operates. A Draft is not selectable on Risks until an authorised manager activates it.</p><form action={createControl} className="mt-5 grid gap-4 md:grid-cols-2">
   <Field label="Control title"><input name="title" required minLength={3} className="input" placeholder="Medication competency assessment"/></Field><Field label="Control family"><select name="family" className="input">{["PEOPLE","PROCESS","TECHNOLOGY","PROFESSIONAL_EXTERNAL","PHYSICAL_ENVIRONMENTAL","GOVERNANCE"].map(item=><option key={item}>{item.replaceAll("_"," ")}</option>)}</select></Field>
   <Field label="Description" wide><textarea name="description" required minLength={10} className="input min-h-24" placeholder="State what operates, for whom and how it reduces risk."/></Field>
   <Field label="Accountable Control owner"><select name="ownerId" className="input"><option value="">Role/owner not assigned</option>{members.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Scope"><select name="scopeType" className="input" defaultValue={canOrganisationWide?"ORGANISATION":"SELECTED_LOCATIONS"}><option value="SELECTED_LOCATIONS">Selected locations</option>{canOrganisationWide?<option value="ORGANISATION">Organisation-wide</option>:null}</select></Field>
   <Field label="Applicable locations" wide><div className="flex flex-wrap gap-3">{locations.map(item=><label key={item.id} className="rounded-lg border bg-white px-3 py-2"><input type="checkbox" name="locationIds" value={item.id} className="mr-2"/>{item.name}</label>)}</div></Field>
   <Field label="Applicable Risk categories" wide><p className="mb-2 text-xs text-slate-600">Leave all unticked only when the Control genuinely applies across every Risk category.</p><div className="flex flex-wrap gap-2">{RISK_CATEGORIES.map(([key,label])=><label key={key} className="rounded-lg border bg-white px-3 py-2 text-sm"><input type="checkbox" name="riskCategories" value={key} className="mr-2"/>{label}</label>)}</div></Field>
   <Field label="Expected Evidence family"><select name="evidenceFamily" className="input" value={familyKey} onChange={event=>setFamilyKey(event.target.value)}>{families.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></Field><Field label="Expected Evidence type"><select name="evidenceType" className="input"><option value="">Any type in this family</option>{types.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></Field>
   <Field label="Normal effectiveness method" wide><textarea name="method" className="input min-h-20" placeholder="For example: competency reassessment plus subsequent record audit."/></Field><Field label="Effective from"><input type="date" name="effectiveFrom" className="input"/></Field><Field label="Review due"><input type="date" name="reviewDueAt" className="input"/></Field><Field label="Draft rationale" wide><textarea name="rationale" required minLength={8} className="input" placeholder="Why this organisational control is being introduced."/></Field><button disabled={busy} className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white md:col-span-2">{busy?"Saving…":"Create governed Draft"}</button>
  </form></details>
  <section><h2 className="text-xl font-bold">Provider Controls</h2><p className="text-sm text-slate-600">Approved organisation controls are kept separate from QCGMS suggestions. Effective versions are immutable; a change creates a new version.</p><div className="mt-4 grid gap-4 xl:grid-cols-2">{controls.map(control=>{const latest=control.versions[0];return <article key={control.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-3"><div><p className="font-mono text-xs text-slate-500">{control.stableKey} · v{latest.versionNumber}</p><h3 className="font-bold">{latest.title}</h3></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{latest.status}</span></div><p className="mt-2 text-sm text-slate-700">{latest.description}</p><p className="mt-3 text-xs text-slate-500">{latest.scopeType==="ORGANISATION"?"Organisation-wide":latest.locations.map(item=>item.location.name).join(", ")||"No location selected"} · {latest.family.replaceAll("_"," ")}</p><div className="mt-4 flex flex-wrap gap-2">{latest.status==="DRAFT"?<button disabled={busy} onClick={()=>send(`/api/settings/provider-controls/${control.id}`,{intent:"ACTIVATE"})} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white">Activate Draft</button>:null}{latest.status==="EFFECTIVE"?<><button disabled={busy} onClick={()=>send(`/api/settings/provider-controls/${control.id}`,{intent:"CREATE_NEW_VERSION",changeRationale:"Controlled review of the effective Provider Control."})} className="rounded-lg border px-3 py-2 text-sm font-bold">Create new version</button><button disabled={busy} onClick={()=>send(`/api/settings/provider-controls/${control.id}`,{intent:"RETIRE"})} className="rounded-lg border border-red-300 px-3 py-2 text-sm font-bold text-red-800">Retire</button></>:null}</div></article>})}{!controls.length?<p className="rounded-2xl border border-dashed p-8 text-center text-slate-500">No Provider Controls have been created. QCGMS suggestions remain advisory only.</p>:null}</div></section>
  <details className="rounded-2xl border border-slate-200 bg-white p-5">
   <summary className="cursor-pointer text-lg font-bold">Provider Evidence type extensions</summary>
   <p className="mt-2 text-sm text-slate-600">Add a provider-specific subtype beneath a stable QCGMS core family. Extensions never replace the core taxonomy.</p>
   <form action={createExtension} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Core family"><select name="familyKey" className="input">{families.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></Field><Field label="Extension label"><input name="label" className="input" required placeholder="Tissue Viability Nurse"/></Field><Field label="Currentness behaviour"><select name="currentnessMode" className="input"><option value="HISTORICAL_NON_EXPIRING">Historical — does not expire</option><option value="EXPIRY_BASED">Expiry based</option><option value="REVIEW_BASED">Review based</option><option value="SUPERSESSION_BASED">Supersession based</option><option value="CURRENT_SOURCE">Current source</option></select></Field><Field label="Owner"><select name="ownerId" className="input" required>{members.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Description" wide><textarea name="description" className="input"/></Field><button disabled={busy} className="rounded-xl bg-slate-900 px-5 py-3 font-bold text-white md:col-span-2">Add provider extension</button></form>
   <div className="mt-5 grid gap-2">{extensions.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-100 px-3 py-2 text-sm"><span><strong>{families.find(f=>f.key===item.familyKey)?.label}:</strong> {item.label} · {item.status}</span>{item.status==="ACTIVE"?<button type="button" disabled={busy} onClick={()=>retireExtension(item.id)} className="min-h-11 rounded-lg border border-red-300 bg-white px-3 py-2 font-bold text-red-800">Retire extension</button>:null}</div>)}</div>
  </details>
 </div>
}
function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"md:col-span-2":""}><span className="mb-1 block text-sm font-bold">{label}</span>{children}</label>}
