"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

const RISK_CATEGORIES=[["CARE_QUALITY","Care quality"],["CLINICAL","Clinical"],["SAFEGUARDING","Safeguarding"],["MEDICINES","Medicines"],["WORKFORCE","Workforce"],["OPERATIONAL","Operational"],["BUSINESS_CONTINUITY","Business continuity"],["FINANCIAL","Financial"],["INFORMATION_GOVERNANCE","Information governance"],["CYBER_SECURITY","Cyber security"],["HEALTH_AND_SAFETY","Health and safety"],["COMPLIANCE","Compliance"],["COMMISSIONER_CONTRACT","Commissioner contract"],["REPUTATIONAL","Reputational"],["STRATEGIC","Strategic"],["OTHER","Other"]] as const;
type Option={id:string;name:string};
type Family={key:string;label:string;types:{key:string;label:string}[]};
type Draft={title:string;description:string;family:string;applicableRiskCategoryKeys:string[];scopeType:string;accountableOwnerId:string|null;expectedEvidenceFamilyKeys:string[];expectedEvidenceTypeKeys:string[];expectedEffectivenessMethod:string|null;effectiveFrom:string|null;reviewDueAt:string|null;changeRationale:string;locations:{location:{id:string;name:string}}[]};

export function ProviderControlDraftEditor({controlId,reference,draft,locations,members,families,canOrganisationWide}:{controlId:string;reference:string;draft:Draft;locations:Option[];members:Option[];families:Family[];canOrganisationWide:boolean}){
 const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState(""),[familyKey,setFamilyKey]=useState(draft.expectedEvidenceFamilyKeys[0]??families[0]?.key??"OTHER");
 const types=useMemo(()=>families.find(item=>item.key===familyKey)?.types??[],[families,familyKey]);
 async function save(data:FormData){setBusy(true);setError("");const evidenceType=String(data.get("evidenceType"));try{const response=await fetch(`/api/settings/provider-controls/${controlId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:String(data.get("title")),description:String(data.get("description")),family:String(data.get("family")),applicableRiskCategoryKeys:data.getAll("riskCategories").map(String),scopeType:String(data.get("scopeType")),locationIds:data.getAll("locationIds").map(String),accountableOwnerId:String(data.get("ownerId"))||null,expectedEvidenceFamilyKeys:familyKey?[familyKey]:[],expectedEvidenceTypeKeys:evidenceType?[`${familyKey}:${evidenceType}`]:[],expectedEffectivenessMethod:String(data.get("method"))||null,effectiveFrom:String(data.get("effectiveFrom"))||null,reviewDueAt:String(data.get("reviewDueAt"))||null,changeRationale:String(data.get("rationale"))})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not update Draft.");router.refresh()}catch(value){setError(value instanceof Error?value.message:"Could not update Draft.")}finally{setBusy(false)}}
 return <details className="rounded-2xl border border-amber-300 bg-amber-50 p-5"><summary className="cursor-pointer text-lg font-bold">Edit Draft Provider Control · {reference}</summary><p className="mt-2 text-sm text-amber-950"><strong>Draft only:</strong> this is not yet an approved operating Control. Save changes, review the complete position, then activate it deliberately.</p>{error?<p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 font-semibold text-red-900">{error}</p>:null}<form action={save} className="mt-5 grid gap-4 md:grid-cols-2">
  <Field label="What is this Control?"><input name="title" className="input" required defaultValue={draft.title}/></Field><Field label="Control family"><select name="family" className="input" defaultValue={draft.family}>{["PEOPLE","PROCESS","TECHNOLOGY","PROFESSIONAL_EXTERNAL","PHYSICAL_ENVIRONMENTAL","GOVERNANCE"].map(item=><option key={item}>{item.replaceAll("_"," ")}</option>)}</select></Field>
  <Field label="How does it operate?" wide><textarea name="description" className="input min-h-24" required defaultValue={draft.description}/></Field>
  <Field label="Control owner"><select name="ownerId" className="input" defaultValue={draft.accountableOwnerId??""}><option value="">Not assigned</option>{members.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Where does it apply?"><select name="scopeType" className="input" defaultValue={draft.scopeType}><option value="SELECTED_LOCATIONS">Selected locations</option>{canOrganisationWide?<option value="ORGANISATION">Organisation-wide</option>:null}</select></Field>
  <Field label="Locations" wide><div className="flex flex-wrap gap-2">{locations.map(item=><label key={item.id} className="rounded-lg border bg-white px-3 py-2"><input name="locationIds" type="checkbox" value={item.id} defaultChecked={draft.locations.some(link=>link.location.id===item.id)} className="mr-2"/>{item.name}</label>)}</div></Field>
  <Field label="Applicable Risk categories" wide><div className="flex flex-wrap gap-2">{RISK_CATEGORIES.map(([key,label])=><label key={key} className="rounded-lg border bg-white px-3 py-2 text-sm"><input name="riskCategories" type="checkbox" value={key} defaultChecked={draft.applicableRiskCategoryKeys.includes(key)} className="mr-2"/>{label}</label>)}</div></Field>
  <Field label="Expected Evidence family"><select className="input" value={familyKey} onChange={event=>setFamilyKey(event.target.value)}>{families.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></Field><Field label="Expected Evidence type"><select name="evidenceType" className="input" defaultValue={draft.expectedEvidenceTypeKeys[0]?.split(":")[1]??""}><option value="">Any relevant type in family</option>{types.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></Field>
  <Field label="How should we know it is working?" wide><textarea name="method" className="input min-h-20" defaultValue={draft.expectedEffectivenessMethod??""}/></Field><Field label="Effective from"><input name="effectiveFrom" type="date" className="input" defaultValue={draft.effectiveFrom??""}/></Field><Field label="Review date"><input name="reviewDueAt" type="date" className="input" defaultValue={draft.reviewDueAt??""}/></Field><Field label="Change rationale" wide><textarea name="rationale" className="input" minLength={8} required defaultValue={draft.changeRationale}/></Field>
  <button disabled={busy} className="rounded-xl bg-amber-800 px-5 py-3 font-bold text-white md:col-span-2">{busy?"Saving Draft…":"Save Draft changes"}</button>
 </form></details>
}
function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"md:col-span-2":""}><span className="mb-1 block text-sm font-bold">{label}</span>{children}</label>}
