"use client";
import{useRouter}from"next/navigation";import{useState}from"react";import type{RegisterField}from"@/lib/registers";import{REGISTER_RISK_LEVELS,REGISTER_STATUSES,registerStatusLabel}from"@/lib/registers";
type Option={id:string;name:string};type Initial={id:string;reference:string;eventDate:string;title:string;summary:string;riskLevel:string;status:string;locationId:string;ownerId:string;closureDate:string;data:Record<string,unknown>;evidenceIds:string[]};
export function RegisterEntryForm({registerKey,registerName,fields,locations,owners,evidence,initial}:{registerKey:string;registerName:string;fields:RegisterField[];locations:Option[];owners:Option[];evidence:{id:string;title:string}[];initial?:Initial}){const router=useRouter();const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const response=await fetch(initial?`/api/registers/${registerKey}/${initial.id}`:`/api/registers/${registerKey}`,{method:initial?"PATCH":"POST",body:new FormData(event.currentTarget)});const result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error??"Could not save entry.");setBusy(false);return;}router.push(`/registers/${registerKey}/${initial?.id??result.id}`);router.refresh();}const cls="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm";return <form onSubmit={submit} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{error&&<div role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<section><h2 className="text-lg font-bold">Core details</h2><div className="mt-4 grid gap-4 md:grid-cols-2">
<label className="text-sm font-medium">Reference <span className="font-normal text-slate-500">(auto-generated if blank)</span><input className={cls} name="reference" defaultValue={initial?.reference} readOnly={Boolean(initial)}/></label><label className="text-sm font-medium">Event or received date<input className={cls} name="eventDate" type="date" defaultValue={initial?.eventDate??new Date().toISOString().slice(0,10)} required/></label>
<label className="md:col-span-2 text-sm font-medium">Title<input className={cls} name="title" defaultValue={initial?.title} required minLength={3}/></label><label className="md:col-span-2 text-sm font-medium">Summary<textarea className={`${cls} min-h-24`} name="summary" defaultValue={initial?.summary} required/></label>
<label className="text-sm font-medium">Risk level<select className={cls} name="riskLevel" defaultValue={initial?.riskLevel??"LOW"}>{REGISTER_RISK_LEVELS.map((value)=><option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium">Status<select className={cls} name="status" defaultValue={initial?.status??"OPEN"}>{REGISTER_STATUSES.map((value)=><option key={value} value={value}>{registerStatusLabel(value)}</option>)}</select></label>
<label className="text-sm font-medium">Location<select className={cls} name="locationId" defaultValue={initial?.locationId??""}><option value="">Organisation-wide</option>{locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Owner<select className={cls} name="ownerId" defaultValue={initial?.ownerId??""}><option value="">Unassigned</option>{owners.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Closure date<input className={cls} name="closureDate" type="date" defaultValue={initial?.closureDate}/></label></div></section>
<section><h2 className="text-lg font-bold">{registerName} details</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{fields.map((field)=><DynamicField key={field.key} field={field} value={initial?.data[field.key]}/>)}</div></section>
<section><h2 className="text-lg font-bold">Supporting evidence</h2><p className="mt-1 text-sm text-slate-500">Use Ctrl or Command to select more than one item.</p><select multiple name="evidenceIds" defaultValue={initial?.evidenceIds??[]} className={`${cls} min-h-32`}>{evidence.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><p className="mt-3 text-sm text-slate-500">Linked actions can be created from the saved register entry.</p></section><button disabled={busy} className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy?"Saving…":initial?"Save entry":"Add entry"}</button></form>}
function DynamicField({field,value}:{field:RegisterField;value:unknown}){const cls="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm";if(field.type==="boolean")return <label className="text-sm font-medium">{field.label}<select className={cls} name={`field_${field.key}`} defaultValue={String(value??false)}><option value="false">No</option><option value="true">Yes</option></select></label>;if(field.type==="textarea")return <label className="md:col-span-2 text-sm font-medium">{field.label}<textarea className={`${cls} min-h-20`} name={`field_${field.key}`} defaultValue={String(value??"")} required={field.required}/></label>;return <label className="text-sm font-medium">{field.label}<input className={cls} name={`field_${field.key}`} type={field.type==="number"?"number":field.type==="date"?"date":"text"} defaultValue={String(value??"")} required={field.required}/></label>}
