"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { controlSuggestions, treatmentSuggestions } from "@/lib/governance-catalogues";
import { RISK_CATEGORY_DEFINITIONS } from "@/lib/risk-framework";
import { CONTROL_EFFECTIVENESS, REVIEW_FREQUENCIES, RISK_APPETITES, RISK_CATEGORIES, RISK_SOURCES, RISK_STATUSES, TREATMENT_STRATEGIES, isOutsideTolerance, levelClasses, riskLevel, riskScore, riskStatusLabel } from "@/lib/risks";

type Option={id:string;name:string};
export type RiskEvidenceOption={id:string;name:string;category:string;relatedModule:string;sourceName:string;sourceReference:string;assuranceState:string};
export type RiskInitial={id:string;reference:string;title:string;description:string;cause:string;riskEvent:string;consequence:string;peopleAffected:string;category:string;sourceType:string;sourceReference:string;identifiedDate:string;locationId:string;ownerId:string;existingControls:string;controlEffectiveness:string;controlAssurance:string;likelihood:number;impact:number;residualLikelihood:number;residualImpact:number;appetite:string;toleranceScore:number;acceptanceRationale:string;treatmentStrategy:string;furtherControls:string;targetDate:string;targetLikelihood:number;targetImpact:number;keyRiskIndicator:string;indicatorThreshold:string;escalationRoute:string;reviewTriggers:string;reviewFrequency:string;lastReviewDate:string;nextReviewDate:string;status:string;closureRationale:string;closureApprovedById:string;closureDate:string;evidenceIds:string[];frameworkVersionNumber?:number};
type RiskFrameworkInput={versionNumber:number;defaultAppetite:string;defaultToleranceScore:number;rules:{categoryKey:string;appetite:string;toleranceScore:number}[]};

export function RiskForm({locations,owners,evidence,initial,framework}:{locations:Option[];owners:Option[];evidence:RiskEvidenceOption[];initial?:RiskInitial;framework?:RiskFrameworkInput}){
  const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const[cause,setCause]=useState(initial?.cause??"");const[event,setEvent]=useState(initial?.riskEvent??"");const[consequence,setConsequence]=useState(initial?.consequence??"");
  const[category,setCategory]=useState(initial?.category??"Operational");const[sourceType,setSourceType]=useState(initial?.sourceType??"Manual identification");const[sourceReference,setSourceReference]=useState(initial?.sourceReference??"");const[sourceEvidenceId,setSourceEvidenceId]=useState("");
  const[status,setStatus]=useState(initial?.status??"OPEN");
  const[existingControls,setExistingControls]=useState(initial?.existingControls??"");const[furtherControls,setFurtherControls]=useState(initial?.furtherControls??"");const[evidenceQuery,setEvidenceQuery]=useState("");const[selectedEvidenceIds,setSelectedEvidenceIds]=useState(()=>new Set(initial?.evidenceIds??[]));
  const categoryKey=RISK_CATEGORY_DEFINITIONS.find(([,label])=>label===category)?.[0];const frameworkRule=initial?undefined:framework?.rules.find(rule=>rule.categoryKey===categoryKey);const inheritedAppetite=frameworkRule?.appetite??framework?.defaultAppetite;const inheritedTolerance=frameworkRule?.toleranceScore??framework?.defaultToleranceScore;
  const[likelihood,setLikelihood]=useState(initial?.likelihood??3);const[impact,setImpact]=useState(initial?.impact??3);const[residualLikelihood,setResidualLikelihood]=useState(initial?.residualLikelihood??3);const[residualImpact,setResidualImpact]=useState(initial?.residualImpact??3);const[targetLikelihood,setTargetLikelihood]=useState(initial?.targetLikelihood??2);const[targetImpact,setTargetImpact]=useState(initial?.targetImpact??2);const[manualTolerance,setManualTolerance]=useState(initial?.toleranceScore??9);const tolerance=inheritedTolerance??manualTolerance;
  const initialScore=useMemo(()=>riskScore(likelihood,impact),[likelihood,impact]),residualScore=useMemo(()=>riskScore(residualLikelihood,residualImpact),[residualLikelihood,residualImpact]),targetScore=useMemo(()=>riskScore(targetLikelihood,targetImpact),[targetLikelihood,targetImpact]);const outside=isOutsideTolerance(residualScore,tolerance);
  const controls=useMemo(()=>controlSuggestions(category,sourceType),[category,sourceType]),treatments=useMemo(()=>treatmentSuggestions(category,sourceType),[category,sourceType]);
  const visibleEvidence=useMemo(()=>{const query=evidenceQuery.trim().toLowerCase();return query?evidence.filter(item=>`${item.name} ${item.category} ${item.relatedModule} ${item.sourceReference}`.toLowerCase().includes(query)):evidence},[evidence,evidenceQuery]);
  const cls="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-100";
  const defaultNext=initial?.nextReviewDate??(()=>{const date=new Date();date.setMonth(date.getMonth()+3);return date.toISOString().slice(0,10)})();
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const response=await fetch(initial?`/api/risks/${initial.id}`:"/api/risks",{method:initial?"PATCH":"POST",body:new FormData(e.currentTarget)});const result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error??"Could not save the risk.");setBusy(false);return}router.push(`/risks/${initial?.id??result.id}`);router.refresh()}
  return <form onSubmit={submit} className="space-y-6">
    <section className="overflow-hidden rounded-2xl border border-emerald-900 bg-emerald-950 text-white shadow-sm"><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Guided risk assessment</p><h2 className="mt-2 text-2xl font-bold">One risk, three clear positions</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-50/80">Score the risk before controls, test what controls achieve now, then set the target after planned treatment. Record facts and internal references—never unnecessary personal details.</p></div><div className="grid border-t border-white/10 md:grid-cols-3"><Stage number="1" title="Inherent" text="Before any controls"/><Stage number="2" title="Current residual" text="After existing controls"/><Stage number="3" title="Target" text="After planned actions"/></div></section>
    {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</div>:null}
    <Section number="1" title="Identify the risk" intro="Start with the source, then write a cause–event–consequence statement. This makes the risk understandable to someone who was not in the room."><div className="grid gap-4 md:grid-cols-2">
      <Field label="Risk reference" hint="Generated automatically if blank"><input name="reference" className={cls} defaultValue={initial?.reference} readOnly={Boolean(initial)}/></Field><Field label="Date identified"><input type="date" name="identifiedDate" className={cls} defaultValue={initial?.identifiedDate??new Date().toISOString().slice(0,10)} required/></Field>
      <Field label="How was this risk identified?"><select name="sourceType" className={cls} value={sourceType} onChange={e=>setSourceType(e.target.value)}>{RISK_SOURCES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Link an existing source record" hint="recommended when available"><select value={sourceEvidenceId} onChange={e=>{const id=e.target.value;setSourceEvidenceId(id);const item=evidence.find(option=>option.id===id);if(item){setSourceReference(item.sourceReference||item.name);setSourceType(riskSourceForEvidence(item));setSelectedEvidenceIds(current=>new Set([...current,id]))}}} className={cls}><option value="">No source record selected</option>{evidence.filter(item=>item.relatedModule&&item.relatedModule!=="Risk").map(item=><option key={item.id} value={item.id}>{item.sourceReference?`${item.sourceReference} — `:""}{item.name}</option>)}</select></Field>
      <Field label="Source reference" hint="filled from a linked record when selected"><input name="sourceReference" className={cls} value={sourceReference} onChange={e=>setSourceReference(e.target.value)} placeholder="For example, INC-2026-014 or July medicines audit"/></Field>
      <Field label="Risk category">{initial?.frameworkVersionNumber?<><input type="hidden" name="category" value={category}/><select className={cls} value={category} disabled aria-label="Risk category governed by the applied framework">{RISK_CATEGORIES.map(v=><option key={v}>{v}</option>)}</select><span className="mt-1 block text-xs font-normal text-slate-500">Change through a formal review to preserve framework provenance.</span></>:<select name="category" className={cls} value={category} onChange={e=>setCategory(e.target.value)}>{RISK_CATEGORIES.map(v=><option key={v}>{v}</option>)}</select>}</Field><Field label="Service location"><select name="locationId" className={cls} defaultValue={initial?.locationId??""}><option value="">Organisation-wide</option>{locations.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>
      <Field label="Short risk name" wide><input name="title" className={cls} defaultValue={initial?.title} required minLength={3} placeholder="For example, Care visits disrupted by severe weather"/></Field>
      <Field label="Cause — why might it happen?" wide><textarea name="cause" value={cause} onChange={e=>setCause(e.target.value)} className={`${cls} min-h-20`} required placeholder="For example, severe weather and road closures reduce available travel routes"/></Field>
      <Field label="Uncertain event — what might happen?" wide><textarea name="riskEvent" value={event} onChange={e=>setEvent(e.target.value)} className={`${cls} min-h-20`} required placeholder="For example, care workers may be unable to reach scheduled visits on time"/></Field>
      <Field label="Consequences — what harm or disruption could follow?" wide><textarea name="consequence" value={consequence} onChange={e=>setConsequence(e.target.value)} className={`${cls} min-h-20`} required placeholder="For example, people may miss essential care or medicines and staff may travel unsafely"/></Field>
      <Field label="Who or what could be affected?" wide><input name="peopleAffected" className={cls} defaultValue={initial?.peopleAffected} required placeholder="People receiving care, care workers, families, service continuity and commissioner confidence"/></Field>
    </div><div className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><strong>Risk statement preview</strong><p className="mt-1">Because {cause||"[cause]"}, there is a risk that {event||"[event]"}, resulting in {consequence||"[consequence]"}.</p></div></Section>
    <Section number="2" title="Inherent risk — before controls" intro="Imagine no controls are operating. Select likelihood and impact separately; their definitions are deliberately different."><div className="grid gap-4 md:grid-cols-2"><ScaleSelect kind="likelihood" name="likelihood" value={likelihood} setValue={setLikelihood}/><ScaleSelect kind="impact" name="impact" value={impact} setValue={setImpact}/><ScoreCard label="Inherent risk" score={initialScore}/></div></Section>
    <Section number="3" title="Existing controls and current residual risk" intro="List controls that are operating now—not planned actions. Then record how you know they work and score the risk that remains."><div className="grid gap-4 md:grid-cols-2">
      <div className="md:col-span-2 text-sm font-semibold"><p>Controls currently operating</p><SuggestionPicker title="Suggested for this risk" help="Select only controls that are genuinely operating, then edit the wording." items={controls} onChoose={wording=>setExistingControls(value=>appendWording(value,wording))}/><textarea aria-label="Controls currently operating" name="existingControls" className={`${cls} min-h-28`} value={existingControls} onChange={e=>setExistingControls(e.target.value)} required placeholder="Select relevant controls above, or describe another control that is operating now."/></div>
      <Field label="Control effectiveness"><select name="controlEffectiveness" className={cls} defaultValue={initial?.controlEffectiveness??"NOT_TESTED"}>{CONTROL_EFFECTIVENESS.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></Field><Field label="How were controls tested?"><textarea name="controlAssurance" className={`${cls} min-h-24`} defaultValue={initial?.controlAssurance} placeholder="For example, audit sample, observation, KPI trend, incident review or external assurance."/></Field>
      <ScaleSelect kind="likelihood" name="residualLikelihood" value={residualLikelihood} setValue={setResidualLikelihood} labelText="Current likelihood after controls"/><ScaleSelect kind="impact" name="residualImpact" value={residualImpact} setValue={setResidualImpact} labelText="Current impact after controls"/><ScoreCard label="Current residual risk" score={residualScore}/>
      {(inheritedAppetite&&inheritedTolerance)||initial?.frameworkVersionNumber?<div className="md:col-span-2 rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-blue-900">Organisation Risk Framework v{framework?.versionNumber??initial?.frameworkVersionNumber}</p><p className="mt-1 text-sm text-blue-950">{category}: <strong>{label(inheritedAppetite??initial?.appetite??"LOW")}</strong> appetite · tolerance <strong>{inheritedTolerance??initial?.toleranceScore}</strong>. {initial?"This historical applied position is changed only through formal review.":"QCGMS applies this governed position automatically to this new Risk."}</p><input type="hidden" name="appetite" value={inheritedAppetite??initial?.appetite}/><input type="hidden" name="toleranceScore" value={inheritedTolerance??initial?.toleranceScore}/></div>:<><Field label="Risk appetite"><select name="appetite" className={cls} defaultValue={initial?.appetite??"LOW"}>{RISK_APPETITES.map(v=><option key={v} value={v}>{label(v)}{v==="ZERO_TOLERANCE"?" — avoid exposure wherever reasonably practicable":v==="LOW"?" — accept only limited exposure":v==="MODERATE"?" — balanced, controlled exposure":" — more exposure may be accepted for a justified benefit"}</option>)}</select></Field><Field label="Tolerance threshold" hint="highest acceptable score"><input type="number" min={1} max={25} name="toleranceScore" value={manualTolerance} onChange={e=>setManualTolerance(Number(e.target.value))} className={cls}/></Field></>}
    </div><div className={`mt-5 rounded-xl border p-4 text-sm ${outside?"border-red-300 bg-red-50 text-red-900":"border-emerald-200 bg-emerald-50 text-emerald-950"}`}><strong>{outside?"Outside tolerance — treatment or documented acceptance is required":"Within the recorded tolerance"}</strong><p className="mt-1">Current score {residualScore}; tolerance {tolerance}. This threshold supports escalation—it does not override legal duties or the need to prevent avoidable harm.</p></div></Section>
    <Section number="4" title="Treatment plan and target risk" intro="Choose the management response, describe the change required, and show the score expected only after those actions are implemented and tested."><div className="grid gap-4 md:grid-cols-2">
      <Field label="Treatment strategy"><select name="treatmentStrategy" className={cls} defaultValue={initial?.treatmentStrategy??"REDUCE"}>{TREATMENT_STRATEGIES.map(v=><option key={v} value={v}>{v==="TRANSFER_OR_SHARE"?"Transfer or share":label(v)}</option>)}</select></Field><Field label="Accountable risk owner"><select name="ownerId" className={cls} defaultValue={initial?.ownerId??""}><option value="">Choose owner</option>{owners.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>
      <div className="md:col-span-2 text-sm font-semibold"><p>Further controls or actions</p><SuggestionPicker title="Common treatment options" help="These draft the plan. After saving, create accountable records in the central Action Tracker." items={treatments} onChoose={wording=>setFurtherControls(value=>appendWording(value,wording))}/><textarea aria-label="Further controls or actions" name="furtherControls" className={`${cls} min-h-28`} value={furtherControls} onChange={e=>setFurtherControls(e.target.value)} placeholder="Select a relevant option above, then add only the professional detail that is specific to this risk."/></div><Field label="Treatment target date"><input type="date" name="targetDate" className={cls} defaultValue={initial?.targetDate}/></Field>
      <Field label="Acceptance rationale" hint="required when accepting"><textarea name="acceptanceRationale" className={`${cls} min-h-24`} defaultValue={initial?.acceptanceRationale} placeholder="Explain why the exposure is justified, proportionate and authorised, including any benefits or constraints."/></Field>
      <ScaleSelect kind="likelihood" name="targetLikelihood" value={targetLikelihood} setValue={setTargetLikelihood} labelText="Target likelihood after treatment"/><ScaleSelect kind="impact" name="targetImpact" value={targetImpact} setValue={setTargetImpact} labelText="Target impact after treatment"/><ScoreCard label="Target risk" score={targetScore}/>
    </div></Section>
    <Section number="5" title="Early warning, escalation and review" intro="Make the risk active: define what will warn you, what triggers an immediate review, and where escalation goes."><div className="grid gap-4 md:grid-cols-2">
      <Field label="Key risk indicator"><input name="keyRiskIndicator" className={cls} defaultValue={initial?.keyRiskIndicator} placeholder="For example, percentage of calls delivered over 30 minutes late"/></Field><Field label="Warning threshold"><input name="indicatorThreshold" className={cls} defaultValue={initial?.indicatorThreshold} placeholder="For example, more than 2% in any rolling 7-day period"/></Field>
      <Field label="Immediate escalation route"><textarea name="escalationRoute" className={`${cls} min-h-20`} defaultValue={initial?.escalationRoute} placeholder="Who is notified, how quickly and which external notification routes may apply?"/></Field><Field label="Review triggers"><textarea name="reviewTriggers" className={`${cls} min-h-20`} defaultValue={initial?.reviewTriggers} placeholder="Incident, near miss, complaint, change in need, failed control, threshold breach or regulatory change."/></Field>
      <Field label="Review frequency"><select name="reviewFrequency" className={cls} defaultValue={initial?.reviewFrequency??"Quarterly"}>{REVIEW_FREQUENCIES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Next scheduled review"><input type="date" name="nextReviewDate" className={cls} defaultValue={defaultNext} required/></Field>
      <Field label="Last review"><input type="date" name="lastReviewDate" className={cls} defaultValue={initial?.lastReviewDate}/></Field><Field label="Workflow status"><select name="status" className={cls} value={status} onChange={event=>setStatus(event.target.value)}>{RISK_STATUSES.filter(v=>!["ARCHIVED","CLOSED","CLOSURE_PROPOSED"].includes(v)).map(v=><option key={v} value={v}>{riskStatusLabel(v)}</option>)}</select></Field>
    </div><div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm"><strong>Governed closure</strong><p className="mt-1 text-slate-600">Closure is proposed from the saved Risk record. QCGMS then checks evidence, treatment Actions, effectiveness and the organisation&apos;s approval authority—no approval can be entered on another person&apos;s behalf.</p></div></Section>
    <Section number="6" title="Assurance evidence" intro="Search and link records already held by QCGMS. A record existing is not proof that a control worked; verification and RM judgement still matter.">{[...selectedEvidenceIds].map(id=><input key={id} type="hidden" name="evidenceIds" value={id}/>)}<label className="text-sm font-semibold">Find existing evidence<input value={evidenceQuery} onChange={e=>setEvidenceQuery(e.target.value)} className={cls} placeholder="Search by reference, title, module or category"/></label><div className="mt-3 max-h-80 space-y-2 overflow-y-auto rounded-xl border border-slate-200 p-3">{visibleEvidence.length?visibleEvidence.map(v=><label key={v.id} className="flex cursor-pointer items-start gap-3 rounded-lg border border-transparent p-2 text-sm hover:border-slate-200 hover:bg-slate-50"><input type="checkbox" checked={selectedEvidenceIds.has(v.id)} onChange={event=>setSelectedEvidenceIds(current=>{const next=new Set(current);if(event.target.checked)next.add(v.id);else next.delete(v.id);return next})} className="mt-1 size-4 accent-emerald-700"/><span className="min-w-0"><span className="block font-semibold">{v.name}</span><span className="mt-1 flex flex-wrap gap-1 text-xs text-slate-500"><span>{v.category}</span>{v.relatedModule?<span>· {v.relatedModule}</span>:null}{v.sourceReference?<span>· {v.sourceReference}</span>:null}<span className={assuranceClass(v.assuranceState)}>· {label(v.assuranceState)}</span></span></span></label>):<p className="p-3 text-sm text-slate-500">{evidence.length?"No evidence matches this search.":"No evidence is available yet. Save the risk, then upload or link assurance evidence later."}</p>}</div></Section>
    <div className="sticky bottom-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-xl backdrop-blur"><p className="text-sm text-slate-600">Current residual: <strong className={outside?"text-red-700":"text-emerald-700"}>{residualScore} · {riskLevel(residualScore)}</strong>{outside?" · outside tolerance":" · within tolerance"}</p><button disabled={busy} className="rounded-xl bg-emerald-700 px-6 py-3 text-sm font-bold text-white disabled:opacity-60">{busy?"Saving risk…":initial?"Save risk assessment":"Create risk and open record"}</button></div>
  </form>
}
function Stage({number,title,text}:{number:string;title:string;text:string}){return <div className="border-white/10 p-4 md:border-r"><p className="text-xs font-bold text-emerald-300">{number}</p><p className="font-bold">{title}</p><p className="text-xs text-emerald-50/65">{text}</p></div>}
function Section({number,title,intro,children}:{number:string;title:string;intro:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex gap-3 border-b border-slate-200 pb-4"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-emerald-100 text-sm font-black text-emerald-800">{number}</span><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{intro}</p></div></div>{children}</section>}
function Field({label,hint,wide,children}:{label:string;hint?:string;wide?:boolean;children:React.ReactNode}){return <label className={`${wide?"md:col-span-2 ":""}text-sm font-semibold`}>{label}{hint?<span className="ml-1 font-normal text-slate-500">({hint})</span>:null}{children}</label>}
const likelihoodLabels=["Rare — exceptional circumstances","Unlikely — could happen, but not expected","Possible — might happen sometimes","Likely — expected in many circumstances","Almost certain — expected frequently or imminently"];
const impactLabels=["Negligible — no harm; minimal disruption","Minor — low harm; short disruption","Moderate — reportable harm or material service impact","Major — serious harm or major service failure","Severe — death, catastrophic harm or service loss"];
function ScaleSelect({kind,name,value,setValue,labelText}:{kind:"likelihood"|"impact";name:string;value:number;setValue:(value:number)=>void;labelText?:string}){const values=kind==="likelihood"?likelihoodLabels:impactLabels;return <Field label={labelText??(kind==="likelihood"?"Likelihood":"Impact")}><select name={name} value={value} onChange={e=>setValue(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm">{values.map((text,index)=><option key={text} value={index+1}>{index+1} — {text}</option>)}</select></Field>}
function ScoreCard({label:heading,score}:{label:string;score:number}){const level=riskLevel(score);return <div className={`rounded-xl p-4 md:col-span-2 ${levelClasses(level)}`}><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider">{heading}</p><p className="mt-1 text-sm">Likelihood × impact</p></div><p className="text-3xl font-black">{score} <span className="text-base">· {level}</span></p></div></div>}
function label(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/^\w/,c=>c.toUpperCase())}
function SuggestionPicker({title,help,items,onChoose}:{title:string;help:string;items:{key:string;label:string;wording:string}[];onChoose:(wording:string)=>void}){return <div className="mt-2 rounded-xl border border-emerald-100 bg-emerald-50/60 p-3"><p className="text-xs font-bold uppercase tracking-wide text-emerald-900">{title}</p><p className="mt-1 text-xs font-normal text-slate-600">{help}</p><div className="mt-3 flex flex-wrap gap-2">{items.map(item=><button type="button" key={item.key} onClick={()=>onChoose(item.wording)} className="rounded-full border border-emerald-300 bg-white px-3 py-1.5 text-xs font-bold text-emerald-900 hover:bg-emerald-100">+ {item.label}</button>)}</div></div>}
function appendWording(current:string,wording:string){if(current.includes(wording))return current;return `${current.trim()}${current.trim()?"\n":""}• ${wording}`}
function riskSourceForEvidence(item:RiskEvidenceOption){const value=`${item.relatedModule} ${item.sourceName} ${item.category}`.toLowerCase();if(value.includes("incident"))return "Incident or near miss";if(value.includes("safeguard"))return "Safeguarding concern";if(value.includes("complaint")||value.includes("feedback"))return "Complaint or feedback";if(value.includes("audit"))return "Audit finding";if(value.includes("kpi"))return "KPI or data trend";if(value.includes("inspection")||value.includes("commission"))return "Inspection or commissioner";if(value.includes("continuity"))return "Business continuity exercise";if(value.includes("workforce")||value.includes("staff"))return "Staff concern";return "Other"}
function assuranceClass(state:string){return ["EXPIRED","REJECTED","STALE_VERIFICATION"].includes(state)?"font-bold text-red-700":state==="CURRENT_VERIFIED"?"font-bold text-emerald-700":"font-semibold text-amber-700"}
