"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { RISK_APPETITE_VALUES, RISK_CATEGORY_DEFINITIONS } from "@/lib/risk-framework";

type Role = { key: string; name: string };
export type RiskFrameworkDraftInitial={id:string;effectiveFrom:string;defaultAppetite:string;defaultToleranceScore:number;defaultEscalation:string;changeRationale:string;categoryRules:{categoryKey:string;appetite:string;toleranceScore:number;escalationIndicator:string}[];closureRules:{riskLevel:string;proposerRoleKeys:string[];approverRoleKeys:string[];selfApprovalAllowed:boolean;requiredApprovalCount:number;verifiedEvidenceRequired:boolean;effectivenessEvidenceRequired:boolean;escalationRequirement:string}[]};
const levels = ["LOW", "MODERATE", "HIGH", "CRITICAL"] as const;
const appetiteLabel = (value:string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, (c) => c.toUpperCase());

export function RiskFrameworkForm({ roles,initial }: { roles: Role[];initial?:RiskFrameworkDraftInitial }) {
  const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const categoryRule=(key:string)=>initial?.categoryRules.find(rule=>rule.categoryKey===key),closureRule=(level:string)=>initial?.closureRules.find(rule=>rule.riskLevel===level);
  const [categoryOverrides,setCategoryOverrides]=useState<Record<string,boolean>>(()=>Object.fromEntries((initial?.categoryRules??[]).map(rule=>[rule.categoryKey,true])));
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError("");
    const categoryRules=RISK_CATEGORY_DEFINITIONS.filter(([key])=>categoryOverrides[key]).map(([categoryKey])=>({categoryKey,appetite:String(form.get(`category.${categoryKey}.appetite`)),toleranceScore:Number(form.get(`category.${categoryKey}.tolerance`)),escalationIndicator:String(form.get(`category.${categoryKey}.escalation`)??"")||null}));
    const closureRules=levels.map(riskLevel=>({riskLevel,categoryKey:"*",proposerRoleKeys:form.getAll(`closure.${riskLevel}.proposer`).map(String),approverRoleKeys:form.getAll(`closure.${riskLevel}.approver`).map(String),selfApprovalAllowed:form.get(`closure.${riskLevel}.self`)==="on",requiredApprovalCount:Number(form.get(`closure.${riskLevel}.count`)),verifiedEvidenceRequired:form.get(`closure.${riskLevel}.verified`)==="on",effectivenessEvidenceRequired:form.get(`closure.${riskLevel}.effectiveness`)==="on",escalationRequirement:String(form.get(`closure.${riskLevel}.escalation`)??"")||null}));
    const response=await fetch(initial?`/api/settings/risk-framework/${initial.id}`:"/api/settings/risk-framework",{method:initial?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({effectiveFrom:String(form.get("effectiveFrom")),defaultAppetite:String(form.get("defaultAppetite")),defaultToleranceScore:Number(form.get("defaultToleranceScore")),defaultEscalation:String(form.get("defaultEscalation")??"")||null,changeRationale:String(form.get("changeRationale")),categoryRules,closureRules})});const result=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(result.error??`Could not ${initial?"update":"create"} the framework draft.`);return}router.refresh();}
  const suggested=(level:string,role:string)=>{if(level==="CRITICAL")return ["organisation-owner","registered-manager","nominated-individual"].includes(role);return ["organisation-owner","registered-manager","quality-compliance-manager"].includes(role)};
  return <form onSubmit={submit} className="space-y-5">{error?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>:null}<div className="grid gap-4 md:grid-cols-2"><Field label="Effective from"><input required type="date" name="effectiveFrom" defaultValue={initial?.effectiveFrom} className={cls}/></Field><Field label="Organisation appetite"><select name="defaultAppetite" defaultValue={initial?.defaultAppetite} className={cls}>{RISK_APPETITE_VALUES.map(v=><option key={v} value={v}>{appetiteLabel(v)}</option>)}</select></Field><Field label="Default tolerance threshold"><input required type="number" min="1" max="25" name="defaultToleranceScore" defaultValue={initial?.defaultToleranceScore} className={cls} placeholder="Provider decision: 1–25"/></Field><Field label="Default escalation indicator"><input name="defaultEscalation" defaultValue={initial?.defaultEscalation} className={cls} placeholder="When management escalation is expected"/></Field><Field label="Why this version is needed" wide><textarea required minLength={12} name="changeRationale" defaultValue={initial?.changeRationale} className={`${cls} min-h-20`}/></Field></div>
  <section><h3 className="font-bold">Category appetite and tolerance</h3><p className="text-sm text-slate-600">The organisation default applies unless you deliberately enable a category override.</p><div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="bg-slate-50 text-left"><th className="p-2">Override</th><th className="p-2">Category</th><th className="p-2">Appetite</th><th className="p-2">Tolerance</th><th className="p-2">Escalation</th></tr></thead><tbody>{RISK_CATEGORY_DEFINITIONS.map(([key,label])=><tr key={key} className="border-t"><td className="p-2"><input type="checkbox" checked={Boolean(categoryOverrides[key])} onChange={e=>setCategoryOverrides(v=>({...v,[key]:e.target.checked}))} aria-label={`Override ${label}`}/></td><td className="p-2 font-semibold">{label}</td><td className="p-2"><select disabled={!categoryOverrides[key]} name={`category.${key}.appetite`} defaultValue={categoryRule(key)?.appetite} className={small}>{RISK_APPETITE_VALUES.map(v=><option key={v} value={v}>{appetiteLabel(v)}</option>)}</select></td><td className="p-2"><input disabled={!categoryOverrides[key]} required={categoryOverrides[key]} type="number" min="1" max="25" name={`category.${key}.tolerance`} defaultValue={categoryRule(key)?.toleranceScore} className={small}/></td><td className="p-2"><input disabled={!categoryOverrides[key]} name={`category.${key}.escalation`} defaultValue={categoryRule(key)?.escalationIndicator} className={small}/></td></tr>)}</tbody></table></div></section>
  <section><h3 className="font-bold">Closure authority policy</h3><p className="text-sm text-slate-600">Suggested role patterns are editable. They are provider configuration, not regulatory standards.</p><div className="mt-3 space-y-4">{levels.map(level=>{const rule=closureRule(level);return <fieldset key={level} className="rounded-xl border p-4"><legend className="px-2 font-bold">{appetiteLabel(level)}</legend><div className="grid gap-4 lg:grid-cols-2"><RoleChecks label="May propose" name={`closure.${level}.proposer`} roles={roles} checked={role=>rule?rule.proposerRoleKeys.includes(role):suggested(level,role)}/><RoleChecks label="May approve" name={`closure.${level}.approver`} roles={roles} checked={role=>rule?rule.approverRoleKeys.includes(role):suggested(level,role)}/><Field label="Approvals required"><input name={`closure.${level}.count`} type="number" min="1" max="5" defaultValue={rule?.requiredApprovalCount??(level==="CRITICAL"?2:1)} className={small}/></Field><Field label="Escalation requirement"><input name={`closure.${level}.escalation`} defaultValue={rule?.escalationRequirement} className={small}/></Field></div><div className="mt-3 flex flex-wrap gap-5 text-sm"><Check name={`closure.${level}.self`} label="Self-approval allowed" checked={rule?.selfApprovalAllowed??level==="LOW"}/><Check name={`closure.${level}.verified`} label="Verified evidence required" checked={rule?.verifiedEvidenceRequired??["HIGH","CRITICAL"].includes(level)}/><Check name={`closure.${level}.effectiveness`} label="Effectiveness evidence required" checked={rule?.effectivenessEvidenceRequired??["HIGH","CRITICAL"].includes(level)}/></div></fieldset>})}</div></section>
  <button disabled={busy} className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-60">{busy?`${initial?"Saving":"Creating"} draft…`:initial?"Save draft changes":"Create controlled draft"}</button></form>
}

export function RiskFrameworkStatusAction({id,intent,label}:{id:string;intent:"submit"|"approve"|"activate"|"retire"|"withdraw";label:string}){const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState("");async function act(){const comment=prompt(`${label}: record a governance comment (minimum 8 characters).`);if(!comment)return;setBusy(true);setError("");const response=await fetch(`/api/settings/risk-framework/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({intent,comment})});const result=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(result.error??"Could not update the framework.");return}router.refresh()}return <span><button type="button" onClick={act} disabled={busy} className="rounded-lg border border-emerald-700 bg-white px-3 py-2 text-sm font-bold text-emerald-800 disabled:opacity-60">{busy?"Working…":label}</button>{error?<span role="alert" className="ml-2 text-xs font-semibold text-red-700">{error}</span>:null}</span>}
function RoleChecks({label,name,roles,checked}:{label:string;name:string;roles:Role[];checked:(key:string)=>boolean}){return <fieldset><legend className="text-sm font-semibold">{label}</legend><div className="mt-2 grid gap-1 sm:grid-cols-2">{roles.map(role=><label key={role.key} className="flex items-center gap-2 text-xs"><input type="checkbox" name={name} value={role.key} defaultChecked={checked(role.key)}/>{role.name}</label>)}</div></fieldset>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={`${wide?"md:col-span-2 ":""}text-sm font-semibold`}>{label}{children}</label>}
function Check({name,label,checked}:{name:string;label:string;checked:boolean}){return <label className="flex items-center gap-2"><input type="checkbox" name={name} defaultChecked={checked}/>{label}</label>}
const cls="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5";const small="w-full min-w-28 rounded-lg border border-slate-300 bg-white px-2 py-1.5 disabled:bg-slate-100";
