"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { TEMPLATE_CATEGORIES, TEMPLATE_STATUSES, templateLabel } from "@/lib/templates";

type Option={id:string;name:string};
export function TemplateForm({members}:{members:Option[]}){const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState("");const field="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm";async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/templates",{method:"POST",body:new FormData(event.currentTarget)}),result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error??"Could not add template.");setBusy(false);return}router.push(`/templates/${result.id}`);router.refresh()}return <form onSubmit={submit} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{error?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium md:col-span-2">Title<input name="title" required minLength={3} className={field}/></label><label className="text-sm font-medium">Category<select name="category" className={field}>{TEMPLATE_CATEGORIES.map((item)=><option key={item}>{item}</option>)}</select></label><label className="text-sm font-medium">Version<input name="version" required defaultValue="1.0" className={field}/></label><label className="text-sm font-medium md:col-span-2">Description<textarea name="description" required minLength={10} className={`${field} min-h-24`}/></label><label className="text-sm font-medium">Author<select name="authorId" className={field}>{members.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Review date<input name="reviewDate" type="date" className={field}/></label><label className="text-sm font-medium">Status<select name="status" defaultValue="PUBLISHED" className={field}>{TEMPLATE_STATUSES.filter((item)=>item!=="ARCHIVED").map((item)=><option key={item} value={item}>{templateLabel(item)}</option>)}</select></label><label className="text-sm font-medium">Tags <span className="font-normal text-slate-500">(comma-separated)</span><input name="tags" className={field}/></label><label className="rounded-xl border-2 border-dashed border-emerald-300 bg-emerald-50 p-5 text-sm font-medium md:col-span-2">Template file <span className="font-normal text-slate-600">(PDF, Office, CSV, text, JPG or PNG; 10 MB maximum)</span><input name="file" type="file" required className={`${field} border-0`} accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.jpg,.jpeg,.png"/></label></div><button disabled={busy} className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white">{busy?"Uploading...":"Add template"}</button></form>}

export function TemplateActions({id,status}:{id:string;status:string}){const router=useRouter(),[busy,setBusy]=useState(false);async function update(intent:string){setBusy(true);await fetch(`/api/templates/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({intent})});router.refresh();setBusy(false)}return <button disabled={busy} onClick={()=>update(status==="ARCHIVED"?"restore":"archive")} className="text-sm font-semibold text-red-700">{status==="ARCHIVED"?"Restore template":"Archive template"}</button>}

export function CopyTemplateForm({id,members,locations}:{id:string;members:Option[];locations:Option[]}){const router=useRouter(),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const response=await fetch(`/api/templates/${id}/copy`,{method:"POST",body:new FormData(event.currentTarget)}),result=await response.json().catch(()=>({}));if(response.ok){router.push(`/evidence/${result.id}`);router.refresh();return}setMessage(result.error??"Could not copy template.");setBusy(false)}return <form onSubmit={submit} className="space-y-3"><label className="block text-sm font-medium">Evidence owner<select name="ownerId" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" required>{members.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm font-medium">Location<select name="locationId" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">Organisation-wide</option>{locations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button disabled={busy} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">{busy?"Copying...":"Copy into Evidence Library"}</button>{message?<p className="text-sm text-red-700">{message}</p>:null}</form>}
