import Link from "next/link";
import { notFound } from "next/navigation";
import { ExtractActionForm, MeetingArchive } from "@/components/meeting-controls";
import { actionScopeWhere } from "@/lib/actions";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { evidenceScopeWhere } from "@/lib/evidence";
import { meetingCurrentWork, meetingLabel, meetingScopeWhere } from "@/lib/meetings";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

export default async function MeetingPage({ params }: { params: Promise<{ id: string }> }) {
  const context = await requirePermission(PERMISSIONS.GOVERNANCE_VIEW), { id } = await params, db = createDb();
  try {
    const [meeting, memberships] = await Promise.all([
      db.governanceMeeting.findFirst({ where: { id, ...meetingScopeWhere(context) }, include: { location: { select: { name: true } }, chair: { select: { name: true } }, approvedBy: { select: { name: true } }, createdBy: { select: { name: true } }, attendees: { include: { user: { select: { name: true } } }, orderBy: { user: { name: "asc" } } }, agendaItems: { orderBy: { sortOrder: "asc" } }, evidenceLinks: { include: { evidence: { select: { id: true, title: true, relatedModule: true, evidenceType: true } } } } } }),
      db.organisationMembership.findMany({ where: { organisationId: context.organisation.id, status: "ACTIVE" }, select: { user: { select: { id: true, name: true } } }, orderBy: { user: { name: "asc" } } }),
    ]);
    if (!meeting) notFound();
    const actionIds = [...meeting.previousActionIds, ...meeting.agendaItems.map((item) => item.linkedActionId).filter(Boolean) as string[]];
    const [previousActions, meetingActions, visibleEvidence] = await Promise.all([
      db.action.findMany({ where: { AND: [actionScopeWhere(context), { id: { in: actionIds } }] }, select: { id: true, reference: true, title: true, status: true, dueDate: true, owner: { select: { name: true } } } }),
      db.action.findMany({ where: { AND: [actionScopeWhere(context), { sourceType: "GOVERNANCE_MEETING", sourceRecordId: id }] }, select: { id: true, reference: true, title: true, status: true, dueDate: true, owner: { select: { name: true } } }, orderBy: { createdAt: "desc" } }),
      db.evidence.findMany({ where: { AND: [evidenceScopeWhere(context), { id: { in: meeting.evidenceLinks.map(({ evidenceId }) => evidenceId) } }] }, select: { id: true } }),
    ]);
    const actionMap = new Map(previousActions.map((item) => [item.id, item]));
    const decisionCount = meeting.agendaItems.filter((item) => item.decision?.trim()).length;
    const currentWork = meetingCurrentWork({ status: meeting.status, meetingDate: meeting.meetingDate, attendeeCount: meeting.attendees.length, agendaCount: meeting.agendaItems.length, decisionCount, minutes: meeting.minutes, approvedById: meeting.approvedById, approvalDate: meeting.approvalDate });
    const canManage = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_EDIT) && (context.allLocations || Boolean(meeting.locationId && context.locations.some(({ id: locationId }) => locationId === meeting.locationId))), canEdit = canManage && !["ARCHIVED", "APPROVED"].includes(meeting.status), canActions = hasPermission(context.permissions, PERMISSIONS.ACTIONS_MANAGE) && !["ARCHIVED", "CANCELLED"].includes(meeting.status) && (context.allLocations || Boolean(meeting.locationId && context.locations.some(({ id: locationId }) => locationId === meeting.locationId))), members = memberships.map(({ user }) => user);
    const evidenceIds = new Set(visibleEvidence.map(({ id: evidenceId }) => evidenceId));

    return <main className="space-y-6">
      <header><Link href="/meetings" className="text-sm font-semibold text-emerald-700">← Governance Meetings</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-sm font-bold text-emerald-700">{meeting.reference}</p><h1 className="mt-1 text-3xl font-black">{meeting.title}</h1><p className="mt-1 text-slate-600">{meeting.meetingType} · {meetingLabel(meeting.status)}</p></div><div className="flex flex-wrap gap-2"><Link href={`/meetings/${id}/agenda`} className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold">Agenda / PDF</Link><Link href={`/meetings/${id}/minutes`} className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold">Minutes / PDF</Link>{canEdit && <Link href={`/meetings/${id}/edit`} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Update meeting</Link>}{canManage && <MeetingArchive id={id} archived={meeting.status === "ARCHIVED"} />}</div></div></header>

      <section aria-label="What needs attention" className="border-l-4 border-emerald-700 bg-emerald-50/70 px-5 py-4">
        <p className="text-xs font-bold uppercase tracking-wide text-emerald-800">What needs attention</p>
        <h2 className="mt-1 text-xl font-bold">{currentWork.title}</h2>
        <p className="mt-1 text-sm text-slate-700">{currentWork.description}</p>
        <div className="mt-3 flex flex-wrap items-center gap-4 text-sm"><span>{decisionCount} recorded decisions · {meetingActions.length} linked actions · {evidenceIds.size} available Evidence records</span>{currentWork.action && currentWork.target && (currentWork.target === "minutes-record" || canEdit) && <Link href={currentWork.target === "minutes-record" ? `#${currentWork.target}` : `/meetings/${id}/edit#${currentWork.target}`} className="font-bold text-emerald-800 underline underline-offset-2">{currentWork.action} →</Link>}</div>
      </section>

      <section aria-label="Current work" className="space-y-4"><h2 className="text-xl font-bold">Current work</h2><p className="text-sm text-slate-600">Review the discussion and decisions, then create accountable actions where agreed.</p></section>

      <Card title="Agenda, discussion and decisions"><ol className="space-y-5">{meeting.agendaItems.map((item) => <li key={item.id} className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">{item.sortOrder}. {item.topic}</p><h3 className="mt-1 font-bold">{item.title}</h3><div className="mt-3 grid gap-3 lg:grid-cols-2"><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">Discussion and evidence</p><p className="mt-1 whitespace-pre-wrap">{item.notes ?? "Not recorded."}</p></div><div className="rounded-lg bg-emerald-50 p-3"><p className="text-xs font-bold uppercase text-emerald-800">Decision</p><p className="mt-1 whitespace-pre-wrap">{item.decision ?? "No decision recorded."}</p></div></div>{item.linkedActionId && actionMap.get(item.linkedActionId) ? <Link href={`/actions/${item.linkedActionId}`} className="mt-3 inline-block font-semibold text-emerald-700">Open linked action →</Link> : canActions && item.decision ? <ExtractActionForm meetingId={id} agendaId={item.id} title={item.title} owners={members} /> : null}</li>)}</ol></Card>

      <div id="minutes-record"><Card title="Formal minutes"><p className="whitespace-pre-wrap">{meeting.minutes ?? "Minutes not yet recorded."}</p></Card></div>

      <Card title="Actions agreed at this meeting">{meetingActions.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-2">Action</th><th>Owner</th><th>Due</th><th>Status</th></tr></thead><tbody>{meetingActions.map((action) => <tr key={action.id} className="border-b last:border-0"><td className="py-3"><Link href={`/actions/${action.id}`} className="font-semibold text-emerald-700">{action.reference} · {action.title}</Link></td><td>{action.owner.name}</td><td>{date(action.dueDate)}</td><td>{meetingLabel(action.status)}</td></tr>)}</tbody></table></div> : <p className="text-slate-500">No actions have been created from the decisions yet.</p>}</Card>

      <section className="grid gap-5 lg:grid-cols-2"><Card title="Evidence reviewed and linked"><div className="space-y-2">{meeting.evidenceLinks.some(({ evidenceId }) => evidenceIds.has(evidenceId)) ? meeting.evidenceLinks.filter(({ evidenceId }) => evidenceIds.has(evidenceId)).map(({ evidence }) => <Link key={evidence.id} href={`/evidence/${evidence.id}`} className="flex items-center justify-between rounded-lg bg-emerald-50 px-3 py-2 font-semibold text-emerald-900"><span>{evidence.title}</span><span className="text-xs">{evidence.relatedModule === "GovernanceMeeting" ? "Meeting record" : evidence.evidenceType}</span></Link>) : <p className="text-slate-500">No accessible Evidence is linked yet.</p>}</div></Card><Card title="Approval and follow-up"><dl className="grid grid-cols-2 gap-4"><Dt label="Approved by" value={meeting.approvedBy?.name ?? "Not approved"} /><Dt label="Approval date" value={date(meeting.approvalDate)} /><Dt label="Next meeting" value={date(meeting.nextMeetingDate)} /><Dt label="Record status" value={meetingLabel(meeting.status)} /></dl></Card></section>

      <details className="rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer text-lg font-bold">Meeting context and review detail</summary><div className="mt-5 space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Info label="Date and time" value={`${date(meeting.meetingDate)} · ${meeting.meetingTime}`} /><Info label="Room or secure link" value={meeting.locationOrLink} /><Info label="Chair" value={meeting.chair.name} /><Info label="Service and period" value={`${meeting.location?.name ?? "Organisation-wide"} · ${meeting.reportingPeriod ?? "Period not set"}`} /></div><section className="grid gap-5 lg:grid-cols-2"><Card title="Attendance"><h3 className="font-semibold">Attended</h3><p>{meeting.attendees.filter((item) => item.attendance !== "APOLOGY").map((item) => item.user.name).join(", ") || "No attendance recorded."}</p><h3 className="mt-3 font-semibold">Apologies</h3><p>{meeting.attendees.filter((item) => item.attendance === "APOLOGY").map((item) => item.user.name).join(", ") || "No apologies recorded."}</p></Card><Card title="Actions brought forward">{meeting.previousActionIds.length ? <ul className="space-y-2">{meeting.previousActionIds.map((actionId) => { const action = actionMap.get(actionId); return action ? <li key={actionId}><Link href={`/actions/${action.id}`} className="font-semibold text-emerald-700">{action.reference} · {action.title}</Link><span className="text-slate-500"> · {meetingLabel(action.status)} · {action.owner.name}</span></li> : null; })}</ul> : <p className="text-slate-500">No accessible actions were brought forward.</p>}</Card></section><section className="grid gap-5 lg:grid-cols-2">{[["Performance and KPI exceptions", meeting.kpiReview], ["Audit findings", meeting.auditFindings], ["Complaints, compliments and feedback", meeting.complaints], ["Incidents and medicines", meeting.incidents], ["Safeguarding and duty of candour", meeting.safeguarding], ["Workforce", meeting.workforce], ["Risks", meeting.risks], ["Quality improvement", meeting.qualityImprovement], ["Decision summary", meeting.decisions]].map(([title, value]) => <Card key={title} title={title as string}><p className="whitespace-pre-wrap">{value ?? "Nothing recorded."}</p></Card>)}</section><nav className="flex flex-wrap gap-4 text-sm font-semibold"><Link href="/calendar" className="text-emerald-800">Calendar</Link><Link href="/actions" className="text-emerald-800">Action Tracker</Link><Link href="/evidence" className="text-emerald-800">Evidence Library</Link></nav></div></details>
      <p className="text-xs text-slate-500">Created by {meeting.createdBy.name} on {date(meeting.createdAt)}. Updates are recorded in the Activity Log.</p>
    </main>;
  } finally { await db.$disconnect(); }
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">{title}</h2><div className="mt-3 text-sm leading-6">{children}</div></section>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 font-bold break-words">{value}</p></div>; }
function Dt({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd>{value}</dd></div>; }
function date(value: Date | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeZone: "Europe/London" }).format(value) : "Not set"; }
