import Link from "next/link";
import { notFound } from "next/navigation";
import { ReportPrintButton } from "@/components/report-print-button";
import { requirePermission } from "@/lib/auth/dal";
import { generateReport } from "@/lib/report-data";
import { PERMISSIONS } from "@/lib/permissions";
import {
  isReportType,
  label,
  parseReportFilters,
  REPORT_DEFINITIONS,
  reportQuery,
} from "@/lib/reports";

export default async function ReportPage({
  params,
  searchParams,
}: {
  params: Promise<{ type: string }>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const context = await requirePermission(PERMISSIONS.REPORTS_EXPORT);
  const { type } = await params;
  if (!isReportType(type)) notFound();
  const filters = parseReportFilters(await searchParams, context.locations.map((item) => item.id));
  const report = await generateReport(type, context, filters);
  const definition = REPORT_DEFINITIONS[type];
  const query = reportQuery(filters);

  return (
    <main className="space-y-6">
      <header className="print:hidden">
        <Link href="/reports" className="text-sm font-semibold text-emerald-700">Back to Reports</Link>
        <h1 className="mt-2 text-3xl font-bold">{definition.title}</h1>
        <p className="mt-1 text-slate-600">{definition.description}</p>
      </header>
      <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 print:hidden md:grid-cols-2 xl:grid-cols-4">
        <label className="text-sm font-medium">From<input name="from" type="date" defaultValue={filters.from?.toISOString().slice(0, 10)} className={field}/></label>
        <label className="text-sm font-medium">To<input name="to" type="date" defaultValue={filters.to?.toISOString().slice(0, 10)} className={field}/></label>
        <label className="text-sm font-medium">Location<select name="location" defaultValue={filters.locationId ?? ""} className={field}><option value="">All authorised locations</option>{context.locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
        <label className="text-sm font-medium">Status<select name="status" defaultValue={filters.status ?? ""} className={field}><option value="">All statuses</option>{report.statuses.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label>
        <label className="text-sm font-medium">Category<select name="category" defaultValue={filters.category ?? ""} className={field}><option value="">All categories</option>{report.categories.map((item) => <option key={item}>{item}</option>)}</select></label>
        <label className="flex items-center gap-2 self-end rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-medium"><input name="appendices" value="true" type="checkbox" defaultChecked={filters.appendices}/>Include appendices</label>
        <button className="self-end rounded-lg bg-slate-800 px-4 py-2.5 text-sm font-semibold text-white">Generate report</button>
      </form>
      <section className="flex flex-wrap gap-3 print:hidden">
        <ReportPrintButton />
        <a href={`/api/reports/${type}${query ? `?${query}` : ""}`} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Download CSV</a>
      </section>
      <article className="mx-auto max-w-7xl bg-white p-7 text-slate-900 print:p-0">
        <header className="border-b-4 border-emerald-800 pb-5">
          <p className="font-bold uppercase tracking-widest text-emerald-800">{context.organisation.name}</p>
          <h2 className="mt-2 text-4xl font-bold">{definition.title}</h2>
          <p className="mt-2 text-sm text-slate-600">
            Generated by {context.user.name} on {new Intl.DateTimeFormat("en-GB", { dateStyle: "long", timeStyle: "short" }).format(new Date())}
          </p>
          <p className="mt-1 text-sm text-slate-600">
            Period: {filters.from?.toLocaleDateString("en-GB") ?? "All records"} to {filters.to?.toLocaleDateString("en-GB") ?? "present"} · {report.rows.length} matching records
          </p>
        </header>
        {report.rows.length ? (
          <div className="mt-6 overflow-x-auto">
            <table className="w-full border-collapse text-left text-xs">
              <thead><tr className="bg-slate-100"><th className={cell}>Type</th><th className={cell}>Reference</th><th className={cell}>Record</th><th className={cell}>Date</th><th className={cell}>Location</th><th className={cell}>Category</th><th className={cell}>Status</th><th className={cell}>Owner</th><th className={cell}>Detail</th></tr></thead>
              <tbody>{report.rows.map((row, index) => <tr key={`${row.type}-${row.reference}-${index}`} className="break-inside-avoid"><td className={cell}>{row.type}</td><td className={`${cell} font-mono`}>{row.reference}</td><td className={`${cell} font-semibold`}>{row.title}</td><td className={cell}>{row.date}</td><td className={cell}>{row.location}</td><td className={cell}>{row.category}</td><td className={cell}>{label(row.status)}</td><td className={cell}>{row.owner}</td><td className={cell}>{row.detail}</td></tr>)}</tbody>
            </table>
          </div>
        ) : <p className="mt-8 rounded-lg border border-dashed p-8 text-center text-sm">No real database records match the selected filters.</p>}
        {filters.appendices ? <section className="mt-8 break-before-page"><h3 className="text-xl font-bold">Appendix: source record counts</h3><p className="mt-1 text-sm text-slate-600">Counts reflect the same authorised scope and active report filters.</p><ul className="mt-4 space-y-2">{report.sourceCounts.map((item) => <li key={item.source} className="flex max-w-md justify-between border-b pb-2 text-sm"><span>{item.source}</span><strong>{item.count}</strong></li>)}</ul></section> : null}
        <footer className="mt-8 border-t pt-3 text-xs text-slate-500">QCGMS · Internal governance record · Contains only records available to the signed-in user.</footer>
      </article>
    </main>
  );
}

const field = "mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm";
const cell = "border border-slate-200 p-2 align-top";
