import Link from "next/link";
import { notFound } from "next/navigation";
import { OrganisationDocumentBrand } from "@/components/organisation-document-brand";
import { ReportPrintButton } from "@/components/report-print-button";
import { requirePermission } from "@/lib/auth/dal";
import { generateReport } from "@/lib/report-data";
import { PERMISSIONS } from "@/lib/permissions";
import { isReportType, label, parseReportFilters, REPORT_DEFINITIONS, reportQuery } from "@/lib/reports";

export default async function ReportPage({ params, searchParams }: { params: Promise<{ type: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const context = await requirePermission(PERMISSIONS.REPORTS_EXPORT);
  const { type } = await params;
  if (!isReportType(type)) notFound();
  const filters = parseReportFilters(await searchParams, context.locations.map((item) => item.id));
  const report = await generateReport(type, context, filters);
  const definition = REPORT_DEFINITIONS[type];
  const query = reportQuery(filters);
  const generatedAt = new Date();
  const attentionRows = report.rows.filter((row) => row.attention);

  return <main className="space-y-6">
    <header className="print:hidden"><Link href="/reports" className="text-sm font-semibold text-emerald-700">Back to Reporting centre</Link><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">{definition.group}</p><h1 className="mt-1 text-3xl font-bold">{definition.title}</h1><p className="mt-1 max-w-3xl text-slate-600">{definition.description}</p></div><span className="rounded-full border border-slate-300 bg-white px-3 py-2 text-xs font-bold">Recommended: {definition.cadence}</span></div></header>

    <form className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm print:hidden">
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="text-sm font-medium">From<input name="from" type="date" defaultValue={filters.from?.toISOString().slice(0, 10)} className={field}/></label><label className="text-sm font-medium">To<input name="to" type="date" defaultValue={filters.to?.toISOString().slice(0, 10)} className={field}/></label><label className="text-sm font-medium">Location<select name="location" defaultValue={filters.locationId ?? ""} className={field}><option value="">All authorised locations</option>{context.locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Status<select name="status" defaultValue={filters.status ?? ""} className={field}><option value="">All statuses</option>{report.statuses.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label className="text-sm font-medium">Category<select name="category" defaultValue={filters.category ?? ""} className={field}><option value="">All categories</option>{report.categories.map((item) => <option key={item}>{item}</option>)}</select></label></div>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium"><input name="appendices" value="true" type="checkbox" defaultChecked={filters.appendices}/>Include governance appendix and sign-off</label><div className="flex gap-2"><Link href={`/reports/${type}`} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Clear filters</Link><button className="rounded-lg bg-slate-800 px-4 py-2 text-sm font-semibold text-white">Generate report</button></div></div>
    </form>

    <section className="flex flex-wrap gap-3 print:hidden"><ReportPrintButton/><a href={`/api/reports/${type}${query ? `?${query}` : ""}`} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Download detailed CSV</a></section>

    <article className="mx-auto max-w-7xl bg-white p-7 text-slate-900 shadow-sm print:p-0 print:shadow-none">
      <header className="border-b-4 border-emerald-800 pb-5"><div className="flex flex-wrap items-start justify-between gap-5"><OrganisationDocumentBrand name={context.organisation.name} hasLogo={Boolean(context.organisation.policyLogoStorageKey)}/><div className="text-right text-xs text-slate-500"><p className="font-bold uppercase tracking-wide">Controlled management report</p><p>Generated {new Intl.DateTimeFormat("en-GB", { dateStyle: "long", timeStyle: "short" }).format(generatedAt)}</p></div></div><h2 className="mt-5 text-3xl font-bold">{definition.title}</h2><table className="mt-4 w-full border-collapse text-xs"><tbody><MetaRow label1="Reporting period" value1={`${filters.from?.toLocaleDateString("en-GB") ?? "All available records"} to ${filters.to?.toLocaleDateString("en-GB") ?? "present"}`} label2="Location scope" value2={filters.locationId ? context.locations.find((item) => item.id === filters.locationId)?.name ?? "Authorised location" : "All authorised locations"}/><MetaRow label1="Prepared by" value1={context.user.name} label2="Intended audience" value2={definition.audience}/></tbody></table></header>

      <section className="mt-6"><h3 className={sectionTitle}>1. Executive assurance summary</h3><div className="mt-3 grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Records reviewed" value={report.summary.total}/><Metric label="Require attention" value={report.summary.attention} tone={report.summary.attention ? "amber" : "green"}/><Metric label="Overdue" value={report.summary.overdue} tone={report.summary.overdue ? "red" : "green"}/><Metric label="Completed / assured" value={report.summary.completed}/><Metric label="Locations covered" value={report.summary.locations}/></div><table className="mt-3 w-full border-collapse text-sm"><tbody><tr><th className={`${cell} w-48 bg-slate-50 text-left`}>System assurance indication</th><td className={cell}><strong className={assuranceTone(report.summary.assurance)}>{report.summary.assurance}</strong><p className="mt-1 leading-6 text-slate-700">{report.summary.conclusion}</p></td></tr><tr><th className={`${cell} bg-slate-50 text-left`}>Management validation</th><td className={cell}>Review the exceptions and source records below, challenge missing or contradictory evidence, then record the final management conclusion and actions in the sign-off section.</td></tr></tbody></table></section>

      <section className="mt-7"><h3 className={sectionTitle}>2. Exceptions and decisions required</h3>{attentionRows.length ? <div className="mt-3 overflow-x-auto"><table className="w-full border-collapse text-left text-xs"><thead><tr className="bg-amber-50"><th className={cell}>Priority</th><th className={cell}>Reference and record</th><th className={cell}>Location</th><th className={cell}>Owner</th><th className={cell}>Reason for attention</th><th className={cell}>Management decision / action</th></tr></thead><tbody>{attentionRows.slice(0, 25).map((row, index) => <tr key={`attention-${row.type}-${row.reference}-${index}`} className="break-inside-avoid"><td className={cell}><span className={`rounded px-2 py-1 font-bold ${row.overdue ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-900"}`}>{row.overdue ? "OVERDUE" : "REVIEW"}</span></td><td className={cell}><Link href={row.href} className="font-bold text-emerald-800 underline print:text-slate-900 print:no-underline">{row.reference} · {row.title}</Link></td><td className={cell}>{row.location}</td><td className={cell}>{row.owner}</td><td className={cell}>{row.attentionReason}</td><td className={`${cell} min-w-44`}></td></tr>)}</tbody></table>{attentionRows.length > 25 ? <p className="mt-2 text-xs text-slate-500">Showing the first 25 exceptions. Use the detailed CSV for the complete list.</p> : null}</div> : <p className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950">No automated exceptions were identified in the selected records. Management validation is still required.</p>}</section>

      <section className="mt-7"><h3 className={sectionTitle}>3. Source-record schedule</h3>{report.rows.length ? <div className="mt-3 overflow-x-auto"><table className="w-full border-collapse text-left text-[11px]"><thead><tr className="bg-slate-100"><th className={cell}>Type</th><th className={cell}>Reference / record</th><th className={cell}>Date</th><th className={cell}>Location</th><th className={cell}>Category</th><th className={cell}>Status</th><th className={cell}>Owner</th><th className={cell}>Evidence detail</th></tr></thead><tbody>{report.rows.map((row, index) => <tr key={`${row.type}-${row.reference}-${index}`} className={`break-inside-avoid ${row.attention ? "bg-amber-50/40" : ""}`}><td className={cell}>{row.type}</td><td className={cell}><span className="font-mono text-[10px]">{row.reference}</span><br/><Link href={row.href} className="font-semibold text-emerald-800 underline print:text-slate-900 print:no-underline">{row.title}</Link></td><td className={cell}>{row.date}</td><td className={cell}>{row.location}</td><td className={cell}>{row.category}</td><td className={cell}>{label(row.status)}</td><td className={cell}>{row.owner}</td><td className={cell}>{row.detail}</td></tr>)}</tbody></table></div> : <p className="mt-3 rounded-lg border border-dashed p-8 text-center text-sm">No database records match the selected scope. Confirm whether this is expected or a recording gap.</p>}</section>

      {filters.appendices ? <section className="mt-8 break-before-page"><h3 className={sectionTitle}>4. Governance appendix and approval</h3><div className="mt-3 grid gap-5 lg:grid-cols-2"><Distribution title="Records by source" rows={report.sourceCounts.map((item) => [item.source, item.count])}/><Distribution title="Records by status" rows={report.statusCounts.map((item) => [label(item.status), item.count])}/></div><table className="mt-5 w-full border-collapse text-sm"><thead><tr className="bg-slate-100"><th className={cell}>Management sign-off</th><th className={cell}>Completion record</th></tr></thead><tbody><Signoff label="Final assurance judgement" prompt="☐ Assured   ☐ Partially assured   ☐ Not assured"/><Signoff label="Key strengths and positive outcomes"/><Signoff label="Material risks, gaps and escalations"/><Signoff label="Actions, owners and deadlines"/><Signoff label="Effectiveness review arrangements"/><Signoff label="Registered Manager / accountable approver" prompt="Name:                                      Signature:                                      Date:"/></tbody></table><table className="mt-5 w-full border-collapse text-xs"><tbody><MetaRow label1="Method" value1="Authorised live records filtered by record date, location, status and category. Automated exceptions use overdue dates, risk levels, RAG status, assurance scores and missing evidence." label2="Limitations" value2="The indication depends on timely and accurate source records. It does not independently validate evidence quality, legal compliance or outcomes for people."/></tbody></table></section> : null}
      <footer className="mt-8 border-t pt-3 text-xs text-slate-500">QCGMS · Controlled internal governance record · Access and content limited to records authorised for the signed-in user.</footer>
    </article>
  </main>;
}

function Metric({ label: text, value, tone = "slate" }: { label: string; value: number; tone?: "slate" | "green" | "amber" | "red" }) { const styles = { slate: "border-slate-200 bg-slate-50", green: "border-emerald-200 bg-emerald-50", amber: "border-amber-200 bg-amber-50", red: "border-red-200 bg-red-50" }; return <div className={`rounded-xl border p-4 ${styles[tone]}`}><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-xs font-semibold text-slate-600">{text}</p></div>; }
function MetaRow({ label1, value1, label2, value2 }: { label1: string; value1: string; label2: string; value2: string }) { return <tr><th className={`${cell} w-36 bg-slate-50 text-left`}>{label1}</th><td className={cell}>{value1}</td><th className={`${cell} w-36 bg-slate-50 text-left`}>{label2}</th><td className={cell}>{value2}</td></tr>; }
function Distribution({ title, rows }: { title: string; rows: [string, number][] }) { return <table className="w-full border-collapse text-sm"><thead><tr className="bg-slate-100"><th className={`${cell} text-left`}>{title}</th><th className={`${cell} w-24 text-right`}>Count</th></tr></thead><tbody>{rows.length ? rows.map(([name, count]) => <tr key={name}><td className={cell}>{name}</td><td className={`${cell} text-right font-bold`}>{count}</td></tr>) : <tr><td className={cell}>No matching records</td><td className={`${cell} text-right`}>0</td></tr>}</tbody></table>; }
function Signoff({ label: text, prompt = "" }: { label: string; prompt?: string }) { return <tr><th className={`${cell} w-64 bg-slate-50 text-left`}>{text}</th><td className={`${cell} h-16 whitespace-pre-wrap`}>{prompt}</td></tr>; }
function assuranceTone(value: string) { if (value === "Assured") return "text-emerald-800"; if (value === "Not assured") return "text-red-800"; return "text-amber-800"; }
const field = "mt-1 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm";
const cell = "border border-slate-200 p-2 align-top";
const sectionTitle = "border-b-2 border-emerald-800 pb-2 text-lg font-bold text-emerald-950";
