-- Assessment Centre: structured assessment types that reuse the controlled register workflow.
WITH specialist(key,name,description,sort_order,extra) AS (VALUES
('assessment-holistic-needs','Holistic needs assessment','Physical, mental, emotional, social, cultural, religious, communication and equality needs with personal outcomes.',202,'[{"key":"domainsAssessed","label":"Needs domains assessed and important findings","type":"textarea","required":true},{"key":"desiredOutcomes","label":"Outcomes that matter to the person","type":"textarea","required":true}]'::jsonb),
('assessment-moving-handling','Moving and handling assessment','Person-specific mobility, transfers, equipment, staffing and emergency handling.',203,'[{"key":"independentAbility","label":"What can the person do independently?","type":"textarea","required":true},{"key":"transferPlan","label":"Safe transfer method, staffing and equipment","type":"textarea","required":true}]'::jsonb),
('assessment-falls','Falls assessment','Falls history, modifiable factors, prevention and escalation.',204,'[{"key":"fallsHistory","label":"Falls, near falls and circumstances","type":"textarea","required":true},{"key":"riskFactors","label":"Mobility, medicines, vision, continence and environmental factors","type":"textarea","required":true}]'::jsonb),
('assessment-skin-integrity','Skin integrity and pressure-risk assessment','Skin condition, pressure risk, equipment, repositioning and escalation.',205,'[{"key":"skinFindings","label":"Current skin findings and pressure areas","type":"textarea","required":true},{"key":"validatedTool","label":"Validated tool and score, if used","type":"text"}]'::jsonb),
('assessment-nutrition-hydration','Nutrition and hydration assessment','Eating, drinking, weight, swallowing, preferences, monitoring and referral.',206,'[{"key":"nutritionFindings","label":"Eating, drinking, weight and swallowing findings","type":"textarea","required":true},{"key":"monitoringReferral","label":"Monitoring and professional referral required","type":"textarea","required":true}]'::jsonb),
('assessment-medication-support','Medicines support assessment','Ability, agreed medicines assistance, storage, monitoring and escalation.',207,'[{"key":"selfManagement","label":"What medicines can the person manage independently?","type":"textarea","required":true},{"key":"agreedSupport","label":"Exact medicines support agreed","type":"textarea","required":true}]'::jsonb),
('assessment-infection-risk','Individual infection-risk assessment','Susceptibility, symptoms, exposure and additional precautions.',208,'[{"key":"infectionFactors","label":"Susceptibility, symptoms, exposure and known history","type":"textarea","required":true},{"key":"precautions","label":"Additional precautions and professional advice","type":"textarea","required":true}]'::jsonb),
('assessment-home-environment','Home and environmental assessment','Access, premises, utilities, fire, equipment, infection and worker hazards.',209,'[{"key":"environmentAreas","label":"Access, lighting, floors, stairs, utilities, smoking, pets and other findings","type":"textarea","required":true},{"key":"permissionForChanges","label":"Permission and responsibility for environmental changes","type":"textarea"}]'::jsonb),
('assessment-behaviour-distress','Distress, behaviour and violence-risk assessment','Triggers, communication, unmet needs, de-escalation and worker safety.',210,'[{"key":"triggersEarlySigns","label":"Known triggers, unmet needs and early signs","type":"textarea","required":true},{"key":"supportResponse","label":"Agreed support, de-escalation and emergency response","type":"textarea","required":true}]'::jsonb),
('assessment-communication','Communication and accessible-information assessment','Understanding, expression, formats, aids and reasonable adjustments.',211,'[{"key":"communicationProfile","label":"How the person communicates and understands information","type":"textarea","required":true},{"key":"adjustments","label":"Formats, aids, interpreters and adjustments required","type":"textarea","required":true}]'::jsonb),
('assessment-capacity-decision','Decision-specific mental-capacity assessment','Support offered and decision-specific functional capacity test.',212,'[{"key":"specificDecision","label":"Exact decision being assessed","type":"textarea","required":true},{"key":"supportOffered","label":"Practicable support offered before assessment","type":"textarea","required":true},{"key":"functionalTest","label":"Understand, retain, use or weigh, and communicate findings","type":"textarea","required":true},{"key":"causalLink","label":"Impairment or disturbance and causal link","type":"textarea","required":true}]'::jsonb),
('assessment-restrictive-practice','Restriction and least-restrictive-option assessment','Necessity, proportionality, alternatives, authority and time-limited review.',213,'[{"key":"restriction","label":"Exact restriction proposed or in use","type":"textarea","required":true},{"key":"alternatives","label":"Less restrictive alternatives tried or considered","type":"textarea","required":true},{"key":"legalAuthority","label":"Consent, capacity and lawful authority","type":"textarea","required":true}]'::jsonb),
('assessment-fire-evacuation','Personal emergency evacuation assessment','Individual evacuation assistance, staffing, equipment and emergency arrangements.',214,'[{"key":"evacuationAbility","label":"Evacuation ability and assistance required","type":"textarea","required":true},{"key":"evacuationPlan","label":"Route, equipment, staffing and contingency","type":"textarea","required":true}]'::jsonb),
('assessment-equipment','Person-specific equipment assessment','Suitability, compatibility, training, maintenance and contingency.',215,'[{"key":"equipmentDetails","label":"Equipment, purpose and person-specific suitability","type":"textarea","required":true},{"key":"maintenanceContingency","label":"Training, checks, maintenance and contingency","type":"textarea","required":true}]'::jsonb),
('assessment-end-of-life','End-of-life wishes and coordination assessment','Wishes, capacity, representation, advance planning and professional coordination.',216,'[{"key":"wishesPriorities","label":"Person’s wishes, priorities and what matters now","type":"textarea","required":true},{"key":"advancePlanning","label":"Advance decisions, DNACPR location and professional coordination","type":"textarea"}]'::jsonb),
('assessment-money-property','Money and property support assessment','Authority, capacity, limits, safeguards and records for staff assistance.',217,'[{"key":"supportAuthority","label":"Support requested and lawful authority","type":"textarea","required":true},{"key":"financialControls","label":"Limits, receipts, reconciliation and safeguarding controls","type":"textarea","required":true}]'::jsonb),
('assessment-community-activity','Community access and activity assessment','Positive risk-taking for travel, appointments and activities.',218,'[{"key":"activityOutcome","label":"Activity, destination and outcome important to the person","type":"textarea","required":true},{"key":"travelControls","label":"Travel, accessibility, staffing and emergency controls","type":"textarea","required":true}]'::jsonb),
('assessment-safeguarding-vulnerability','Safeguarding vulnerability assessment','Vulnerabilities, strengths, warning signs and safety planning.',219,'[{"key":"vulnerabilityStrengths","label":"Vulnerabilities and protective strengths","type":"textarea","required":true},{"key":"safetyPlan","label":"Warning signs, safety plan and escalation","type":"textarea","required":true}]'::jsonb),
('assessment-equality-impact','Equality impact assessment','Impact on protected groups, inequalities and reasonable mitigation.',220,'[{"key":"proposal","label":"Policy, service or decision being assessed","type":"textarea","required":true},{"key":"affectedGroups","label":"Protected groups and evidence considered","type":"textarea","required":true},{"key":"equalityEffects","label":"Positive, negative or unequal effects","type":"textarea","required":true}]'::jsonb),
('assessment-service-change-impact','Service-change impact assessment','Safety, people, workforce, equality, continuity, information and financial impact.',221,'[{"key":"changeDescription","label":"Proposed change and reason","type":"textarea","required":true},{"key":"impactDomains","label":"Safety, people, workforce, equality, continuity, data and financial impacts","type":"textarea","required":true}]'::jsonb),
('assessment-data-protection-impact','Data protection impact assessment','High-risk processing, necessity, proportionality, privacy risks and approval.',222,'[{"key":"processing","label":"Processing, data, people and technology involved","type":"textarea","required":true},{"key":"necessityProportionality","label":"Purpose, lawful basis, necessity and proportionality","type":"textarea","required":true},{"key":"privacyRisks","label":"Risks to people’s rights and freedoms","type":"textarea","required":true}]'::jsonb),
('assessment-business-impact','Business impact assessment','Critical services, tolerable disruption, dependencies and recovery priorities.',223,'[{"key":"criticalActivities","label":"Critical care and business activities","type":"textarea","required":true},{"key":"disruptionTolerance","label":"Maximum tolerable disruption and minimum service level","type":"textarea","required":true},{"key":"dependenciesRecovery","label":"Dependencies and recovery priorities","type":"textarea","required":true}]'::jsonb),
('assessment-coshh','COSHH assessment','Hazardous substances, exposure, controls, storage and emergencies.',224,'[{"key":"substanceHazards","label":"Substance, safety data and health hazards","type":"textarea","required":true},{"key":"exposureControls","label":"Exposure routes, control hierarchy, PPE and storage","type":"textarea","required":true},{"key":"emergencyHealthSurveillance","label":"Spill, first aid and health-surveillance arrangements","type":"textarea"}]'::jsonb),
('assessment-workplace-manual-handling','Workplace manual-handling assessment','Task, load, environment, capability and equipment controls.',225,'[{"key":"taskLoadEnvironment","label":"Task, load, frequency and environment","type":"textarea","required":true},{"key":"handlingControls","label":"Avoidance, equipment, staffing and safe-system controls","type":"textarea","required":true}]'::jsonb),
('assessment-lone-working','Lone-working assessment','Violence, travel, communication, welfare checks and emergencies.',226,'[{"key":"loneWorkScenario","label":"Work, location, timing and foreseeable hazards","type":"textarea","required":true},{"key":"contactEscalation","label":"Check-in, failed-contact and emergency arrangements","type":"textarea","required":true}]'::jsonb),
('assessment-pregnancy-new-mother','New and expectant mother risk assessment','Individual working conditions, adjustment and review.',227,'[{"key":"individualFactors","label":"Confidential individual and work factors considered","type":"textarea","required":true},{"key":"adjustments","label":"Adjustments, restrictions and occupational-health advice","type":"textarea","required":true}]'::jsonb),
('assessment-stress-wellbeing','Work-related stress assessment','Demands, control, support, relationships, role and change.',228,'[{"key":"stressFactors","label":"Demands, control, support, relationships, role and change findings","type":"textarea","required":true},{"key":"wellbeingControls","label":"Collective and individual controls agreed","type":"textarea","required":true}]'::jsonb),
('assessment-fire-premises','Premises fire-risk assessment record','Fire hazards, people at risk, precautions, evacuation and competent review.',229,'[{"key":"fireHazardsPeople","label":"Fire hazards and people especially at risk","type":"textarea","required":true},{"key":"precautionsEvacuation","label":"Detection, warning, escape, firefighting and evacuation controls","type":"textarea","required":true},{"key":"competentPerson","label":"Competent assessor and review arrangements","type":"textarea","required":true}]'::jsonb)
), common AS (
 SELECT '[{"key":"initialAssessmentReference","label":"Initial assessment reference","type":"text","required":true},{"key":"consentRecordReference","label":"Consent and authority record reference","type":"text","required":true},{"key":"personInvolvement","label":"How was the person involved and supported?","type":"textarea","required":true},{"key":"assessorCompetence","label":"Assessor role, competence and professional input","type":"textarea","required":true},{"key":"assessmentFindings","label":"Assessment findings and evidence considered","type":"textarea","required":true},{"key":"controlsPlan","label":"Agreed controls, support plan and responsible people","type":"textarea","required":true},{"key":"escalation","label":"Escalation or referral required","type":"textarea"},{"key":"reviewTriggers","label":"Review triggers","type":"textarea","required":true},{"key":"nextReviewDate","label":"Next review date","type":"date","required":true}]'::jsonb fields
), rows AS (
 SELECT key,name,description,sort_order,(common.fields || specialist.extra) field_schema FROM specialist CROSS JOIN common
 UNION ALL
 SELECT 'assessment-initial-needs','Initial needs and suitability assessment','First assessment of needs, preferences, outcomes, urgent risks and whether the service can safely meet them.',200,'[{"key":"personReference","label":"Person’s secure internal reference","type":"text","required":true},{"key":"referralSource","label":"Referral source and commissioner reference","type":"text"},{"key":"personInvolvement","label":"How was the person involved and supported?","type":"textarea","required":true},{"key":"representativesProfessionals","label":"Representatives and professionals involved","type":"textarea"},{"key":"needsPreferences","label":"Physical, mental, emotional, social, cultural, spiritual and communication needs","type":"textarea","required":true},{"key":"desiredOutcomes","label":"Outcomes and daily routines important to the person","type":"textarea","required":true},{"key":"urgentRisks","label":"Immediate risks and interim controls","type":"textarea","required":true},{"key":"serviceCompatibility","label":"Can the service safely meet the assessed needs?","type":"select","required":true,"options":["Yes","Yes with conditions","Further information required","No"]},{"key":"conditionsGaps","label":"Conditions, information gaps or reasons service is unsuitable","type":"textarea"},{"key":"consentRequired","label":"Consent and authority checklist required before specialist assessments","type":"boolean","required":true},{"key":"assessorDecision","label":"Assessor decision and management approval","type":"textarea","required":true},{"key":"nextReviewDate","label":"Next review date","type":"date","required":true}]'::jsonb
 UNION ALL
 SELECT 'assessment-consent-authority','Consent and authority checklist','Separate decision-specific consent and legal-authority record completed before specialist assessments.',201,'[{"key":"personReference","label":"Person’s secure internal reference","type":"text","required":true},{"key":"initialAssessmentReference","label":"Initial assessment reference","type":"text","required":true},{"key":"informationSupport","label":"Accessible information and decision-making support provided","type":"textarea","required":true},{"key":"careConsent","label":"Consent to care and personal support","type":"select","required":true,"options":["Consented","Declined","Not applicable","Capacity assessment required","Lawful representative decision"]},{"key":"medicinesConsent","label":"Consent to medicines support","type":"select","required":true,"options":["Consented","Declined","Not applicable","Capacity assessment required","Lawful representative decision"]},{"key":"healthcareConsent","label":"Consent to delegated healthcare tasks","type":"select","required":true,"options":["Consented","Declined","Not applicable","Capacity assessment required","Lawful representative decision"]},{"key":"informationSharingConsent","label":"Routine information-sharing choice","type":"select","required":true,"options":["Consented","Declined","Not applicable","Other lawful basis recorded","Capacity assessment required"]},{"key":"photoConsent","label":"Photograph or video choice","type":"select","required":true,"options":["Consented","Declined","Not applicable","Capacity assessment required","Lawful representative decision"]},{"key":"accessConsent","label":"Home, key-safe and access arrangements","type":"select","required":true,"options":["Consented","Declined","Not applicable","Capacity assessment required","Lawful representative decision"]},{"key":"moneyConsent","label":"Money, shopping or property support","type":"select","required":true,"options":["Consented","Declined","Not applicable","Capacity assessment required","Lawful representative decision"]},{"key":"representativeConsent","label":"Family, advocate or representative involvement","type":"select","required":true,"options":["Consented","Declined","Not applicable","Legal authority confirmed","Capacity assessment required"]},{"key":"authorityEvidence","label":"LPA, deputyship, advance decision or other authority evidence","type":"textarea"},{"key":"restrictionsRefusals","label":"Refusals, limits, conditions and withdrawal arrangements","type":"textarea","required":true},{"key":"capacityActions","label":"Decision-specific capacity or best-interest actions required","type":"textarea"},{"key":"assessorConfirmation","label":"Assessor confirmation and evidence checked","type":"textarea","required":true},{"key":"nextReviewDate","label":"Next review date or review trigger date","type":"date","required":true}]'::jsonb
)
INSERT INTO "RegisterDefinition" (id,"organisationId",key,name,description,"fieldSchema","isPublished","sortOrder","createdAt","updatedAt")
SELECT md5('register-definition:'||key)::uuid,NULL,key,name,description,field_schema,true,sort_order,NOW(),NOW() FROM rows
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,"fieldSchema"=EXCLUDED."fieldSchema","isPublished"=true,"sortOrder"=EXCLUDED."sortOrder","updatedAt"=NOW();
