import Link from "next/link";
import { notFound } from "next/navigation";
import { CarePlanForm } from "@/components/care-plan-form";
import { requirePermission } from "@/lib/auth/dal";
import { loadCarePlan } from "@/lib/care-plan-data";
import { parseCarePlanSnapshot } from "@/lib/care-plans";
import { createDb } from "@/lib/db";
import { evidenceScopeWhere } from "@/lib/evidence";
import { PERMISSIONS } from "@/lib/permissions";

export default async function EditCarePlanPage({params}:{params:Promise<{id:string}>}){const context=await requirePermission(PERMISSIONS.GOVERNANCE_EDIT),{id}=await params,db=createDb();try{const loaded=await loadCarePlan(db,context,id);if(!loaded)notFound();const[members,evidence,staff]=await Promise.all([db.organisationMembership.findMany({where:{organisationId:context.organisation.id,status:"ACTIVE"},select:{user:{select:{id:true,name:true}}},orderBy:{user:{name:"asc"}}}),db.evidence.findMany({where:{...evidenceScopeWhere(context),status:"ACTIVE"},select:{id:true,title:true},orderBy:{title:"asc"},take:1000}),db.staffMember.findMany({where:{organisationId:context.organisation.id,archivedAt:null,employmentStatus:"ACTIVE"},select:{id:true,firstName:true,lastName:true,preferredName:true},orderBy:[{lastName:"asc"},{firstName:"asc"}],take:1000})]);const p=loaded.person;return <main className="space-y-5"><header><Link href={`/care-plans/${id}`} className="text-sm font-semibold text-emerald-700">← Back to care plan</Link><p className="mt-3 font-mono text-sm text-emerald-700">{loaded.plan.reference}</p><h1 className="text-3xl font-bold">Prepare controlled care-plan update</h1><p className="mt-1 text-slate-600">Published clinical records remain read-only. Saving creates or updates a proposed version for comparison and approval.</p></header><CarePlanForm organisationName={context.organisation.name} person={{id:loaded.plan.clientId,name:p.name,reference:p.reference,preferredName:p.preferredName,dateOfBirth:p.dateOfBirth,phone:p.phone,address:p.address,communicationSummary:p.communicationSummary,emergencyContact:p.emergencyContact,representative:p.representative}} locations={context.locations.map(({id,name})=>({id,name}))} users={members.map(({user})=>user)} evidence={evidence.map((x)=>({id:x.id,name:x.title}))} staff={staff.map((x)=>({id:x.id,name:`${x.preferredName?.trim()||x.firstName} ${x.lastName}`}))} initial={{id,reference:loaded.plan.reference,locationId:loaded.plan.locationId??"",clientId:loaded.plan.clientId,careCoordinatorId:loaded.plan.careCoordinatorId??"",registeredManagerId:loaded.plan.registeredManagerId??"",status:loaded.plan.status,overallRisk:loaded.plan.overallRisk,nextReviewDate:(loaded.display.nextReviewDate??loaded.plan.nextReviewDate)?.toISOString().slice(0,10)??"",serviceType:loaded.plan.serviceType??"",fundingType:loaded.plan.fundingType??"",localAuthorityCode:loaded.plan.localAuthorityCode??"",localAuthorityName:loaded.plan.localAuthorityName??"",commissioner:loaded.plan.commissioner??"",snapshot:parseCarePlanSnapshot(loaded.display.snapshot),evidenceIds:loaded.display.evidenceLinks.map((x)=>x.evidenceId),staffIds:loaded.plan.assignments.filter((x)=>x.isActive).map((x)=>x.staffMemberId)}}/></main>}finally{await db.$disconnect()}}
