import { notFound } from "next/navigation";
import { OrganisationDocumentBrand } from "@/components/organisation-document-brand";
import { requirePermission } from "@/lib/auth/dal";
import { actionScopeWhere } from "@/lib/actions";
import { createDb } from "@/lib/db";
import { PERMISSIONS } from "@/lib/permissions";
import { registerScopeWhere, registerStatusLabel } from "@/lib/registers";

export default async function ComplaintAssuranceReport({ params }: { params: Promise<{ id: string }> }) {
  const context = await requirePermission(PERMISSIONS.REPORTS_EXPORT);
  const { id } = await params;
  const db = createDb();
  try {
    const complaint = await db.registerEntry.findFirst({ where: { id, ...registerScopeWhere(context), definition: { key: "complaints" } }, include: { location: { select: { name: true } }, client: { select: { clientReference: true } }, staffMember: { select: { employeeReference: true } }, owner: { select: { name: true } }, createdBy: { select: { name: true } }, evidenceLinks: { include: { evidence: { select: { id: true, title: true, category: true } } } }, complaintInvestigation: { include: { investigator: { select: { name: true } }, responseApprovedBy: { select: { name: true } } } }, complaintIssues: { include: { evidenceLinks: { include: { evidence: { select: { title: true } } } } }, orderBy: { sequence: "asc" } }, complaintCommunications: { include: { author: { select: { name: true } }, evidence: { select: { title: true } } }, orderBy: { occurredAt: "asc" } }, complaintAssuranceReviews: { include: { reviewer: { select: { name: true } }, evidenceLinks: { include: { evidence: { select: { title: true } } } } }, orderBy: { reviewedAt: "asc" } }, history: { include: { user: { select: { name: true } } }, orderBy: { createdAt: "asc" } } } });
    if (!complaint) notFound();
    const actions = await db.action.findMany({ where: { ...actionScopeWhere(context), sourceType: "COMPLAINT", sourceRecordId: id, archivedAt: null }, include: { owner: { select: { name: true } }, verifications: { orderBy: { verifiedAt: "desc" }, take: 1 }, effectivenessReviews: { orderBy: { reviewDate: "desc" }, take: 1 } }, orderBy: { createdAt: "asc" } });
    const investigation = complaint.complaintInvestigation;
    return <main className="mx-auto max-w-6xl bg-white p-8 text-slate-900 print:p-0"><p className="mb-4 rounded-lg bg-emerald-700 px-4 py-2 text-center text-sm font-semibold text-white print:hidden">Use your browser Print command to save this organisation-branded Complaint Assurance record as PDF.</p><header className="border-b-4 border-emerald-800 pb-5"><div className="flex items-start justify-between gap-5"><OrganisationDocumentBrand name={context.organisation.name} hasLogo={Boolean(context.organisation.policyLogoStorageKey)}/><div className="text-right text-xs text-slate-500"><p className="font-bold uppercase tracking-wide">Controlled Complaint Assurance record</p><p>Generated {dateTime(new Date())}</p></div></div><h1 className="mt-5 text-3xl font-black">{complaint.reference} · {complaint.title}</h1><p className="mt-2 text-sm leading-6">{complaint.summary}</p></header>
      <Section number="1" title="Complaint control"><Table rows={[["Date received",date(complaint.eventDate)],["Status",registerStatusLabel(complaint.status)],["Current risk",complaint.riskLevel],["Location",complaint.location?.name??"Organisation-wide"],["Owner",complaint.owner?.name??"Unassigned"],["Client reference",complaint.client?.clientReference??"Not linked"],["Staff reference",complaint.staffMember?.employeeReference??"Not linked"],["Complainant",investigation?.complainantName??"Not recorded"],["Relationship",investigation?.complainantRelationship??"Not recorded"],["Contact/accessibility",[investigation?.contactPreference,investigation?.accessibilityNeeds].filter(Boolean).join(" · ")||"Not recorded"]]} /></Section>
      <Section number="2" title="Safety, acknowledgement and investigation"><Table rows={[["Immediate safety",investigation?.immediateSafetyConcern??"Not recorded"],["Immediate response",investigation?.immediateSafetyResponse??"Not recorded"],["Safeguarding decision",investigation?.safeguardingDecision??"Not recorded"],["Incident decision",investigation?.incidentDecision??"Not recorded"],["Acknowledgement due",date(investigation?.acknowledgementDueAt)],["Response due",date(investigation?.extensionDueAt??investigation?.responseDueAt)],["Investigator",investigation?.investigator.name??"Not assigned"],["Investigation status",investigation?.status??"Not started"],["Approach",investigation?.investigationApproach??"Not recorded"],["Evidence sources",investigation?.evidenceSources??"Not recorded"],["Complainant involvement",investigation?.complainantInvolvement??"Not recorded"]]} /></Section>
      <Section number="3" title="Issues and findings">{complaint.complaintIssues.length?<table className={table}><thead><tr className={head}><th className={cell}>Issue</th><th className={cell}>Concern</th><th className={cell}>Finding</th><th className={cell}>Reason and outcome</th><th className={cell}>Evidence</th><th className={cell}>Action</th></tr></thead><tbody>{complaint.complaintIssues.map((issue)=><tr key={issue.id} className="break-inside-avoid"><td className={cell}>{issue.sequence}. {issue.category}</td><td className={cell}>{issue.concern}</td><td className={cell}>{issue.finding?registerStatusLabel(issue.finding):"Not determined"}</td><td className={cell}>{issue.reasoning??"Not recorded"}<br/>{issue.outcomeSummary}</td><td className={cell}>{issue.evidenceLinks.map(({evidence})=>evidence.title).join("; ")||"None linked"}</td><td className={cell}>{issue.actionRequired===true?"Required":issue.actionRequired===false?"Not required":"Not determined"}</td></tr>)}</tbody></table>:<p>No issues recorded.</p>}</Section>
      <Section number="4" title="Response, remedy and learning"><Table rows={[["Investigation outcome",investigation?.investigationOutcome??"Not recorded"],["Remedy",investigation?.remedy??"Not recorded"],["Learning",investigation?.learning??"Not recorded"],["Learning scope",investigation?.learningScopes.join(", ")||"Not recorded"],["Affected records",investigation?.affectedRecordsReviewed??"Not recorded"],["Recurrence review",investigation?.recurrenceReview??"Not recorded"],["Response prepared",date(investigation?.responsePreparedAt)],["Response approved",investigation?.responseApprovedAt?`${date(investigation.responseApprovedAt)} by ${investigation.responseApprovedBy?.name??"authorised manager"}`:"Not recorded"],["Response summary",investigation?.responseSummary??"Not recorded"],["Escalation information",yesNo(investigation?.escalationRightsConfirmed)],["Complainant feedback",[investigation?.complainantSatisfaction,investigation?.satisfactionComment].filter(Boolean).join(" · ")||"Not recorded (not a closure test)"]]} /></Section>
      <Section number="5" title="Communication chronology">{complaint.complaintCommunications.length?<table className={table}><thead><tr className={head}><th className={cell}>Date</th><th className={cell}>Type/direction</th><th className={cell}>Participants</th><th className={cell}>Summary</th><th className={cell}>Evidence</th></tr></thead><tbody>{complaint.complaintCommunications.map((item)=><tr key={item.id} className="break-inside-avoid"><td className={cell}>{dateTime(item.occurredAt)}</td><td className={cell}>{registerStatusLabel(item.type)}<br/>{registerStatusLabel(item.direction)}</td><td className={cell}>{item.participants}<br/><small>Recorded by {item.author.name}</small></td><td className={cell}>{item.summary}</td><td className={cell}>{item.evidence?.title??"No separate document"}</td></tr>)}</tbody></table>:<p>No communications recorded.</p>}</Section>
      <Section number="6" title="Central Actions and effectiveness">{actions.length?<table className={table}><thead><tr className={head}><th className={cell}>Action</th><th className={cell}>Owner/due</th><th className={cell}>Lifecycle</th><th className={cell}>Verification</th><th className={cell}>Effectiveness</th></tr></thead><tbody>{actions.map((action)=><tr key={action.id}><td className={cell}>{action.reference}<br/><strong>{action.title}</strong></td><td className={cell}>{action.owner.name}<br/>{date(action.dueDate)}</td><td className={cell}>{registerStatusLabel(action.lifecycleStatus)}</td><td className={cell}>{action.verifications[0]?.outcome?registerStatusLabel(action.verifications[0].outcome):"Not recorded"}</td><td className={cell}>{action.effectivenessReviews[0]?.outcome?registerStatusLabel(action.effectivenessReviews[0].outcome):"Not demonstrated"}</td></tr>)}</tbody></table>:<p>No central Action linked.</p>}</Section>
      <Section number="7" title="Management Assurance and reopening history">{complaint.complaintAssuranceReviews.length?<div className="space-y-3">{complaint.complaintAssuranceReviews.map((review)=><article key={review.id} className="break-inside-avoid rounded-xl border p-4"><div className="flex justify-between gap-3"><strong>{registerStatusLabel(review.decision)}</strong><span>{dateTime(review.reviewedAt)}</span></div><p className="mt-2">{review.rationale}</p>{review.newInformation?<p className="mt-2"><strong>New information:</strong> {review.newInformation}</p>:null}<p className="mt-2 text-xs text-slate-500">{review.reviewer.name} · {review.reviewerRoleKeySnapshot.replaceAll("-"," ")} · Evidence: {review.evidenceLinks.map(({evidence})=>evidence.title).join("; ")||"None separately selected"}</p></article>)}</div>:<p>No Management Assurance decision recorded.</p>}</Section>
      <Section number="8" title="Governed Evidence"><ul className="grid gap-2 md:grid-cols-2">{complaint.evidenceLinks.map(({evidence})=><li key={evidence.id} className="rounded-lg border p-3 text-sm"><strong>{evidence.category}</strong><br/>{evidence.title}</li>)}</ul></Section>
      <footer className="mt-8 border-t pt-3 text-xs text-slate-500">QCGMS · Controlled internal governance record · A system record supports, but does not replace, authorised professional judgement.</footer>
    </main>;
  } finally { await db.$disconnect(); }
}

function Section({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="mt-7 break-inside-avoid"><h2 className="border-b-2 border-emerald-800 pb-2 text-lg font-black text-emerald-950">{number}. {title}</h2><div className="mt-3">{children}</div></section>}
function Table({rows}:{rows:[string,string][]}){return <table className={table}><tbody>{rows.map(([label,value])=><tr key={label}><th className={`${cell} w-1/3 bg-slate-50 text-left`}>{label}</th><td className={`${cell} whitespace-pre-wrap`}>{value}</td></tr>)}</tbody></table>}
function date(value:Date|null|undefined){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value):"Not set"}
function dateTime(value:Date){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(value)}
function yesNo(value:boolean|null|undefined){return value===true?"Yes":value===false?"No / not applicable":"Not recorded"}
const table="w-full border-collapse text-left text-xs";const head="bg-slate-100";const cell="border border-slate-200 p-2 align-top";
