import Link from "next/link";
import { notFound } from "next/navigation";
import { CheckCircle2, CircleAlert, Clock3, ExternalLink, GitBranch, ShieldCheck } from "lucide-react";
import { ActionClosureControl, ActionEvidenceManager, DependencyDecision, EffectivenessControl, ExternalDependencyControl, RetireActionEvidence, RootCauseControl, VerificationControl } from "@/components/assurance-workflow-controls";
import { requireAnyPermission } from "@/lib/auth/dal";
import { actionAssuranceReadiness, evidenceRoleLabel, resolveActionAssurancePolicy } from "@/lib/action-assurance";
import { actionLabel, actionScopeWhere } from "@/lib/actions";
import { assuranceStage, externalDependencyState } from "@/lib/assurance-improvement";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS, ROLE_KEYS } from "@/lib/permissions";

export default async function ActionAssurancePage({ params }: { params: Promise<{ id: string }> }) {
  const context = await requireAnyPermission([PERMISSIONS.GOVERNANCE_VIEW, PERMISSIONS.ACTIONS_MANAGE]), { id } = await params, db = createDb();
  try {
    const [action, memberships, externalParties] = await Promise.all([
      db.action.findFirst({ where: { id, ...actionScopeWhere(context) }, include: { finding: true, rootCauseReview: true, verifications: { orderBy: { verifiedAt: "desc" } }, effectivenessReviews: { orderBy: [{ reviewDate: "desc" }, { createdAt: "desc" }] }, recurrenceCases: { orderBy: { detectedAt: "desc" } }, externalDependencies: { orderBy: { dueDate: "asc" } }, improvementPlanLinks: { include: { plan: true } }, evidenceLinks: { include: { evidence: { select: { id: true, title: true } }, linkedBy: { select: { name: true } }, retiredBy: { select: { name: true } } }, orderBy: { linkedAt: "desc" } }, owner: { select: { name: true } }, closedBy: { select: { name: true } } } }),
      db.organisationMembership.findMany({ where: { organisationId: context.organisation.id, status: "ACTIVE" }, select: { user: { select: { id: true, name: true } } }, orderBy: { user: { name: "asc" } } }),
      db.externalParty.findMany({ where: { organisationId: context.organisation.id, archivedAt: null }, select: { id: true, name: true }, orderBy: { name: "asc" } }),
    ]);
    if (!action) notFound();
    const canManage = hasPermission(context.permissions, PERMISSIONS.ACTIONS_MANAGE), canApprove = [ROLE_KEYS.OWNER, ROLE_KEYS.REGISTERED_MANAGER, ROLE_KEYS.QUALITY_MANAGER].includes(context.role.key as never), verification = action.verifications[0] ?? null, effectiveness = action.effectivenessReviews[0] ?? null;
    const stage = assuranceStage({ hasRootCause: Boolean(action.rootCauseReview && ["COMPLETED", "APPROVED"].includes(action.rootCauseReview.status)), verificationOutcome: verification?.outcome ?? null, effectivenessOutcome: effectiveness?.outcome ?? null, recurrenceCount: action.recurrenceCount });
    const activeLinks=action.evidenceLinks.filter(item=>!item.retiredAt),members = memberships.map(({ user }) => ({ id: user.id, name: user.name })), evidence = [...new Map(activeLinks.map(({ evidence: item }) => [item.id, { id: item.id, name: item.title }])).values()], today = new Date().toISOString().slice(0, 10);
    const roleCounts=activeLinks.reduce<Record<string,number>>((counts,item)=>({...counts,[item.role]:(counts[item.role]??0)+1}),{});
    const providerPolicy=action.sourceType==="RISK"?undefined:await resolveActionAssurancePolicy(db,{organisationId:context.organisation.id,priority:action.priority,sourceType:action.sourceType});
    const assurance=actionAssuranceReadiness({priority:action.priority,sourceType:action.sourceType,progressPercent:action.progressPercent,completionDate:action.completionDate,ownerId:action.ownerId,closerId:context.user.id,verification:verification?{outcome:verification.outcome,verifierId:verification.verifierId}:null,effectiveness:effectiveness?{outcome:effectiveness.outcome,recurrenceFound:effectiveness.recurrenceFound}:null,roleCounts,unresolvedDependencies:action.externalDependencies.filter(item=>!["RESOLVED","CANCELLED"].includes(item.status)).length,rootCauseComplete:Boolean(action.rootCauseReview&&["COMPLETED","APPROVED"].includes(action.rootCauseReview.status)),policy:providerPolicy});
    return <main className="space-y-6">
      <header className="rounded-3xl bg-gradient-to-br from-slate-950 via-emerald-950 to-teal-800 p-7 text-white"><Link href={`/actions/${id}`} className="text-sm font-bold text-emerald-100">← Back to action {action.reference}</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-200">Issue-to-improvement chronology</p><h1 className="mt-1 text-3xl font-bold">{action.title}</h1><p className="mt-2 text-emerald-50">Current assurance stage: <strong>{actionLabel(stage)}</strong></p></div><ShieldCheck className="size-12 text-emerald-200"/></div></header>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Finding",Boolean(action.finding)],["Cause",Boolean(action.rootCauseReview&&["COMPLETED","APPROVED"].includes(action.rootCauseReview.status))],["Action",true],["Verification",verification?.outcome==="VERIFIED"],["Effectiveness",effectiveness?.outcome==="EFFECTIVE"],["Sustained",stage==="SUSTAINED"]].map(([label,done])=><div key={String(label)} className={`rounded-2xl border p-4 ${done?"border-emerald-200 bg-emerald-50":"border-slate-200 bg-white"}`}>{done?<CheckCircle2 className="text-emerald-700" size={20}/>:<Clock3 className="text-slate-400" size={20}/>}<p className="mt-2 text-sm font-bold">{String(label)}</p></div>)}</section>
      <Section icon={CircleAlert} title="1. Canonical finding" description="The finding retains the originating record and is resolved only when the linked action is verified."><dl className="grid gap-3 md:grid-cols-3"><Fact label="Reference" value={action.finding?.reference ?? `FND-${action.reference}`}/><Fact label="Source" value={`${actionLabel(action.sourceType)} · ${action.sourceReference ?? "Manual"}`}/><Fact label="Severity" value={action.priority}/><Fact label="Identified" value={date(action.firstSeenAt)}/><Fact label="Owner" value={action.owner.name}/><Fact label="Status" value={action.finding?.status ? actionLabel(action.finding.status) : "Action linked"}/></dl></Section>
      <Section icon={GitBranch} title="2. Root-cause review" description="Separate immediate causes from contributing and system causes, then identify learning and prevention.">{action.rootCauseReview ? <Summary rows={[["Method",actionLabel(action.rootCauseReview.method)],["Status",actionLabel(action.rootCauseReview.status)],["Immediate causes",action.rootCauseReview.immediateCauses.join("; ")],["Contributing factors",action.rootCauseReview.contributingFactors.join("; ")],["System causes",action.rootCauseReview.systemCauses.join("; ")],["Learning",action.rootCauseReview.lessons],["Prevention",action.rootCauseReview.preventiveControls]]}/> : <Empty text="Structured cause review not completed."/>}{canManage&&!action.closedAt?<div className="mt-5 border-t pt-5"><RootCauseControl id={id} canApprove={canApprove} initial={action.rootCauseReview ? { method: action.rootCauseReview.method, problemStatement: action.rootCauseReview.problemStatement, immediateCauses: action.rootCauseReview.immediateCauses, contributingFactors: action.rootCauseReview.contributingFactors, systemCauses: action.rootCauseReview.systemCauses, lessons: action.rootCauseReview.lessons, preventiveControls: action.rootCauseReview.preventiveControls } : undefined}/></div>:null}</Section>
      <Section icon={ShieldCheck} title="3. Role-aware Evidence" description="One canonical Evidence record may support more than one governance purpose. Retired relationships stay visible so earlier decisions retain their provenance."><div className="grid gap-3 md:grid-cols-2">{action.evidenceLinks.length?action.evidenceLinks.map(link=><article key={link.id} className={`rounded-xl border p-3 ${link.retiredAt?"bg-slate-50 opacity-75":""}`}><div className="flex items-start justify-between gap-2"><Link href={`/evidence/${link.evidence.id}`} className="font-bold text-emerald-800">{link.evidence.title}</Link><Badge value={link.retiredAt?`${evidenceRoleLabel(link.role)} · Retired`:evidenceRoleLabel(link.role)}/></div><p className="mt-1 text-xs text-slate-500">Linked {date(link.linkedAt)}{link.linkedBy?` by ${link.linkedBy.name}`:" · legacy relationship"}</p>{link.retiredAt?<p className="mt-1 text-xs text-slate-600">Retired {date(link.retiredAt)}{link.retiredBy?` by ${link.retiredBy.name}`:""} · {link.retirementReason}</p>:canManage&&!action.closedAt?<RetireActionEvidence actionId={id} linkId={link.id}/>:null}</article>):<Empty text="No Evidence relationship history."/>}</div>{canManage&&!action.closedAt?<div className="mt-5"><ActionEvidenceManager id={id}/></div>:null}</Section>
      <Section icon={ShieldCheck} title="4. Verification" description={`Verification tests completion evidence against the predefined success measure. ${assurance.policy.separateVerifierRequired?"A verifier separate from the delivery owner is required.":"Separate verification is not mandatory solely because of this Action's priority, but the decision remains attributable."}`}>{action.verifications.length?<div className="space-y-3">{action.verifications.map((item,index)=><article key={item.id} className={`rounded-xl border p-4 ${index===0?"border-emerald-200 bg-emerald-50/40":"border-slate-200"}`}><div className="flex flex-wrap items-center justify-between gap-2"><strong>{index===0?"Current verification decision":"Earlier verification decision"}</strong><Badge value={item.outcome}/></div><dl className="mt-3 grid gap-3 md:grid-cols-2"><Fact label="Decision date" value={date(item.verifiedAt)}/><Fact label="Evidence checked" value={item.evidenceSummary}/><Fact label="Success measure result" value={item.successMeasureResult}/><Fact label="Rationale" value={item.rationale}/><Fact label="Separate from owner" value={item.independenceConfirmed?"Yes":"No"}/></dl></article>)}</div>:<Empty text="No structured verification recorded."/>}{canManage&&!action.closedAt&&assurance.policy.verificationRequired?<div className="mt-5 border-t pt-5"><VerificationControl id={id} members={members} evidence={evidence} ownerId={action.ownerId} currentUserId={context.user.id} today={today}/></div>:null}</Section>
      <Section icon={CheckCircle2} title="5. Effectiveness and sustained improvement" description="Compare observed results with the success measure after verification. Recurrence or an Ineffective outcome reopens the improvement path without erasing earlier completion evidence.">{effectiveness?.outcome==="INEFFECTIVE"||action.lifecycleStatus==="REOPENED_REPEAT_FINDING"?<p role="status" className="mb-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-800">Action reopened for further management attention. The original completion and ineffective judgement remain in the history.</p>:null}{action.effectivenessReviews.length?<div className="space-y-3">{action.effectivenessReviews.map((item)=><article key={item.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><strong>{date(item.reviewDate)}</strong><Badge value={item.outcome}/></div><p className="mt-2 text-sm"><strong>Observed:</strong> {item.observedResult}</p><p className="mt-1 text-sm"><strong>Decision:</strong> {item.decision}</p>{item.recurrenceFound?<p className="mt-2 text-xs font-bold text-red-700">Recurrence identified; Action reopened.</p>:null}</article>)}</div>:<Empty text="No effectiveness review recorded."/>}{canManage&&!action.closedAt&&assurance.policy.effectivenessRequired?<div className="mt-5 border-t pt-5"><EffectivenessControl id={id} evidence={evidence} today={today}/></div>:null}</Section>
      <Section icon={ExternalLink} title="5. External dependencies" description="Track requests, chasing, interim controls and escalation without treating an external delay as completed work.">{action.externalDependencies.length?<div className="grid gap-3 lg:grid-cols-2">{action.externalDependencies.map((item)=>{const status=externalDependencyState(item);return <article key={item.id} className={`rounded-xl border p-4 ${status==="OVERDUE"?"border-red-200 bg-red-50":"border-slate-200"}`}><div className="flex justify-between gap-3"><strong>{item.partyName}</strong><Badge value={status}/></div><p className="mt-2 text-sm">{item.request}</p><p className="mt-2 text-xs text-slate-600">Due {date(item.dueDate)} · chased {item.chaseCount} time(s) · {item.contactEmail??item.contactPhone??"No contact"}</p><p className="mt-2 text-xs"><strong>Interim control:</strong> {item.interimControl}</p>{canManage&&!action.closedAt&&!['RESOLVED','CANCELLED'].includes(item.status)?<DependencyDecision actionId={id} dependencyId={item.id}/>:null}</article>})}</div>:<Empty text="No external dependency recorded."/>}{canManage&&!action.closedAt?<div className="mt-5 border-t pt-5"><ExternalDependencyControl id={id} members={members} parties={externalParties} today={today}/></div>:null}</Section>
      <Section icon={CircleAlert} title="6. Recurrence and improvement plans" description="Repeat findings remain linked to the original improvement record and require renewed control review."><div className="grid gap-4 lg:grid-cols-2"><div><h3 className="font-bold">Recurrence cases</h3>{action.recurrenceCases.length?<ul className="mt-2 space-y-2 text-sm">{action.recurrenceCases.map((item)=><li key={item.id} className="rounded-lg bg-red-50 p-3"><strong>{item.reference} · {actionLabel(item.status)}</strong><p>{item.narrative}</p></li>)}</ul>:<p className="mt-2 text-sm text-slate-500">No confirmed recurrence.</p>}</div><div><h3 className="font-bold">Improvement plans</h3>{action.improvementPlanLinks.length?<ul className="mt-2 space-y-2 text-sm">{action.improvementPlanLinks.map(({plan})=><li key={plan.id} className="rounded-lg bg-blue-50 p-3"><strong>{plan.reference} · {plan.title}</strong><p>{actionLabel(plan.status)} · target {date(plan.targetDate)}</p></li>)}</ul>:<p className="mt-2 text-sm text-slate-500">Not grouped into a wider plan.</p>}<Link href="/improvement" className="mt-3 inline-block text-sm font-bold text-emerald-800">Open improvement workbench →</Link></div></div></Section>
      <Section icon={ShieldCheck} title="7. Management assurance and closure" description="Completion, verification, effectiveness and closure are separate attributable decisions. Server-side rules apply even if a browser control is bypassed.">{action.closedAt?<Summary rows={[["Closed",date(action.closedAt)],["Closed by",action.closedBy?.name??"Legacy closure actor not recorded"],["Rationale",action.closureAssuranceRationale??action.closureNote??"Legacy closure rationale not recorded"]]}/>:null}{canManage?<div className={action.closedAt?"mt-5 border-t pt-5":""}><ActionClosureControl id={id} evidence={evidence} outstanding={assurance.outstanding.map(({label,reason})=>({label,reason}))} closed={Boolean(action.closedAt)}/></div>:null}</Section>
    </main>;
  } finally { await db.$disconnect(); }
}
function Section({icon:Icon,title,description,children}:{icon:typeof ShieldCheck;title:string;description:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-3"><Icon className="mt-0.5 text-emerald-700" size={22}/><div><h2 className="text-lg font-bold">{title}</h2><p className="mt-1 text-sm text-slate-600">{description}</p></div></div><div className="mt-5">{children}</div></section>}
function Fact({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm">{value}</dd></div>}
function Summary({rows}:{rows:string[][]}){return <dl className="grid gap-3 md:grid-cols-2">{rows.map(([label,value])=><Fact key={label} label={label} value={value||"Not recorded"}/>)}</dl>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed border-slate-300 p-4 text-sm text-slate-500">{text}</p>}
function Badge({value}:{value:string}){return <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{actionLabel(value)}</span>}
function date(value:Date|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value):"Not set"}
