import { notFound } from "next/navigation";
import { OrganisationDocumentBrand } from "@/components/organisation-document-brand";
import { requirePermission } from "@/lib/auth/dal";
import { auditScopeWhere, auditStatusLabel, calculateAuditScore } from "@/lib/audits";
import { createDb } from "@/lib/db";
import { PERMISSIONS } from "@/lib/permissions";

export default async function AuditReportPage({params}:{params:Promise<{id:string}>}) {
  const context=await requirePermission(PERMISSIONS.REPORTS_EXPORT);const {id}=await params;const db=createDb();
  const audit=await db.audit.findFirst({where:{id,...auditScopeWhere(context)},include:{template:{include:{sections:{include:{questions:{orderBy:{sortOrder:"asc"}}},orderBy:{sortOrder:"asc"}}}},auditor:{select:{name:true}},location:{select:{name:true}},signedOffBy:{select:{name:true}},responses:{include:{evidence:{select:{title:true}}}},findings:true}}).finally(()=>db.$disconnect());
  if(!audit)notFound();
  return <main className="mx-auto max-w-5xl bg-white p-8 text-slate-900 print:p-0"><div className="mb-8 flex items-start justify-between border-b-4 border-emerald-800 pb-6"><div><OrganisationDocumentBrand name={context.organisation.name} hasLogo={Boolean(context.organisation.policyLogoStorageKey)} /><h1 className="mt-2 text-4xl font-bold">Audit report</h1><p className="mt-2 text-xl">{audit.title}</p></div><p className="print:hidden rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Press Ctrl+P to save PDF</p></div>
    <section className="grid grid-cols-2 gap-4 rounded-xl bg-slate-50 p-5 text-sm"><Detail term="Template" value={`${audit.template.name} v${audit.templateVersion}`}/><Detail term="Audit area" value={audit.template.category}/><Detail term="Location" value={audit.location.name}/><Detail term="Auditor" value={audit.auditor.name}/><Detail term="Audit date" value={date(audit.auditDate)}/><Detail term="Status" value={auditStatusLabel(audit.status)}/><Detail term="Internal assurance score" value={audit.overallScore===null?"Not scored":`${audit.overallScore}%`}/><Detail term="Period reviewed" value={`${date(audit.periodStart)} – ${date(audit.periodEnd)}`}/><Detail term="Sample" value={`${audit.sampleSize??"Not recorded"} · ${audit.sampleMethod?.replaceAll("_"," ")??"method not recorded"}`}/><Detail term="Signed off by" value={audit.signedOffBy?.name??"Not signed off"}/></section>
    <section className="mt-6 grid gap-4 md:grid-cols-2"><Summary title="Objective" value={audit.objective}/><Summary title="Standard or procedure tested" value={audit.standardApplied??audit.template.standardRefs.join(" · ")}/><Summary title="Sample details" value={audit.sampleDetails}/><Summary title="Known limitations" value={audit.limitations}/></section>
    {audit.scope&&<section className="mt-6"><h2 className="text-xl font-bold">Scope</h2><p className="mt-2 whitespace-pre-wrap">{audit.scope}</p></section>}
    {audit.template.sections.map((section)=><section key={section.id} className="mt-8 break-inside-avoid"><div className="flex items-baseline justify-between border-b border-slate-300 pb-2"><h2 className="text-2xl font-bold">{section.title}</h2><strong>{sectionScore(section.questions,audit.responses)}</strong></div><div className="divide-y divide-slate-200">{section.questions.map((question)=>{const response=audit.responses.find((item)=>item.questionId===question.id);return <div key={question.id} className="py-4"><h3 className="font-semibold">{question.text}</h3><div className="mt-2 grid grid-cols-[1fr_2fr] gap-4 text-sm"><p><span className="text-slate-500">Response</span><br/><strong>{response?.answer?.replaceAll("_"," ")??"Not answered"}</strong></p><p><span className="text-slate-500">Comment</span><br/>{response?.comment??"—"}{response?.evidence&&<><br/><span className="text-slate-500">Evidence: {response.evidence.title}</span></>}</p></div></div>})}</div></section>)}
    <section className="mt-8 grid gap-4 md:grid-cols-3">{[["Strengths",audit.strengths],["Risks",audit.risks],["Recommendations",audit.recommendations]].map(([title,value])=><div key={title} className="rounded-xl border border-slate-200 p-4"><h2 className="font-bold">{title}</h2><p className="mt-2 whitespace-pre-wrap text-sm">{value??"None recorded."}</p></div>)}</section>
    <footer className="mt-10 border-t border-slate-300 pt-4 text-xs text-slate-500">Generated from QCGMS · {new Date().toLocaleDateString("en-GB")} · This report is governance evidence and not an official CQC rating.</footer>
  </main>;
}
function Detail({term,value}:{term:string;value:string}){return <div><dt className="text-slate-500">{term}</dt><dd className="font-semibold">{value}</dd></div>}
function Summary({title,value}:{title:string;value:string|null}){return <div className="rounded-xl border border-slate-200 p-4"><h2 className="font-bold">{title}</h2><p className="mt-2 whitespace-pre-wrap text-sm">{value??"Not recorded."}</p></div>}
function date(value:Date|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value):"Not set"}
function sectionScore(questions:{id:string;weighting:number}[],responses:{questionId:string;score:number|null}[]){const score=calculateAuditScore(questions.map((question)=>({score:responses.find((response)=>response.questionId===question.id)?.score??null,weighting:question.weighting})));return score===null?"Not scored":`${score}%`}
