import Link from "next/link";
import { notFound } from "next/navigation";
import { ActionArchive, ActionUpdateForm } from "@/components/action-controls";
import { requireAnyPermission } from "@/lib/auth/dal";
import { actionDaysRemaining, actionLabel, actionReadiness, actionScopeWhere, effectiveActionStatus, priorityClasses, sourcePath } from "@/lib/actions";
import { createDb } from "@/lib/db";
import { evidenceScopeWhere } from "@/lib/evidence";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

export default async function ActionPage({ params }: { params: Promise<{ id: string }> }) {
  const context = await requireAnyPermission([PERMISSIONS.GOVERNANCE_VIEW, PERMISSIONS.ASSIGNED_TASKS_EDIT, PERMISSIONS.ACTIONS_MANAGE]), { id } = await params, db = createDb();
  try {
    const [action, evidenceOptions, syncedEvidence] = await Promise.all([
      db.action.findFirst({ where: { id, ...actionScopeWhere(context) }, include: { location: { select: { name: true } }, client: { select: { firstName: true, lastName: true } }, staffMember: { select: { firstName: true, lastName: true } }, owner: { select: { name: true } }, oversightOwner: { select: { name: true } }, createdBy: { select: { name: true } }, verifiedBy: { select: { name: true } }, managementResponseBy: { select: { name: true } }, evidenceLinks: { include: { evidence: { select: { id: true, title: true } } } }, occurrences: { include: { decidedBy: { select: { name: true } } }, orderBy: { occurredAt: "desc" } }, updates: { include: { user: { select: { name: true } }, evidence: { select: { id: true, title: true } } }, orderBy: { createdAt: "desc" } } } }),
      db.evidence.findMany({ where: { ...evidenceScopeWhere(context), status: "ACTIVE" }, select: { id: true, title: true }, orderBy: { title: "asc" } }),
      db.evidence.findFirst({ where: { organisationId: context.organisation.id, relatedModule: "Action", relatedRecordId: id }, select: { id: true } }),
    ]);
    if (!action) notFound();
    const canManage = hasPermission(context.permissions, PERMISSIONS.ACTIONS_MANAGE), canUpdate = canManage || action.ownerId === context.user.id;
    const effective = effectiveActionStatus(action.status, action.dueDate), days = actionDaysRemaining(action.dueDate), sourceHref = sourcePath(action.sourceType, action.sourceRecordId, action.sourceUrl);
    const readiness = actionReadiness({ status: action.status, evidenceRequired: true, evidenceCount: action.evidenceLinks.length, progressPercent: action.progressPercent, verifiedById: action.verifiedById, verificationDate: action.verificationDate });
    return <main className="space-y-6">
      <header className="rounded-3xl bg-gradient-to-br from-emerald-950 to-emerald-800 p-7 text-white shadow-sm"><Link href="/actions" className="text-sm font-semibold text-emerald-100">← Action Tracker</Link><div className="mt-3 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-sm text-emerald-200">{action.reference} · {action.category}</p><h1 className="mt-1 text-3xl font-bold">{action.title}</h1><p className="mt-2 text-emerald-50">{actionLabel(effective)} · {actionLabel(action.lifecycleStatus)} · {action.owner.name} · due {date(action.dueDate)}</p></div>{canManage && <div className="flex gap-2"><Link href={`/actions/${id}/edit`} className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-emerald-900">Edit action</Link><ActionArchive id={id} archived={action.status === "ARCHIVED"} /></div>}</div><div className="mt-5 h-3 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-emerald-300" style={{ width: `${action.progressPercent}%` }} /></div><div className="mt-5 flex flex-wrap gap-2 text-sm"><Link href={`/actions/${id}/assurance`} className="rounded-full bg-white px-4 py-2 font-bold text-emerald-900">Assurance chronology</Link>{sourceHref && <Link href={sourceHref} className="rounded-full bg-white/10 px-4 py-2 font-semibold">Open source record</Link>}{syncedEvidence && <Link href={`/evidence/${syncedEvidence.id}`} className="rounded-full bg-white/10 px-4 py-2 font-semibold">Live evidence record</Link>}<Link href="/actions/report" className="rounded-full bg-white/10 px-4 py-2 font-semibold">Improvement report</Link></div></header>
      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><Info label="Priority" value={actionLabel(action.priority)} className={priorityClasses(action.priority)} /><Info label="Lifecycle" value={actionLabel(action.lifecycleStatus)} /><Info label="Delivery owner" value={action.owner.name} /><Info label="RM / senior oversight" value={action.oversightOwner?.name ?? "Not assigned"} /><Info label="Deadline" value={days < 0 ? `${Math.abs(days)} days overdue` : `${days} days remaining`} /><Info label="Occurrences" value={String(action.occurrences.length)} /><Info label="Closure readiness" value={actionLabel(readiness)} /></section>
      <section className="grid gap-5 lg:grid-cols-2"><Card title="Required work"><p className="whitespace-pre-wrap">{action.description}</p>{action.rootCause && <><h3 className="mt-4 font-bold">Root cause</h3><p>{action.rootCause}</p></>}</Card><Card title="Outcome and success"><h3 className="font-bold">Expected outcome</h3><p>{action.expectedOutcome ?? "Not recorded"}</p><h3 className="mt-4 font-bold">Success measure</h3><p>{action.successMeasure ?? "Not recorded"}</p></Card><Card title="Scope and recurrence"><dl className="grid grid-cols-2 gap-3"><Dt label="Location" value={action.location?.name ?? "Organisation-wide"} /><Dt label="Service user" value={action.client ? `${action.client.firstName} ${action.client.lastName}` : "Not linked"} /><Dt label="Staff member" value={action.staffMember ? `${action.staffMember.firstName} ${action.staffMember.lastName}` : "Not linked"} /><Dt label="Issue key" value={action.issueKey ?? "Not set"} /><Dt label="Medication type" value={action.medicationIssueType ? actionLabel(action.medicationIssueType) : "Not applicable"} /><Dt label="Recurrences" value={String(action.recurrenceCount)} /><Dt label="First seen" value={date(action.firstSeenAt)} /><Dt label="Last seen" value={date(action.lastSeenAt)} /><Dt label="Monitor until" value={date(action.monitoringUntil)} /><Dt label="Next review" value={date(action.nextRecurrenceReviewDate)} /></dl></Card><Card title="Management response"><p className="whitespace-pre-wrap">{action.managementResponse ?? "No management response recorded."}</p>{action.managementResponseAt && <p className="mt-3 text-xs text-slate-500">Recorded by {action.managementResponseBy?.name ?? "Unknown"} on {dateTime(action.managementResponseAt)}</p>}</Card></section>
      <Card title="Occurrence and decision history">{action.occurrences.length ? <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b"><th className="py-2">Date</th><th>Source</th><th>Decision</th><th>Reason</th></tr></thead><tbody>{action.occurrences.map((item) => <tr key={item.id} className="border-b align-top"><td className="py-3">{date(item.occurredAt)}</td><td>{item.sourceUrl ? <Link className="font-semibold text-emerald-700" href={item.sourceUrl}>{item.sourceReference ?? actionLabel(item.sourceType)}</Link> : item.sourceReference ?? actionLabel(item.sourceType)}</td><td>{actionLabel(item.decision)}{item.decidedBy && <span className="block text-xs text-slate-500">by {item.decidedBy.name}</span>}</td><td>{item.matchRationale ?? "Original finding"}{item.matchScore !== null && <span className="block text-xs text-slate-500">{item.matchScore}% match</span>}</td></tr>)}</tbody></table></div> : <p className="text-slate-500">No occurrence history has been migrated for this older action.</p>}</Card>
      <section className="grid gap-5 lg:grid-cols-2"><Card title="Verification record"><dl className="grid grid-cols-2 gap-3"><Dt label="Action completed" value={action.completedActionSummary ?? "Not recorded"} /><Dt label="Evidence reviewed" value={action.evidenceReviewedSummary ?? "Not recorded"} /><Dt label="Immediate risk controlled" value={yesNo(action.immediateRiskControlled)} /><Dt label="Record corrected" value={yesNo(action.underlyingRecordCorrected)} /><Dt label="Staff support completed" value={yesNo(action.staffSupportCompleted)} /><Dt label="Wider records checked" value={yesNo(action.widerRecordsChecked)} /><Dt label="Recurrence checked" value={yesNo(action.recurrenceChecked)} /><Dt label="Verified by" value={action.verifiedBy?.name ?? "Not verified"} /><Dt label="Verification date" value={date(action.verificationDate)} /></dl><h3 className="mt-4 font-bold">Verification rationale</h3><p>{action.verificationRationale ?? "Not recorded"}</p><h3 className="mt-4 font-bold">Closure outcome</h3><p>{action.closureNote ?? "Not closed"}</p></Card><Card title="Evidence attached"><div className="flex flex-wrap gap-2">{action.evidenceLinks.length ? action.evidenceLinks.map(({ evidence }) => <Link key={evidence.id} href={`/evidence/${evidence.id}`} className="rounded-lg bg-emerald-50 px-3 py-2 font-semibold text-emerald-800">{evidence.title}</Link>) : <p className="text-slate-500">No evidence attached. A response alone cannot close this action.</p>}</div></Card></section>
      {canUpdate && !["COMPLETED", "CANCELLED", "ARCHIVED"].includes(action.status) && <Card title="Add progress update"><ActionUpdateForm id={id} status={effective} progress={action.progressPercent} evidence={evidenceOptions.map((item) => ({ id: item.id, name: item.title }))} /></Card>}
      <Card title="Progress history">{action.updates.length ? <ol className="space-y-4">{action.updates.map((item) => <li key={item.id} className="border-l-4 border-emerald-600 pl-4"><strong>{item.user.name}</strong>{item.status && <span className="ml-2 rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{actionLabel(item.status)}</span>}<p className="mt-1 whitespace-pre-wrap">{item.note}</p>{item.evidence && <Link href={`/evidence/${item.evidence.id}`} className="font-semibold text-emerald-700">Evidence: {item.evidence.title}</Link>}<p className="text-xs text-slate-500">{dateTime(item.createdAt)}</p></li>)}</ol> : <p>No updates recorded.</p>}</Card>
      <p className="text-xs text-slate-500">Created by {action.createdBy.name} on {date(action.createdAt)}.</p>
    </main>;
  } finally { await db.$disconnect(); }
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">{title}</h2><div className="mt-3 text-sm leading-6">{children}</div></section>; }
function Info({ label, value, className = "bg-white" }: { label: string; value: string; className?: string }) { return <div className={`rounded-2xl border border-slate-200 p-5 ${className}`}><p className="text-xs font-bold uppercase tracking-wider">{label}</p><p className="mt-2 font-bold">{value}</p></div>; }
function Dt({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd>{value}</dd></div>; }
function date(value: Date | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(value) : "Not set"; }
function dateTime(value: Date) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(value); }
function yesNo(value: boolean | null) { return value === null ? "Not checked" : value ? "Yes" : "No / N/A"; }
