import { NextResponse } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { evidenceFamily } from "@/lib/evidence-taxonomy";
import { PERMISSIONS } from "@/lib/permissions";

const schema=z.object({familyKey:z.string().trim().min(1),label:z.string().trim().min(2).max(120),description:z.string().trim().max(1000).nullable().optional(),currentnessMode:z.enum(["HISTORICAL_NON_EXPIRING","EXPIRY_BASED","REVIEW_BASED","SUPERSESSION_BASED","CURRENT_SOURCE"]),ownerId:z.string().uuid()});
export async function POST(request:Request){const context=await requirePermission(PERMISSIONS.CONTROLS_MANAGE),db=createDb();try{const input=schema.parse(await request.json());if(!evidenceFamily(input.familyKey))throw new Error("Choose a recognised core Evidence family.");if(!(await db.organisationMembership.findFirst({where:{organisationId:context.organisation.id,userId:input.ownerId,status:"ACTIVE"}})))throw new Error("Choose an active owner.");const base=input.label.toUpperCase().replace(/[^A-Z0-9]+/g,"_").replace(/^_|_$/g,"").slice(0,48)||"TYPE";let stableKey=base,suffix=1;while(await db.providerEvidenceType.findUnique({where:{organisationId_stableKey:{organisationId:context.organisation.id,stableKey}}}))stableKey=`${base}_${++suffix}`;const item=await db.$transaction(async tx=>{const created=await tx.providerEvidenceType.create({data:{organisationId:context.organisation.id,stableKey,familyKey:input.familyKey,label:input.label,description:input.description||null,currentnessMode:input.currentnessMode,ownerId:input.ownerId,createdById:context.user.id}});await tx.activityLog.create({data:{organisationId:context.organisation.id,userId:context.user.id,action:"CREATE",recordType:"ProviderEvidenceType",recordId:created.id,summary:`Created Provider Evidence type: ${input.label}`,afterValue:{familyKey:input.familyKey,currentnessMode:input.currentnessMode}}});return created});return NextResponse.json({id:item.id},{status:201})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not create Provider Evidence type."},{status:400})}finally{await db.$disconnect()}}
