import Link from "next/link";
import { AlertTriangle, ArrowRight, Building2, CalendarClock, CheckCheck, CircleUserRound, Network, ShieldAlert } from "lucide-react";
import { CreateManagementDelegation, EndDelegation, RemoveSavedView, SaveManagementView } from "@/components/management-command-controls";
import { requireAnyPermission } from "@/lib/auth/dal";
import { getDefaultManagementFilters, getManagementCommandData } from "@/lib/management-data";
import { allowedManagementViews, managementFocusLabel, managementViewLabel, MANAGEMENT_FOCUSES, parseManagementFilters, responsibilityLabel } from "@/lib/management-intelligence";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

export default async function ManagementPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const context = await requireAnyPermission([PERMISSIONS.GOVERNANCE_VIEW, PERMISSIONS.ASSIGNED_TASKS_EDIT]);
  const query = await searchParams;
  const savedDefault = !query.view && !query.focus && !query.location ? await getDefaultManagementFilters(context) : null;
  const filters = parseManagementFilters(savedDefault ? { ...query, ...savedDefault } : query, { roleKey: context.role.key, allLocations: context.allLocations, locationIds: context.locations.map(({ id }) => id) });
  const data = await getManagementCommandData(context, filters);
  const views = allowedManagementViews(context.role.key, context.allLocations);
  const canDelegate = hasPermission(context.permissions, PERMISSIONS.ACTIONS_MANAGE) || hasPermission(context.permissions, PERMISSIONS.MEMBERS_MANAGE);
  return <main className="space-y-7">
    <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-emerald-950 via-teal-900 to-slate-900 p-6 text-white shadow-lg sm:p-8">
      <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-200">Phase 4 · management intelligence</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Management Command</h1><p className="mt-3 max-w-3xl leading-7 text-emerald-50">See the decisions that need attention across your authorised services, then open the live source record to act. No duplicate dashboards and no invented readiness score.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-4"><p className="text-xs uppercase tracking-wider text-emerald-200">Signed-in command role</p><p className="mt-1 font-bold">{context.role.name}</p><p className="text-sm text-emerald-100">{filters.locationId ? context.locations.find(({ id }) => id === filters.locationId)?.name : context.allLocations ? "All authorised locations" : `${context.locations.length} authorised location(s)`}</p></div></div>
    </header>

    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5" aria-label="Command filters">
      <nav className="flex flex-wrap gap-2" aria-label="Command view">{views.map((view) => <Link key={view} href={url({ view, focus: filters.focus, location: view === "LOCATION" ? filters.locationId ?? context.locations[0]?.id : undefined })} className={`rounded-full px-4 py-2 text-sm font-bold ${filters.view === view ? "bg-emerald-800 text-white" : "border border-slate-300 bg-white text-slate-700 hover:border-emerald-500"}`}>{managementViewLabel(view)}</Link>)}</nav>
      <form className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]" method="get"><input type="hidden" name="view" value={filters.view}/><label className="text-sm font-semibold">Priority focus<select name="focus" defaultValue={filters.focus} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5">{MANAGEMENT_FOCUSES.map((focus) => <option key={focus} value={focus}>{managementFocusLabel(focus)}</option>)}</select></label><label className="text-sm font-semibold">Location<select name="location" defaultValue={filters.locationId ?? ""} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">All authorised locations</option>{context.locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><button className="self-end rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white">Apply view</button></form>
      {data.savedViews.length ? <div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase tracking-wide text-slate-500">Saved</span>{data.savedViews.map((view) => <span key={view.id} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5"><Link href={url({ view: view.commandView, focus: view.focus, location: view.locationId ?? undefined })} className="text-xs font-bold text-emerald-900">{view.name}{view.isDefault ? " · default" : ""}</Link><RemoveSavedView id={view.id}/></span>)}</div> : null}
    </section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="All priorities" value={data.totals.all} icon={CheckCheck} href={url({ view: filters.view, focus: "ALL", location: filters.locationId })}/><Metric label="Critical" value={data.totals.critical} icon={ShieldAlert} href={url({ view: filters.view, focus: "CRITICAL", location: filters.locationId })} alert/><Metric label="Overdue" value={data.totals.overdue} icon={CalendarClock} href={url({ view: filters.view, focus: "OVERDUE", location: filters.locationId })} alert/><Metric label="Awaiting assurance" value={data.totals.unverified} icon={CircleUserRound} href={url({ view: filters.view, focus: "UNVERIFIED", location: filters.locationId })}/><Metric label="External" value={data.totals.external} icon={Network} href={url({ view: filters.view, focus: "EXTERNAL", location: filters.locationId })}/></section>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Decision queue</h2><p className="mt-1 text-sm text-slate-600">{managementFocusLabel(filters.focus)} · highest consequence and overdue records first.</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold">{data.queue.length} shown</span></div><div className="mt-5 grid gap-3">{data.queue.length ? data.queue.map((item) => <article key={item.key} className={`rounded-2xl border p-4 ${item.severity === "CRITICAL" || item.overdue ? "border-amber-300 bg-amber-50/50" : "border-slate-200"}`}><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(180px,0.35fr)_auto] lg:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${item.severity === "CRITICAL" ? "bg-red-100 text-red-800" : item.severity === "HIGH" ? "bg-amber-100 text-amber-900" : "bg-slate-100 text-slate-700"}`}>{item.severity}</span><span className="text-xs font-bold text-slate-500">{item.source} · {item.reference}</span></div><h3 className="mt-2 font-bold text-slate-950">{item.title}</h3><p className="mt-1 text-sm text-slate-600">{item.reason}</p></div><dl className="grid grid-cols-2 gap-2 text-xs lg:grid-cols-1"><div><dt className="text-slate-500">Location</dt><dd className="font-semibold">{item.locationName}</dd></div><div><dt className="text-slate-500">Owner / due</dt><dd className="font-semibold">{item.ownerName} · {date(item.dueAt)}</dd></div></dl><Link href={item.href} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white">Open source <ArrowRight size={16}/></Link></div></article>) : <div className="rounded-2xl border border-dashed border-emerald-300 bg-emerald-50 p-8 text-center"><CheckCheck className="mx-auto text-emerald-700"/><h3 className="mt-2 font-bold">No records match this view</h3><p className="mt-1 text-sm text-slate-600">Change the focus or location to review a different command queue.</p></div>}</div></section>

    {filters.view === "OWNER" || filters.view === "REGISTERED_MANAGER" ? <section><div className="mb-3"><h2 className="text-xl font-black">Location oversight</h2><p className="text-sm text-slate-600">Select a service to move directly into its command view.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.locationSummaries.map((location) => <Link key={location.id} href={url({ view: "LOCATION", focus: "ALL", location: location.id })} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-400 hover:shadow-md"><div className="flex items-center justify-between"><Building2 className="text-emerald-700"/><ArrowRight size={18}/></div><h3 className="mt-3 font-black">{location.name}</h3><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Mini label="Priority" value={location.total}/><Mini label="Critical" value={location.critical}/><Mini label="Overdue" value={location.overdue}/></div></Link>)}</div></section> : null}

    <section className="grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Save this decision view</h2><p className="mt-1 text-sm text-slate-600">Keep useful role, focus and location filters ready for recurring reviews.</p><div className="mt-4"><SaveManagementView filters={filters} locations={context.locations}/></div></div>{canDelegate ? <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Controlled delegation</h2><p className="mt-1 text-sm text-slate-600">Record who is covering a management responsibility, for what period and why.</p><div className="mt-4"><CreateManagementDelegation members={data.members} locations={context.locations} canUseOrganisationScope={context.allLocations}/></div></div> : null}</section>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Delegation register</h2><p className="mt-1 text-sm text-slate-600">A visible, time-bound accountability record. Delegation never changes system permissions.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{data.delegations.length ? data.delegations.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{item.title}</h3><p className="text-sm text-slate-600">{item.delegator.user.name} → {item.delegate.user.name}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${item.effectiveStatus === "ACTIVE" ? "bg-emerald-100 text-emerald-800" : item.effectiveStatus === "SCHEDULED" ? "bg-blue-100 text-blue-800" : "bg-slate-100 text-slate-700"}`}>{item.effectiveStatus}</span></div><p className="mt-2 text-sm">{item.reason}</p><p className="mt-2 text-xs text-slate-500">{item.location?.name ?? "Organisation-wide"} · {date(item.startsAt)} to {date(item.endsAt)}</p><div className="mt-2 flex flex-wrap gap-1">{item.responsibilities.map((value) => <span key={value} className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold">{responsibilityLabel(value)}</span>)}</div>{item.effectiveStatus === "ACTIVE" && (item.delegator.id === context.membershipId || hasPermission(context.permissions, PERMISSIONS.MEMBERS_MANAGE)) ? <EndDelegation id={item.id}/> : null}</article>) : <p className="rounded-xl border border-dashed p-5 text-sm text-slate-500">No delegations have been recorded.</p>}</div></section>
  </main>;
}

function Metric({ label, value, icon: Icon, href, alert = false }: { label: string; value: number; icon: typeof AlertTriangle; href: string; alert?: boolean }) { return <Link href={href} className={`rounded-2xl border p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${alert && value ? "border-amber-300 bg-amber-50" : "border-slate-200 bg-white"}`}><Icon size={21} className={alert && value ? "text-amber-800" : "text-emerald-700"}/><p className="mt-3 text-sm text-slate-600">{label}</p><p className="text-3xl font-black">{value}</p></Link>; }
function Mini({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-slate-50 p-2"><p className="text-lg font-black">{value}</p><p className="text-[11px] text-slate-500">{label}</p></div>; }
function date(value: Date | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(value) : "No date"; }
function url(input: { view: string; focus: string; location?: string }) { const params = new URLSearchParams({ view: input.view, focus: input.focus }); if (input.location) params.set("location", input.location); return `/management?${params}`; }
