import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { CreateManagementDelegation, EndDelegation } from "@/components/management-command-controls";
import { AttentionStrip, GovernanceWorklist, type GovernanceWorklistItem } from "@/components/governance-experience";
import { requireAnyPermission } from "@/lib/auth/dal";
import { getManagementCommandData } from "@/lib/management-data";
import { allowedManagementViews, managementFocusLabel, managementViewLabel, MANAGEMENT_FOCUSES, parseManagementFilters, responsibilityLabel, type ManagementFilters } from "@/lib/management-intelligence";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

type CommandData = Awaited<ReturnType<typeof getManagementCommandData>>;

export default async function ManagementPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const context = await requireAnyPermission([PERMISSIONS.GOVERNANCE_VIEW]);
  const query = await searchParams;
  const filters = parseManagementFilters(query, { roleKey: context.role.key, allLocations: context.allLocations, locationIds: context.locations.map(({ id }) => id) });
  const data = await getManagementCommandData(context, filters);
  const views = allowedManagementViews(context.role.key, context.allLocations);
  const canDelegate = hasPermission(context.permissions, PERMISSIONS.ACTIONS_MANAGE) || hasPermission(context.permissions, PERMISSIONS.MEMBERS_MANAGE);
  const locationName = filters.locationId ? context.locations.find(({ id }) => id === filters.locationId)?.name ?? "Selected service" : null;
  const purpose = filters.view === "OWNER"
    ? "Organisation-wide assurance: see whether governance work has an owner, target, oversight lead and evidence route."
    : filters.view === "LOCATION"
      ? `Location accountability for ${locationName}: see who owns each governance action and what needs intervention.`
      : "Registered Manager control: assign governance actions, delegate defined responsibilities and track team delivery without running care visits or rotas.";

  return <main className="space-y-7">
    <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-emerald-950 via-teal-900 to-slate-900 p-6 text-white shadow-lg sm:p-8">
      <div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-4xl"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-200">Governance accountability</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Management Oversight</h1><p className="mt-3 leading-7 text-emerald-50">{purpose}</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-4"><p className="text-xs uppercase tracking-wider text-emerald-200">Signed-in role</p><p className="mt-1 font-bold">{context.role.name}</p><p className="text-sm text-emerald-100">{locationName ?? (context.allLocations ? "All authorised services" : `${context.locations.length} authorised location(s)`)}</p></div></div>
    </header>

    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm" aria-label="Management command views">
      <nav className="flex flex-wrap gap-2">{views.map((view) => <Link key={view} href={commandUrl({ view, focus: "ALL", location: view === "LOCATION" ? filters.locationId ?? context.locations[0]?.id : undefined })} className={`rounded-full px-4 py-2.5 text-sm font-bold ${filters.view === view ? "bg-emerald-800 text-white" : "border border-slate-300 text-slate-700 hover:border-emerald-500"}`}>{managementViewLabel(view)}</Link>)}</nav>
      <div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-600"><strong className="text-slate-900">Each view now has a different job:</strong> Owner is assurance, Registered Manager is assignment and delegation, Location is local accountability. Personal delivery remains in <Link href="/my-work" className="font-bold text-emerald-800">My Work</Link>.</div>
    </section>

    {filters.view === "OWNER" ? <OwnerOverview data={data} filters={filters}/> : null}
    {filters.view === "REGISTERED_MANAGER" ? <RegisteredManagerCommand data={data} context={context} canDelegate={canDelegate}/> : null}
    {filters.view === "LOCATION" ? <LocationCommand data={data} filters={filters} locations={context.locations} locationName={locationName ?? "Selected service"}/> : null}
  </main>;
}

function OwnerOverview({ data, filters }: { data: CommandData; filters: ManagementFilters }) {
  const exceptions = data.queue.filter((item) => item.overdue || item.unverified || item.severity !== "MEDIUM" || item.source === "EXTERNAL");
  const mostAffected = [...data.locationSummaries].sort((a,b)=>b.critical-a.critical||b.overdue-a.overdue||b.total-a.total||a.name.localeCompare(b.name))[0];
  return <>
    <AttentionStrip title={data.totals.critical?`${data.totals.critical} Critical matter${data.totals.critical===1?"":"s"} require senior attention`:data.totals.overdue?`${data.totals.overdue} overdue governance matter${data.totals.overdue===1?"":"s"} require intervention`:"No Critical or overdue exception is visible in this authorised scope"} detail={mostAffected?`${mostAffected.name} currently has the greatest exception pressure: ${mostAffected.critical} Critical, ${mostAffected.overdue} overdue and ${mostAffected.unverified} awaiting assurance.`:"No active service-location exception is available in this view."} tone={data.totals.critical?"critical":data.totals.overdue?"attention":"ready"} items={[data.totals.external?`${data.totals.external} external dependency or response requires oversight.`:"",data.assignmentTotals.missingOversight?`${data.assignmentTotals.missingOversight} Action${data.assignmentTotals.missingOversight===1?" has":"s have"} no RM or senior oversight owner.`:""].filter(Boolean)}/>
    <LocationComparison items={data.locationSummaries}/>
    <FocusNav filters={filters}/>
    <ExceptionQueue items={exceptions} title="Owner assurance exceptions" detail="Only material exceptions are shown here; routine delivery remains with the Registered Manager and assigned owners."/>
    <DelegationRegister items={data.delegations} title="Delegation assurance register" readOnly/>
  </>;
}

function RegisteredManagerCommand({ data, context, canDelegate }: { data: CommandData; context: Awaited<ReturnType<typeof requireAnyPermission>>; canDelegate: boolean }) {
  return <>
    <OversightPulse items={[{label:"Open Actions",value:data.assignmentTotals.all},{label:"Assigned to team",value:data.assignmentTotals.delegatedToTeam},{label:"My own",value:data.assignmentTotals.personallyOwned},{label:"I oversee",value:data.assignmentTotals.overseenByMe},{label:"Overdue",value:data.assignmentTotals.overdue,alert:true},{label:"Missing oversight",value:data.assignmentTotals.missingOversight,alert:true}]}/>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr] xl:items-start"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">Assignment control</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">Create a specific governance action with a delivery owner, RM or senior oversight lead, measurable target and evidence requirement.</p></div><div className="flex flex-wrap gap-2"><Link href="/actions/new" className="rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white">Assign governance action</Link><Link href="/my-work" className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-bold">Open My Work</Link></div></div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-950"><strong>Product boundary:</strong> use this for audit findings, review actions, risks, incidents, complaints and assurance follow-up—not visits, rotas, medication rounds or routine care tasks.</p></div>{canDelegate ? <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Delegate responsibility cover</h2><p className="mt-1 text-sm leading-6 text-slate-600">Record time-limited management cover. Then create the specific actions and targets that person must deliver.</p><div className="mt-4"><CreateManagementDelegation members={data.members} locations={context.locations} canUseOrganisationScope={context.allLocations}/></div></div> : null}</section>
    <TeamAccountability items={data.teamSummaries}/>
    <AssignmentBoard items={data.assignments} title="Team governance assignments" detail="Every open action in the Registered Manager’s authorised scope, showing delivery ownership and independent oversight."/>
    <DelegationRegister items={data.delegations} title="Active and scheduled management cover"/>
  </>;
}

function LocationCommand({ data, filters, locations, locationName }: { data: CommandData; filters: ManagementFilters; locations: Array<{ id: string; name: string }>; locationName: string }) {
  return <>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form method="get" className="grid gap-3 sm:grid-cols-[1fr_auto]"><input type="hidden" name="view" value="LOCATION"/><input type="hidden" name="focus" value={filters.focus}/><label className="text-sm font-bold">Service location<select name="location" defaultValue={filters.locationId} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5">{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><button className="self-end rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white">Open location</button></form></section>
    <OversightPulse items={[{label:"Open Actions",value:data.assignmentTotals.all},{label:"Assigned owners",value:data.teamSummaries.length},{label:"Overdue",value:data.assignmentTotals.overdue,alert:true},{label:"Due in 7 days",value:data.assignmentTotals.dueSoon},{label:"Missing oversight",value:data.assignmentTotals.missingOversight,alert:true}]}/>
    <TeamAccountability items={data.teamSummaries} title={`${locationName} accountability`}/>
    <AssignmentBoard items={data.assignments} title={`${locationName} assigned actions`} detail="Governance actions allocated to people at this service, with target, progress and RM/senior oversight."/>
    <DelegationRegister items={data.delegations} title={`${locationName} delegated responsibility cover`} readOnly/>
    <FocusNav filters={filters}/>
    <ExceptionQueue items={data.queue} title={`${locationName} governance exceptions`} detail="High-risk, overdue, unverified and external matters that may require escalation beyond the assigned action."/>
  </>;
}

function AssignmentBoard({ items, title, detail }: { items: CommandData["assignments"]; title: string; detail: string }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Heading title={title} detail={detail}/><div className="mt-5 space-y-3">{items.length ? items.map((item) => <article key={item.id} className={`rounded-2xl border p-4 ${item.overdue ? "border-red-300 bg-red-50/50" : item.dueSoon ? "border-amber-300 bg-amber-50/40" : "border-slate-200"}`}><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(230px,.45fr)_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-900 px-2.5 py-1 text-[11px] font-black text-white">{label(item.sourceType)}</span><span className="text-xs font-bold text-slate-500">{item.reference} · {item.category}</span></div><h3 className="mt-2 font-black">{item.title}</h3><p className="mt-1 text-xs text-slate-500">{item.location?.name ?? "Organisation-wide"}{item.clientName ? ` · Person: ${item.clientName}` : ""}</p></div><dl className="grid grid-cols-2 gap-3 text-xs"><Meta label="Delivery owner" value={item.owner.name}/><Meta label="RM / senior oversight" value={item.oversightOwner?.name ?? "Not assigned"}/><Meta label="Target" value={date(item.dueDate)}/><Meta label="Progress" value={`${item.progressPercent}% · ${label(item.lifecycleStatus)}`}/></dl><Link href={`/actions/${item.id}`} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white">Open action <ArrowRight size={16}/></Link></div></article>) : <Empty text="No open governance actions are assigned in this scope."/>}</div></section>; }

function TeamAccountability({ items, title = "Team accountability" }: { items: CommandData["teamSummaries"]; title?: string }) { return <section><Heading title={title} detail="Workload here means open governance actions, not care visits or shift tasks."/><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.length ? items.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-emerald-100 font-black text-emerald-800">{item.name.slice(0,1).toUpperCase()}</span><div><h3 className="font-black">{item.name}</h3><p className="text-xs text-slate-500">{item.total} open governance action{item.total === 1 ? "" : "s"}</p></div></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Mini label="Overdue" value={item.overdue}/><Mini label="High" value={item.critical}/><Mini label="Assure" value={item.awaitingAssurance}/></div></article>) : <Empty text="No team assignments are recorded in this scope."/>}</div></section>; }

function ExceptionQueue({ items, title, detail }: { items: CommandData["queue"]; title: string; detail: string }) { const worklist:GovernanceWorklistItem[]=items.map(item=>({id:item.key,href:item.href,reference:item.reference,title:item.title,location:item.locationName,owner:item.ownerName,stage:label(item.source),attention:item.reason,supporting:[item.dueAt?`Target ${date(item.dueAt)}`:"No target date",label(item.state)],tone:item.severity==="CRITICAL"?"critical":item.overdue?"overdue":item.unverified?"assurance":"attention",ctaLabel:"Review source"}));return <section><Heading title={title} detail={detail}/><div className="mt-4">{worklist.length?<GovernanceWorklist items={worklist}/>:<Empty text="No governance exceptions match this view."/>}</div></section>; }

function DelegationRegister({ items, title, readOnly = false }: { items: CommandData["delegations"]; title: string; readOnly?: boolean }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Heading title={title} detail="Time-bound responsibility cover remains visible and never transfers the provider’s or Registered Manager’s legal duties."/><div className="mt-4 grid gap-3 md:grid-cols-2">{items.length ? items.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{item.title}</h3><p className="text-sm text-slate-600">{item.delegator.user.name} → {item.delegate.user.name}</p></div><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-black text-emerald-800">{item.effectiveStatus}</span></div><p className="mt-2 text-sm">{item.reason}</p><p className="mt-2 text-xs text-slate-500">{item.location?.name ?? "Organisation-wide"} · {date(item.startsAt)} to {date(item.endsAt)}</p><div className="mt-2 flex flex-wrap gap-1">{item.responsibilities.map((value) => <span key={value} className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold">{responsibilityLabel(value)}</span>)}</div>{!readOnly && item.canEnd && item.effectiveStatus === "ACTIVE" ? <EndDelegation id={item.id}/> : null}</article>) : <Empty text="No management delegation records are active in this scope."/>}</div></section>; }

function FocusNav({ filters }: { filters: ManagementFilters }) { return <nav className="flex flex-wrap gap-2" aria-label="Exception focus">{MANAGEMENT_FOCUSES.map((focus) => <Link key={focus} href={commandUrl({ view: filters.view, focus, location: filters.locationId })} className={`rounded-full px-3 py-2 text-xs font-bold ${filters.focus === focus ? "bg-slate-900 text-white" : "border border-slate-300 bg-white text-slate-700"}`}>{managementFocusLabel(focus)}</Link>)}</nav>; }
function OversightPulse({items}:{items:Array<{label:string;value:number;alert?:boolean}>}){return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm" aria-label="Oversight summary"><dl className="grid sm:grid-cols-3 xl:grid-cols-6">{items.map(item=><div key={item.label} className={`border-b border-slate-200 p-4 last:border-b-0 sm:border-r xl:border-b-0 ${item.alert&&item.value?"bg-amber-50 text-amber-950":""}`}><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{item.label}</dt><dd className="mt-1 text-2xl font-black">{item.value}</dd></div>)}</dl></section>}
function LocationComparison({items}:{items:CommandData["locationSummaries"]}){return <section><Heading title="Location comparison" detail="Compare actual exceptions. A Critical matter always takes priority over reassuring totals."/><div className="mt-4 hidden overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Location</th><th className="px-4 py-3">Critical</th><th className="px-4 py-3">Overdue</th><th className="px-4 py-3">Awaiting assurance</th><th className="px-4 py-3">External</th><th className="px-4 py-3">All exceptions</th><th className="px-4 py-3"><span className="sr-only">Open</span></th></tr></thead><tbody className="divide-y divide-slate-200">{items.map(item=><tr key={item.id} className={item.critical?"bg-red-50/70":item.overdue?"bg-amber-50/60":""}><th className="px-4 py-3 font-black">{item.name}</th><td className="px-4 py-3 font-bold">{item.critical}</td><td className="px-4 py-3">{item.overdue}</td><td className="px-4 py-3">{item.unverified}</td><td className="px-4 py-3">{item.external}</td><td className="px-4 py-3">{item.total}</td><td className="px-4 py-3"><Link href={commandUrl({view:"LOCATION",focus:"ALL",location:item.id})} className="font-bold text-emerald-800">Review <ArrowRight aria-hidden="true" className="inline" size={14}/></Link></td></tr>)}</tbody></table></div><div className="mt-4 grid gap-3 md:hidden">{items.map(item=><Link key={item.id} href={commandUrl({view:"LOCATION",focus:"ALL",location:item.id})} className={`rounded-2xl border p-4 ${item.critical?"border-red-300 bg-red-50":item.overdue?"border-amber-300 bg-amber-50":"border-slate-200 bg-white"}`}><div className="flex items-center justify-between gap-3"><strong>{item.name}</strong><ArrowRight size={16}/></div><p className="mt-2 text-sm">{item.critical} Critical · {item.overdue} overdue · {item.unverified} awaiting assurance</p><p className="mt-1 text-xs text-slate-500">{item.total} total exceptions · {item.external} external</p></Link>)}</div></section>}
function Heading({ title, detail }: { title: string; detail: string }) { return <div><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{detail}</p></div>; }
function Meta({ label: term, value }: { label: string; value: string }) { return <div><dt className="text-slate-500">{term}</dt><dd className="font-bold text-slate-900">{value}</dd></div>; }
function Mini({ label: text, value }: { label: string; value: number }) { return <div className="rounded-lg bg-slate-50 p-2"><p className="text-lg font-black">{value}</p><p className="text-[11px] text-slate-500">{text}</p></div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm text-slate-500">{text}</p>; }
function date(value: Date | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(value) : "Target not set"; }
function label(value: string) { return value.replaceAll("_", " ").toLowerCase().replace(/^\w/, (letter) => letter.toUpperCase()); }
function commandUrl(input: { view: string; focus: string; location?: string }) { const params = new URLSearchParams({ view: input.view, focus: input.focus }); if (input.location) params.set("location", input.location); return `/management?${params}`; }
