import { NextResponse } from "next/server";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { PERMISSIONS } from "@/lib/permissions";
import { parseOptionalDate } from "@/lib/policies";
import { STAFF_LEAVE_STATUSES, STAFF_LEAVE_TYPES, workingDaysInclusive, workforceScopeWhere } from "@/lib/workforce";

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const context = await requirePermission(PERMISSIONS.WORKFORCE_MANAGE); const { id } = await params; const form = await request.formData(); const type = String(form.get("type") ?? ""); const status = String(form.get("status") ?? "PENDING"); const startDate = parseOptionalDate(form.get("startDate")); const endDate = parseOptionalDate(form.get("endDate"));
  if (!STAFF_LEAVE_TYPES.includes(type as never) || !STAFF_LEAVE_STATUSES.includes(status as never) || !startDate || !endDate || endDate < startDate) return NextResponse.json({ error: "Choose a valid leave type and date range." }, { status: 400 });
  const entered = Number(String(form.get("requestedDays") ?? "")); const requestedDays = Number.isFinite(entered) && entered > 0 ? entered : workingDaysInclusive(startDate, endDate); if (requestedDays <= 0 || requestedDays > 366) return NextResponse.json({ error: "Enter the number of working days requested." }, { status: 400 });
  const db = createDb(); try { const staff = await db.staffMember.findFirst({ where: { id, ...workforceScopeWhere(context) }, select: { id: true, employeeReference: true, locationId: true } }); if (!staff) return NextResponse.json({ error: "Staff record not found." }, { status: 404 }); const created = await db.$transaction(async (tx) => { const leave = await tx.staffLeaveRequest.create({ data: { organisationId: context.organisation.id, staffMemberId: id, type: type as never, status: status as never, startDate, endDate, requestedDays, reason: optional(form.get("reason"), 500), managerNote: optional(form.get("managerNote"), 1000), fitNoteReceived: form.get("fitNoteReceived") === "on", returnToWorkCompleted: form.get("returnToWorkCompleted") === "on", requestedById: context.user.id, decidedById: status === "PENDING" ? null : context.user.id, decidedAt: status === "PENDING" ? null : new Date() } }); await tx.activityLog.create({ data: { organisationId: context.organisation.id, locationId: staff.locationId, userId: context.user.id, action: "CREATE", recordType: "StaffLeaveRequest", recordId: leave.id, summary: `Recorded ${type.toLowerCase().replaceAll("_", " ")} for ${staff.employeeReference}`, afterValue: { staffMemberId: id, type, status, startDate, endDate, requestedDays } } }); return leave; }); return NextResponse.json({ id: created.id }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not save the leave record." }, { status: 400 }); } finally { await db.$disconnect(); }
}
function optional(value: FormDataEntryValue | null, limit: number) { return String(value ?? "").trim().slice(0, limit) || null; }
