import Link from "next/link";
import { AlertTriangle, CheckCircle2, ClipboardCheck, Network, ShieldCheck } from "lucide-react";
import { ImprovementPlanControl, ImprovementPlanUpdate } from "@/components/assurance-workflow-controls";
import { requirePermission } from "@/lib/auth/dal";
import { actionLabel, actionScopeWhere } from "@/lib/actions";
import { assuranceStage, externalDependencyState } from "@/lib/assurance-improvement";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

export default async function ImprovementPage(){const context=await requirePermission(PERMISSIONS.GOVERNANCE_VIEW),db=createDb();try{const [actions,plans,members]=await Promise.all([
  db.action.findMany({where:{...actionScopeWhere(context),archivedAt:null},include:{finding:true,rootCauseReview:true,verifications:{where:{verificationType:"CLOSURE"},take:1},effectivenessReviews:{orderBy:{reviewDate:"desc"},take:1},externalDependencies:true,recurrenceCases:{where:{status:{not:"CLOSED"}}},owner:{select:{name:true}}},orderBy:[{priority:"desc"},{dueDate:"asc"}],take:150}),
  db.improvementPlan.findMany({where:{organisationId:context.organisation.id,archivedAt:null,...(context.allLocations?{}:{OR:[{locationId:null},{locationId:{in:context.locations.map(({id})=>id)}}]})},include:{actions:{include:{action:{select:{id:true,reference:true,title:true,status:true}}}}},orderBy:{targetDate:"asc"},take:50}),
  db.organisationMembership.findMany({where:{organisationId:context.organisation.id,status:"ACTIVE"},select:{user:{select:{id:true,name:true}}},orderBy:{user:{name:"asc"}}}),
]);const rows=actions.map(action=>{const verification=action.verifications[0],effectiveness=action.effectivenessReviews[0];return{action,stage:assuranceStage({hasRootCause:Boolean(action.rootCauseReview&&["COMPLETED","APPROVED"].includes(action.rootCauseReview.status)),verificationOutcome:verification?.outcome??null,effectivenessOutcome:effectiveness?.outcome??null,recurrenceCount:action.recurrenceCount}),overdueExternal:action.externalDependencies.filter(item=>externalDependencyState(item)==="OVERDUE").length}});const canManage=hasPermission(context.permissions,PERMISSIONS.ACTIONS_MANAGE),awaitingCause=rows.filter(item=>item.stage==="CAUSE_REVIEW").length,awaitingVerification=rows.filter(item=>item.stage==="ACTION_AND_EVIDENCE").length,monitoring=rows.filter(item=>item.stage==="MONITORING").length,reopened=rows.filter(item=>item.stage==="REOPENED").length,sustained=rows.filter(item=>item.stage==="SUSTAINED").length,externalOverdue=rows.reduce((sum,item)=>sum+item.overdueExternal,0);return <main className="space-y-7">
  <header className="rounded-3xl bg-gradient-to-br from-emerald-950 via-teal-900 to-slate-900 p-7 text-white"><p className="text-sm font-bold uppercase tracking-widest text-emerald-200">Phase 3 · assurance and improvement</p><h1 className="mt-1 text-3xl font-bold">Improvement Assurance Workbench</h1><p className="mt-2 max-w-3xl text-emerald-50">Follow every issue from source finding through cause, action, evidence, independent verification, effectiveness and sustained improvement.</p></header>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Stat label="Cause review" value={awaitingCause} icon={Network}/><Stat label="Action & evidence" value={awaitingVerification} icon={ClipboardCheck}/><Stat label="Monitoring" value={monitoring} icon={ShieldCheck}/><Stat label="Reopened" value={reopened} icon={AlertTriangle} warn/><Stat label="External overdue" value={externalOverdue} icon={AlertTriangle} warn/><Stat label="Sustained" value={sustained} icon={CheckCircle2}/></section>
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">Assurance queue</h2><p className="mt-1 text-sm text-slate-600">Open the chronology to complete the next controlled decision.</p></div><Link href="/actions" className="text-sm font-bold text-emerald-800">Action Tracker →</Link></div><div className="mt-4 overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead><tr className="border-b bg-slate-50"><th className="p-3">Finding / action</th><th className="p-3">Owner</th><th className="p-3">Priority</th><th className="p-3">Stage</th><th className="p-3">External</th><th className="p-3">Next step</th></tr></thead><tbody>{rows.map(({action,stage,overdueExternal})=><tr key={action.id} className="border-b"><td className="p-3"><strong>{action.finding?.reference??`FND-${action.reference}`}</strong><p className="text-slate-600">{action.title}</p></td><td className="p-3">{action.owner.name}</td><td className="p-3 font-bold">{action.priority}</td><td className="p-3"><Badge value={stage}/></td><td className="p-3">{overdueExternal?<span className="font-bold text-red-700">{overdueExternal} overdue</span>:"Clear"}</td><td className="p-3"><Link href={`/actions/${action.id}/assurance`} className="font-bold text-emerald-800">Open chronology →</Link></td></tr>)}</tbody></table></div></section>
  <section className="grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Improvement plans</h2><p className="mt-1 text-sm text-slate-600">Group related actions under one measurable objective without replacing their individual owners and evidence.</p><div className="mt-4 space-y-3">{plans.length?plans.map(plan=><article key={plan.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><strong>{plan.reference} · {plan.title}</strong><Badge value={plan.status}/></div><p className="mt-2 text-sm">{plan.objective}</p><p className="mt-2 text-xs text-slate-500">{plan.actions.length} linked action(s) · target {date(plan.targetDate)}</p>{canManage?<ImprovementPlanUpdate id={plan.id} status={plan.status} progressSummary={plan.progressSummary??""} outcome={plan.outcome??""}/>:null}</article>):<p className="rounded-xl border border-dashed p-5 text-sm text-slate-500">No improvement plans yet.</p>}</div></div>{canManage?<div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Create improvement plan</h2><p className="mt-1 text-sm text-slate-600">Use a plan for a systemic theme involving several linked actions.</p><div className="mt-4"><ImprovementPlanControl members={members.map(({user})=>user)} locations={context.locations.map(({id,name})=>({id,name}))} actions={actions.filter(item=>!["CANCELLED","ARCHIVED"].includes(item.status)).map(item=>({id:item.id,name:`${item.reference} · ${item.title}`}))}/></div></div>:null}</section>
</main>}finally{await db.$disconnect()}}
function Stat({label,value,icon:Icon,warn=false}:{label:string;value:number;icon:typeof ShieldCheck;warn?:boolean}){return <div className={`rounded-2xl border p-5 ${warn&&value?"border-red-200 bg-red-50":"border-slate-200 bg-white"}`}><Icon size={20} className={warn&&value?"text-red-700":"text-emerald-700"}/><p className="mt-2 text-sm text-slate-600">{label}</p><p className="text-3xl font-black">{value}</p></div>}
function Badge({value}:{value:string}){return <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{actionLabel(value)}</span>}
function date(value:Date){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value)}
