import Link from "next/link";
import { AlertTriangle, Building2, CheckCircle2, Landmark, Scale } from "lucide-react";
import { DecisionRegisterForm, DecisionUpdate, ExternalPartyForm, ObligationForm, ObligationUpdate } from "@/components/governance-control-forms";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { dependencyIsOverdue, governanceLabel, obligationIsOverdue } from "@/lib/governance-control";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

export default async function GovernanceControlPage() {
  const context = await requirePermission(PERMISSIONS.GOVERNANCE_VIEW), db = createDb(), locationIds = context.locations.map((item) => item.id), scope = context.allLocations ? {} : { OR: [{ locationId: null }, { locationId: { in: locationIds } }] }, now = new Date();
  try {
    const [decisions, obligations, dependencies, parties, members, evidence, agendaItems, kpiReturns] = await Promise.all([
      db.governanceDecision.findMany({ where: { organisationId: context.organisation.id, ...scope }, include: { owner: { select: { name: true } }, meeting: { select: { reference: true, title: true } }, linkedAction: { select: { id: true, reference: true, title: true } }, externalParty: { select: { name: true } }, implementationEvidence: { select: { id: true, title: true } }, implementedBy: { select: { name: true } }, reviewedBy: { select: { name: true } } }, orderBy: [{ reviewDueAt: "asc" }, { createdAt: "desc" }], take: 100 }),
      db.governanceObligation.findMany({ where: { organisationId: context.organisation.id, ...scope }, include: { owner: { select: { name: true } }, externalParty: { select: { name: true, email: true, phone: true } }, evidence: { select: { id: true, title: true } }, updates: { include: { actor: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 3 } }, orderBy: [{ dueAt: "asc" }, { createdAt: "desc" }], take: 100 }),
      db.externalDependency.findMany({ where: { organisationId: context.organisation.id, ...scope, status: { notIn: ["RESOLVED", "CANCELLED"] } }, include: { action: { select: { id: true, reference: true, title: true } }, owner: { select: { name: true } }, externalParty: { select: { name: true } } }, orderBy: { dueDate: "asc" }, take: 100 }),
      db.externalParty.findMany({ where: { organisationId: context.organisation.id, archivedAt: null, ...scope }, orderBy: { name: "asc" } }),
      db.organisationMembership.findMany({ where: { organisationId: context.organisation.id, status: "ACTIVE" }, select: { user: { select: { id: true, name: true } } }, orderBy: { user: { name: "asc" } } }),
      db.evidence.findMany({ where: { organisationId: context.organisation.id, status: "ACTIVE", archivedAt: null, ...scope }, select: { id: true, title: true }, orderBy: { title: "asc" }, take: 250 }),
      db.meetingAgendaItem.findMany({ where: { decision: { not: null }, controlledDecision: null, meeting: { organisationId: context.organisation.id, status: "APPROVED", ...scope } }, include: { meeting: { select: { reference: true, title: true } } }, orderBy: { meeting: { meetingDate: "desc" } }, take: 100 }),
      db.kpiReturn.findMany({ where: { organisationId: context.organisation.id, ...(context.allLocations ? {} : { locationId: { in: locationIds } }), status: { in: ["DRAFT", "READY_FOR_REVIEW"] } }, select: { id: true }, take: 100 }),
    ]);
    const canManage = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_EDIT), options = members.map(({ user }) => user), evidenceOptions = evidence.map((item) => ({ id: item.id, name: item.title })), partyOptions = parties.map((item) => ({ id: item.id, name: item.name })), overdueObligations = obligations.filter((item) => obligationIsOverdue(item, now)).length, decisionsDue = decisions.filter((item) => !["REVIEWED", "SUPERSEDED", "WITHDRAWN"].includes(item.status) && (!item.reviewDueAt || item.reviewDueAt <= new Date(now.getTime() + 30 * 86_400_000))).length, externalOverdue = dependencies.filter((item) => dependencyIsOverdue(item, now)).length;
    return <main className="space-y-7">
      <header className="rounded-3xl bg-gradient-to-br from-slate-950 via-teal-950 to-emerald-900 p-7 text-white shadow-lg"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-200">Phase 7 · governance control</p><h1 className="mt-2 text-3xl font-black">Decisions, obligations and external assurance</h1><p className="mt-2 max-w-3xl text-emerald-50">One accountable view of what governance decided, what must be returned externally, what is delayed and what evidence proves closure.</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/calendar" className="rounded-xl bg-white/10 px-3 py-2 text-sm font-bold">Unified calendar</Link><Link href="/meetings" className="rounded-xl bg-white/10 px-3 py-2 text-sm font-bold">Governance meetings</Link><Link href="/actions" className="rounded-xl bg-white/10 px-3 py-2 text-sm font-bold">Action tracker</Link></div></header>

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat icon={AlertTriangle} label="Overdue obligations" value={overdueObligations} warn/><Stat icon={Scale} label="Decisions needing control" value={decisionsDue}/><Stat icon={Building2} label="External delays overdue" value={externalOverdue} warn/><Stat icon={Landmark} label="Returns needing work" value={kpiReturns.length}/><Stat icon={CheckCircle2} label="Reviewed decisions" value={decisions.filter((item)=>item.status==="REVIEWED").length}/></section>

      {canManage ? <section className="grid gap-5 xl:grid-cols-2"><Panel title="Register an approved decision" intro="The wording comes from approved meeting minutes and cannot be replaced with an invented summary."><DecisionRegisterForm agendaItems={agendaItems.map((item)=>({ id:item.id, name:`${item.meeting.reference} · ${item.title}: ${item.decision}` }))} members={options} parties={partyOptions}/></Panel><Panel title="Open an external obligation" intro="Track commissioner, regulator, contract and information-return commitments through acceptance and closure."><ObligationForm parties={partyOptions} members={options} locations={context.locations}/></Panel></section> : null}

      <section className="space-y-3"><SectionHeading title="Controlled decisions" count={decisions.length} link="/meetings" linkLabel="Open source meetings"/><div className="grid gap-4 lg:grid-cols-2">{decisions.length ? decisions.map((item)=><article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-teal-700">{item.meeting.reference} · {governanceLabel(item.impact)} impact</p><h3 className="mt-1 text-lg font-bold">{item.decisionText}</h3></div><Badge value={item.status}/></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Meta label="Accountable owner" value={item.owner.name}/><Meta label="Review due" value={date(item.reviewDueAt)}/><Meta label="Source" value={item.meeting.title}/><Meta label="External party" value={item.externalParty?.name ?? "Not applicable"}/></dl>{item.linkedAction?<Link href={`/actions/${item.linkedAction.id}/assurance`} className="mt-3 inline-block text-sm font-bold text-emerald-800">{item.linkedAction.reference} · open linked action →</Link>:null}{item.implementationEvidence?<p className="mt-3 rounded-lg bg-emerald-50 p-2 text-xs"><strong>Implementation evidence:</strong> {item.implementationEvidence.title}</p>:null}{item.reviewOutcome?<p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm"><strong>Independent outcome:</strong> {item.reviewOutcome}</p>:null}{canManage && ["RECORDED","ACTION_REQUIRED","IMPLEMENTED"].includes(item.status)?<DecisionUpdate id={item.id} status={item.status} evidence={evidenceOptions}/>:null}</article>) : <Empty text="No controlled decisions have been registered from approved minutes yet."/>}</div></section>

      <section className="space-y-3"><SectionHeading title="Commissioner and external obligations" count={obligations.length}/><div className="grid gap-4 xl:grid-cols-2">{obligations.length ? obligations.map((item)=>{const overdue=obligationIsOverdue(item,now);return <article key={item.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${overdue?"border-red-300":""}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-teal-700">{item.reference} · {governanceLabel(item.obligationType)}</p><h3 className="mt-1 text-lg font-bold">{item.title}</h3></div><Badge value={overdue?"OVERDUE":item.status} warn={overdue}/></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Meta label="External party" value={item.externalParty.name}/><Meta label="Accountable owner" value={item.owner.name}/><Meta label="Submission due" value={date(item.dueAt)}/><Meta label="Chases" value={String(item.chaseCount)}/></dl><div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm"><strong>Interim control:</strong> {item.interimControl}<br/><strong>Escalation:</strong> {item.escalationRoute}</div>{item.sourceHref?<Link href={item.sourceHref} className="mt-3 inline-block text-sm font-bold text-emerald-800">Open canonical source →</Link>:null}{item.updates.length?<ol className="mt-4 space-y-2 border-l-2 border-slate-200 pl-4">{item.updates.map((update)=><li key={update.id} className="text-xs"><strong>{governanceLabel(update.updateType)}</strong> · {update.actor.name} · {dateTime(update.createdAt)}<p className="text-slate-600">{update.note}</p></li>)}</ol>:null}{canManage&&!['CLOSED','CANCELLED'].includes(item.status)?<ObligationUpdate id={item.id} status={item.status} evidence={evidenceOptions}/>:null}</article>}) : <Empty text="No commissioner or external obligations are open."/>}</div></section>

      <section className="space-y-3"><SectionHeading title="External action delays" count={dependencies.length} link="/improvement" linkLabel="Open assurance workbench"/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{dependencies.length?dependencies.map((item)=>{const overdue=dependencyIsOverdue(item,now);return <article key={item.id} className={`rounded-2xl border bg-white p-4 ${overdue?"border-red-300":""}`}><div className="flex justify-between gap-2"><strong>{item.externalParty?.name??item.partyName}</strong><Badge value={overdue?"OVERDUE":item.status} warn={overdue}/></div><p className="mt-2 text-sm text-slate-700">{item.request}</p><p className="mt-3 text-xs text-slate-500">Owner {item.owner.name} · due {date(item.dueDate)} · {item.chaseCount} chase(s)</p><Link href={`/actions/${item.action.id}/assurance`} className="mt-3 inline-block text-sm font-bold text-emerald-800">{item.action.reference} · {item.action.title} →</Link></article>}):<Empty text="No unresolved external action dependencies."/>}</div></section>

      {canManage?<section className="grid gap-5 xl:grid-cols-[1fr_1.4fr]"><Panel title="Controlled external parties" intro="Create each commissioner, authority, regulator or partner once, with an email or phone contact."><ExternalPartyForm locations={context.locations}/></Panel><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Directory</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{parties.map((party)=><div key={party.id} className="rounded-xl border p-3"><strong>{party.name}</strong><p className="text-xs text-slate-500">{governanceLabel(party.partyType)}</p><p className="mt-2 text-sm">{party.email??"No email"}<br/>{party.phone??"No phone"}</p></div>)}</div></div></section>:null}
    </main>;
  } finally { await db.$disconnect(); }
}

function Stat({ icon:Icon,label,value,warn=false }:{icon:typeof AlertTriangle;label:string;value:number;warn?:boolean}){return <div className={`rounded-2xl border p-5 shadow-sm ${warn&&value?"border-red-200 bg-red-50":"bg-white"}`}><Icon size={20} className={warn&&value?"text-red-700":"text-emerald-700"}/><p className="mt-2 text-sm text-slate-600">{label}</p><p className="text-3xl font-black">{value}</p></div>}
function Panel({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <details className="rounded-2xl border bg-white p-5 shadow-sm"><summary className="cursor-pointer text-xl font-bold">{title}</summary><p className="mb-4 mt-2 text-sm text-slate-600">{intro}</p>{children}</details>}
function SectionHeading({title,count,link,linkLabel}:{title:string;count:number;link?:string;linkLabel?:string}){return <div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="text-xl font-bold">{title}</h2><p className="text-sm text-slate-500">{count} controlled record{count===1?"":"s"}</p></div>{link?<Link href={link} className="text-sm font-bold text-emerald-800">{linkLabel} →</Link>:null}</div>}
function Badge({value,warn=false}:{value:string;warn?:boolean}){return <span className={`rounded-full px-2.5 py-1 text-xs font-black ${warn?"bg-red-100 text-red-800":"bg-slate-100 text-slate-700"}`}>{governanceLabel(value)}</span>}
function Meta({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-0.5 font-semibold">{value}</dd></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed bg-slate-50 p-6 text-sm text-slate-500">{text}</div>}
function date(value:Date|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value):"Not set"}
function dateTime(value:Date){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(value)}
