import Link from "next/link";
import { redirect } from "next/navigation";
import type { Prisma } from "@/generated/prisma/client";
import { requireAuthorisedContext } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { evidenceDisplayStatus, evidenceScopeWhere } from "@/lib/evidence";
import { EVIDENCE_SOURCE_TYPES } from "@/lib/evidence-assurance";
import { CORE_EVIDENCE_FAMILIES } from "@/lib/evidence-taxonomy";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

const PAGE_SIZE=24;
export default async function EvidencePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const context=await requireAuthorisedContext(),canViewAll=hasPermission(context.permissions,PERMISSIONS.GOVERNANCE_VIEW),canUpload=hasPermission(context.permissions,PERMISSIONS.EVIDENCE_UPLOAD);if(!canViewAll&&!canUpload)redirect("/forbidden");
 const params=await searchParams,q=String(params.q??"").trim(),family=String(params.family??""),type=String(params.type??""),providerType=String(params.providerType??""),status=String(params.status??""),locationId=String(params.location??""),currentness=String(params.currentness??""),verification=String(params.verification??""),sourceType=String(params.sourceType??""),view=params.view==="folders"?"folders":"cards",page=Math.max(1,Number(params.page)||1),now=new Date();
 const filters:Prisma.EvidenceWhereInput[]=[evidenceScopeWhere(context)];
 if(!canViewAll) filters.push({OR:[{ownerId:context.user.id},{uploadedById:context.user.id}]});
 if(q) filters.push({OR:[
  {title:{contains:q,mode:"insensitive"}},
  {description:{contains:q,mode:"insensitive"}},
  {sourceName:{contains:q,mode:"insensitive"}},
  {sourceReference:{contains:q,mode:"insensitive"}},
  {tags:{has:q}},
 ]});
 if(family) filters.push({taxonomyFamilyKey:family});
 if(type) filters.push({taxonomyTypeKey:type});
 if(providerType) filters.push({providerEvidenceTypeId:providerType});
 if(locationId) filters.push({locationId});
 if(status==="ACTIVE"||status==="ARCHIVED") filters.push({status});
 if(sourceType) filters.push({sourceType:sourceType as never});
 if(verification==="PENDING") filters.push({verifications:{none:{}}});
 if(verification==="REJECTED") filters.push({verifications:{some:{outcome:"REJECTED"}}});
 if(verification==="VERIFIED") filters.push({verifications:{some:{outcome:{in:["VERIFIED","VERIFIED_WITH_LIMITATIONS"]}}}});
 if(currentness==="HISTORICAL") filters.push({currentnessStatus:"HISTORICAL"});
 if(currentness==="SUPERSEDED") filters.push({currentnessStatus:"SUPERSEDED"});
 if(currentness==="REVIEW_DUE") filters.push({reviewExpiryDate:{lt:now},currentnessMode:{in:["REVIEW_BASED","CURRENT_SOURCE"]}});
 if(currentness==="EXPIRED") filters.push({reviewExpiryDate:{lt:now},currentnessMode:"EXPIRY_BASED"});
 if(currentness==="LEGACY") filters.push({taxonomyFamilyKey:null});
 const where:Prisma.EvidenceWhereInput={AND:filters},db=createDb();
 try{
  const[items,total,providerTypes,attention]=await Promise.all([db.evidence.findMany({where,include:{owner:{select:{name:true}},location:{select:{name:true}},currentVersion:{select:{versionNumber:true,fileName:true}},providerEvidenceType:{select:{label:true}}},orderBy:[{archivedAt:"asc"},{reviewExpiryDate:"asc"},{title:"asc"}],skip:(page-1)*PAGE_SIZE,take:PAGE_SIZE}),db.evidence.count({where}),db.providerEvidenceType.findMany({where:{organisationId:context.organisation.id,status:"ACTIVE"},select:{id:true,familyKey:true,label:true},orderBy:{label:"asc"}}),db.evidence.count({where:{AND:[evidenceScopeWhere(context),{status:"ACTIVE"},{OR:[{verifications:{none:{}}},{currentnessStatus:"SUPERSEDED"},{taxonomyFamilyKey:null},{reviewExpiryDate:{lt:now},currentnessMode:{in:["EXPIRY_BASED","REVIEW_BASED","CURRENT_SOURCE"]}}]}]}})]);
  const pages=Math.max(1,Math.ceil(total/PAGE_SIZE)),selectedTypes=CORE_EVIDENCE_FAMILIES.find(item=>item.key===family)?.types??[],grouped=[...new Set(items.map(item=>item.taxonomyFamilySnapshot??`${item.category} · legacy`))].map(label=>({label,items:items.filter(item=>(item.taxonomyFamilySnapshot??`${item.category} · legacy`)===label)}));
  return <main className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Evidence Library</h1><p className="mt-1 text-slate-600">Find the right governed record without loading the whole Library. Start with Evidence requiring attention or narrow by classification, location and source.</p></div><div className="flex flex-wrap gap-2"><Link href="/evidence/requirements" className="rounded-xl border border-emerald-700 bg-white px-5 py-3 text-sm font-semibold text-emerald-800">Required evidence and gaps</Link>{canUpload?<Link href="/evidence/new" className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white">Upload evidence</Link>:null}</div></div>
   <section className="grid gap-3 sm:grid-cols-3"><Stat label="Matching Evidence" value={total}/><Stat label="Requires attention" value={attention}/><Stat label="Page" value={`${Math.min(page,pages)} of ${pages}`}/></section>
   <form className="rounded-2xl border border-slate-200 bg-white p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input name="q" defaultValue={q} placeholder="Search title, source, reference or exact tag" className="input"/><Select name="family" value={family} label="All core families" options={CORE_EVIDENCE_FAMILIES.map(item=>({value:item.key,label:item.label}))}/><Select name="type" value={type} label={family?"All types in family":"Choose family first"} options={selectedTypes.map(item=>({value:item.key,label:item.label}))}/><Select name="providerType" value={providerType} label="All provider subtypes" options={providerTypes.filter(item=>!family||item.familyKey===family).map(item=>({value:item.id,label:item.label}))}/><Select name="location" value={locationId} label="All locations" options={context.locations.map(item=>({value:item.id,label:item.name}))}/><Select name="currentness" value={currentness} label="All currentness states" options={[{value:"REVIEW_DUE",label:"Review due"},{value:"EXPIRED",label:"Expired"},{value:"SUPERSEDED",label:"Superseded"},{value:"HISTORICAL",label:"Historical"},{value:"LEGACY",label:"Unclassified legacy"}]}/><Select name="verification" value={verification} label="All verification states" options={[{value:"PENDING",label:"Verification required"},{value:"VERIFIED",label:"Verified"},{value:"REJECTED",label:"Rejected"}]}/><Select name="sourceType" value={sourceType} label="All provenance types" options={EVIDENCE_SOURCE_TYPES.map(item=>({value:item,label:item.replaceAll("_"," ")}))}/></div><div className="mt-4 flex flex-wrap gap-2"><button className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">Apply filters</button><Link href="/evidence" className="rounded-xl border px-5 py-3 text-sm font-bold">Clear</Link><input type="hidden" name="view" value={view}/></div></form>
   <div className="flex items-center justify-between"><p className="text-sm text-slate-600">Showing {items.length?`${(page-1)*PAGE_SIZE+1}–${(page-1)*PAGE_SIZE+items.length}`:"0"} of {total}</p><div className="flex gap-2"><Link href={withParams(params,{view:"cards",page:"1"})} className={`rounded-lg px-3 py-2 text-sm ${view==="cards"?"bg-emerald-100 font-bold":"bg-white"}`}>Cards</Link><Link href={withParams(params,{view:"folders",page:"1"})} className={`rounded-lg px-3 py-2 text-sm ${view==="folders"?"bg-emerald-100 font-bold":"bg-white"}`}>Families</Link></div></div>
   {!items.length?<section className="rounded-2xl border border-dashed bg-white p-10 text-center"><h2 className="text-xl font-bold">No Evidence matches</h2><p className="mt-2 text-slate-600">Adjust the filters or add a new authorised Evidence record.</p></section>:view==="cards"?<section className="grid gap-4 lg:grid-cols-2">{items.map(item=><EvidenceCard key={item.id} item={item}/>)}</section>:<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{grouped.map(group=><article key={group.label} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-bold">{group.label}</h2><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-bold">{group.items.length}</span></div><div className="mt-4 space-y-2">{group.items.map(item=><Link key={item.id} href={`/evidence/${item.id}`} className="block rounded-lg bg-slate-50 p-3 text-sm font-semibold">{item.title}<span className="block text-xs font-normal text-slate-500">{item.taxonomyTypeSnapshot??item.evidenceType}</span></Link>)}</div></article>)}</section>}
   {pages>1?<nav aria-label="Evidence pages" className="flex items-center justify-center gap-3"><Link aria-disabled={page<=1} href={withParams(params,{page:String(Math.max(1,page-1))})} className={`rounded-lg border px-4 py-2 font-bold ${page<=1?"pointer-events-none opacity-40":"bg-white"}`}>Previous</Link><span className="text-sm font-semibold">Page {Math.min(page,pages)} of {pages}</span><Link aria-disabled={page>=pages} href={withParams(params,{page:String(Math.min(pages,page+1))})} className={`rounded-lg border px-4 py-2 font-bold ${page>=pages?"pointer-events-none opacity-40":"bg-white"}`}>Next</Link></nav>:null}
  </main>
 }finally{await db.$disconnect()}
}
function Select({name,value,label,options}:{name:string;value:string;label:string;options:{value:string;label:string}[]}){return <select name={name} defaultValue={value} className="input"><option value="">{label}</option>{options.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select>}
function Stat({label,value}:{label:string;value:number|string}){return <div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>}
function EvidenceCard({item}:{item:{id:string;title:string;category:string;evidenceType:string;taxonomyFamilySnapshot:string|null;taxonomyTypeSnapshot:string|null;currentnessMode:string|null;currentnessStatus:string|null;confidentiality:string;status:string;reviewExpiryDate:Date|null;owner:{name:string};location:{name:string}|null;currentVersion:{versionNumber:string;fileName:string}|null;providerEvidenceType:{label:string}|null;relatedModule:string|null;generatedPolicyId:string|null}}){const display=evidenceDisplayStatus(item.status,item.reviewExpiryDate,new Date(),{mode:item.currentnessMode,status:item.currentnessStatus}),systemRecord=Boolean(item.generatedPolicyId)||["RegisterEntry","Audit","Risk"].includes(item.relatedModule??"");return <Link href={`/evidence/${item.id}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-emerald-400"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">{item.taxonomyFamilySnapshot??`${item.category} · legacy`} · {item.taxonomyTypeSnapshot??item.evidenceType}{item.providerEvidenceType?` · ${item.providerEvidenceType.label}`:""}</p><h2 className="mt-1 break-words text-lg font-bold">{item.title}</h2><p className="mt-1 text-xs text-slate-500">{systemRecord?"Linked to its governed source record":item.currentVersion?.fileName}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-bold ${display==="Expired"||display==="Review due"||display==="Superseded"?"bg-amber-100 text-amber-900":display==="Current"?"bg-emerald-100 text-emerald-800":"bg-slate-100"}`}>{display}</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Owner</dt><dd className="font-medium">{item.owner.name}</dd></div><div><dt className="text-slate-500">Location</dt><dd className="font-medium">{item.location?.name??"Organisation"}</dd></div><div><dt className="text-slate-500">Review</dt><dd className="font-medium">{formatDate(item.reviewExpiryDate)}</dd></div></dl></Link>}
function formatDate(value:Date|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value):"Not set"}
function withParams(params:Record<string,string|string[]|undefined>,updates:Record<string,string>){const search=new URLSearchParams();for(const[key,value]of Object.entries(params)){if(typeof value==="string"&&value)search.set(key,value)}for(const[key,value]of Object.entries(updates)){if(value)search.set(key,value);else search.delete(key)}return `/evidence?${search}`}
