import Link from "next/link";
import { CarePlanForm } from "@/components/care-plan-form";
import { requirePermission } from "@/lib/auth/dal";
import { clientName, clientScopeWhere } from "@/lib/clients";
import { createDb } from "@/lib/db";
import { evidenceScopeWhere } from "@/lib/evidence";
import { PERMISSIONS } from "@/lib/permissions";

export default async function NewCarePlanPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const context=await requirePermission(PERMISSIONS.GOVERNANCE_EDIT),query=await searchParams,clientId=String(query.clientId??""),db=createDb();try{const clients=await db.client.findMany({where:{...clientScopeWhere(context),status:{in:["PROSPECT","ACTIVE","PAUSED"]}},orderBy:[{lastName:"asc"},{firstName:"asc"}]});if(!clientId){return <main className="space-y-5"><header><Link href="/care-plans" className="text-sm font-semibold text-emerald-700">← Care Plans</Link><h1 className="mt-3 text-3xl font-bold">Choose the person</h1><p className="mt-1 text-slate-600">A care plan is always linked to one controlled Client Directory profile.</p></header><div className="grid gap-3 md:grid-cols-2">{clients.map((person)=><Link key={person.id} href={`/care-plans/new?clientId=${person.id}`} className="rounded-2xl border bg-white p-5 hover:border-emerald-500"><strong>{clientName(person)}</strong><p className="text-sm text-slate-500">Client {person.clientNumber} · {person.clientReference}</p></Link>)}</div></main>}const person=clients.find((x)=>x.id===clientId);if(!person)return <main><h1 className="text-2xl font-bold">Person not found</h1><Link href="/care-plans/new" className="text-emerald-700">Choose another person</Link></main>;const[members,evidence,staff]=await Promise.all([db.organisationMembership.findMany({where:{organisationId:context.organisation.id,status:"ACTIVE"},select:{user:{select:{id:true,name:true}}},orderBy:{user:{name:"asc"}}}),db.evidence.findMany({where:{...evidenceScopeWhere(context),status:"ACTIVE"},select:{id:true,title:true},orderBy:{title:"asc"},take:1000}),db.staffMember.findMany({where:{organisationId:context.organisation.id,archivedAt:null,employmentStatus:"ACTIVE"},select:{id:true,firstName:true,lastName:true,preferredName:true},orderBy:[{lastName:"asc"},{firstName:"asc"}],take:1000})]);return <main className="space-y-5"><header><Link href="/care-plans" className="text-sm font-semibold text-emerald-700">← Care Plans</Link><p className="mt-3 text-xs font-bold uppercase tracking-[.2em] text-emerald-700">New controlled source of truth</p><h1 className="mt-1 text-3xl font-bold">Create care plan for {clientName(person)}</h1></header><CarePlanForm organisationName={context.organisation.name} person={personProp(person)} locations={context.locations.map(({id,name})=>({id,name}))} users={members.map(({user})=>user)} evidence={evidence.map((x)=>({id:x.id,name:x.title}))} staff={staff.map((x)=>({id:x.id,name:`${x.preferredName?.trim()||x.firstName} ${x.lastName}`}))}/></main>}finally{await db.$disconnect()}}
function personProp(p:{id:string;clientNumber:number;clientReference:string;firstName:string;lastName:string;preferredName:string|null;dateOfBirth:Date|null;phone:string|null;addressLine:string|null;town:string|null;postcode:string|null;communicationSummary:string|null;emergencyContact:string|null;nextOfKinName:string|null;nextOfKinRelationship:string|null;nextOfKinPhone:string|null}){return{id:p.id,name:clientName(p),reference:`Client ${p.clientNumber} · ${p.clientReference}`,preferredName:p.preferredName?.trim()||p.firstName,dateOfBirth:p.dateOfBirth?.toISOString().slice(0,10)??"Not recorded",phone:p.phone??"Not recorded",address:[p.addressLine,p.town,p.postcode].filter(Boolean).join(", ")||"Not recorded",communicationSummary:p.communicationSummary??"Not recorded",emergencyContact:p.emergencyContact??p.nextOfKinPhone??"Not recorded",representative:p.nextOfKinName?[p.nextOfKinName,p.nextOfKinRelationship,p.nextOfKinPhone].filter(Boolean).join(" · "):"Not recorded"}}
