import { describe, expect, it } from "vitest";
import { evidenceAssuranceState } from "@/lib/evidence-assurance";
import { CORE_EVIDENCE_FAMILIES, evidenceTaxonomySuggestions, taxonomyLabels } from "@/lib/evidence-taxonomy";
import { controlApplicationAssurance, providerControlApplies, providerControlScopeAllowed } from "@/lib/provider-controls";

const now=new Date("2026-08-21T12:00:00.000Z");
describe("Evidence taxonomy",()=>{
 it("resolves the stable core family and contextual type hierarchy",()=>{expect(CORE_EVIDENCE_FAMILIES).toHaveLength(15);expect(taxonomyLabels("MEDICINES","MEDICATION_COMPETENCY")).toEqual({familyLabel:"Medicines",typeLabel:"Medication competency",currentnessMode:"EXPIRY_BASED"})});
 it("narrows deterministic suggestions by Risk category",()=>{expect(evidenceTaxonomySuggestions("Medicines").some(item=>item.key==="MEDICATION_COMPETENCY")).toBe(true);expect(evidenceTaxonomySuggestions("Medicines").some(item=>item.key==="SAFEGUARDING_OUTCOME")).toBe(false)});
 it("safe-handles unknown legacy values without inventing a mapping",()=>expect(taxonomyLabels("OLD_CUSTOM","UNKNOWN")).toBeNull());
});

describe("type-aware Evidence currentness",()=>{
 const base={status:"ACTIVE",updatedAt:new Date("2026-01-01"),currentVersionId:null,verification:undefined};
 it("keeps historical Evidence non-expiring",()=>expect(evidenceAssuranceState({...base,currentnessMode:"HISTORICAL_NON_EXPIRING",reviewExpiryDate:new Date("2020-01-01")},now)).toBe("UNVERIFIED"));
 it("distinguishes expiry, review due and supersession",()=>{expect(evidenceAssuranceState({...base,currentnessMode:"EXPIRY_BASED",reviewExpiryDate:new Date("2026-01-01")},now)).toBe("EXPIRED");expect(evidenceAssuranceState({...base,currentnessMode:"REVIEW_BASED",reviewExpiryDate:new Date("2026-01-01")},now)).toBe("REVIEW_DUE");expect(evidenceAssuranceState({...base,currentnessMode:"SUPERSESSION_BASED",currentnessStatus:"SUPERSEDED",reviewExpiryDate:null},now)).toBe("SUPERSEDED")});
 it("uses review dates for current-source Evidence and does not age historical Evidence by date alone",()=>{const verification={outcome:"VERIFIED",verifiedAt:new Date("2026-02-01"),evidenceVersionId:null,reviewDueAt:null};expect(evidenceAssuranceState({...base,currentnessMode:"CURRENT_SOURCE",reviewExpiryDate:new Date("2026-01-01"),verification},now)).toBe("REVIEW_DUE");expect(evidenceAssuranceState({...base,currentnessMode:"HISTORICAL_NON_EXPIRING",reviewExpiryDate:new Date("2020-01-01"),verification},now)).toBe("CURRENT_VERIFIED")});
 it("keeps legacy null-mode expiry behaviour backwards compatible",()=>{const verification={outcome:"VERIFIED",verifiedAt:new Date("2026-02-01"),evidenceVersionId:null,reviewDueAt:null};expect(evidenceAssuranceState({...base,currentnessMode:null,reviewExpiryDate:new Date("2026-01-01"),verification},now)).toBe("EXPIRED")});
});

describe("Provider Control scope and assurance",()=>{
 const context={allLocations:false,locations:[{id:"loc-a"}]};
 it("prevents location-scoped managers creating organisation-wide controls",()=>{expect(providerControlScopeAllowed(context,"ORGANISATION",[])).toBe(false);expect(providerControlScopeAllowed(context,"SELECTED_LOCATIONS",["loc-a"])).toBe(true);expect(providerControlScopeAllowed(context,"SELECTED_LOCATIONS",["loc-b"])).toBe(false)});
 it("rejects irrelevant scope/category and permits matching effective control",()=>{expect(providerControlApplies({status:"EFFECTIVE",scopeType:"SELECTED_LOCATIONS",locationIds:["loc-a"],riskLocationId:"loc-a",categoryKeys:["MEDICINES"],riskCategory:"Medicines"})).toBe(true);expect(providerControlApplies({status:"EFFECTIVE",scopeType:"SELECTED_LOCATIONS",locationIds:["loc-a"],riskLocationId:"loc-b",categoryKeys:["MEDICINES"],riskCategory:"Medicines"})).toBe(false);expect(providerControlApplies({status:"DRAFT",scopeType:"ORGANISATION",locationIds:[],riskLocationId:null,categoryKeys:[],riskCategory:"Other"})).toBe(false)});
 it("does not treat linked supporting Evidence as effectiveness",()=>{const assessment=controlApplicationAssurance({status:"APPLIED",controlStatus:"EFFECTIVE",expectedFamilyKeys:["WORKFORCE"],expectedTypeKeys:["WORKFORCE:COMPETENCY_ASSESSMENT"],evidenceLinks:[{role:"CONTROL",evidence:{title:"Competency",status:"ACTIVE",reviewExpiryDate:null,updatedAt:new Date("2026-01-01"),currentVersionId:null,currentnessMode:"HISTORICAL_NON_EXPIRING",currentnessStatus:"HISTORICAL",verifications:[]}}],latestEffectiveness:null});expect(assessment.supportingEvidenceCount).toBe(1);expect(assessment.gaps).toContain("Control effectiveness has not been tested.")});
 it("flags a deterministic conflict when Effective has no effectiveness Evidence",()=>{const assessment=controlApplicationAssurance({status:"APPLIED",controlStatus:"EFFECTIVE",expectedFamilyKeys:[],expectedTypeKeys:[],evidenceLinks:[],latestEffectiveness:{outcome:"EFFECTIVE"}});expect(assessment.conflicts).toContain("The Control is marked Effective, but no Effectiveness Evidence is linked.")});
 it("surfaces a deterministic expected-taxonomy gap",()=>{const assessment=controlApplicationAssurance({status:"APPLIED",controlStatus:"EFFECTIVE",expectedFamilyKeys:["MEDICINES"],expectedTypeKeys:["MEDICINES:MEDICATION_AUDIT"],evidenceLinks:[{role:"CONTROL",evidence:{title:"Unrelated record",taxonomyFamilyKey:"WORKFORCE",taxonomyTypeKey:"SUPERVISION",status:"ACTIVE",reviewExpiryDate:null,updatedAt:new Date("2026-01-01"),currentVersionId:null,currentnessMode:"HISTORICAL_NON_EXPIRING",currentnessStatus:"CURRENT",verifications:[{outcome:"VERIFIED",verifiedAt:new Date("2026-02-01"),evidenceVersionId:null,reviewDueAt:null}]}}],latestEffectiveness:null});expect(assessment.gaps).toContain("Linked Control Evidence does not match an expected Evidence family.");expect(assessment.gaps).toContain("Linked Control Evidence does not match an expected contextual Evidence type.")});
 it("permits one canonical Evidence record to serve distinct Control and Effectiveness roles",()=>{const evidence={title:"Medication audit",taxonomyFamilyKey:"MEDICINES",taxonomyTypeKey:"MEDICATION_AUDIT",status:"ACTIVE",reviewExpiryDate:null,updatedAt:new Date("2026-01-01"),currentVersionId:null,currentnessMode:"HISTORICAL_NON_EXPIRING",currentnessStatus:"CURRENT",verifications:[{outcome:"VERIFIED",verifiedAt:new Date("2026-02-01"),evidenceVersionId:null,reviewDueAt:null}]};const assessment=controlApplicationAssurance({status:"APPLIED",controlStatus:"EFFECTIVE",expectedFamilyKeys:["MEDICINES"],expectedTypeKeys:["MEDICINES:MEDICATION_AUDIT"],evidenceLinks:[{role:"CONTROL",evidence},{role:"EFFECTIVENESS",evidence}],latestEffectiveness:{outcome:"EFFECTIVE"}});expect(assessment.supportingEvidenceCount).toBe(1);expect(assessment.effectivenessEvidenceCount).toBe(1);expect(assessment.gaps).toEqual([]);expect(assessment.conflicts).toEqual([])});
});
