import Link from "next/link";
import { notFound } from "next/navigation";
import { InspectionRequirementForm } from "@/components/inspection-requirement-form";
import { requirePermission } from "@/lib/auth/dal";
import { assuranceLabel } from "@/lib/inspection-assurance";
import { CQC_EVIDENCE_CATEGORIES } from "@/lib/inspection-framework";
import { getInspectionFormOptions, getInspectionRequirements } from "@/lib/inspection-data";
import { INSPECTION_DISCLAIMER, inspectionLabel } from "@/lib/inspection";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

export default async function InspectionRequirementPage({params}:{params:Promise<{id:string}>}){const context=await requirePermission(PERMISSIONS.GOVERNANCE_VIEW),{id}=await params;const requirements=await getInspectionRequirements(context),requirement=requirements.find(x=>x.id===id);if(!requirement)notFound();const canEdit=hasPermission(context.permissions,PERMISSIONS.GOVERNANCE_EDIT),options=canEdit?await getInspectionFormOptions(context):null;return <main className="mx-auto max-w-6xl space-y-6"><div><Link href="/inspection" className="text-sm font-semibold text-emerald-700">Back to Inspection Centre</Link><div className="mt-2 flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">{inspectionLabel(requirement.keyQuestion)} · {requirement.qualityStatement??"Local standard"}</p><h1 className="mt-1 text-3xl font-bold">{requirement.title}</h1><p className="mt-2 max-w-3xl text-slate-600">{requirement.explanation}</p></div><div className="rounded-2xl border bg-white p-4 text-right"><p className="text-3xl font-black">{requirement.assurance.score}%</p><p className="text-sm font-bold">{assuranceLabel(requirement.assurance.status)}</p></div></div></div><section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{INSPECTION_DISCLAIMER}</section>
<section className="grid gap-4 md:grid-cols-4"><Meta label="Owner" value={requirement.owner?.name??"Unassigned"}/><Meta label="Location" value={requirement.location?.name??"Organisation-wide"}/><Meta label="Review date" value={requirement.reviewDate?date(requirement.reviewDate):"Not set"}/><Meta label="RM decision" value={assuranceLabel(requirement.managementDecision)}/></section>
{requirement.assurance.blockers.length||requirement.assurance.warnings.length?<section className="grid gap-4 md:grid-cols-2"><Notice title="Assurance blockers" values={requirement.assurance.blockers} tone="red"/><Notice title="Warnings" values={requirement.assurance.warnings} tone="amber"/></section>:null}
<section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">CQC evidence-category coverage</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{CQC_EVIDENCE_CATEGORIES.map(x=>{const expected=requirement.expectedEvidenceCategories.includes(x),covered=requirement.coveredCategories.includes(x);return <div key={x} className={`rounded-lg border p-3 text-sm ${covered?"border-emerald-200 bg-emerald-50":expected?"border-red-200 bg-red-50":"border-slate-200"}`}><strong>{covered?"✓ ":expected?"○ ":"– "}{assuranceLabel(x)}</strong><p className="mt-1 text-xs">{covered?"Covered by connected evidence or RM review":expected?"Expected and not yet evidenced":"Not expected for this requirement"}</p></div>})}</div></section>
<section className="grid gap-5 md:grid-cols-2"><TextPanel title="Strengths" value={requirement.strengths}/><TextPanel title="Areas for improvement" value={requirement.areasForImprovement}/><TextPanel title="Impact on people" value={requirement.impactOnPeople}/><TextPanel title="RM sign-off" value={requirement.signedOffAt?`${requirement.signedOffBy?.name??"Registered Manager"} · ${date(requirement.signedOffAt)}`:"Not signed off"}/></section>
<section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-bold">Connected live records ({requirement.connectedRecords.length})</h2>{canEdit?<div className="flex flex-wrap gap-2">{requirement.catalogueKey?<Link href={`/evidence/new?requirement=${encodeURIComponent(requirement.catalogueKey)}`} className="rounded-lg border border-emerald-700 px-3 py-2 text-sm font-semibold text-emerald-800">Upload evidence</Link>:null}<Link href={`/actions/new?sourceType=INSPECTION&sourceId=${requirement.id}`} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Create improvement action</Link></div>:null}</div>{requirement.connectedRecords.length?<div className="mt-3 divide-y">{requirement.connectedRecords.map((record,index)=><div key={`${record.id}:${index}`} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><Link href={record.href} className="font-semibold text-emerald-700">{record.label}</Link><p className="text-xs text-slate-500">{record.type}</p></div><p className="text-xs font-semibold">{assuranceLabel(record.status)}{record.date?` · ${date(record.date)}`:""}</p></div>)}</div>:<p className="mt-2 text-sm text-slate-600">No records are connected yet.</p>}</section>
<section className="grid gap-5 md:grid-cols-2"><TextPanel title="Regulatory basis" value={requirement.regulations.join(" · ")||"Local standard"}/><div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Framework source</h2><p className="mt-2 text-sm text-slate-600">{requirement.frameworkVersion}</p>{requirement.frameworkSourceUrl?<a href={requirement.frameworkSourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-semibold text-emerald-700 underline">Open official source</a>:null}</div></section>
{canEdit&&options?<section><h2 className="mb-4 text-xl font-bold">RM review, evidence mapping and sign-off</h2><InspectionRequirementForm {...options} initial={{id:requirement.id,baseline:Boolean(requirement.catalogueKey),keyQuestion:requirement.keyQuestion,qualityStatement:requirement.qualityStatement??"",title:requirement.title,explanation:requirement.explanation,evidenceExamples:requirement.evidenceExamples,locationId:requirement.locationId??"",ownerId:requirement.ownerId??"",reviewDate:requirement.reviewDate?.toISOString().slice(0,10)??"",confidenceNote:requirement.confidenceNote??"",coveredEvidenceCategories:requirement.coveredEvidenceCategories,strengths:requirement.strengths??"",areasForImprovement:requirement.areasForImprovement??"",impactOnPeople:requirement.impactOnPeople??"",managementDecision:requirement.managementDecision,signedOff:Boolean(requirement.signedOffAt),evidenceIds:requirement.evidenceLinks.map(x=>x.evidenceId),auditIds:requirement.auditLinks.map(x=>x.auditId),registerEntryIds:requirement.registerLinks.map(x=>x.registerEntryId),actionIds:requirement.actionLinks.map(x=>x.actionId)}}/></section>:null}</main>}
function Meta({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 text-sm">{value}</p></div>}
function TextPanel({title,value}:{title:string;value:string|null}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">{title}</h2><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{value||"Not recorded"}</p></div>}
function Notice({title,values,tone}:{title:string;values:string[];tone:"red"|"amber"}){return <section className={`rounded-2xl border p-4 ${tone==="red"?"border-red-200 bg-red-50 text-red-900":"border-amber-200 bg-amber-50 text-amber-950"}`}><h2 className="font-bold">{title}</h2>{values.length?<ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{values.map(x=><li key={x}>{x}</li>)}</ul>:<p className="mt-2 text-sm">None</p>}</section>}
function date(value:Date){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value)}
