import Link from "next/link";
import { notFound } from "next/navigation";
import { InspectionRequirementForm } from "@/components/inspection-requirement-form";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { INSPECTION_DISCLAIMER, inspectionLabel, inspectionScopeWhere } from "@/lib/inspection";
import { getInspectionFormOptions } from "@/lib/inspection-data";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

export default async function InspectionRequirementPage({ params }: { params: Promise<{ id: string }> }) {
  const context = await requirePermission(PERMISSIONS.GOVERNANCE_VIEW), { id } = await params, db = createDb();
  try {
    const requirement = await db.complianceRequirement.findFirst({ where: { id, ...inspectionScopeWhere(context) }, include: { owner: { select: { name: true } }, location: { select: { name: true } }, evidenceLinks: { include: { evidence: { select: { id: true, title: true } } } }, auditLinks: { include: { audit: { select: { id: true, title: true } } } }, registerLinks: { include: { registerEntry: { select: { id: true, reference: true, title: true, definition: { select: { key: true } } } } } }, actionLinks: { include: { action: { select: { id: true, reference: true, title: true } } } } } });
    if (!requirement) notFound();
    const canEdit = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_EDIT);
    const options = canEdit ? await getInspectionFormOptions(context) : null;
    return <main className="mx-auto max-w-6xl space-y-6"><div><Link href="/inspection" className="text-sm font-semibold text-emerald-700">Back to Inspection Centre</Link><div className="mt-2 flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">{inspectionLabel(requirement.keyQuestion)} · {requirement.qualityStatement ?? "Custom statement"}</p><h1 className="mt-1 text-3xl font-bold">{requirement.title}</h1><p className="mt-2 max-w-3xl text-slate-600">{requirement.explanation}</p></div><span className="rounded-full bg-slate-100 px-3 py-2 text-sm font-bold">{inspectionLabel(requirement.evidenceStatus)}</span></div></div><section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-medium text-amber-950">{INSPECTION_DISCLAIMER}</section>
      <section className="grid gap-4 md:grid-cols-4"><Meta label="Owner" value={requirement.owner?.name ?? "Unassigned"} /><Meta label="Location" value={requirement.location?.name ?? "Organisation-wide"} /><Meta label="Review date" value={requirement.reviewDate ? date(requirement.reviewDate) : "Not set"} /><Meta label="Confidence" value={requirement.confidenceNote ?? "No note recorded"} /></section>
      <section className="grid gap-5 md:grid-cols-2"><Links title="Documents" items={requirement.evidenceLinks.map(({ evidence }) => ({ label: evidence.title, href: `/evidence/${evidence.id}` }))} /><Links title="Audits" items={requirement.auditLinks.map(({ audit }) => ({ label: audit.title, href: `/audits/${audit.id}` }))} /><Links title="Register entries" items={requirement.registerLinks.map(({ registerEntry }) => ({ label: `${registerEntry.reference} - ${registerEntry.title}`, href: `/registers/${registerEntry.definition.key}/${registerEntry.id}` }))} /><Links title="Actions" items={requirement.actionLinks.map(({ action }) => ({ label: `${action.reference} - ${action.title}`, href: `/actions/${action.id}` }))} /></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Evidence examples</h2>{requirement.evidenceExamples.length ? <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-600">{requirement.evidenceExamples.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-2 text-sm text-slate-600">No examples recorded.</p>}</section>
      {canEdit && options ? <section><h2 className="mb-4 text-xl font-bold">Update requirement and mappings</h2><InspectionRequirementForm {...options} initial={{ id: requirement.id, keyQuestion: requirement.keyQuestion, qualityStatement: requirement.qualityStatement ?? "", title: requirement.title, explanation: requirement.explanation, evidenceExamples: requirement.evidenceExamples, locationId: requirement.locationId ?? "", ownerId: requirement.ownerId ?? "", reviewDate: requirement.reviewDate?.toISOString().slice(0, 10) ?? "", evidenceStatus: requirement.evidenceStatus, confidenceNote: requirement.confidenceNote ?? "", evidenceIds: requirement.evidenceLinks.map((item) => item.evidenceId), auditIds: requirement.auditLinks.map((item) => item.auditId), registerEntryIds: requirement.registerLinks.map((item) => item.registerEntryId), actionIds: requirement.actionLinks.map((item) => item.actionId) }} /></section> : null}
    </main>;
  } finally { await db.$disconnect(); }
}
function Meta({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 text-sm">{value}</p></div>; }
function Links({ title, items }: { title: string; items: { label: string; href: string }[] }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">{title} <span className="text-slate-400">({items.length})</span></h2>{items.length ? <ul className="mt-3 space-y-2">{items.map((item) => <li key={item.href}><Link href={item.href} className="text-sm font-semibold text-emerald-700 hover:underline">{item.label}</Link></li>)}</ul> : <p className="mt-2 text-sm text-slate-600">None linked.</p>}</div>; }
function date(value: Date) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(value); }
