import Link from "next/link";
import { requirePermission } from "@/lib/auth/dal";
import { createDb } from "@/lib/db";
import { CQC_KEY_QUESTIONS, INSPECTION_DISCLAIMER, INSPECTION_EVIDENCE_STATUSES, inspectionLabel, inspectionScopeWhere, readinessSummary } from "@/lib/inspection";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

type Query = Record<string, string | string[] | undefined>;
const GAP_STATUSES = ["NO_EVIDENCE", "LIMITED_EVIDENCE", "IMPROVEMENT_REQUIRED"];

export default async function InspectionCentrePage({ searchParams }: { searchParams: Promise<Query> }) {
  const context = await requirePermission(PERMISSIONS.GOVERNANCE_VIEW), query = await searchParams, view = ["readiness", "gaps", "overdue", "checklist", "index"].includes(String(query.view)) ? String(query.view) : "readiness", db = createDb();
  try {
    const [requirements, memberships] = await Promise.all([
      db.complianceRequirement.findMany({ where: inspectionScopeWhere(context), include: { owner: { select: { id: true, name: true } }, location: { select: { id: true, name: true } }, evidenceLinks: { include: { evidence: { select: { id: true, title: true, category: true, reviewExpiryDate: true } } } }, _count: { select: { evidenceLinks: true, auditLinks: true, registerLinks: true, actionLinks: true } } }, orderBy: [{ keyQuestion: "asc" }, { title: "asc" }] }),
      db.organisationMembership.findMany({ where: { organisationId: context.organisation.id, status: "ACTIVE" }, select: { user: { select: { id: true, name: true } } }, orderBy: { user: { name: "asc" } } }),
    ]);
    const summary = readinessSummary(requirements.map((item) => item.evidenceStatus)), now = new Date();
    const filters = { question: String(query.question ?? ""), status: String(query.status ?? ""), owner: String(query.owner ?? ""), location: String(query.location ?? "") };
    const filtered = requirements.filter((item) => (!filters.question || item.keyQuestion === filters.question) && (!filters.status || item.evidenceStatus === filters.status) && (!filters.owner || item.ownerId === filters.owner) && (!filters.location || item.locationId === filters.location)).filter((item) => view === "gaps" ? GAP_STATUSES.includes(item.evidenceStatus) : view === "overdue" ? Boolean(item.reviewDate && item.reviewDate < now) : true);
    const canEdit = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_EDIT);
    return <main className="space-y-7">
      <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Internal evidence readiness</p><h1 className="text-3xl font-bold">Inspection Centre</h1><p className="mt-1 text-slate-600">Organise assurance evidence under the five CQC key questions.</p></div><div className="flex flex-wrap gap-2">{canEdit ? <Link href="/inspection/new" prefetch={false} className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white">Add requirement</Link> : null}<Link href="/inspection/pack" prefetch={false} className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold">Inspection pack</Link><Link href="/api/inspection/export" className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold">Evidence index CSV</Link></div></header>
      <section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-950">{INSPECTION_DISCLAIMER}</section>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Evidence coverage" value={`${summary.coverage}%`} /><Stat label="Requirements reviewed" value={String(summary.reviewed)} /><Stat label="Evidence gaps" value={String(summary.gaps)} warn={summary.gaps > 0} /><Stat label="Overdue reviews" value={String(requirements.filter((item) => item.reviewDate && item.reviewDate < now).length)} warn /></section>
      <section className="grid gap-3 md:grid-cols-5">{CQC_KEY_QUESTIONS.map((question) => { const items = requirements.filter((item) => item.keyQuestion === question), score = readinessSummary(items.map((item) => item.evidenceStatus)); return <Link key={question} href={href(query, { question, view: "readiness" })} prefetch={false} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm hover:border-emerald-400"><p className="text-sm font-bold text-emerald-800">{inspectionLabel(question)}</p><p className="mt-3 text-2xl font-black">{score.coverage}%</p><p className="text-xs text-slate-500">{items.length} requirements · internal coverage</p></Link>; })}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap gap-2">{[["readiness","Readiness summary"],["gaps","Evidence gaps"],["overdue","Overdue evidence"],["checklist","Inspection checklist"],["index","Evidence index"]].map(([key,label]) => <Link key={key} href={href(query, { view: key })} prefetch={false} className={`rounded-lg px-3 py-2 text-sm font-semibold ${view === key ? "bg-emerald-700 text-white" : "border border-slate-200"}`}>{label}</Link>)}</div></section>
      <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-3 xl:grid-cols-5"><input type="hidden" name="view" value={view} /><select name="question" defaultValue={filters.question} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All key questions</option>{CQC_KEY_QUESTIONS.map((item) => <option key={item} value={item}>{inspectionLabel(item)}</option>)}</select><select name="status" defaultValue={filters.status} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All evidence statuses</option>{INSPECTION_EVIDENCE_STATUSES.map((item) => <option key={item} value={item}>{inspectionLabel(item)}</option>)}</select><select name="owner" defaultValue={filters.owner} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All owners</option>{memberships.map(({ user }) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><select name="location" defaultValue={filters.location} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All locations</option>{context.locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="rounded-lg bg-slate-800 px-4 py-2 text-sm font-semibold text-white">Apply filters</button></form>
      {view === "index" ? <EvidenceIndex requirements={filtered} /> : view === "checklist" ? <Checklist requirements={filtered} /> : <RequirementGrid requirements={filtered} />}
    </main>;
  } finally { await db.$disconnect(); }
}
type PageRequirement = { id:string;keyQuestion:string;evidenceStatus:string;title:string;qualityStatement:string|null;explanation:string;ownerId:string|null;locationId:string|null;reviewDate:Date|null;owner:{name:string}|null;location:{name:string}|null;evidenceLinks:{evidence:{id:string;title:string;category:string;reviewExpiryDate:Date|null}}[];_count:{evidenceLinks:number;auditLinks:number;registerLinks:number;actionLinks:number} };
function RequirementGrid({ requirements }: { requirements: PageRequirement[] }) { if (!requirements.length) return <Empty />; return <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{requirements.map((item) => <Link key={item.id} href={`/inspection/${item.id}`} prefetch={false} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-emerald-400"><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">{inspectionLabel(item.keyQuestion)}</p><Status value={item.evidenceStatus} /></div><h2 className="mt-3 text-lg font-bold">{item.title}</h2><p className="mt-1 text-sm text-slate-600">{item.qualityStatement ?? "Custom statement"}</p><p className="mt-3 line-clamp-2 text-sm text-slate-600">{item.explanation}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs text-slate-500"><span>{item.owner?.name ?? "Unassigned"}</span><span>{item.location?.name ?? "Organisation-wide"}</span><span>{item.reviewDate ? `Review ${date(item.reviewDate)}` : "No review date"}</span><span>{item._count.evidenceLinks + item._count.auditLinks + item._count.registerLinks + item._count.actionLinks} linked records</span></div></Link>)}</section>; }
function Checklist({ requirements }: { requirements: PageRequirement[] }) { if (!requirements.length) return <Empty />; return <section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Ready</th><th className="p-3">Key question</th><th className="p-3">Requirement</th><th className="p-3">Owner</th><th className="p-3">Review</th><th className="p-3">Evidence</th></tr></thead><tbody>{requirements.map((item) => <tr key={item.id} className="border-t"><td className="p-3 text-lg">{item.evidenceStatus === "EVIDENCE_REVIEWED" ? "✓" : "○"}</td><td className="p-3">{inspectionLabel(item.keyQuestion)}</td><td className="p-3"><Link href={`/inspection/${item.id}`} className="font-semibold text-emerald-700">{item.title}</Link></td><td className="p-3">{item.owner?.name ?? "Unassigned"}</td><td className="p-3">{item.reviewDate ? date(item.reviewDate) : "Not set"}</td><td className="p-3"><Status value={item.evidenceStatus} /></td></tr>)}</tbody></table></section>; }
function EvidenceIndex({ requirements }: { requirements: PageRequirement[] }) { const rows = requirements.flatMap((requirement) => requirement.evidenceLinks.map(({ evidence }) => ({ requirement, evidence }))); if (!rows.length) return <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-bold">No documents linked</h2><p className="mt-1 text-sm text-slate-600">Open an evidence requirement to map documents from the Evidence Library.</p></section>; return <section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-[800px] w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Document</th><th className="p-3">Category</th><th className="p-3">Requirement</th><th className="p-3">Key question</th><th className="p-3">Expiry</th></tr></thead><tbody>{rows.map(({ requirement, evidence }) => <tr key={`${requirement.id}:${evidence.id}`} className="border-t"><td className="p-3"><Link href={`/evidence/${evidence.id}`} className="font-semibold text-emerald-700">{evidence.title}</Link></td><td className="p-3">{evidence.category}</td><td className="p-3"><Link href={`/inspection/${requirement.id}`}>{requirement.title}</Link></td><td className="p-3">{inspectionLabel(requirement.keyQuestion)}</td><td className="p-3">{evidence.reviewExpiryDate ? date(evidence.reviewExpiryDate) : "Not set"}</td></tr>)}</tbody></table></section>; }
function Status({ value }: { value: string }) { const style = value === "EVIDENCE_REVIEWED" ? "bg-emerald-100 text-emerald-800" : value === "EVIDENCE_AVAILABLE" ? "bg-blue-100 text-blue-800" : value === "LIMITED_EVIDENCE" ? "bg-amber-100 text-amber-900" : "bg-red-100 text-red-800"; return <span className={`rounded-full px-2 py-1 text-xs font-bold ${style}`}>{inspectionLabel(value)}</span>; }
function Stat({ label, value, warn = false }: { label: string; value: string; warn?: boolean }) { return <div className={`rounded-2xl border p-5 ${warn ? "border-amber-200 bg-amber-50" : "border-slate-200 bg-white"}`}><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>; }
function Empty() { return <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-bold">No requirements found</h2><p className="mt-1 text-sm text-slate-600">Adjust the filters or add a new evidence requirement.</p></section>; }
function date(value: Date) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(value); }
function href(query: Query, updates: Record<string, string>) { const params = new URLSearchParams(); for (const [key, value] of Object.entries(query)) if (value) params.set(key, Array.isArray(value) ? value[0] : value); for (const [key, value] of Object.entries(updates)) params.set(key, value); return `/inspection?${params}`; }
