import Link from "next/link";
import { requirePermission } from "@/lib/auth/dal";
import { assuranceLabel } from "@/lib/inspection-assurance";
import { CQC_EVIDENCE_CATEGORIES, INSPECTION_FRAMEWORK_VERSION } from "@/lib/inspection-framework";
import { getInspectionRequirements, type InspectionRequirementView } from "@/lib/inspection-data";
import { CQC_KEY_QUESTIONS, INSPECTION_DISCLAIMER, inspectionLabel } from "@/lib/inspection";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

type Query = Record<string, string | string[] | undefined>;
const GAP_STATUSES = ["NOT_READY", "NEEDS_REVIEW", "PARTIALLY_ASSURED"];

export default async function InspectionCentrePage({ searchParams }: { searchParams: Promise<Query> }) {
  const context = await requirePermission(PERMISSIONS.GOVERNANCE_VIEW), query = await searchParams;
  const view = ["readiness", "gaps", "overdue", "checklist", "index", "framework"].includes(String(query.view)) ? String(query.view) : "readiness";
  const requirements = await getInspectionRequirements(context), now = new Date();
  const filters = { question: String(query.question ?? ""), status: String(query.status ?? ""), owner: String(query.owner ?? ""), location: String(query.location ?? "") };
  const filtered = requirements.filter((item) => (!filters.question || item.keyQuestion === filters.question) && (!filters.status || item.assurance.status === filters.status) && (!filters.owner || item.ownerId === filters.owner) && (!filters.location || item.locationId === filters.location)).filter((item) => view === "gaps" ? GAP_STATUSES.includes(item.assurance.status) : view === "overdue" ? Boolean(item.reviewDate && item.reviewDate < now) : true);
  const average = requirements.length ? Math.round(requirements.reduce((sum, item) => sum + item.assurance.score, 0) / requirements.length) : 0;
  const canEdit = hasPermission(context.permissions, PERMISSIONS.GOVERNANCE_EDIT), members = [...new Map(requirements.flatMap((x) => x.owner ? [[x.owner.id, x.owner.name] as const] : [])).entries()];
  return <main className="space-y-7">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Registered Manager assurance workspace</p><h1 className="text-3xl font-bold">Inspection Centre</h1><p className="mt-1 max-w-4xl text-slate-600">One sourced baseline joining evidence, operational records, management judgement, improvement and sign-off across the system.</p></div><div className="flex flex-wrap gap-2">{canEdit ? <Link href="/inspection/new" prefetch={false} className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white">Add local requirement</Link> : null}<Link href="/inspection/pack" prefetch={false} className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold">RM assurance pack</Link><Link href="/api/inspection/export" className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold">Evidence index CSV</Link></div></header>
    <section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>{INSPECTION_DISCLAIMER}</strong><p className="mt-1">Framework: {INSPECTION_FRAMEWORK_VERSION}. Scores are calculated from current linked records, evidence-category coverage, open findings and actions, RM review and sign-off.</p></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Calculated assurance" value={`${average}%`} /><Stat label="RM assured" value={String(requirements.filter((x) => x.assurance.status === "ASSURED").length)} /><Stat label="Requirements needing attention" value={String(requirements.filter((x) => GAP_STATUSES.includes(x.assurance.status)).length)} warn /><Stat label="Overdue RM reviews" value={String(requirements.filter((x) => x.reviewDate && x.reviewDate < now).length)} warn /></section>
    <section className="grid gap-3 md:grid-cols-5">{CQC_KEY_QUESTIONS.map((question) => { const items = requirements.filter((item) => item.keyQuestion === question), score = items.length ? Math.round(items.reduce((sum, x) => sum + x.assurance.score, 0) / items.length) : 0; return <Link key={question} href={href(query, { question, view: "readiness" })} prefetch={false} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm hover:border-emerald-400"><p className="text-sm font-bold text-emerald-800">{inspectionLabel(question)}</p><p className="mt-3 text-2xl font-black">{score}%</p><p className="text-xs text-slate-500">{items.length} sourced requirements</p></Link>; })}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap gap-2">{[["readiness","Assurance summary"],["gaps","Attention required"],["overdue","Overdue reviews"],["checklist","RM checklist"],["index","Connected records"],["framework","Framework coverage"]].map(([key,label]) => <Link key={key} href={href(query, { view: key })} prefetch={false} className={`rounded-lg px-3 py-2 text-sm font-semibold ${view === key ? "bg-emerald-700 text-white" : "border border-slate-200"}`}>{label}</Link>)}</div></section>
    <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-3 xl:grid-cols-5"><input type="hidden" name="view" value={view} /><select name="question" defaultValue={filters.question} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All key questions</option>{CQC_KEY_QUESTIONS.map((item) => <option key={item} value={item}>{inspectionLabel(item)}</option>)}</select><select name="status" defaultValue={filters.status} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All assurance statuses</option>{["NOT_READY","NEEDS_REVIEW","PARTIALLY_ASSURED","ASSURED","NOT_APPLICABLE"].map((item) => <option key={item} value={item}>{assuranceLabel(item)}</option>)}</select><select name="owner" defaultValue={filters.owner} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All owners</option>{members.map(([id,name]) => <option key={id} value={id}>{name}</option>)}</select><select name="location" defaultValue={filters.location} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All locations</option>{context.locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="rounded-lg bg-slate-800 px-4 py-2 text-sm font-semibold text-white">Apply filters</button></form>
    {view === "index" ? <ConnectedIndex requirements={filtered} /> : view === "checklist" ? <Checklist requirements={filtered} /> : view === "framework" ? <Framework requirements={filtered} /> : <RequirementGrid requirements={filtered} />}
  </main>;
}

function RequirementGrid({ requirements }: { requirements: InspectionRequirementView[] }) { if (!requirements.length) return <Empty />; return <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{requirements.map((item) => <Link key={item.id} href={`/inspection/${item.id}`} prefetch={false} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-emerald-400"><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">{inspectionLabel(item.keyQuestion)}</p><Status value={item.assurance.status} /></div><h2 className="mt-3 text-lg font-bold">{item.title}</h2><p className="mt-1 text-sm text-slate-600">{item.qualityStatement ?? "Local standard"}</p><div className="mt-4 flex items-end justify-between"><div><p className="text-3xl font-black">{item.assurance.score}%</p><p className="text-xs text-slate-500">calculated assurance</p></div><p className="text-right text-xs text-slate-500">{item.assurance.currentRecords} current records<br/>{item.assurance.categoryCoverage}% category coverage</p></div>{item.assurance.blockers.length ? <p className="mt-3 rounded-lg bg-red-50 p-2 text-xs font-semibold text-red-800">{item.assurance.blockers[0]}</p> : null}<div className="mt-4 grid grid-cols-2 gap-2 text-xs text-slate-500"><span>{item.owner?.name ?? "Unassigned"}</span><span>{item.location?.name ?? "Organisation-wide"}</span><span>{item.reviewDate ? `Review ${date(item.reviewDate)}` : "No review date"}</span><span>{item.connectedRecords.length} connected records</span></div></Link>)}</section>; }
function Checklist({ requirements }: { requirements: InspectionRequirementView[] }) { if (!requirements.length) return <Empty />; return <section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-[1000px] w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Assurance</th><th className="p-3">Requirement</th><th className="p-3">RM decision</th><th className="p-3">Owner</th><th className="p-3">Review</th><th className="p-3">Blockers</th></tr></thead><tbody>{requirements.map((item) => <tr key={item.id} className="border-t"><td className="p-3"><strong>{item.assurance.score}%</strong><br/><Status value={item.assurance.status}/></td><td className="p-3"><Link href={`/inspection/${item.id}`} className="font-semibold text-emerald-700">{item.title}</Link><p className="text-xs text-slate-500">{inspectionLabel(item.keyQuestion)}</p></td><td className="p-3">{assuranceLabel(item.managementDecision)}{item.signedOffAt ? <p className="text-xs text-emerald-700">Signed {date(item.signedOffAt)}</p> : null}</td><td className="p-3">{item.owner?.name ?? "Unassigned"}</td><td className="p-3">{item.reviewDate ? date(item.reviewDate) : "Not set"}</td><td className="p-3">{item.assurance.blockers.length ? item.assurance.blockers.join("; ") : "None"}</td></tr>)}</tbody></table></section>; }
function ConnectedIndex({ requirements }: { requirements: InspectionRequirementView[] }) { const rows=requirements.flatMap((r)=>r.connectedRecords.map((record)=>({r,record}))); if(!rows.length)return <Empty/>; return <section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Connected record</th><th className="p-3">Module</th><th className="p-3">Requirement</th><th className="p-3">Status</th><th className="p-3">Relevant date</th></tr></thead><tbody>{rows.map(({r,record},index)=><tr key={`${r.id}:${record.id}:${index}`} className="border-t"><td className="p-3"><Link href={record.href} className="font-semibold text-emerald-700">{record.label}</Link></td><td className="p-3">{record.type}</td><td className="p-3"><Link href={`/inspection/${r.id}`}>{r.title}</Link></td><td className="p-3">{assuranceLabel(record.status)}</td><td className="p-3">{record.date?date(record.date):"Live"}</td></tr>)}</tbody></table></section>; }
function Framework({requirements}:{requirements:InspectionRequirementView[]}){return <section className="space-y-4"><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-bold text-blue-950">Six CQC evidence categories</h2><p className="mt-1 text-sm text-blue-900">Every requirement records expected and evidenced categories. A requirement cannot reach full assurance until all expected categories are covered and the RM signs it off.</p><div className="mt-3 flex flex-wrap gap-2">{CQC_EVIDENCE_CATEGORIES.map((x)=><span key={x} className="rounded-full bg-white px-3 py-1 text-xs font-semibold">{assuranceLabel(x)}</span>)}</div></div><RequirementGrid requirements={requirements}/></section>}
function Status({ value }: { value: string }) { const style=value==="ASSURED"||value==="NOT_APPLICABLE"?"bg-emerald-100 text-emerald-800":value==="PARTIALLY_ASSURED"||value==="NEEDS_REVIEW"?"bg-amber-100 text-amber-900":"bg-red-100 text-red-800";return <span className={`rounded-full px-2 py-1 text-xs font-bold ${style}`}>{assuranceLabel(value)}</span>; }
function Stat({ label, value, warn=false }: {label:string;value:string;warn?:boolean}){return <div className={`rounded-2xl border p-5 ${warn?"border-amber-200 bg-amber-50":"border-slate-200 bg-white"}`}><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>}
function Empty(){return <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-bold">No requirements found</h2><p className="mt-1 text-sm text-slate-600">Adjust the filters or add a local requirement.</p></section>}
function date(value:Date){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value)}
function href(query:Query,updates:Record<string,string>){const params=new URLSearchParams();for(const[key,value]of Object.entries(query))if(value)params.set(key,Array.isArray(value)?value[0]:value);for(const[key,value]of Object.entries(updates))params.set(key,value);return`/inspection?${params}`}
