import Link from "next/link";
import { redirect } from "next/navigation";
import { requireAuthorisedContext } from "@/lib/auth/dal";
import { auditScopeWhere, auditStatusLabel } from "@/lib/audits";
import { createDb } from "@/lib/db";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";

export default async function AuditsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  const context=await requireAuthorisedContext(); const canComplete=hasPermission(context.permissions,PERMISSIONS.AUDITS_COMPLETE); const canView=hasPermission(context.permissions,PERMISSIONS.GOVERNANCE_VIEW); if(!canComplete&&!canView)redirect("/forbidden");
  const params=await searchParams; const status=String(params.status??""); const q=String(params.q??"").trim(); const db=createDb();
  const [audits,templates]=await Promise.all([
    db.audit.findMany({where:{...auditScopeWhere(context),...(status?{status:status as never}:{}),...(q?{title:{contains:q,mode:"insensitive"}}:{})},include:{template:{select:{name:true}},auditor:{select:{name:true}},location:{select:{name:true}},_count:{select:{findings:true}}},orderBy:{updatedAt:"desc"}}),
    db.auditTemplate.findMany({where:{isPublished:true,OR:[{organisationId:null},{organisationId:context.organisation.id}]},include:{_count:{select:{sections:true,audits:true}}},orderBy:{name:"asc"}}),
  ]).finally(()=>db.$disconnect());
  const inProgress=audits.filter((item)=>["DRAFT","IN_PROGRESS"].includes(item.status)).length; const awaiting=audits.filter((item)=>item.status==="AWAITING_REVIEW").length; const completed=audits.filter((item)=>["COMPLETED","CLOSED"].includes(item.status)).length;
  return <main className="space-y-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Assurance programme</p><h1 className="text-3xl font-bold">Audit Centre</h1><p className="mt-1 text-slate-600">Reusable templates, evidence-led assessments, findings and sign-off.</p></div>{canComplete&&<Link href="/audits/new" className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white">Start audit</Link>}</div>
    <section className="grid gap-3 sm:grid-cols-3">{[["In progress",inProgress],["Awaiting review",awaiting],["Completed or closed",completed]].map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div>)}</section>
    <section><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Audit work</p><h2 className="text-2xl font-bold">Recent audits</h2></div><form className="flex flex-wrap gap-2"><input name="q" defaultValue={q} placeholder="Search audits" className="rounded-lg border border-slate-300 px-3 py-2 text-sm"/><select name="status" defaultValue={status} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All statuses</option>{["DRAFT","IN_PROGRESS","AWAITING_REVIEW","COMPLETED","CLOSED","ARCHIVED"].map((value)=><option key={value} value={value}>{auditStatusLabel(value)}</option>)}</select><button className="rounded-lg bg-slate-800 px-4 py-2 text-sm font-semibold text-white">Filter</button></form></div>
      {!audits.length?<div className="mt-4 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><h3 className="font-bold">No audits found</h3><p className="mt-1 text-sm text-slate-600">Start with one of the published templates below.</p></div>:<div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-4">Audit</th><th className="p-4">Location</th><th className="p-4">Auditor</th><th className="p-4">Score</th><th className="p-4">Findings</th><th className="p-4">Status</th></tr></thead><tbody>{audits.map((audit)=><tr key={audit.id} className="border-t border-slate-200"><td className="p-4"><Link href={`/audits/${audit.id}`} className="font-semibold text-emerald-800">{audit.title}</Link><p className="text-xs text-slate-500">{audit.template.name} · {formatDate(audit.auditDate)}</p></td><td className="p-4">{audit.location.name}</td><td className="p-4">{audit.auditor.name}</td><td className="p-4 font-semibold">{audit.overallScore===null?"—":`${audit.overallScore}%`}</td><td className="p-4">{audit._count.findings}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{auditStatusLabel(audit.status)}</span></td></tr>)}</tbody></table></div>}</section>
    <section><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Template library</p><h2 className="text-2xl font-bold">Published templates</h2><p className="mt-1 text-sm text-slate-600">Twenty starter templates are ready to use and version controlled.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{templates.map((template)=><div key={template.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{template.name}</h3><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-semibold text-emerald-800">v{template.version}</span></div><p className="mt-2 text-sm text-slate-600">{template.description}</p><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>{template._count.sections} section</span>{canComplete&&<Link href={`/audits/new?template=${template.id}`} className="font-semibold text-emerald-700">Use template →</Link>}</div></div>)}</div></section>
  </main>;
}
function formatDate(value:Date){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(value);}
