ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'DOWNLOAD';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'REPORT_GENERATION';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'APPROVAL';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'STATUS_CHANGE';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'CLOSE';
